import { EditorialPage } from "@/components/EditorialPage";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("Research methodology", "How Madabase separates official specifications, research synthesis, hands-on evidence, product identity, compatibility, recurring cost, and editorial judgment.", "/methodology");

export default function MethodologyPage() {
  return <EditorialPage eyebrow="Methodology" title="Evidence should change the recommendation." lede="Our job is not to repeat a product page. It is to identify the decision, verify the facts that control it, show what remains uncertain, and make the trade-off understandable." sections={[
    { heading: "Three evidence modes", paragraphs: ["Every product-led page should tell readers which kind of evidence supports it. The label controls what the page may claim and what structured data it may use."], bullets: ["Official-spec: manufacturer documentation and verified compatibility or listing evidence, without a first-hand-use claim.", "Research-synthesis: a visible no-hands-on disclosure plus attributed independent tests, with each setup and limitation kept separate.", "Hands-on: direct use of the actual product with the setup, duration, measurements, and limitations stated. Only this mode may be described as a hands-on review."] },
    { heading: "Verify the exact thing being sold", paragraphs: ["Closely related product names can hide different generations, regions, bundles, pack counts, ports, accessories, or subscription commitments. We verify model, variant, ASIN where applicable, and the current merchant destination before treating an offer as valid.", "When official documentation and a live listing disagree, the contradiction becomes a visible checkout risk. We do not silently average conflicting specifications."] },
    { heading: "Judge the decision, not the feature count", paragraphs: ["Recommendations begin with a user, place, constraint, and task. A faster router is not automatically better for an apartment; a carrier with more positions is not automatically better for a newborn routine; a camera with more AI alerts is not automatically better when the useful features require an unwanted subscription."], bullets: ["Best-for and skip reasons", "Installation and compatibility", "Recurring and consumable cost", "Version and pack-count risk", "Cleaning, storage, and daily effort", "Return and warranty friction where it changes the decision"] },
    { heading: "Use sources in the right order", paragraphs: ["We prefer current manufacturer specifications, manuals, support documents, standards bodies, and public safety guidance for factual limits. Independent testing may add performance evidence when the test setup is disclosed and comparable.", "Merchant listings are used to verify the exact item, bundle, availability, and checkout risk. Marketplace ratings and customer reviews are not presented as our own evidence or copied into the editorial conclusion."] },
    { heading: "Update when the decision changes", paragraphs: ["A changed model, plan price, firmware requirement, compatibility statement, bundle, or merchant destination can reverse a recommendation. Material updates receive a new date and an explanation of what changed.", "A recent date alone is not evidence of freshness. We update the page only when its facts or judgment were actually rechecked."] },
    { heading: "Corrections and independence", paragraphs: ["Affiliate relationships do not guarantee favorable coverage or placement. Products can be omitted, downgraded, or marked unavailable when evidence or identity fails verification.", "Readers and manufacturers may report factual errors through the contact page. Corrections are evaluated against primary evidence and recorded when they materially change the page."] },
  ]} />;
}
