import type { Guide, Product, Roundup } from "./types";

const updatedAt = "July 1, 2026";

export const adjacentExpansionProducts: Product[] = [
  {
    site: "smarthome",
    slug: "aqara-hub-m3",
    asin: "B0CWLHSKYC",
    seoTitle: "Aqara Hub M3 Review Guide: Matter, Thread, Zigbee & PoE",
    updatedAt,
    name: "Aqara Hub M3",
    brand: "Aqara",
    category: "automation",
    image: "/images/affiliate/smarthome-aqara-hub-m3.svg",
    summary: "A compatibility-first guide to Aqara's multi-protocol hub, covering its Matter controller and Thread border-router roles, Aqara Zigbee devices, Ethernet with PoE, infrared control, and migration limits.",
    verdict: "The Hub M3 is the strongest Aqara hub for a new mixed Matter, Thread, and Aqara Zigbee setup. It is less compelling when an existing Matter controller already covers every device and no Aqara Zigbee or infrared automation is planned.",
    whyItMatters: "A hub can perform several different jobs without making every connected device use the same protocol. Mapping Matter controller, Thread border router, Aqara Zigbee hub, and ecosystem bridge roles prevents expensive compatibility assumptions.",
    bestFor: "Aqara-heavy smart homes adding Matter and Thread devices",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Protocol coverage", value: 9 },
      { label: "Local automation", value: 8 },
      { label: "Setup simplicity", value: 6 },
    ],
    pros: ["Matter controller and Thread border-router functions", "Aqara Zigbee hub support for compatible Aqara devices", "Ethernet, PoE, Wi-Fi, USB-C power, and infrared control options"],
    cons: ["Does not make every legacy device a native Matter device", "Migration and ecosystem exposure vary by device", "Advanced setups still require protocol and controller planning"],
    specs: {
      ASIN: "B0CWLHSKYC",
      Model: "HM-G01D / HM-G01E; confirm regional version",
      Roles: "Matter controller, Thread border router, Aqara Zigbee hub",
      Network: "Ethernet with PoE and 2.4GHz/5GHz Wi-Fi",
      Power: "USB-C or compatible PoE",
      Infrared: "360° IR control for supported appliances",
    },
    evidence: [
      "Confirm the regional model and ecosystem support before migrating an existing Aqara home",
      "List which devices use Zigbee, Thread, Wi-Fi, infrared, and Matter before assuming one hub replaces every bridge",
      "Treat Matter exposure and native Matter-over-Thread operation as different integration paths",
    ],
    editorialSections: [
      {
        heading: "Four hub roles that sound similar",
        body: "The M3 can coordinate Aqara Zigbee devices, act as a Matter controller, provide a Thread border-router path, and expose supported devices to other ecosystems. Those roles overlap in the app but are not interchangeable.",
      },
      {
        heading: "When PoE is useful",
        body: "Ethernet with compatible Power over Ethernet can place the hub away from a crowded outlet while giving it a wired network path. Check the switch or injector standard and cable route before treating PoE as automatic.",
      },
      {
        heading: "Migration needs a device list",
        body: "Before replacing an older Aqara hub, inventory automations, child devices, infrared scenes, ecosystem links, and household access. Move a small group first and verify behavior before resetting the old hub.",
      },
    ],
    sources: [
      {
        name: "Aqara Hub M3 product page",
        url: "https://www.aqara.com/us/product/hub-m3/",
        note: "Official protocol, networking, power, infrared, and ecosystem information.",
      },
      {
        name: "Aqara Hub M3 specifications",
        url: "https://www.aqara.com/us/product/hub-e1/hub-m3-specs/",
        note: "Official model and hardware specifications.",
      },
    ],
    compareSlugs: ["aqara-door-and-window-sensor-p2", "aqara-smart-lock-u400"],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4wiir5x",
        label: "Check Aqara Hub M3 price on Amazon",
        priceNote: "Confirm ASIN B0CWLHSKYC, regional version, seller, and included power accessories.",
      },
    ],
  },
  {
    site: "smarthome",
    slug: "aqara-door-and-window-sensor-p2",
    asin: "B0BTL8B72D",
    seoTitle: "Aqara Door and Window Sensor P2 Guide: Matter over Thread Setup",
    updatedAt,
    name: "Aqara Door and Window Sensor P2",
    brand: "Aqara",
    category: "automation",
    image: "/images/affiliate/smarthome-aqara-door-window-sensor-p2.svg",
    summary: "A setup-focused guide to Aqara's Matter-over-Thread contact sensor, including the controller and border-router requirements, magnet alignment, battery access, automations, and the difference from Zigbee Aqara sensors.",
    verdict: "The P2 is a clean contact-sensor choice when the home already has a compatible Matter controller and Thread border router. A Zigbee Aqara sensor may be simpler for an established Aqara hub installation that does not need native Matter over Thread.",
    whyItMatters: "The sensor does not join an Aqara Zigbee hub like older Aqara contact sensors. Its Thread network and Matter commissioning path must be ready before the small hardware can become useful.",
    bestFor: "Native Matter-over-Thread door and window automations",
    priceBand: "$",
    rating: 4.3,
    scores: [
      { label: "Ecosystem reach", value: 9 },
      { label: "Installation", value: 8 },
      { label: "Controller clarity", value: 6 },
    ],
    pros: ["Native Matter over Thread", "Works across compatible Matter ecosystems", "Simple open-and-closed state enables many automations"],
    cons: ["Requires a compatible Matter controller and Thread border router", "Not an Aqara Zigbee child device", "Placement and magnet alignment control reliability"],
    specs: {
      ASIN: "B0BTL8B72D",
      Model: "DW-S02D / DW-S02E; confirm regional version",
      Protocol: "Matter over Thread",
      Requirement: "Compatible Matter controller and Thread border router",
      Battery: "CR123A",
      Detection: "Open and closed contact state",
    },
    evidence: [
      "Confirm the chosen ecosystem provides both Matter control and a compatible Thread border router",
      "Dry-fit the sensor and magnet before using permanent adhesive",
      "Check door or window clearance and battery access through the full opening path",
    ],
    editorialSections: [
      {
        heading: "P2 is not the older Zigbee contact sensor",
        body: "The P2 commissions through Matter and communicates over Thread. Do not follow a Zigbee pairing guide or buy an Aqara hub solely on the assumption that every Aqara sensor joins it in the same way.",
      },
      {
        heading: "Controller and border router are separate checks",
        body: "Some ecosystem devices perform both roles, while others do not. Verify the exact Apple, Google, Alexa, SmartThings, Home Assistant, or Aqara controller model and current software before installation.",
      },
      {
        heading: "The magnet gap is part of the setup",
        body: "Test the reported state while opening and closing the door before committing the adhesive. Avoid mounting positions that collide, flex, or make battery replacement difficult.",
      },
    ],
    sources: [
      {
        name: "Aqara Door and Window Sensor P2",
        url: "https://www.aqara.com/us/product/door-and-window-sensor-p2/",
        note: "Official protocol, battery, setup, and ecosystem requirements.",
      },
    ],
    compareSlugs: ["aqara-hub-m3"],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/3RceNLC",
        label: "Check Aqara P2 price on Amazon",
        priceNote: "Confirm ASIN B0BTL8B72D and the Matter-over-Thread P2 model.",
      },
    ],
  },
  {
    site: "smarthome",
    slug: "tapo-p125m-matter-smart-plug",
    asin: "B0BXMNJDW3",
    seoTitle: "Tapo P125M Review Guide: Matter Smart Plug Compatibility",
    updatedAt,
    name: "Tapo P125M Matter Smart Plug (3-Pack)",
    brand: "Tapo",
    category: "automation",
    image: "/images/affiliate/smarthome-tapo-p125m-smart-plug.svg",
    summary: "A model-correct guide to the compact P125M Matter smart plug, covering 15A loads, 2.4GHz Wi-Fi, ecosystem commissioning, local controls, schedules, and the lack of energy monitoring.",
    verdict: "The P125M is a practical Matter plug for lamps and ordinary plug-in appliances when compact size and broad ecosystem control matter. Choose an energy-monitoring model instead when usage data is the reason for buying.",
    whyItMatters: "Smart-plug families reuse similar names while changing Matter, HomeKit, energy-monitoring, and pack-count features. The linked offer is the P125M three-pack, not the P125 or P110M.",
    bestFor: "Compact Matter control for lamps and ordinary appliances",
    priceBand: "$",
    rating: 4.5,
    scores: [
      { label: "Ecosystem fit", value: 9 },
      { label: "Outlet fit", value: 9 },
      { label: "Energy insight", value: 2 },
    ],
    pros: ["Matter support for compatible ecosystems", "Compact body is designed to avoid blocking the second outlet", "Tapo app schedules, timers, and away-mode controls"],
    cons: ["2.4GHz Wi-Fi only", "No energy-monitoring feature", "Not suitable for loads outside the listed electrical rating"],
    specs: {
      ASIN: "B0BXMNJDW3",
      Model: "P125M",
      Pack: "3-pack",
      Electrical: "15A / 1800W maximum listed; follow load restrictions",
      Network: "2.4GHz Wi-Fi",
      Ecosystems: "Matter-compatible Apple Home, Alexa, Google Home, and SmartThings",
      "Energy monitoring": "No",
    },
    evidence: [
      "Confirm P125M and the three-pack before checkout",
      "Check the appliance's running and startup load against the plug's rating and restrictions",
      "Use the physical button and original appliance controls as a fallback",
    ],
    editorialSections: [
      {
        heading: "The M suffix matters",
        body: "P125M is the Matter version. P125 and P110M are different products with different ecosystem and energy features, so model numbers should stay visible in comparisons and setup instructions.",
      },
      {
        heading: "Matter does not remove Wi-Fi setup",
        body: "The plug still needs a suitable 2.4GHz network and a compatible Matter controller for the selected ecosystem. Keep the Matter setup code until commissioning and household sharing are complete.",
      },
      {
        heading: "Choose loads conservatively",
        body: "Use the plug for supported plug-in loads and follow Tapo's electrical restrictions. Avoid treating a headline 15A rating as approval for every heater, motor, compressor, or safety-critical appliance.",
      },
    ],
    sources: [
      {
        name: "TP-Link Tapo P125M product page",
        url: "https://www.tp-link.com/us/home-networking/smart-plug/tapo-p125m/",
        note: "Official Matter, electrical, network, app, and compatibility details.",
      },
    ],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4y3dwqY",
        label: "Check Tapo P125M 3-pack price on Amazon",
        priceNote: "Confirm ASIN B0BXMNJDW3, model P125M, and three-pack quantity.",
      },
    ],
  },
  {
    site: "baby",
    slug: "babybjorn-carrier-harmony",
    asin: "B0947B35TG",
    seoTitle: "BabyBjörn Carrier Harmony Review Guide: Fit, Mesh & Positions",
    updatedAt,
    name: "BabyBjörn Carrier Harmony 3D Mesh",
    brand: "BabyBjörn",
    category: "travel",
    image: "/images/affiliate/baby-babybjorn-carrier-harmony.svg",
    summary: "A fit-first guide to Carrier Harmony's newborn sizing, 3D mesh, head support, pressure-relieving waist belt, carry positions, and the practical differences from Ergobaby Omni Breeze.",
    verdict: "Carrier Harmony is the cleaner choice for caregivers who prefer its front-buckle workflow and soft structured feel. Omni Breeze offers a higher listed maximum weight and hip carry, so the better carrier depends on body fit and intended positions rather than brand reputation.",
    whyItMatters: "Carrier comfort cannot be established from specifications alone. The baby's size, developmental milestone, adult torso, strap path, and return window matter more than a small difference in product weight.",
    bestFor: "Soft structured mesh with front-access buckles",
    priceBand: "$$$",
    rating: 4.6,
    scores: [
      { label: "Material comfort", value: 9 },
      { label: "Adjustment access", value: 9 },
      { label: "Long-range capacity", value: 7 },
    ],
    pros: ["Soft 3D mesh and adjustable head support", "Front-access buckles can simplify loading and unloading", "Inward, outward, and back-carry options at the stated milestones"],
    cons: ["No hip-carry position", "Higher price than many structured carriers", "Fit remains personal despite broad adjustment range"],
    specs: {
      ASIN: "B0947B35TG",
      Material: "3D mesh",
      "Listed range": "7–40lb / 3.2–18kg",
      Positions: "Front inward, front outward, and back carry",
      "Newborn use": "Follow minimum size and head-support instructions",
      "Linked color": "Silver; confirm selected variation",
    },
    evidence: [
      "Confirm the baby meets the listed size and developmental requirements for the chosen position",
      "Use inward-facing newborn setup and keep the face and airway visible",
      "Evaluate caregiver comfort while the return window is still open",
    ],
    editorialSections: [
      {
        heading: "Harmony versus Omni Breeze",
        body: "Harmony emphasizes soft material and front-access buckles. Omni Breeze lists hip carry and a 45lb maximum. Neither difference predicts which waist belt and shoulder path will feel better on a particular caregiver.",
      },
      {
        heading: "Positions change with development",
        body: "Newborn use begins inward-facing. Outward and back carry have later age, size, and developmental requirements. Follow the Harmony manual for the exact head-support and zipper settings instead of copying a marketing image.",
      },
      {
        heading: "Fit both adults independently",
        body: "Reset the waist belt, back support, shoulder straps, and head support for each wearer. A shared carrier is not a shared strap setting.",
      },
    ],
    sources: [
      {
        name: "BabyBjörn Carrier Harmony",
        url: "https://www.babybjorn.com/products/baby-carriers/baby-carrier-harmony/",
        note: "Official material, size range, positions, and adjustment guidance.",
      },
    ],
    compareSlugs: ["babybjorn-carrier-mini-3d-mesh", "ergobaby-omni-breeze-carrier"],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4v8GVNL",
        label: "Check BabyBjörn Harmony price on Amazon",
        priceNote: "Confirm ASIN B0947B35TG, 3D Mesh material, color, and seller.",
      },
    ],
  },
  {
    site: "network",
    slug: "tp-link-deco-be67-wifi-7-mesh",
    asin: "B0FQYQRZQX",
    seoTitle: "TP-Link Deco BE67 Review Guide: BE14000, 10GbE & BE63 Comparison",
    updatedAt,
    name: "TP-Link Deco BE67 Wi-Fi 7 Mesh (2-Pack)",
    brand: "TP-Link",
    category: "wifi",
    image: "/images/affiliate/network-tp-link-deco-be67-wifi-7-mesh.svg",
    summary: "A research-based guide to the Deco BE67 two-pack, covering BE14000 tri-band Wi-Fi 7, 10GbE, 2.5GbE, 6GHz, wired backhaul, device compatibility, and when it is worth paying more than BE63.",
    verdict: "Deco BE67 is the stronger choice for multi-gig homes that can use its 10GbE path and higher wireless capacity. BE63 remains the value choice when four 2.5GbE ports and BE10000 performance already cover the actual network.",
    whyItMatters: "The faster mesh only pays off when the modem, wired backhaul, switch, and clients can use it. Otherwise better placement or the less expensive BE63 can deliver the same practical result.",
    bestFor: "Premium Wi-Fi 7 mesh with a real 10GbE use case",
    priceBand: "$$$$",
    rating: 4.5,
    scores: [
      { label: "Wireless capacity", value: 10 },
      { label: "Multi-gig path", value: 9 },
      { label: "Value discipline", value: 6 },
    ],
    pros: ["Tri-band BE14000 Wi-Fi 7 with 6GHz", "10GbE plus 2.5GbE and 1GbE ports per unit", "Ethernet and wireless backhaul options"],
    cons: ["Costs more than BE63", "Only useful at full potential with compatible clients and wired equipment", "Two-pack coverage still depends on layout and placement"],
    specs: {
      ASIN: "B0FQYQRZQX",
      Pack: "2-pack",
      Wireless: "BE14000 tri-band Wi-Fi 7",
      Bands: "2.4GHz, 5GHz, and 6GHz",
      Ports: "1×10GbE, 1×2.5GbE, and 1×1GbE per unit",
      "Listed coverage": "Up to 6,000 sq. ft. for the 2-pack",
      Backhaul: "Wireless or Ethernet",
    },
    evidence: [
      "Confirm the linked offer is the BE67 two-pack and ASIN B0FQYQRZQX",
      "Map the modem, WAN, switch, backhaul, and client port speeds before paying for 10GbE",
      "Check exact client support for Wi-Fi 7, 6GHz, 320MHz channels, and MLO",
    ],
    editorialSections: [
      {
        heading: "BE67 versus BE63",
        body: "BE67 raises the wireless class and adds a 10GbE port, while BE63 provides four 2.5GbE ports. The upgrade is easiest to justify for a 5Gbps or 10Gbps WAN, fast NAS path, capable clients, or a demanding wireless backhaul.",
      },
      {
        heading: "Port mix matters more than the largest port",
        body: "One 10GbE port can be consumed by WAN or a fast LAN path. Draw the topology before buying, especially if satellites, switches, desktops, and storage all need multi-gig Ethernet.",
      },
      {
        heading: "Coverage remains a placement problem",
        body: "The listed square footage is a planning figure, not a guarantee through every wall and floor. Start with two well-connected nodes and test before adding more mesh units.",
      },
    ],
    sources: [
      {
        name: "TP-Link Deco BE67 product page",
        url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be67/",
        note: "Official wireless class, coverage, ports, backhaul, and feature specifications.",
      },
    ],
    compareSlugs: ["tp-link-deco-be63-wifi-7-mesh", "tp-link-deco-be85-wifi-7-mesh"],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4y4b03Q",
        label: "Check Deco BE67 2-pack price on Amazon",
        priceNote: "Confirm ASIN B0FQYQRZQX, model BE67, and two-pack quantity.",
      },
    ],
  },
  {
    site: "pet",
    slug: "levoit-vital-200s-p-air-purifier",
    asin: "B0BGPF71Q6",
    seoTitle: "Levoit Vital 200S-P Guide: Pet Hair, Dander, Odor & Filter Costs",
    updatedAt,
    name: "Levoit Vital 200S-P Air Purifier",
    brand: "Levoit",
    category: "home-care",
    image: "/images/affiliate/pet-levoit-vital-200s-p-air-purifier.svg",
    summary: "A pet-home guide to the Vital 200S-P's washable pre-filter, U-shaped inlet, particle sensor, app controls, replaceable filter, and practical comparison with Shark NeverChange MAX.",
    verdict: "Vital 200S-P is the value choice for a pet room when a washable pre-filter, broad replacement-filter availability, and smart scheduling matter. Shark HP302 is the larger-room alternative for buyers prioritizing debris screens and longer claimed HEPA-filter life.",
    whyItMatters: "Pet hair, airborne dander, and odor sources require different responses. A purifier can help with particles and some airborne odors, but it cannot replace litter, bedding, upholstery, and accident cleaning.",
    bestFor: "Pet rooms needing a washable pre-filter and smart controls",
    priceBand: "$$",
    rating: 4.7,
    scores: [
      { label: "Pet-hair intake", value: 9 },
      { label: "Smart controls", value: 9 },
      { label: "Filter cost clarity", value: 7 },
    ],
    pros: ["Washable pre-filter catches larger hair and dust", "U-shaped inlet and Pet Mode target pet-room use", "VeSync schedules, air-quality display, and automatic modes"],
    cons: ["Main filter remains a recurring replacement cost", "Coverage changes with desired air changes per hour", "Cannot solve persistent odor at its source"],
    specs: {
      ASIN: "B0BGPF71Q6",
      Model: "Vital 200S-P",
      "Linked color": "White",
      "Listed maximum coverage": "Up to 1,875 sq. ft. at one air change per hour",
      "Pre-filter": "Washable",
      Controls: "VeSync app, auto mode, schedules, and air-quality display",
      Filter: "Replaceable multi-stage filter; confirm current part number and cost",
    },
    evidence: [
      "Size the purifier by room volume and desired air changes, not maximum coverage alone",
      "Vacuum or wash the pre-filter on the manufacturer schedule and allow it to dry fully",
      "Check replacement-filter price and availability before comparing the machine price",
    ],
    editorialSections: [
      {
        heading: "Vital 200S-P versus Shark HP302",
        body: "Levoit uses a washable pre-filter and conventional replacement-filter schedule. Shark emphasizes removable debris screens and a long-life HEPA claim. Compare room size, filter cost, fragrance tolerance, controls, and floor space rather than choosing from one coverage number.",
      },
      {
        heading: "Coverage needs an air-change context",
        body: "The maximum 1,875-square-foot figure represents a slower full-room cleaning cycle. Bedrooms and pet rooms usually benefit from sizing around multiple air changes per hour, adjusted for ceilings, doors, and pollutant load.",
      },
      {
        heading: "Source cleaning still wins on odor",
        body: "Place the purifier where air can circulate, but continue scooping litter, washing bedding, vacuuming upholstery, and cleaning accidents. Carbon media can support odor control without removing the source.",
      },
    ],
    sources: [
      {
        name: "Levoit Vital 200S-P product page",
        url: "https://levoit.com/products/vital-200s-p-smart-air-purifier",
        note: "Official room, filtration, app, pre-filter, and operating information.",
      },
      {
        name: "AHAM Verifide directory",
        url: "https://ahamverifide.org/directory-of-air-cleaners/",
        note: "Independent directory for current certified room-air-cleaner performance data.",
      },
    ],
    compareSlugs: ["coway-airmega-mighty2-air-purifier", "winix-5510-air-purifier", "shark-neverchange-max-air-purifier"],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4vaR2RX",
        label: "Check Levoit Vital 200S-P price on Amazon",
        priceNote: "Confirm ASIN B0BGPF71Q6, white Vital 200S-P, seller, and included filter.",
      },
    ],
  },
];

export const adjacentExpansionRoundups: Roundup[] = [
  {
    site: "baby",
    slug: "babybjorn-harmony-vs-ergobaby-omni-breeze",
    title: "BabyBjörn Harmony vs. Ergobaby Omni Breeze",
    dek: "Compare fit workflow, mesh, carry positions, listed weight range, lumbar support, and which differences matter before trying either carrier.",
    category: "travel",
    intent: "Choose between two premium breathable structured baby carriers without pretending specifications can replace a fit test.",
    intro: "Harmony and Omni Breeze both target parents who want a breathable all-stage structured carrier. Harmony emphasizes soft material and front-access buckles; Omni Breeze adds hip carry and a higher listed maximum. The return window remains part of the buying decision.",
    decisionGuide: [
      { label: "Front buckles", detail: "Harmony is easier to shortlist when front-access fastening is the preferred workflow." },
      { label: "Hip carry", detail: "Omni Breeze is the candidate because Harmony does not list a hip-carry position." },
      { label: "Higher maximum", detail: "Omni Breeze lists 45lb versus Harmony's 40lb." },
      { label: "Personal comfort", detail: "Try the waist belt and shoulder path with realistic weight before deciding." },
    ],
    methodology: ["Compare official position and size limits", "Keep newborn and later-position rules separate", "Treat caregiver fit and returns as decision criteria"],
    productSlugs: ["babybjorn-carrier-harmony", "ergobaby-omni-breeze-carrier"],
    faqs: [
      { question: "Which carrier is cooler?", answer: "Both use breathable mesh, but heat also depends on body contact, clothing, weather, activity, and fit." },
      { question: "Which is easier to put on?", answer: "Harmony's front buckles suit some caregivers; others prefer Omni Breeze after learning its strap sequence." },
      { question: "Can both carry a newborn?", answer: "Both list newborn use from stated minimums, but only in the correct inward-facing setup with the required head support." },
    ],
  },
  {
    site: "network",
    slug: "tp-link-deco-be67-vs-be63",
    title: "TP-Link Deco BE67 vs. BE63",
    dek: "Compare BE14000 and BE10000 wireless capacity, 10GbE versus four 2.5GbE ports, coverage, backhaul, and the network required to notice the upgrade.",
    category: "wifi",
    intent: "Decide whether Deco BE67's 10GbE path and added wireless capacity are worth paying over BE63.",
    intro: "BE67 is faster on paper, but BE63 can be the better-designed purchase for a home built around several 2.5GbE devices. The right choice follows the modem, switch, backhaul, client, and room layout.",
    decisionGuide: [
      { label: "10GbE WAN or NAS", detail: "BE67 provides the clearer upgrade path." },
      { label: "Several 2.5GbE devices", detail: "BE63's four equal 2.5GbE ports can be more convenient." },
      { label: "Typical gigabit internet", detail: "BE63 usually leaves more budget for wiring and placement." },
      { label: "Wireless backhaul load", detail: "BE67's higher class may help when nodes cannot be wired." },
    ],
    methodology: ["Map port use before wireless class", "Compare the same pack size", "Separate aggregate link rates from client throughput"],
    productSlugs: ["tp-link-deco-be67-wifi-7-mesh", "tp-link-deco-be63-wifi-7-mesh"],
    faqs: [
      { question: "Is BE67 always faster?", answer: "No. Client support, channel conditions, backhaul, WAN speed, and placement control real throughput." },
      { question: "Do both support wired backhaul?", answer: "Yes, but the negotiated speed follows the slowest port, switch, cable, or wall link in the path." },
      { question: "Should a gigabit home buy BE67?", answer: "Only for a specific coverage, capacity, or future multi-gig plan; otherwise BE63 or a simpler mesh may be enough." },
    ],
  },
  {
    site: "pet",
    slug: "levoit-vital-200s-p-vs-shark-neverchange-max",
    title: "Levoit Vital 200S-P vs. Shark NeverChange MAX for Pet Homes",
    dek: "Compare pet-hair pre-filtration, room sizing, odor strategy, controls, filter replacement, fragrance, and the maintenance each purifier still requires.",
    category: "home-care",
    intent: "Choose a pet-room air purifier by room and maintenance needs instead of the biggest coverage claim.",
    intro: "Levoit is the value-oriented smart purifier with a washable pre-filter. Shark is the larger unit with debris screens and a long-life HEPA claim. Neither replaces source cleaning, and their maximum coverage figures need an air-change context.",
    decisionGuide: [
      { label: "Lower purchase price", detail: "Vital 200S-P is usually the more restrained starting point." },
      { label: "Large open pet area", detail: "Compare HP302 when its size and airflow suit the room." },
      { label: "Fragrance-sensitive home", detail: "Levoit avoids making a scented cartridge central to the purchase." },
      { label: "Filter routine", detail: "Compare conventional replacement cost with Shark's conditional long-life claim." },
    ],
    methodology: ["Compare room size at equivalent air changes", "Separate hair, dander, and odor sources", "Include filters and maintenance in total cost"],
    productSlugs: ["levoit-vital-200s-p-air-purifier", "shark-neverchange-max-air-purifier"],
    faqs: [
      { question: "Will either purifier remove pet hair from furniture?", answer: "No. Pre-filters catch airborne hair, but upholstery and floors still need vacuuming or brushing." },
      { question: "Which removes litter odor better?", answer: "Source cleaning comes first. Carbon media can help with remaining airborne odor, but no purifier fixes a dirty box." },
      { question: "Does NeverChange mean no maintenance?", answer: "No. Debris screens and odor components still need attention, and the HEPA claim depends on stated use conditions." },
    ],
  },
  {
    site: "smarthome",
    slug: "matter-starter-kit-hub-sensor-smart-plug",
    title: "Matter Starter Kit: Hub, Contact Sensor and Smart Plug",
    dek: "Build a small Matter setup with Aqara Hub M3, Aqara P2, and Tapo P125M while keeping Thread, Wi-Fi, controllers, and ecosystem sharing clear.",
    category: "automation",
    intent: "Start with a few useful Matter devices without buying overlapping controllers or confusing Thread with Wi-Fi.",
    intro: "A hub, contact sensor, and smart plug create a useful first automation: when a door opens after dark, a lamp can turn on. The setup works only when each device's network and controller requirements are understood.",
    decisionGuide: [
      { label: "Need Thread", detail: "Hub M3 can provide a Thread border-router and Matter-controller path." },
      { label: "Door state", detail: "Aqara P2 reports open and closed over Matter over Thread." },
      { label: "Control a lamp", detail: "Tapo P125M uses Matter over 2.4GHz Wi-Fi." },
      { label: "Already own controllers", detail: "Check existing Apple, Google, Alexa, SmartThings, or Home Assistant hardware before adding another hub." },
    ],
    methodology: ["Map protocols before brands", "Commission one ecosystem first", "Test physical fallbacks and household sharing"],
    productSlugs: ["aqara-hub-m3", "aqara-door-and-window-sensor-p2", "tapo-p125m-matter-smart-plug"],
    faqs: [
      { question: "Does every Matter device use Thread?", answer: "No. Aqara P2 uses Thread, while Tapo P125M uses Wi-Fi." },
      { question: "Do I always need Hub M3?", answer: "No. Another compatible Matter controller and Thread border router may already cover the P2." },
      { question: "Will Matter expose every advanced feature?", answer: "Not necessarily. Vendor apps can retain model-specific settings beyond the common Matter feature set." },
    ],
  },
];

export const adjacentExpansionGuides: Guide[] = [
  {
    site: "smarthome",
    slug: "aqara-hub-m3-matter-thread-setup",
    title: "Aqara Hub M3 Matter and Thread Setup Checklist",
    dek: "Map controllers, Thread border routers, ecosystems, Ethernet or Wi-Fi, and migration steps before adding child devices.",
    category: "automation",
    updatedAt,
    relatedProducts: ["aqara-hub-m3", "aqara-door-and-window-sensor-p2"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    sources: [
      { name: "Aqara Hub M3", url: "https://www.aqara.com/us/product/hub-m3/", note: "Official roles and setup information." },
      { name: "Matter overview", url: "https://csa-iot.org/all-solutions/matter/", note: "Connectivity Standards Alliance overview of Matter roles and multi-admin." },
    ],
    sections: [
      { heading: "Inventory existing controllers first", body: "List Apple Home hubs, Google hubs, Echo devices, SmartThings hubs, Home Assistant, and older Aqara hubs. Note which devices are Matter controllers and which are Thread border routers." },
      { heading: "Choose the primary commissioning ecosystem", body: "Add the M3 and first devices in the ecosystem that will own day-to-day setup. Share them to secondary Matter ecosystems only after basic control and automations work." },
      { heading: "Choose Ethernet, PoE, or Wi-Fi deliberately", body: "A wired path can reduce one variable during setup. If using PoE, confirm the switch or injector and cable route; otherwise plan USB-C power and network placement together." },
      { heading: "Migrate in small groups", body: "Move one sensor or automation at a time, verify household access and notifications, and keep the old hub available until the important routines have survived several normal days." },
    ],
  },
  {
    site: "smarthome",
    slug: "matter-thread-wifi-zigbee-device-checklist",
    title: "Matter, Thread, Wi-Fi and Zigbee Device Checklist",
    dek: "Identify the application standard, radio network, controller, border router, and bridge required by each smart-home device.",
    category: "automation",
    updatedAt,
    relatedProducts: ["aqara-hub-m3", "aqara-door-and-window-sensor-p2", "tapo-p125m-matter-smart-plug"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    sources: [
      { name: "Matter overview", url: "https://csa-iot.org/all-solutions/matter/", note: "Primary standards-organization overview." },
      { name: "Thread Group overview", url: "https://www.threadgroup.org/What-is-Thread", note: "Primary Thread networking overview." },
    ],
    sections: [
      { heading: "Matter describes interoperability, not one radio", body: "Matter can run over Thread, Wi-Fi, or Ethernet. A Matter logo therefore does not reveal whether the device needs a Thread border router or joins the home Wi-Fi." },
      { heading: "Thread needs a border router", body: "Thread devices join a low-power mesh and need a compatible border router to reach the wider IP network. A Matter controller may or may not include that role." },
      { heading: "Zigbee normally needs a brand or compatible hub", body: "Legacy Aqara Zigbee devices do not become Thread devices. A bridge can expose supported functions to Matter while the device remains on its Zigbee network." },
      { heading: "Write the five-part requirement", body: "For each product record its protocol, radio, controller, border router or bridge, and primary app. This small table prevents most hub-shopping mistakes." },
    ],
  },
  {
    site: "network",
    slug: "deco-be67-10gbe-network-checklist",
    title: "Deco BE67 10GbE Network Checklist",
    dek: "Verify the WAN, switch, NAS, client adapters, backhaul, and cables required to make the BE67 upgrade meaningful.",
    category: "wifi",
    updatedAt,
    relatedProducts: ["tp-link-deco-be67-wifi-7-mesh", "tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["tp-link-deco-be67-vs-be63", "best-mesh-wifi-for-apartments-and-homes"],
    sources: [
      { name: "TP-Link Deco BE67", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be67/", note: "Official port and wireless specifications." },
    ],
    sections: [
      { heading: "Start at the internet handoff", body: "Confirm the modem or ONT presents a compatible multi-gig Ethernet port and that the service plan exceeds gigabit before reserving BE67's 10GbE port for WAN." },
      { heading: "Choose the 10GbE job", body: "Decide whether the port serves WAN, a 10GbE switch, or a fast local storage path. One port cannot simultaneously be the physical endpoint for every use case." },
      { heading: "Audit every slower link", body: "A 1GbE wall jack path, 2.5GbE switch, USB adapter, or satellite port limits that branch. This is normal; only upgrade the branches that have a measured need." },
      { heading: "Keep wireless expectations client-specific", body: "Check the exact laptop or phone radio for Wi-Fi 7, 6GHz, channel width, streams, and MLO. Aggregate BE14000 speed is not one client's transfer rate." },
    ],
  },
  {
    site: "pet",
    slug: "air-purifier-pet-hair-dander-odor-guide",
    title: "Air Purifier Guide for Pet Hair, Dander and Odor",
    dek: "Separate large hair, airborne particles, and odor sources before sizing a purifier or comparing filter claims.",
    category: "home-care",
    updatedAt,
    relatedProducts: ["levoit-vital-200s-p-air-purifier", "shark-neverchange-max-air-purifier"],
    relatedRoundups: ["levoit-vital-200s-p-vs-shark-neverchange-max", "best-pet-odor-and-litter-upgrades"],
    sources: [
      { name: "EPA air cleaners guidance", url: "https://www.epa.gov/indoor-air-quality-iaq/air-cleaners-and-air-filters-home", note: "Primary guidance on filtration, room sizing, and source control." },
      { name: "AHAM Verifide directory", url: "https://ahamverifide.org/directory-of-air-cleaners/", note: "Certified room-air-cleaner performance data." },
    ],
    sections: [
      { heading: "Hair is mainly a surface-cleaning problem", body: "Pre-filters can catch some airborne hair, but floors, bedding, upholstery, and brushes collect most visible hair. Keep vacuuming and washable-fabric routines in the plan." },
      { heading: "Dander is the particle-filtration job", body: "Size the purifier for the room and desired air changes, place it with open intake and exhaust space, and run it long enough to circulate the room air." },
      { heading: "Odor begins with source control", body: "Scoop litter, clean accidents, wash bedding, control moisture, and ventilate when outdoor conditions allow. Carbon media can support the remaining airborne odor." },
      { heading: "Compare maintenance as a yearly routine", body: "Add pre-filter cleaning, main-filter cost, replacement availability, sensor cleaning, and any odor cartridge. A low-maintenance claim should still be translated into actual household tasks." },
    ],
  },
];
