import type { Guide, Product, Roundup } from "./types";

const updatedAt = "July 1, 2026";

export const adjacentExpansionProducts: Product[] = [
  {
    site: "smarthome",
    slug: "aqara-hub-m3",
    asin: "B0CWLHSKYC",
    seoTitle: "Aqara Hub M3 Review: Matter, Thread, PoE & M2 Upgrade",
    updatedAt: "July 16, 2026",
    name: "Aqara Hub M3",
    brand: "Aqara",
    category: "automation",
    image: "/images/affiliate/smarthome-aqara-hub-m3-realistic.webp",
    summary: "A source-backed Aqara Hub M3 review covering Matter controller and bridge roles, Thread border routing, Zigbee migration, Home Assistant, PoE, infrared control, and whether M2 owners should upgrade.",
    verdict: "Buy the Hub M3 when Aqara Home will be the center of a mixed Zigbee, Thread, and Matter installation, or when PoE and local Aqara automations solve a real placement or reliability problem. Keep an M2 or existing controller when stable Zigbee automations already work and the M3's Thread, third-party Matter, or PoE roles would go unused.",
    whyItMatters: "The M3 can be an Aqara Zigbee hub, Matter controller, Matter bridge, and Thread border router, but those are separate jobs. Naming the devices assigned to each job prevents the common assumption that buying one hub automatically migrates every device or exposes every feature to every ecosystem.",
    bestFor: "Aqara-centered homes that need Thread, Matter bridging, and wired PoE placement",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Protocol coverage", value: 9 },
      { label: "Local automation", value: 8 },
      { label: "Setup simplicity", value: 6 },
    ],
    pros: ["Combines Matter controller, Matter bridge, Thread border-router, and Aqara Zigbee hub roles", "Dual-band Wi-Fi, Ethernet with PoE, and USB-C offer flexible network and power placement", "Local storage, local automations, infrared control, and a built-in speaker broaden its use beyond simple bridging"],
    cons: ["Supported third-party Matter device types and bridged features remain narrower than each vendor's native app", "M2-to-M3 migration and ecosystem sharing still require device-by-device checks", "A power adapter is not included and PoE requires compatible network equipment"],
    specs: {
      ASIN: "B0CWLHSKYC",
      Model: "HM-G01D / HM-G01E; confirm regional version",
      Roles: "Matter controller, Matter bridge, Thread border router, Aqara Zigbee hub",
      Capacity: "Up to 127 Thread and Zigbee devices; repeaters can be required",
      Network: "2.4GHz/5GHz Wi-Fi, Ethernet, WPA3, and PoE",
      Power: "5V 2A USB-C or 48V 0.27A PoE; adapter not included",
      Storage: "8GB eMMC with encrypted local storage",
      Infrared: "360-degree IR control with supported feedback and AC use cases",
      Dimensions: "105 x 105 x 36.5 mm",
    },
    evidence: [
      "Confirm ASIN B0CWLHSKYC, the regional HM-G01D/HM-G01E variant, seller, and included power accessories",
      "List which devices use Zigbee, Thread, Wi-Fi, infrared, and Matter before assuming one hub replaces every controller",
      "Check Aqara's current exposed-device list because Matter bridging does not publish every proprietary feature",
      "Verify the Aqara Home migration path on a small device group before resetting an existing M2 or other Aqara hub",
      "For Home Assistant, distinguish adding M3 as a Matter bridge from operating Home Assistant's own Matter controller and Thread network",
    ],
    editorialSections: [
      {
        heading: "A note about this review",
        body: "This is a research-based decision guide built from Aqara's current US product page, developer documentation, manual, and Home Assistant's current Matter documentation. It is not a long-term hands-on reliability test, and firmware, bridged device types, ecosystem features, and retailer bundles can change after publication.",
      },
      {
        heading: "Four roles that should not be collapsed into one label",
        body: "The M3 can coordinate compatible Aqara Zigbee devices, commission supported Matter devices into Aqara Home, bridge supported Aqara devices to other Matter ecosystems, and route Thread traffic. A device exposed through the Matter bridge remains on its original network; it does not become a native Matter-over-Thread device.",
      },
      {
        heading: "M3 versus M2 is an upgrade decision, not a generation contest",
        body: "M2 remains useful for a stable Aqara Zigbee installation with Ethernet and infrared control. M3 earns its higher cost when Thread devices, third-party Matter control in Aqara Home, PoE placement, local edge automations, or broader bridging are part of a written plan. Existing M2 owners should name the missing role before migrating.",
      },
      {
        heading: "Matter compatibility is narrower than the logo suggests",
        body: "Aqara lists selected third-party Matter device categories and notes that device support can vary by ecosystem. The common Matter controls may work while vendor-specific settings, scenes, energy details, infrared functions, or advanced sensor data remain in the Aqara app. Check the exact child-device type rather than assuming the whole account will appear elsewhere.",
      },
      {
        heading: "Home Assistant can use M3 as a Matter bridge",
        body: "Home Assistant's Matter integration acts as a separate Matter controller. The M3 can share supported bridged devices into that controller, but feature exposure is limited by both Aqara's bridge and Home Assistant's supported Matter device types. Keep IPv6 and local discovery working and do not assume the M3 automatically merges every existing Thread network.",
      },
      {
        heading: "PoE is useful only when the cable path is deliberate",
        body: "A compatible PoE port can carry data and power to a central wall, ceiling, or utility location. Confirm the switch or injector, cable route, network segment, and mounting position first. USB-C remains the simpler choice when the hub can sit beside a stable outlet and Ethernet drop.",
      },
      {
        heading: "Migration needs an exit plan",
        body: "Inventory child devices, automations, infrared scenes, ecosystem links, family access, and notification dependencies before replacing an older Aqara hub. Move a small group first, verify it for several normal days, and keep the old hub available until critical routines and physical fallbacks are proven.",
      },
      {
        heading: "Who should skip it",
        body: "Skip the M3 when an existing Apple, Google, SmartThings, Home Assistant, or Aqara controller already provides every required role and no Aqara Zigbee, infrared, PoE, or Aqara Home automation need remains. Adding another controller can increase commissioning and troubleshooting work without improving the household routine.",
      },
    ],
    alternatives: [
      "Keep Hub M2 when existing Aqara Zigbee automations are stable and Thread, PoE, and third-party Matter control are not required.",
      "Use an existing compatible Matter controller and Thread border router when the home has no Aqara Zigbee or infrared plan.",
      "Choose a simpler Aqara hub when price and basic Zigbee bridging matter more than M3's combined controller roles.",
    ],
    sources: [
      {
        name: "Aqara Hub M3 US product page",
        url: "https://us.aqara.com/products/hub-m3",
        note: "Current official roles, device capacity, networking, power, storage, dimensions, and included components.",
      },
      {
        name: "Aqara Hub M3 developer documentation",
        url: "https://opendoc.aqara.com/en/docs/AqaraDevice/Hub-M3.html",
        note: "Official controller, bridge, Thread, Home Assistant, and supported-device-role documentation.",
      },
      {
        name: "Aqara Hub M3 user manual",
        url: "https://www.aqara.com/wp-content/uploads/2024/05/M3-User-Manual-1.pdf",
        note: "Official installation, model, power, network, reset, and safety reference.",
      },
      {
        name: "Aqara Hub M2 product page",
        url: "https://www.aqara.com/us/product/hub-m2/",
        note: "Official M2 Zigbee, Ethernet, infrared, speaker, and USB-power baseline used for the upgrade comparison.",
      },
    ],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4wiir5x",
        label: "Check Aqara Hub M3 price on Amazon",
        priceNote: "Confirm ASIN B0CWLHSKYC, regional version, seller, and included power accessories.",
      },
    ],
  },
  {
    site: "smarthome",
    slug: "aqara-door-and-window-sensor-p2",
    asin: "B0BTL8B72D",
    seoTitle: "Aqara P2 Review: Matter over Thread, Hub Requirements & Battery",
    updatedAt: "July 17, 2026",
    name: "Aqara Door and Window Sensor P2",
    brand: "Aqara",
    category: "automation",
    image: "/images/affiliate/smarthome-aqara-hub-m3-realistic.webp",
    summary: "A setup-focused guide to Aqara's Matter-over-Thread contact sensor, including controller and border-router requirements, magnet alignment, battery access, automations, and why it is closer to IKEA MYGGBETT than the Zigbee IKEA PARASOLL sensor.",
    verdict: "The P2 is a clean contact-sensor choice when the home already has a compatible Matter controller and Thread border router. A Zigbee Aqara sensor may be simpler for an established Aqara hub installation that does not need native Matter over Thread.",
    whyItMatters: "The sensor does not join an Aqara Zigbee hub like older Aqara contact sensors. Its Thread network and Matter commissioning path must be ready before the small hardware can become useful.",
    bestFor: "Native Matter-over-Thread door and window automations",
    priceBand: "$",
    rating: 4.3,
    scores: [
      { label: "Ecosystem reach", value: 9 },
      { label: "Installation", value: 8 },
      { label: "Controller clarity", value: 6 },
    ],
    pros: ["Native Matter over Thread", "Works across compatible Matter ecosystems", "Simple open-and-closed state enables many automations"],
    cons: ["Requires a compatible Matter controller and Thread border router", "Not an Aqara Zigbee child device", "Placement and magnet alignment control reliability"],
    specs: {
      ASIN: "B0BTL8B72D",
      Model: "DW-S02D / DW-S02E; confirm regional version",
      Protocol: "Matter over Thread",
      Requirement: "Compatible Matter controller and Thread border router",
      Battery: "CR123A",
      Detection: "Open and closed contact state",
    },
    evidence: [
      "Confirm the chosen ecosystem provides both Matter control and a compatible Thread border router",
      "Dry-fit the sensor and magnet before using permanent adhesive",
      "Check door or window clearance and battery access through the full opening path",
    ],
    editorialSections: [
      {
        heading: "P2 is not the older Zigbee contact sensor",
        body: "The P2 commissions through Matter and communicates over Thread. Do not follow a Zigbee pairing guide or buy an Aqara hub solely on the assumption that every Aqara sensor joins it in the same way.",
      },
      {
        heading: "IKEA PARASOLL is not a Matter-over-Thread equivalent",
        body: "IKEA's US PARASOLL listing and manual describe a Zigbee sensor that uses DIRIGERA for app notifications or can pair directly with compatible IKEA lighting. IKEA MYGGBETT is the separate Matter-over-Thread contact sensor. Compare P2 with MYGGBETT when Thread is the requirement; compare PARASOLL with other Zigbee sensors when a DIRIGERA-centered setup is the plan.",
      },
      {
        heading: "Controller and border router are separate checks",
        body: "Some ecosystem devices perform both roles, while others do not. Verify the exact Apple, Google, Alexa, SmartThings, Home Assistant, or Aqara controller model and current software before installation.",
      },
      {
        heading: "The magnet gap is part of the setup",
        body: "Test the reported state while opening and closing the door before committing the adhesive. Avoid mounting positions that collide, flex, or make battery replacement difficult.",
      },
    ],
    sources: [
      {
        name: "Aqara Door and Window Sensor P2",
        url: "https://www.aqara.com/us/product/door-and-window-sensor-p2/",
        note: "Official protocol, battery, setup, and ecosystem requirements.",
      },
      {
        name: "IKEA PARASOLL door/window sensor",
        url: "https://www.ikea.com/us/en/p/parasoll-door-window-sensor-smart-white-70504318/",
        note: "Official Zigbee-era DIRIGERA, direct-light pairing, battery, and mounting reference used to prevent protocol confusion.",
      },
      {
        name: "IKEA MYGGBETT door/window sensor",
        url: "https://www.ikea.com/us/en/p/myggbett-door-window-sensor-smart-60617641/",
        note: "Official Matter-over-Thread model and Thread Border Router requirement used for the closest IKEA comparison.",
      },
    ],
    compareSlugs: ["aqara-hub-m3"],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/3RceNLC",
        label: "Check Aqara P2 price on Amazon",
        priceNote: "Confirm ASIN B0BTL8B72D and the Matter-over-Thread P2 model.",
      },
    ],
  },
  {
    site: "smarthome",
    slug: "tapo-p110m-energy-monitoring-smart-plug",
    asin: "B0DKG52WQ4",
    amazonTitle: "Tapo P110M Smart Plug Mini, Matter Certified, Energy Monitoring (4-Pack)",
    amazonDetailUrl: "https://www.amazon.com/dp/B0DKG52WQ4",
    seoTitle: "Tapo P110M Review: Energy Monitoring, Matter & 4-Pack Checks",
    updatedAt: "July 12, 2026",
    name: "Tapo P110M Energy-Monitoring Smart Plug (4-Pack)",
    brand: "Tapo",
    category: "automation",
    image: "/images/affiliate/smarthome-smart-plug-realistic.webp",
    summary: "A model- and pack-aware guide to Tapo P110M, including energy monitoring, Matter setup, 2.4GHz Wi-Fi, electrical limits, and the difference between Tapo app data and third-party ecosystem controls.",
    verdict: "Tapo P110M is the better Tapo choice when energy monitoring is the reason for buying. Pick P125M instead when compact Matter on/off control matters more and usage data does not.",
    whyItMatters: "P110M and P125M look like close siblings, but they solve different shopping problems. The P110M listing also varies by region and pack count, so the model suffix, ASIN, and number of plugs must remain visible at checkout.",
    bestFor: "Energy monitoring for lamps and ordinary indoor plug-in loads",
    priceBand: "$$",
    rating: 4.4,
    scores: [
      { label: "Energy insight", value: 9 },
      { label: "Matter reach", value: 8 },
      { label: "Model clarity", value: 6 },
    ],
    pros: ["Energy monitoring in the Tapo app", "Matter-certified smart-plug path for compatible ecosystems", "Four-pack can cover several small household routines at once"],
    cons: ["Third-party Matter apps may expose fewer energy features than Tapo", "The linked Amazon listing is a four-pack; regional and pack variants are easy to confuse", "Electrical limits and appliance type still need checking before use"],
    specs: {
      ASIN: "B0DKG52WQ4",
      Model: "P110M",
      Pack: "4-pack; confirm current Amazon variation",
      Network: "2.4GHz Wi-Fi",
      Matter: "Matter-certified; verify current firmware and ecosystem feature exposure",
      "Energy monitoring": "Available in Tapo app; third-party availability may differ",
      Electrical: "15A / 1800W maximum listed; follow appliance restrictions",
    },
    evidence: [
      "Confirm ASIN B0DKG52WQ4, model P110M, and four-plug quantity before checkout",
      "Use the Tapo app as the baseline for energy history and confirm what the chosen Matter ecosystem exposes",
      "Check the appliance's running and startup load; do not treat a 15A headline as approval for every motor, compressor, heater, or safety-critical appliance",
      "Confirm the regional plug, voltage, seller, and return path because P110M pack and regional listings differ",
    ],
    editorialSections: [
      {
        heading: "P110M is the energy-monitoring branch",
        body: "Choose P110M when the household wants to see usage history, compare a lamp or appliance's consumption, or build a simple energy-aware routine. If the only requirement is remote on/off control, the less expensive P125M can be the more disciplined choice.",
      },
      {
        heading: "Tapo app and Matter do not expose identical controls",
        body: "Matter makes cross-ecosystem control possible, but the exact energy entities and history may depend on the current firmware and the third-party controller. Set up the plug in Tapo first, confirm energy data there, then verify the Apple Home, Google Home, Alexa, SmartThings, or Home Assistant path you actually plan to use.",
      },
      {
        heading: "The four-pack is part of the decision",
        body: "The linked US listing is a four-pack. Confirm that the cart still contains four P110M plugs rather than a single unit, a two-pack, or a closely named P125M bundle. A multi-pack only saves money when the household has four sensible indoor loads to automate.",
      },
      {
        heading: "Use it on ordinary indoor loads",
        body: "Follow Tapo's current electrical restrictions and keep the plug away from water, outdoor exposure, overloaded strips, and appliances whose startup behavior exceeds the rated use. Keep the appliance's physical switch and a manual fallback available when the load is important.",
      },
      {
        heading: "Who should skip it",
        body: "Skip P110M when energy data will not be used, when the home needs outdoor or high-load control, when the regional plug is wrong, or when a third-party ecosystem must expose every Tapo-specific feature without app setup. P125M is the simpler comparison for basic Matter on/off routines.",
      },
    ],
    alternatives: ["Choose Tapo P125M for compact Matter on/off control without energy monitoring.", "Choose a different energy-monitoring plug when the chosen ecosystem has a better-supported power dashboard.", "Use a local power meter when the job is a one-time measurement rather than an automation."],
    compareSlugs: ["tapo-p125m-matter-smart-plug"],
    sources: [
      {
        name: "TP-Link Tapo P110M US datasheet",
        url: "https://static.tp-link.com/upload/product-overview/2026/202603/20260324/Tapo%20P110M%28US%291.0_Datasheet.pdf",
        note: "Official US model, Matter, energy-monitoring, electrical, and network reference.",
      },
      {
        name: "Amazon listing for ASIN B0DKG52WQ4",
        url: "https://www.amazon.com/dp/B0DKG52WQ4",
        note: "Exact linked four-pack listing; confirm seller, quantity, regional plug, and current variation.",
      },
    ],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://www.amazon.com/dp/B0DKG52WQ4?tag=bingmada-20&linkCode=ll2&language=en_US&ref_=as_li_ss_tl",
        label: "Check Tapo P110M 4-pack on Amazon",
        priceNote: "Confirm ASIN B0DKG52WQ4, P110M model, four-pack quantity, regional plug, seller, and energy-monitoring details.",
      },
    ],
  },
  {
    site: "smarthome",
    slug: "tapo-p125m-matter-smart-plug",
    asin: "B0BXMNJDW3",
    seoTitle: "Tapo P125M Review: Matter Smart Plug vs. P110M Energy Monitoring",
    updatedAt: "July 11, 2026",
    name: "Tapo P125M Matter Smart Plug (3-Pack)",
    brand: "Tapo",
    category: "automation",
    image: "/images/affiliate/smarthome-smart-plug-realistic.webp",
    summary: "A model-correct guide to the compact P125M Matter smart plug, covering 15A loads, 2.4GHz Wi-Fi, ecosystem commissioning, local controls, schedules, and the lack of energy monitoring.",
    verdict: "The P125M is a practical Matter plug for lamps and ordinary plug-in appliances when compact size and broad ecosystem control matter. Choose an energy-monitoring model instead when usage data is the reason for buying.",
    whyItMatters: "Smart-plug families reuse similar names while changing Matter, HomeKit, energy-monitoring, and pack-count features. The linked offer is the P125M three-pack, not the P125 or P110M.",
    bestFor: "Compact Matter control for lamps and ordinary appliances",
    priceBand: "$",
    rating: 4.5,
    scores: [
      { label: "Ecosystem fit", value: 9 },
      { label: "Outlet fit", value: 9 },
      { label: "Energy insight", value: 2 },
    ],
    pros: ["Matter support for compatible ecosystems", "Compact body is designed to avoid blocking the second outlet", "Tapo app schedules, timers, and away-mode controls"],
    cons: ["2.4GHz Wi-Fi only", "No energy-monitoring feature", "Not suitable for loads outside the listed electrical rating"],
    specs: {
      ASIN: "B0BXMNJDW3",
      Model: "P125M",
      Pack: "3-pack",
      Electrical: "15A / 1800W maximum listed; follow load restrictions",
      Network: "2.4GHz Wi-Fi",
      Ecosystems: "Matter-compatible Apple Home, Alexa, Google Home, and SmartThings",
      "Energy monitoring": "No",
    },
    evidence: [
      "Confirm P125M and the three-pack before checkout",
      "Check the appliance's running and startup load against the plug's rating and restrictions",
      "Use the physical button and original appliance controls as a fallback",
    ],
    editorialSections: [
      {
        heading: "The M suffix matters",
        body: "P125M is the Matter version. P125 and P110M are different products with different ecosystem and energy features, so model numbers should stay visible in comparisons and setup instructions.",
      },
      {
        heading: "Matter does not remove Wi-Fi setup",
        body: "The plug still needs a suitable 2.4GHz network and a compatible Matter controller for the selected ecosystem. Keep the Matter setup code until commissioning and household sharing are complete.",
      },
      {
        heading: "Choose loads conservatively",
        body: "Use the plug for supported plug-in loads and follow Tapo's electrical restrictions. Avoid treating a headline 15A rating as approval for every heater, motor, compressor, or safety-critical appliance.",
      },
    ],
    sources: [
      {
        name: "TP-Link Tapo P125M product page",
        url: "https://www.tp-link.com/us/home-networking/smart-plug/tapo-p125m/",
        note: "Official Matter, electrical, network, app, and compatibility details.",
      },
    ],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4y3dwqY",
        label: "Check Tapo P125M 3-pack price on Amazon",
        priceNote: "Confirm ASIN B0BXMNJDW3, model P125M, and three-pack quantity.",
      },
    ],
    compareSlugs: ["tapo-p110m-energy-monitoring-smart-plug"],
  },
  {
    site: "baby",
    slug: "babybjorn-carrier-harmony",
    asin: "B0947B35TG",
    seoTitle: "BabyBjörn Carrier Harmony Review Guide: Fit, Mesh & Positions",
    updatedAt,
    name: "BabyBjörn Carrier Harmony 3D Mesh",
    brand: "BabyBjörn",
    category: "travel",
    image: "/images/affiliate/baby-carrier-realistic.webp",
    summary: "A fit-first guide to Carrier Harmony's newborn sizing, 3D mesh, head support, pressure-relieving waist belt, carry positions, and the practical differences from Ergobaby Omni Breeze.",
    verdict: "Carrier Harmony is the cleaner choice for caregivers who prefer its front-buckle workflow and soft structured feel. Omni Breeze offers a higher listed maximum weight and hip carry, so the better carrier depends on body fit and intended positions rather than brand reputation.",
    whyItMatters: "Carrier comfort cannot be established from specifications alone. The baby's size, developmental milestone, adult torso, strap path, and return window matter more than a small difference in product weight.",
    bestFor: "Soft structured mesh with front-access buckles",
    priceBand: "$$$",
    rating: 4.6,
    scores: [
      { label: "Material comfort", value: 9 },
      { label: "Adjustment access", value: 9 },
      { label: "Long-range capacity", value: 7 },
    ],
    pros: ["Soft 3D mesh and adjustable head support", "Front-access buckles can simplify loading and unloading", "Inward, outward, and back-carry options at the stated milestones"],
    cons: ["No hip-carry position", "Higher price than many structured carriers", "Fit remains personal despite broad adjustment range"],
    specs: {
      ASIN: "B0947B35TG",
      Material: "3D mesh",
      "Listed range": "7–40lb / 3.2–18kg",
      Positions: "Front inward, front outward, and back carry",
      "Newborn use": "Follow minimum size and head-support instructions",
      "Linked color": "Silver; confirm selected variation",
    },
    evidence: [
      "Confirm the baby meets the listed size and developmental requirements for the chosen position",
      "Use inward-facing newborn setup and keep the face and airway visible",
      "Evaluate caregiver comfort while the return window is still open",
    ],
    editorialSections: [
      {
        heading: "Harmony versus Omni Breeze",
        body: "Harmony emphasizes soft material and front-access buckles. Omni Breeze lists hip carry and a 45lb maximum. Neither difference predicts which waist belt and shoulder path will feel better on a particular caregiver.",
      },
      {
        heading: "Positions change with development",
        body: "Newborn use begins inward-facing. Outward and back carry have later age, size, and developmental requirements. Follow the Harmony manual for the exact head-support and zipper settings instead of copying a marketing image.",
      },
      {
        heading: "Fit both adults independently",
        body: "Reset the waist belt, back support, shoulder straps, and head support for each wearer. A shared carrier is not a shared strap setting.",
      },
    ],
    sources: [
      {
        name: "BabyBjörn Carrier Harmony",
        url: "https://www.babybjorn.com/products/baby-carriers/baby-carrier-harmony/",
        note: "Official material, size range, positions, and adjustment guidance.",
      },
    ],
    compareSlugs: ["babybjorn-carrier-mini-3d-mesh", "ergobaby-omni-breeze-carrier"],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4v8GVNL",
        label: "Check BabyBjörn Harmony price on Amazon",
        priceNote: "Confirm ASIN B0947B35TG, 3D Mesh material, color, and seller.",
      },
    ],
  },
  {
    site: "network",
    slug: "tp-link-deco-be67-wifi-7-mesh",
    asin: "B0FQYQRZQX",
    seoTitle: "TP-Link Deco BE67 Review: 10GbE, Ports & Who Should Buy It",
    updatedAt: "July 19, 2026",
    name: "TP-Link Deco BE67 Wi-Fi 7 Mesh (2-Pack)",
    brand: "TP-Link",
    category: "wifi",
    image: "/images/affiliate/network-tp-link-deco-be67-wifi-7-mesh-realistic.webp",
    summary: "A source-checked Deco BE67 review covering the BE14000 two-pack, 10GbE and 2.5GbE ports, 6GHz backhaul, current firmware, and the network that can actually use it.",
    verdict: "Deco BE67 is the stronger choice for multi-gig homes that can use its 10GbE path and higher wireless capacity. BE63 remains the value choice when four 2.5GbE ports and BE10000 performance already cover the actual network.",
    whyItMatters: "The faster mesh only pays off when the modem, wired backhaul, switch, and clients can use it. Otherwise better placement or the less expensive BE63 can deliver the same practical result.",
    bestFor: "Premium Wi-Fi 7 mesh with a real 10GbE use case",
    priceBand: "$$$$",
    rating: 4.5,
    scores: [
      { label: "Wireless capacity", value: 10 },
      { label: "Multi-gig path", value: 9 },
      { label: "Value discipline", value: 6 },
    ],
    pros: ["Tri-band BE14000 Wi-Fi 7 with 6GHz", "10GbE plus 2.5GbE and 1GbE ports per unit", "Ethernet and wireless backhaul options"],
    cons: ["Costs more than BE63", "Only useful at full potential with compatible clients and wired equipment", "Two-pack coverage still depends on layout and placement"],
    specs: {
      ASIN: "B0FQYQRZQX",
      Pack: "2-pack",
      Wireless: "BE14000 tri-band Wi-Fi 7",
      Bands: "2.4GHz, 5GHz, and 6GHz",
      Ports: "1×10GbE, 1×2.5GbE, and 1×1GbE per unit",
      "Listed coverage": "Up to 6,000 sq. ft. for the 2-pack",
      Backhaul: "Wireless or Ethernet",
    },
    evidence: [
      "Confirm the linked offer is the BE67 two-pack and ASIN B0FQYQRZQX",
      "Map the modem, WAN, switch, backhaul, and client port speeds before paying for 10GbE",
      "Check exact client support for Wi-Fi 7, 6GHz, 320MHz channels, and MLO",
      "Match the regional hardware version before installing firmware; TP-Link lists separate BE67 support releases by version",
    ],
    editorialSections: [
      {
        heading: "BE67 versus BE63",
        body: "BE67 raises the wireless class and adds a 10GbE port, while BE63 provides four 2.5GbE ports. The upgrade is easiest to justify for a 5Gbps or 10Gbps WAN, fast NAS path, capable clients, or a demanding wireless backhaul.",
      },
      {
        heading: "Port mix matters more than the largest port",
        body: "One 10GbE port can be consumed by WAN or a fast LAN path. Draw the topology before buying, especially if satellites, switches, desktops, and storage all need multi-gig Ethernet.",
      },
      {
        heading: "Coverage remains a placement problem",
        body: "The listed square footage is a planning figure, not a guarantee through every wall and floor. Start with two well-connected nodes and test before adding more mesh units.",
      },
      {
        heading: "Firmware and hardware version are part of the purchase",
        body: "TP-Link's US support page lists BE67 firmware by hardware version and warns buyers to use the regional release that matches the unit. Current V1.6 firmware adds features such as Hybrid Mesh and Internet Backup, but a listing, used unit, or different region may ship with another version or feature set.",
      },
    ],
    sources: [
      {
        name: "TP-Link Deco BE67 product page",
        url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be67/",
        note: "Official wireless class, coverage, ports, backhaul, and feature specifications.",
      },
      {
        name: "TP-Link Deco BE67 support and firmware",
        url: "https://www.tp-link.com/us/support/download/deco-be67/",
        note: "Official hardware-version, regional-firmware, release-date, and current feature notes.",
      },
    ],
    compareSlugs: ["tp-link-deco-be63-wifi-7-mesh", "tp-link-deco-be85-wifi-7-mesh"],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4y4b03Q",
        label: "Check Deco BE67 2-pack price on Amazon",
        priceNote: "Confirm ASIN B0FQYQRZQX, model BE67, and two-pack quantity.",
      },
    ],
  },
  {
    site: "pet",
    slug: "levoit-vital-200s-p-air-purifier",
    asin: "B0BGPF71Q6",
    seoTitle: "Levoit Vital 200S-P Review: CADR, Noise & Filter Cost",
    updatedAt: "July 28, 2026",
    evidenceMode: "research-synthesis",
    researchNote: "We have not tested the Vital 200S-P ourselves. This guide keeps Levoit's current specifications separate from attributed RTINGS and HouseFresh tests of the Vital 200S family. Their results use different particle sensors, room assumptions, fan settings, and noise methods, so the numbers are not averaged or treated as interchangeable.",
    externalTests: [
      {
        source: "RTINGS",
        url: "https://www.rtings.com/air-purifier/reviews/levoit/vital-200s",
        date: "Test Bench 1.3.1; review updated June 4, 2026 and writing updated July 17, 2026",
        testSetup: "RTINGS tested a purchased White/Black Vital 200S. Its public methodology reports PM1.0 clean-air delivery at maximum output and at a quieter setting capped at 45dBA, plus measured noise at the lowest and highest fan speeds.",
        result: "RTINGS measured 216 CFM PM1.0 CADR at maximum output and associated that result with a 337 sq. ft. room. At Speed 2 under its low-noise method, it measured 87 CFM and associated the result with 135 sq. ft. Measured noise ranged from 32.7 to 55.6dBA.",
        interpretation: "The machine has useful medium-room particle performance, but quiet operation materially reduces the room size it can refresh quickly. A large maximum-coverage claim should not be used as the bedroom sizing target.",
        limitation: "RTINGS tested one color variant of the Vital 200S under its own PM1 and noise methodology. Confirm that the current Vital 200S-P listing and filter match the tested family, and do not compare its room-size output directly with a manufacturer one-air-change claim.",
      },
      {
        source: "HouseFresh",
        url: "https://housefresh.com/levoit-vital-200s-review/",
        date: "Long-term review refreshed in 2026 after more than two years of ownership",
        testSetup: "HouseFresh says it bought the Vital 200S and used the same particle-removal, sound-meter, and energy-meter workflow it applies across its purifier tests. It tested full speed and a sub-45dBA Speed 2 setting.",
        result: "HouseFresh reported 249 CFM PM1 CADR at top speed and 128 CFM below 45dBA. Its room test reached PM1 zero in 23 minutes at full speed and 46 minutes at Speed 2. Sound measured 38.3 to 57.7dBA from three feet, and top-speed power measured 44.55W.",
        interpretation: "The result supports the Vital 200S as a strong value for a medium room and shows the practical speed-versus-noise trade-off. It also makes electricity and replacement filters part of the buying decision rather than an afterthought.",
        limitation: "This is one site's room, sensor, electricity-price assumption, and purchased unit. Its annual-cost estimate changes with fan schedule, local electricity price, filter loading, genuine-filter price, and replacement frequency.",
      },
    ],
    name: "Levoit Vital 200S-P Air Purifier",
    brand: "Levoit",
    category: "home-care",
    image: "/images/affiliate/pet-air-purifier-realistic.webp",
    summary: "A source-attributed Levoit Vital 200S-P review comparing official CADR, filter, app, and room claims with independent particle, noise, energy, and ownership-cost tests for the Vital 200S family.",
    verdict: "Vital 200S-P is a strong value for a medium pet room when a washable pre-filter, smart scheduling, and measured particle performance matter. Skip it for a large open plan, heavy gas or VOC removal, or a buyer who wants to avoid recurring bonded-filter replacement.",
    whyItMatters: "Pet hair, airborne dander, and odor sources require different responses. A purifier can help with particles and some airborne odors, but it cannot replace litter, bedding, upholstery, and accident cleaning.",
    bestFor: "Pet rooms needing a washable pre-filter and smart controls",
    priceBand: "$$",
    rating: 4.7,
    scores: [
      { label: "Pet-hair intake", value: 9 },
      { label: "Smart controls", value: 9 },
      { label: "Filter cost clarity", value: 7 },
    ],
    pros: ["Washable pre-filter catches larger hair and dust", "U-shaped inlet and Pet Mode target pet-room use", "VeSync schedules, air-quality display, and automatic modes"],
    cons: ["Main filter remains a recurring replacement cost", "Coverage changes with desired air changes per hour", "Cannot solve persistent odor at its source"],
    specs: {
      ASIN: "B0BGPF71Q6",
      Model: "Vital 200S-P",
      "Linked color": "White",
      "Official CADR": "250 CFM",
      "Official room ratings": "1,862 sq. ft. at 1 ACH; 388 sq. ft. at 4.8 ACH",
      "Pre-filter": "Washable",
      Controls: "VeSync app, auto mode, schedules, and air-quality display",
      "Official dimensions": "15.6 x 8.5 x 19.8 in",
      "Official rated power": "50W",
      "Official noise range": "23-54dB",
      Filter: "Vital 200S-P three-stage replacement filter; official interval is 6-12 months",
      "Filter purchase check": "Verify the selected Vital 200S-P series filter, live price, and stock before checkout",
    },
    evidence: [
      "Size the purifier by room volume and desired air changes, not maximum coverage alone",
      "Clean the washable pre-filter according to the current manual and allow it to dry fully before reinstalling",
      "Check replacement-filter price and availability before comparing the machine price",
    ],
    editorialSections: [
      {
        heading: "What the independent tests add",
        body: "RTINGS measured 216 CFM PM1 CADR at maximum output, while HouseFresh reported 249 CFM using its own setup. Those results should remain separate because their sensors, rooms, calculations, and units differ. Both point in the same practical direction: useful medium-room particle cleaning, with much less delivery when the fan is held to a quiet setting.",
      },
      {
        heading: "Coverage needs an air-change context",
        body: "Levoit's current 1,862-square-foot figure represents one air change per hour, while its faster official target is 388 square feet at 4.8 air changes per hour. RTINGS associated its maximum-speed result with 337 square feet, while HouseFresh used 373 square feet at five air changes per hour. Ceiling height, doors, leakage, pollutant load, and tolerated fan noise still change the right target.",
      },
      {
        heading: "The filter is the price and version risk",
        body: "The washable part is the pre-filter; the main particle-and-carbon filter remains a consumable. Levoit's replacement page lists a 6-12 month interval, but filter price, selected variant, and stock need a live check. HouseFresh measured 44.55W at full speed and built its annual-cost estimate from continuous top-speed use plus one filter, but a real household can land above or below that assumption.",
      },
      {
        heading: "Do not buy it as a complete odor solution",
        body: "The carbon layer can support control of some airborne odors, but HouseFresh notes that serious VOC or gas problems call for much more carbon media. Continue scooping litter, washing bedding, vacuuming upholstery, ventilating appropriately, and cleaning accidents at the source.",
      },
      {
        heading: "Vital 200S-P versus Shark HP302",
        body: "Levoit is the more compact value path with a washable pre-filter, measured medium-room performance, and familiar annual filter replacement. Shark emphasizes removable debris screens and a longer claimed HEPA-filter life. Compare current filter availability, room target, floor space, noise, and verified operating cost instead of one maximum-coverage number.",
      },
    ],
    sources: [
      {
        name: "Levoit Vital 200S-P product page — White/Grey",
        url: "https://levoit.com/collections/air-purifiers/products/levoit-vital-200s-p-smart-air-purifier-white-grey",
        note: "Official page for the linked color variant and current product-family identity.",
      },
      {
        name: "Levoit Vital 200S-P product page — Black",
        url: "https://levoit.com/products/levoit-vital-200s-p-smart-air-purifier-black",
        note: "Official current CADR, ACH-based room ratings, filtration, controls, dimensions, power, and noise specifications; the linked Amazon offer remains the White variant.",
      },
      {
        name: "Levoit Vital 200S-P user manual",
        url: "https://levoit.com/cdn/shop/files/HEAPAPLVSUS0166Y_0124A_LAP-V201S-WUS_LAP-V201S-KUS_Vital_200S-P_Smart_Air_Purifier_manual_US_A0-240924.pdf?v=13235666559482571905",
        note: "Official LAP-V201S-WUS and LAP-V201S-KUS operating modes, particle-sensor limits, care, and filter-life guidance.",
      },
      {
        name: "AHAM Verifide directory",
        url: "https://ahamverifide.org/directory-of-air-cleaners/",
        note: "Independent directory for current certified room-air-cleaner performance data.",
      },
      {
        name: "Levoit Vital 200S replacement filter",
        url: "https://levoit.com/products/vital-200s-replacement-filter",
        note: "Official compatibility, 6-12 month interval, filtration-layer, variant, price, and availability check.",
      },
      {
        name: "RTINGS Vital 200S test",
        url: "https://www.rtings.com/air-purifier/reviews/levoit/vital-200s",
        note: "Attributed maximum and low-noise PM1 CADR, room-size, noise, filter, and variant evidence.",
      },
      {
        name: "HouseFresh Vital 200S long-term test",
        url: "https://housefresh.com/levoit-vital-200s-review/",
        note: "Attributed purchased-unit particle, noise, power, filter-cost, and long-term-use evidence.",
      },
    ],
    compareSlugs: ["coway-airmega-mighty2-air-purifier", "winix-5510-air-purifier", "shark-neverchange-max-air-purifier"],
    offers: [
      {
        merchant: "Amazon US",
        url: "https://amzn.to/4vaR2RX",
        label: "Check Levoit Vital 200S-P price on Amazon",
        priceNote: "Confirm ASIN B0BGPF71Q6, white Vital 200S-P, seller, and included filter.",
      },
    ],
  },
];

export const adjacentExpansionRoundups: Roundup[] = [
  {
    site: "baby",
    slug: "babybjorn-harmony-vs-ergobaby-omni-breeze",
    updatedAt,
    title: "BabyBjörn Harmony vs. Ergobaby Omni Breeze",
    dek: "Compare fit workflow, mesh, carry positions, listed weight range, lumbar support, and which differences matter before trying either carrier.",
    category: "travel",
    intent: "Choose between two premium breathable structured baby carriers without pretending specifications can replace a fit test.",
    intro: "Harmony and Omni Breeze both target parents who want a breathable all-stage structured carrier. Harmony emphasizes soft material and front-access buckles; Omni Breeze adds hip carry and a higher listed maximum. The return window remains part of the buying decision.",
    decisionGuide: [
      { label: "Front buckles", detail: "Harmony is easier to shortlist when front-access fastening is the preferred workflow." },
      { label: "Hip carry", detail: "Omni Breeze is the candidate because Harmony does not list a hip-carry position." },
      { label: "Higher maximum", detail: "Omni Breeze lists 45lb versus Harmony's 40lb." },
      { label: "Personal comfort", detail: "Try the waist belt and shoulder path with realistic weight before deciding." },
    ],
    methodology: ["Compare official position and size limits", "Keep newborn and later-position rules separate", "Treat caregiver fit and returns as decision criteria"],
    productSlugs: ["babybjorn-carrier-harmony", "ergobaby-omni-breeze-carrier"],
    faqs: [
      { question: "Which carrier is cooler?", answer: "Both use breathable mesh, but heat also depends on body contact, clothing, weather, activity, and fit." },
      { question: "Which is easier to put on?", answer: "Harmony's front buckles suit some caregivers; others prefer Omni Breeze after learning its strap sequence." },
      { question: "Can both carry a newborn?", answer: "Both list newborn use from stated minimums, but only in the correct inward-facing setup with the required head support." },
    ],
  },
  {
    site: "network",
    slug: "tp-link-deco-be67-vs-be63",
    seoTitle: "Deco BE67 vs BE63: Is 10GbE Worth Paying More For?",
    updatedAt: "July 19, 2026",
    title: "Deco BE67 vs BE63: 10GbE, Port Layout and Best Value",
    dek: "Compare equal-size Deco BE67 and BE63 packs by 10GbE versus four 2.5GbE ports, wireless backhaul, client support, and the upgrade cost your network can use.",
    category: "wifi",
    intent: "Decide whether Deco BE67's 10GbE path and added wireless capacity are worth paying over BE63.",
    intro: "BE67 is the faster specification and the only one of this pair with a 10GbE port, but BE63 can be the better-designed purchase for a home built around several 2.5GbE devices. Compare the same pack size, then trace the modem, primary node, switch, backhaul, satellite, and client path before paying for either upgrade.",
    decisionGuide: [
      { label: "5Gbps or 10Gbps WAN/NAS", detail: "Choose BE67 only when its 10GbE port remains connected to an end-to-end multi-gig path." },
      { label: "Several 2.5GbE devices", detail: "BE63's four equal 2.5GbE ports can be more useful than one faster headline port." },
      { label: "Gigabit internet with wired backhaul", detail: "BE63 usually leaves more budget for Ethernet, switches, and better node placement." },
      { label: "Heavy wireless backhaul", detail: "BE67's higher wireless class can matter when nodes cannot be wired and the layout supports a clean 6GHz link." },
      { label: "Same pack, region and version", detail: "Compare equal node counts and confirm the listing, regional hardware, firmware path, and return window." },
    ],
    methodology: [
      "Compare the same pack size and regional hardware version",
      "Map every WAN, LAN, switch, backhaul, and client link before using wireless class as the tiebreaker",
      "Separate aggregate link rates from measured single-client throughput",
      "Treat coverage figures as planning estimates and preserve the return-and-placement test window",
    ],
    productSlugs: ["tp-link-deco-be67-wifi-7-mesh", "tp-link-deco-be63-wifi-7-mesh"],
    faqs: [
      { question: "Is Deco BE67 worth it over BE63?", answer: "It is worth considering for a usable 5Gbps or 10Gbps path, demanding wireless backhaul, or compatible high-end clients. BE63 is usually the better value when the network is built around gigabit or 2.5GbE links." },
      { question: "Which model has the better Ethernet ports?", answer: "BE67 provides one 10GbE, one 2.5GbE, and one 1GbE port per unit. BE63 provides four 2.5GbE ports, which can be more flexible for several wired devices." },
      { question: "Do both support wired backhaul?", answer: "Yes, but the negotiated speed follows the slowest port, switch, cable, or wall link in the path." },
      { question: "Which should a gigabit home buy?", answer: "BE63 normally provides enough headroom and more flexible 2.5GbE connectivity. Pay for BE67 only when there is a specific capacity, coverage, or future multi-gig plan." },
    ],
  },
  {
    site: "pet",
    slug: "levoit-vital-200s-p-vs-shark-neverchange-max",
    title: "Levoit Vital 200S-P vs. Shark NeverChange MAX for Pet Homes",
    dek: "Compare pet-hair pre-filtration, room sizing, odor strategy, controls, filter replacement, fragrance, and the maintenance each purifier still requires.",
    category: "home-care",
    intent: "Choose a pet-room air purifier by room and maintenance needs instead of the biggest coverage claim.",
    intro: "Levoit is the value-oriented smart purifier with a washable pre-filter. Shark is the larger unit with debris screens and a long-life HEPA claim. Neither replaces source cleaning, and their maximum coverage figures need an air-change context.",
    decisionGuide: [
      { label: "Lower purchase price", detail: "Vital 200S-P is usually the more restrained starting point." },
      { label: "Large open pet area", detail: "Compare HP302 when its size and airflow suit the room." },
      { label: "Fragrance-sensitive home", detail: "Levoit avoids making a scented cartridge central to the purchase." },
      { label: "Filter routine", detail: "Compare conventional replacement cost with Shark's conditional long-life claim." },
    ],
    methodology: ["Compare room size at equivalent air changes", "Separate hair, dander, and odor sources", "Include filters and maintenance in total cost"],
    productSlugs: ["levoit-vital-200s-p-air-purifier", "shark-neverchange-max-air-purifier"],
    faqs: [
      { question: "Will either purifier remove pet hair from furniture?", answer: "No. Pre-filters catch airborne hair, but upholstery and floors still need vacuuming or brushing." },
      { question: "Which removes litter odor better?", answer: "Source cleaning comes first. Carbon media can help with remaining airborne odor, but no purifier fixes a dirty box." },
      { question: "Does NeverChange mean no maintenance?", answer: "No. Debris screens and odor components still need attention, and the HEPA claim depends on stated use conditions." },
    ],
  },
  {
    site: "smarthome",
    slug: "matter-starter-kit-hub-sensor-smart-plug",
    title: "Matter Starter Kit: Hub, Contact Sensor and Smart Plug",
    updatedAt: "July 26, 2026",
    dek: "Build a small Matter setup with Aqara Hub M3, Aqara P2, and Tapo P125M while keeping Thread, Wi-Fi, controllers, and ecosystem sharing clear.",
    category: "automation",
    intent: "Start with a few useful Matter devices without buying overlapping controllers or confusing Thread with Wi-Fi.",
    intro: "A hub, contact sensor, and smart plug create a useful first automation: when a door opens after dark, a lamp can turn on. The setup works only when each device's network and controller requirements are understood.",
    comparisonTable: {
      title: "Starter-kit role map",
      columns: ["Aqara Hub M3", "Aqara P2 sensor", "Tapo P125M plug"],
      rows: [
        { label: "Matter role", values: ["Controller and hub option", "Matter accessory", "Matter accessory"] },
        { label: "Network path", values: ["Ethernet or Wi-Fi plus supported hub radios", "Matter over Thread", "Matter over 2.4GHz Wi-Fi"] },
        { label: "Main requirement", values: ["Confirm whether an existing controller already covers the plan", "Compatible controller and Thread border router", "Compatible controller and reliable 2.4GHz coverage"] },
        { label: "Physical fallback", values: ["Keep network and reset access", "Door still opens normally", "Use the plug's local button"] },
      ],
    },
    decisionGuide: [
      { label: "Need Thread", detail: "Hub M3 can provide a Thread border-router and Matter-controller path." },
      { label: "Door state", detail: "Aqara P2 reports open and closed over Matter over Thread." },
      { label: "Control a lamp", detail: "Tapo P125M uses Matter over 2.4GHz Wi-Fi." },
      { label: "Already own controllers", detail: "Check existing Apple, Google, Alexa, SmartThings, or Home Assistant hardware before adding another hub." },
    ],
    methodology: ["Map protocols before brands", "Commission one ecosystem first", "Test physical fallbacks and household sharing"],
    productSlugs: ["aqara-hub-m3", "aqara-door-and-window-sensor-p2", "tapo-p125m-matter-smart-plug"],
    faqs: [
      { question: "Does every Matter device use Thread?", answer: "No. Aqara P2 uses Thread, while Tapo P125M uses Wi-Fi." },
      { question: "Do I always need Hub M3?", answer: "No. Another compatible Matter controller and Thread border router may already cover the P2." },
      { question: "Will Matter expose every advanced feature?", answer: "Not necessarily. Vendor apps can retain model-specific settings beyond the common Matter feature set." },
    ],
  },
];

export const adjacentExpansionGuides: Guide[] = [
  {
    site: "smarthome",
    slug: "aqara-hub-m3-matter-thread-setup",
    title: "Aqara Hub M3 Setup: Matter, Thread, PoE & Migration Checklist",
    dek: "Set up Aqara Hub M3 by assigning Matter, Thread, Zigbee, Ethernet or PoE, ecosystem sharing, and migration roles before resetting an existing hub.",
    category: "automation",
    updatedAt: "July 16, 2026",
    image: "/images/affiliate/smarthome-aqara-hub-m3-realistic.webp",
    imageAlt: "Smart-home hub, contact sensor, router, and Ethernet cable arranged for Matter and Thread setup planning",
    comparisonTable: {
      title: "Choose the M3 connection and controller path",
      columns: ["Use it when", "Check before setup"],
      rows: [
        { label: "PoE Ethernet", values: ["One cable should carry network and power to a deliberate hub location", "Compatible PoE source, cable route, LAN, and mounting position"] },
        { label: "Ethernet plus USB-C", values: ["Wired networking is useful but PoE is unavailable", "5V 2A power source, cable strain, and outlet backup"] },
        { label: "Dual-band Wi-Fi plus USB-C", values: ["No Ethernet run exists and signal is stable", "2.4/5GHz coverage, WPA settings, and outage behavior"] },
        { label: "Aqara Home as primary controller", values: ["Aqara automations and device settings are the main workflow", "Which devices and features will be shared to other ecosystems"] },
        { label: "Existing ecosystem as primary", values: ["Apple, Google, SmartThings, Alexa, or Home Assistant already owns the routines", "Whether M3 adds Zigbee, IR, Thread, PoE, or bridging value"] },
      ],
    },
    relatedProducts: ["aqara-hub-m3", "aqara-door-and-window-sensor-p2"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    relatedGuides: ["aqara-hub-m3-vs-m2", "aqara-hub-m3-home-assistant-matter-guide", "matter-thread-wifi-zigbee-device-checklist"],
    sources: [
      { name: "Aqara Hub M3", url: "https://us.aqara.com/products/hub-m3", note: "Current official controller, bridge, Thread, Zigbee, network, power, storage, and placement information." },
      { name: "Aqara Hub M3 user manual", url: "https://www.aqara.com/wp-content/uploads/2024/05/M3-User-Manual-1.pdf", note: "Official pairing, installation, reset, power, model, and safety reference." },
      { name: "Matter overview", url: "https://csa-iot.org/all-solutions/matter/", note: "Connectivity Standards Alliance overview of Matter roles and multi-admin." },
      { name: "Home Assistant Matter integration", url: "https://www.home-assistant.io/integrations/matter", note: "Official controller, bridge, IPv6, mDNS, Thread, and multi-admin guidance for Home Assistant users." },
    ],
    sections: [
      { heading: "Write the four M3 roles before plugging it in", body: "Decide whether M3 will be an Aqara Zigbee hub, Matter controller, Matter bridge, Thread border router, or a combination. For each role, name at least one actual device or ecosystem that needs it. An unused role is not a reason to migrate a working home." },
      { heading: "Inventory existing controllers and Thread border routers", body: "List Apple Home hubs, Google hubs, Echo devices, SmartThings, Home Assistant, older Aqara hubs, and any OpenThread border router. Record the primary Matter controller and the Thread network used by each existing Thread device before adding another fabric or border router." },
      { heading: "Choose the network and power path together", body: "Use PoE only with a compatible source and intentional cable route. Ethernet plus USB-C separates wired data from power. Wi-Fi can be simpler, but test signal and recovery at the final hub position. The M3 package includes a USB cable but the current US page says the 5V 2A adapter is not included." },
      { heading: "Commission M3 in the system that will own setup", body: "Complete M3 setup in Aqara Home, update firmware, name the hub clearly, and verify its local network state. Add or share devices to secondary Matter ecosystems only after native Aqara controls and one simple automation work reliably." },
      { heading: "Add one device from each protocol", body: "Use one existing Aqara Zigbee child device, one planned Matter device, and one Thread device if available. Confirm status, control, automation, and recovery after a hub restart. This small protocol sample reveals architecture problems before a whole-home migration." },
      { heading: "Treat ecosystem sharing as a feature audit", body: "After sharing M3 to Apple Home, Google Home, SmartThings, Alexa, or Home Assistant, list the devices and controls that actually appear. Matter bridging can expose a useful common subset without carrying every Aqara setting, infrared scene, event, or automation into the second platform." },
      { heading: "Migrate old hubs in small groups", body: "Document child devices, automations, rooms, family access, notifications, and infrared remotes. Move a small group, use it for several normal days, and keep the old hub powered until the household's critical routines and physical fallbacks are proven." },
      { heading: "Back up the recovery information", body: "Keep model and region, purchase record, network path, Matter pairing information, device list, automation list, and reset instructions in a private household record. Do not publish or store active pairing codes in screenshots, support posts, or analytics notes." },
      { heading: "Stop when the architecture becomes harder to explain", body: "If no one can name which platform owns commissioning, automations, Thread credentials, and household access, pause before adding more devices. A smaller setup with one clear controller path is usually easier to recover than a larger system built around overlapping logos." },
    ],
  },
  {
    site: "smarthome",
    slug: "matter-thread-wifi-zigbee-device-checklist",
    title: "Matter, Thread, Wi-Fi and Zigbee Device Checklist",
    dek: "Identify the application standard, radio network, controller, border router, and bridge required by each smart-home device.",
    category: "automation",
    updatedAt: "July 16, 2026",
    image: "/images/affiliate/smarthome-aqara-hub-m3-realistic.webp",
    imageAlt: "Smart-home hub, contact sensor, router, and Ethernet cable representing Matter, Thread, Wi-Fi, and Zigbee roles",
    relatedProducts: ["aqara-hub-m3", "aqara-door-and-window-sensor-p2", "tapo-p125m-matter-smart-plug"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    relatedGuides: ["ikea-parasoll-vs-myggbett-zigbee-matter-thread", "aqara-hub-m3-vs-m2", "aqara-hub-m3-matter-thread-setup", "aqara-hub-m3-home-assistant-matter-guide"],
    sources: [
      { name: "Matter overview", url: "https://csa-iot.org/all-solutions/matter/", note: "Primary standards-organization overview." },
      { name: "Thread Group overview", url: "https://www.threadgroup.org/What-is-Thread", note: "Primary Thread networking overview." },
    ],
    sections: [
      { heading: "Matter describes interoperability, not one radio", body: "Matter can run over Thread, Wi-Fi, or Ethernet. A Matter logo therefore does not reveal whether the device needs a Thread border router or joins the home Wi-Fi." },
      { heading: "Thread needs a border router", body: "Thread devices join a low-power mesh and need a compatible border router to reach the wider IP network. A Matter controller may or may not include that role." },
      { heading: "Zigbee normally needs a brand or compatible hub", body: "Legacy Aqara Zigbee devices do not become Thread devices. A bridge can expose supported functions to Matter while the device remains on its Zigbee network." },
      { heading: "Write the five-part requirement", body: "For each product record its protocol, radio, controller, border router or bridge, and primary app. This small table prevents most hub-shopping mistakes." },
    ],
  },
  {
    site: "smarthome",
    slug: "ikea-parasoll-vs-myggbett-zigbee-matter-thread",
    title: "IKEA PARASOLL vs MYGGBETT: Zigbee, Matter, Thread & DIRIGERA",
    dek: "PARASOLL is a Zigbee contact sensor; MYGGBETT is the IKEA Matter-over-Thread model. Check whether DIRIGERA, another Thread Border Router, or Aqara P2 fits the system you already own.",
    category: "automation",
    updatedAt: "July 17, 2026",
    image: "/images/affiliate/smarthome-contact-sensor-protocol-guide-realistic.webp",
    imageAlt: "Two realistic door and window contact sensors near a smart-home hub and network router for protocol planning",
    comparisonTable: {
      title: "Contact-sensor protocol and hub decision",
      columns: ["Radio and standard", "What the home needs", "Best reason to choose it"],
      rows: [
        { label: "IKEA PARASOLL", values: ["Zigbee; not Matter over Thread", "DIRIGERA for IKEA Home smart app notifications, or supported direct IKEA light pairing", "Low-cost IKEA-centered contact automation when Zigbee is acceptable"] },
        { label: "IKEA MYGGBETT", values: ["Matter over Thread", "A compatible Thread Border Router; DIRIGERA is one option", "Native Matter choice for a current IKEA or cross-ecosystem Thread plan"] },
        { label: "Aqara P2", values: ["Matter over Thread", "A compatible Matter controller and Thread Border Router", "Native Matter sensor with an established Amazon purchase path and broad ecosystem guidance"] },
      ],
    },
    relatedProducts: ["aqara-door-and-window-sensor-p2", "aqara-hub-m3"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    relatedGuides: ["matter-thread-wifi-zigbee-device-checklist", "aqara-hub-m3-matter-thread-setup", "aqara-hub-m3-home-assistant-matter-guide"],
    sources: [
      { name: "IKEA PARASOLL door/window sensor", url: "https://www.ikea.com/us/en/p/parasoll-door-window-sensor-smart-white-70504318/", note: "Official PARASOLL protocol path, DIRIGERA notifications, battery, mounting, and direct-light use." },
      { name: "IKEA PARASOLL instructions", url: "https://www.ikea.com/us/en/manuals/parasoll-door-window-sensor-smart-white__AA-2422302-1-100.pdf", note: "Official setup paths with DIRIGERA or direct smart-light pairing." },
      { name: "IKEA MYGGBETT door/window sensor", url: "https://www.ikea.com/us/en/p/myggbett-door-window-sensor-smart-60617641/", note: "Official Matter-over-Thread model, ecosystem support, battery, and Thread Border Router requirement." },
      { name: "Aqara Door and Window Sensor P2", url: "https://www.aqara.com/us/product/door-and-window-sensor-p2/", note: "Official native-Matter, Thread, controller, and border-router reference for the commissionable alternative." },
    ],
    sections: [
      { heading: "Quick answer: PARASOLL does not need a Thread Border Router", body: "The current US PARASOLL page and manual describe a Zigbee sensor. Use DIRIGERA when IKEA Home smart app notifications and remote routines are wanted, or follow IKEA's supported direct-light pairing path for a simple local automation. A Thread Border Router is not the missing requirement for PARASOLL." },
      { heading: "MYGGBETT is the IKEA Matter-over-Thread sensor", body: "IKEA lists MYGGBETT as a Matter-over-Thread door and window sensor. It therefore needs a compatible Thread Border Router. DIRIGERA can fill that role, but buyers using Apple, Google, Amazon, Samsung, Homey, or another ecosystem should verify the exact controller and border-router hardware already installed before buying another hub." },
      { heading: "DIRIGERA performs different jobs for the two sensors", body: "For PARASOLL, DIRIGERA is the IKEA Zigbee hub that enables app notifications and wider IKEA Home smart control. For MYGGBETT, IKEA identifies DIRIGERA as an example Thread Border Router for the Matter-over-Thread path. The same hub name does not make the two sensors use the same radio." },
      { heading: "Do not follow a PARASOLL setup guide for MYGGBETT", body: "A ten-second Zigbee pairing sequence near an IKEA bulb belongs to PARASOLL's documented direct-light path. MYGGBETT should be commissioned through its Matter ecosystem and Thread network. Check the article number and product name on the package before resetting hardware or rebuilding the home network." },
      { heading: "Aqara P2 is the closest commissionable alternative", body: "Aqara P2 is also native Matter over Thread and requires a compatible Matter controller plus Thread Border Router. It is worth comparing when the household wants a current Amazon option, already uses Aqara Home or Hub M3, or needs Aqara's ecosystem-specific automation guidance. It is not a drop-in Zigbee replacement for PARASOLL." },
      { heading: "Choose from the system already running", body: "Keep PARASOLL when DIRIGERA and IKEA Zigbee routines already work. Choose MYGGBETT when the goal is a current IKEA Matter-over-Thread sensor. Choose P2 when native Matter, Aqara support, or its merchant path is more useful. Avoid buying a new hub until the existing Matter controller, Thread Border Router, and Zigbee hub inventory is written down." },
      { heading: "Check placement before protocol", body: "All three products still depend on magnet alignment, frame depth, adhesive or screw placement, battery access, and a clear opening path. Dry-fit the sensor, confirm state changes in the final app, and keep packaging until the intended automation and notification both work." },
    ],
  },
  {
    site: "network",
    slug: "deco-be67-10gbe-network-checklist",
    title: "Deco BE67 10GbE Network Checklist",
    dek: "Verify the WAN, switch, NAS, client adapters, backhaul, and cables required to make the BE67 upgrade meaningful.",
    category: "wifi",
    updatedAt,
    relatedProducts: ["tp-link-deco-be67-wifi-7-mesh", "tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["tp-link-deco-be67-vs-be63", "best-mesh-wifi-for-apartments-and-homes"],
    sources: [
      { name: "TP-Link Deco BE67", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be67/", note: "Official port and wireless specifications." },
    ],
    sections: [
      { heading: "Start at the internet handoff", body: "Confirm the modem or ONT presents a compatible multi-gig Ethernet port and that the service plan exceeds gigabit before reserving BE67's 10GbE port for WAN." },
      { heading: "Choose the 10GbE job", body: "Decide whether the port serves WAN, a 10GbE switch, or a fast local storage path. One port cannot simultaneously be the physical endpoint for every use case." },
      { heading: "Audit every slower link", body: "A 1GbE wall jack path, 2.5GbE switch, USB adapter, or satellite port limits that branch. This is normal; only upgrade the branches that have a measured need." },
      { heading: "Keep wireless expectations client-specific", body: "Check the exact laptop or phone radio for Wi-Fi 7, 6GHz, channel width, streams, and MLO. Aggregate BE14000 speed is not one client's transfer rate." },
    ],
  },
  {
    site: "pet",
    slug: "air-purifier-pet-hair-dander-odor-guide",
    title: "Air Purifier Guide for Pet Hair, Dander and Odor",
    dek: "Separate large hair, airborne particles, and odor sources before sizing a purifier or comparing filter claims.",
    category: "home-care",
    updatedAt,
    relatedProducts: ["levoit-vital-200s-p-air-purifier", "shark-neverchange-max-air-purifier"],
    relatedRoundups: ["levoit-vital-200s-p-vs-shark-neverchange-max", "best-pet-odor-and-litter-upgrades"],
    sources: [
      { name: "EPA air cleaners guidance", url: "https://www.epa.gov/indoor-air-quality-iaq/air-cleaners-and-air-filters-home", note: "Primary guidance on filtration, room sizing, and source control." },
      { name: "AHAM Verifide directory", url: "https://ahamverifide.org/directory-of-air-cleaners/", note: "Certified room-air-cleaner performance data." },
    ],
    sections: [
      { heading: "Hair is mainly a surface-cleaning problem", body: "Pre-filters can catch some airborne hair, but floors, bedding, upholstery, and brushes collect most visible hair. Keep vacuuming and washable-fabric routines in the plan." },
      { heading: "Dander is the particle-filtration job", body: "Size the purifier for the room and desired air changes, place it with open intake and exhaust space, and run it long enough to circulate the room air." },
      { heading: "Odor begins with source control", body: "Scoop litter, clean accidents, wash bedding, control moisture, and ventilate when outdoor conditions allow. Carbon media can support the remaining airborne odor." },
      { heading: "Compare maintenance as a yearly routine", body: "Add pre-filter cleaning, main-filter cost, replacement availability, sensor cleaning, and any odor cartridge. A low-maintenance claim should still be translated into actual household tasks." },
    ],
  },
];
