import type { Guide } from "./types";

const updatedAt = "August 10, 2026";
type PilotGuide = Omit<Guide, "publicationStatus" | "updatedAt" | "familyRole" | "relatedRoundups"> & {
  relatedRoundups?: string[];
};

function pilotGuide(input: PilotGuide): Guide {
  return {
    publicationStatus: "published",
    updatedAt,
    familyRole: "buying",
    relatedRoundups: [],
    ...input,
  };
}

export const broadProductPilotGuides: Guide[] = [
  pilotGuide({
    site: "network",
    slug: "multigig-poe-switches-buying-guide",
    familySlug: "multigig-poe-switches",
    title: "Multi-Gig PoE Switch Buying Guide: Ports, Power Budget, and Uplinks",
    dek: "Choose a 2.5GbE PoE switch by powered-device count, real wattage, uplink headroom, management needs, cooling, and the cabling already in the walls.",
    category: "wired",
    image: "/images/affiliate/broad-network-multigig-poe-switches.webp",
    imageAlt: "Editorial network rack scene representing a multi-gig PoE switch installation",
    searchQuestion: "Which multi-gig PoE switch should I buy for Wi-Fi access points, cameras, and a faster home network?",
    quickAnswer: "Count the exact 2.5GbE PoE devices, total their maximum power draw with headroom, and reserve an uplink faster than the traffic they can create. A managed 2.5GbE PoE switch is worthwhile when several powered devices need more than gigabit links; otherwise a separate multi-gig switch and injectors may be quieter and cheaper.",
    governance: {
      decision: "rewrite",
      independentDemand: "Buyers need one device to solve both link-speed and PoE-power planning; that is a different decision from choosing an ordinary 2.5GbE switch or a gigabit PoE switch.",
      distinctFrom: "The existing fanless 2.5GbE switch pages do not calculate PoE standards, port power, total budget, or powered-device startup headroom.",
      benchmark: "Publish only after exact switch model, per-port standard, total PoE budget, uplink layout, fan behavior, and current Amazon ASIN are rechecked.",
    },
    comparisonTable: {
      title: "Multi-gig PoE switch checks that change the purchase",
      columns: ["What to record", "Why it changes the choice"],
      rows: [
        { label: "Powered ports", values: ["Number of APs, cameras, phones, and controllers", "A headline port count can include non-PoE or uplink-only ports."] },
        { label: "Per-port standard", values: ["802.3af, at, or bt required by every device", "An underpowered port can prevent startup or disable high-power modes."] },
        { label: "Total PoE budget", values: ["Maximum watts for all devices plus headroom", "Eight PoE+ ports do not mean all eight can deliver their maximum simultaneously."] },
        { label: "Uplinks", values: ["NAS, router, aggregation switch, and backhaul speeds", "A 1GbE uplink can bottleneck several active 2.5GbE ports."] },
        { label: "Management", values: ["VLANs, PoE cycling, monitoring, controller dependence", "Managed features help only when someone will configure and recover them."] },
        { label: "Noise and heat", values: ["Fan, rack location, ambient temperature, airflow", "High PoE budgets commonly add fan noise and heat that matter in living spaces."] },
      ],
    },
    editorialMethod: [
      "Build a port-by-port device and maximum-wattage worksheet before comparing switches.",
      "Verify the exact hardware model against its current datasheet and installation guide.",
      "Separate switching capacity, individual port rate, uplink rate, and internet speed.",
      "Treat the linked Amazon ASIN as a checkout anchor, not a source for stable price or availability claims.",
    ],
    communityEvidence: [{
      sourceName: "Reddit r/HomeNetworking",
      title: "2.5G PoE switch selection discussion",
      url: "https://www.reddit.com/r/HomeNetworking/comments/1j6a6bl",
      note: "Used only to identify recurring questions about port mix, fan noise, power budget, and uplinks; no comment or owner result is reproduced as product evidence.",
    }],
    sections: [
      { heading: "Make a powered-port worksheet first", body: "List every device, link speed, PoE class or stated maximum input, and whether it must survive a switch reboot. Add startup and future-device headroom instead of multiplying the port count by a marketing maximum. A switch with eight PoE sockets can still be the wrong choice when its shared power supply cannot support the intended combination." },
      { heading: "Keep per-port speed separate from uplink capacity", body: "A 2.5GbE access point can exceed one gigabit only under favorable radio, client, and workload conditions, but several active ports can still overwhelm a single gigabit uplink. Draw the path to the router, NAS, and aggregation switch. Pay for 10GbE uplinks only when the rest of that path and the repeated traffic justify them." },
      { heading: "Choose management for an operating task", body: "VLANs, link aggregation, traffic counters, and remote PoE cycling are useful when the network plan names who will configure them and how access is recovered. A controller-managed model may also operate in a reduced standalone mode. Read the exact manual before assuming cloud, local web, command line, or third-party automation support." },
      { heading: "Plan fan noise, heat, and rack power together", body: "High-output PoE switches can use active cooling even when ordinary multi-gig switches are silent. Check acoustic location, front-to-back clearance, rack depth, ambient temperature, surge protection, UPS runtime, and cable bend radius. A closet that is visually tidy but thermally closed is not a complete installation." },
      { heading: "When separate injectors are the better answer", body: "Keep the existing multi-gig switch and add standards-compliant injectors when only one or two devices need power, silence is important, or replacing a large working switch adds cost without a clear traffic benefit. Skip multi-gig PoE entirely when every powered endpoint is gigabit and no planned workload needs the faster link." },
    ],
    sources: [
      { name: "NETGEAR MS108EUP product page", url: "https://www.netgear.com/business/wired/switches/easy-smart/ms108eup/", note: "Official port, PoE budget, management, cooling, and physical specifications for the current draft anchor model." },
      { name: "IEEE 802.3 Power over Ethernet overview", url: "https://standards.ieee.org/ieee/802.3/10422/", note: "Primary standards context for Ethernet and PoE; product requirements still come from each device manual." },
      { name: "Amazon ASIN B09M1JMJS7", url: "https://www.amazon.com/dp/B09M1JMJS7", note: "Exact NETGEAR MS108EUP US listing identity to recheck before publication and checkout." },
    ],
    relatedGuides: ["indoor-wifi-access-points-buying-guide", "ethernet-patch-panels-buying-guide"],
    relatedProducts: ["tp-link-tl-sg105-m2-2-5g-switch", "netgear-gs308e-gigabit-switch"],
    relatedRoundups: ["best-fanless-2-5gbe-switches-home-nas-mesh", "best-wired-networking-upgrades"],
  }),

  pilotGuide({
    site: "network",
    slug: "rackmount-power-distribution-units-buying-guide",
    familySlug: "rackmount-power-distribution-units",
    title: "Rackmount PDU Buying Guide: Outlets, Load, Surge Protection, and UPS Fit",
    dek: "Choose a rack PDU by circuit capacity, plug and outlet layout, protection role, mounting direction, cord reach, and the UPS or wall circuit feeding it.",
    category: "wired",
    image: "/images/affiliate/broad-network-rackmount-pdu.webp",
    imageAlt: "Editorial equipment rack scene representing rack power distribution planning",
    searchQuestion: "What rackmount PDU should I use for a home network rack, and does it replace a UPS or surge protector?",
    quickAnswer: "Use a listed rack PDU to distribute one correctly sized circuit across reachable outlets; do not assume it supplies battery backup or surge protection. Map plug types, continuous load, mounting position, cord path, and the upstream UPS before choosing outlet count.",
    governance: {
      decision: "rewrite",
      independentDemand: "Rack owners are choosing physical and electrical distribution, not a router UPS or ordinary floor surge strip.",
      distinctFrom: "Existing UPS content focuses on runtime and modem/router continuity rather than rack outlet orientation, input plug, branch-circuit load, and PDU protection class.",
      benchmark: "Publish only after the exact model's rating, certification, surge function, breaker, plug, cord, dimensions, and mounting hardware are rechecked.",
    },
    comparisonTable: {
      title: "Rack PDU decisions beyond outlet count",
      columns: ["Verify", "Reject or change course when"],
      rows: [
        { label: "Input", values: ["Voltage, amperage, plug type, cord length", "The plug or circuit does not match without an improvised adapter."] },
        { label: "Load", values: ["Nameplate and measured equipment load", "The planned continuous load leaves inadequate circuit headroom."] },
        { label: "Protection", values: ["Basic, metered, switched, surge, or UPS-fed", "The product is being asked to provide a protection function it does not list."] },
        { label: "Outlet geometry", values: ["Brick clearance, spacing, front or rear access", "Power adapters block adjacent outlets or obstruct service."] },
        { label: "Mounting", values: ["1U, zero-U, depth, brackets, cable strain", "The rack position creates tight bends, heat, or inaccessible plugs."] },
        { label: "Recovery", values: ["Breaker access, labeling, shutdown order", "A fault would require guessing which device or upstream circuit to disconnect."] },
      ],
    },
    editorialMethod: [
      "Map the upstream circuit, UPS, PDU, and every attached load as one electrical path.",
      "Use manufacturer nameplate values and an electrician where branch-circuit suitability is uncertain.",
      "Classify protection features explicitly instead of treating every rack power strip as equivalent.",
      "Verify listing identity and included mounting hardware again at publication time.",
    ],
    communityEvidence: [{
      sourceName: "Reddit r/HomeNetworking",
      title: "Home rack PDU selection discussion",
      url: "https://www.reddit.com/r/HomeNetworking/comments/1sjiau2",
      note: "Used to surface practical questions about rear mounting, wall plugs, UPS chaining, and adapter clearance; anecdotes are not treated as electrical approval.",
    }],
    sections: [
      { heading: "Decide what the PDU is supposed to do", body: "A basic PDU distributes power. Some models add surge suppression, local metering, remote outlet switching, or environmental monitoring, while a UPS adds battery-backed power and voltage behavior of its own. Write the required job first so a row of outlets is not mistaken for protection the model never claims." },
      { heading: "Calculate the whole upstream load", body: "Record the wall circuit, receptacle, input plug, UPS output limit if used, PDU rating, and every connected device. Allow for continuous-load guidance, startup behavior, and future equipment. Do not daisy-chain power strips or use plug adapters to make an incompatible layout appear to fit; follow the current electrical code and product instructions." },
      { heading: "Model power bricks in three dimensions", body: "Outlet count is misleading when wide adapters cover neighbors or cable exits collide with the rack door. Lay out each plug, brick, and service loop at scale. Rear-facing outlets can clean up the front but must remain reachable for labeling, inspection, and emergency disconnection." },
      { heading: "Mount without creating heat or cable strain", body: "Confirm 1U or vertical compatibility, rack depth, bracket orientation, cord reach, ventilation, and bend radius. Keep low-voltage data cabling organized separately from mains power where practical. The breaker, power switch, and upstream disconnect should remain visible and documented after the rack is populated." },
      { heading: "When an ordinary strip or UPS outlet group is enough", body: "Skip a rack PDU when there are only a few low-power devices outside a rack and a correctly rated, listed surge protector reaches them safely. Use UPS outlets directly when the unit's layout, load rating, and supported connection policy already fit. A PDU is valuable for distribution and serviceability, not because rack mounting makes electricity safer by itself." },
    ],
    sources: [
      { name: "CyberPower CPS1215RMS product page", url: "https://www.cyberpowersystems.com/product/pdu/surge/cps1215rms/", note: "Official model specifications, outlet layout, electrical rating, protection, and mounting information." },
      { name: "Eaton rack PDU buying guide", url: "https://www.eaton.com/us/en-us/products/backup-power-ups-surge-it-power-distribution/power-distribution-for-it-equipment/rack-pdu-buying-guide.html", note: "Manufacturer guidance on PDU types, input, output, monitoring, and rack selection." },
      { name: "Amazon ASIN B00077INZU", url: "https://www.amazon.com/dp/B00077INZU", note: "Exact draft anchor listing; recheck seller, model, and live availability before publication." },
    ],
    relatedGuides: ["home-network-racks-buying-guide", "router-ups-runtime-guide"],
    relatedProducts: ["apc-be600m1-router-ups"],
    relatedRoundups: ["best-ups-for-router-and-modem", "best-wired-networking-upgrades"],
  }),

  pilotGuide({
    site: "network",
    slug: "network-cable-toner-probes-buying-guide",
    familySlug: "network-cable-toner-probes",
    title: "Network Cable Toner and Probe Buying Guide: Trace First, Test Second",
    dek: "Choose a toner and probe by cable state, connector types, live-network safety, audible discrimination, continuity functions, and the building you need to trace.",
    category: "wired",
    image: "/images/affiliate/broad-network-cable-toner-probes.webp",
    imageAlt: "Editorial structured-cabling workspace representing cable tracing and labeling",
    searchQuestion: "Which cable toner and probe kit should I buy to identify unknown Ethernet runs without damaging connected equipment?",
    quickAnswer: "Choose a kit rated for the cable and connection state you will trace, with connectors that match the patch panel and wall runs. A toner locates an unknown cable; a wiremap tester diagnoses conductor order and opens. Many buyers need both jobs, but they must follow the model's live-circuit restrictions.",
    governance: {
      decision: "rewrite",
      independentDemand: "Finding an unlabeled cable behind walls is a separate job from certifying Ethernet performance or merely checking an eight-wire map.",
      distinctFrom: "Existing Ethernet tester content does not answer tone injection, inductive probe use, live-service restrictions, analog/digital tone compatibility, or crowded-bundle identification.",
      benchmark: "Publish only after supported connectors, cable types, tone modes, voltage warning, continuity range, included adapters, and safety restrictions are verified from the exact manual.",
    },
    comparisonTable: {
      title: "Choose the tool by the actual tracing job",
      columns: ["Toner and probe", "Simpler or different tool"],
      rows: [
        { label: "Unknown far end", values: ["Useful for locating a cable in a bundle or wall box", "A wiremap tester needs access to both known ends."] },
        { label: "Conductor order", values: ["Only if the kit includes mapping or continuity functions", "A dedicated wiremap tester usually presents faults more clearly."] },
        { label: "Live Ethernet", values: ["Only in modes explicitly approved by the manual", "Use a switch-port discovery or link tool when service must remain connected."] },
        { label: "Crowded bundle", values: ["Adjustable tone and a sensitive probe help discriminate", "Visual tracing may be safer when the route is exposed."] },
        { label: "Coax or phone", values: ["Requires matching connectors and stated support", "Use cable-specific testers when fault diagnosis matters."] },
        { label: "Certification", values: ["Not a bandwidth certifier", "Hire or use a standards certifier for documented link performance."] },
      ],
    },
    editorialMethod: [
      "Separate locating, wiremapping, qualification, and certification before selecting a tool.",
      "Read the exact live-circuit and voltage restrictions before connecting a tone generator.",
      "Check connector and adapter coverage against the real patch panel, jacks, phone, or coax plant.",
      "Use community questions only to identify failure modes, never as permission to ignore the manual.",
    ],
    communityEvidence: [{
      sourceName: "Reddit r/lowvoltage",
      title: "Cable toner and probe buying discussion",
      url: "https://www.reddit.com/r/lowvoltage/comments/1s3p3sk",
      note: "Used to identify repeated concerns about noisy bundles, tool durability, and tracing workflow; no recommendation is copied as test evidence.",
    }],
    sections: [
      { heading: "Name the job before buying the tool", body: "Use a toner and inductive probe to find a cable whose far end is unknown. Use a wiremap tester to identify opens, shorts, reversals, and split pairs when both ends are accessible. Qualification and certification are different, more demanding tasks. One kit can combine basic functions, but its product name does not make those functions equivalent." },
      { heading: "Disconnect and inspect before injecting tone", body: "Identify power, PoE, telephone voltage, active switches, and connected equipment. Follow the exact manual on whether a given mode can touch a live circuit. Label both ends and isolate the run whenever possible. Never assume an RJ45-shaped port is ordinary unpowered Ethernet or connect an unknown cable just to see what happens." },
      { heading: "Match the tone to the building", body: "Crowded bundles, foil, conduit, long parallel runs, and electrical noise change how clearly a probe can distinguish one cable. Compare tone patterns, sensitivity control, audible and visual indication, probe tip access, headphone support, and replaceable parts. Practice on a labeled run before entering a dense cabinet." },
      { heading: "Use a repeatable trace-and-label workflow", body: "Start at a documented outlet, photograph the panel, tone only the isolated run, reduce sensitivity as the candidate narrows, confirm with continuity or a remote identifier, then label both ends with the same permanent identifier. Update the port map immediately; otherwise the tool solves the same uncertainty again on the next visit." },
      { heading: "Know when the kit is not enough", body: "A basic toner does not prove Cat6A performance, locate every intermittent fault, authorize work on energized conductors, or replace a network qualification report. Use a switch-port tool for active endpoint discovery and a proper certifier or qualified cabling professional when the result must support a warranty, building handoff, or compliance record." },
    ],
    sources: [
      { name: "Klein Tools VDV500-820 Pro Kit", url: "https://www.kleintools.com/catalog/tone-probe/tone-probe-pro-electrical-wire-tracing-set-batteries-and-carrying-pouch", note: "Official connector, tone, continuity, voltage, probe, and included-part information for the draft anchor." },
      { name: "Klein Tools VDV500-820 instructions", url: "https://data.kleintools.com/sites/all/product_assets/documents/instructions/klein/VDV500-820_Manual.pdf", note: "Manufacturer operating sequence and safety limits; verify the current revision before use." },
      { name: "Amazon ASIN B07VYN98QV", url: "https://www.amazon.com/dp/B07VYN98QV", note: "Exact draft anchor listing identity to recheck before publication." },
    ],
    relatedGuides: ["ethernet-cable-testers-buying-guide", "ethernet-patch-panels-buying-guide"],
    relatedProducts: ["netgear-gs308e-gigabit-switch"],
    relatedRoundups: ["best-wired-networking-upgrades"],
  }),

  pilotGuide({
    site: "smarthome",
    slug: "in-wall-smart-relays-buying-guide",
    familySlug: "in-wall-smart-relays",
    title: "In-Wall Smart Relay Buying Guide: Wiring, Load, Protocol, and Local Control",
    dek: "Choose a retrofit relay only after confirming box space, line and neutral wiring, load type, dry-contact needs, wall-switch behavior, and a safe offline path.",
    category: "automation",
    image: "/images/affiliate/broad-smarthome-in-wall-relays.webp",
    imageAlt: "Editorial smart-home control scene representing a concealed relay installation",
    searchQuestion: "Should I install an in-wall smart relay or replace the whole wall switch?",
    quickAnswer: "Choose an in-wall relay when the existing control style must remain and the exact wiring, enclosure, load, and protocol all fit. Choose a listed smart switch when it provides a clearer installation path. Mains wiring and box fill are hard gates, not setup details.",
    governance: {
      decision: "rewrite",
      independentDemand: "A concealed module must be matched to wiring topology, load, switch input, enclosure, and controller; that decision is not covered by a finished smart-switch comparison.",
      distinctFrom: "Existing smart wall switch pages compare visible controls but do not address dry contacts, relay isolation, detached input modes, module heat, or fitting a relay behind existing hardware.",
      benchmark: "Publish only after the exact relay manual, electrical ratings, certification, wiring diagrams, supported protocols, and local-control behavior are rechecked.",
    },
    comparisonTable: {
      title: "Relay module or complete smart switch?",
      columns: ["In-wall relay", "Complete smart switch"],
      rows: [
        { label: "Existing appearance", values: ["Can retain a compatible wall control", "Replaces the visible control and its interaction."] },
        { label: "Box space", values: ["Needs room for module, conductors, and heat", "Still needs box depth but removes a separate module layer."] },
        { label: "Wiring", values: ["Topology varies by relay and input mode", "Usually offers a product-specific installation diagram."] },
        { label: "Load", values: ["Can support switched power or dry-contact jobs", "Usually designed for a narrower lighting or fan load."] },
        { label: "Protocol", values: ["May offer Wi-Fi, Zigbee, Matter, or combinations", "Often optimized for one ecosystem or radio."] },
        { label: "Service", values: ["Hidden module must remain identifiable and accessible", "Visible device is easier to locate and reset."] },
      ],
    },
    editorialMethod: [
      "Treat the enclosure, conductors, switch input, load, protection, and controller as one compatibility system.",
      "Use the exact current wiring diagram and a qualified electrician where required.",
      "Distinguish local switching, local API, hub control, cloud control, and remote access.",
      "Recheck the ASIN and certification marks immediately before publication.",
    ],
    communityEvidence: [{
      sourceName: "Reddit r/homeassistant",
      title: "Shelly relay versus smart-switch discussion",
      url: "https://www.reddit.com/r/homeassistant/comments/18ysnwn",
      note: "Used to frame questions about switch retention, neutral wiring, local control, and box fit; electrical anecdotes are not installation instructions.",
    }],
    sections: [
      { heading: "Photograph and identify the circuit first", body: "Turn off and verify power according to appropriate electrical practice, then record line, load, neutral, ground, travelers, switch loops, box material, depth, conductor count, and the connected equipment. Wire color alone does not prove function. If the circuit cannot be confidently identified, stop and use a qualified electrician." },
      { heading: "Match the relay to the load, not just voltage", body: "Lighting drivers, motors, contactors, garage controls, and resistive loads behave differently. Check operating voltage, maximum current, inrush, load type, dry-contact isolation, required protection, and whether the relay is permitted in the intended enclosure. Never extend a rating from a similar model or a community diagram." },
      { heading: "Plan the physical enclosure", body: "A relay adds volume, terminations, and heat behind the existing device. Apply box-fill rules, conductor bend space, terminal torque, antenna placement, service access, and local code. Do not compress conductors until the device fits or bury a module where it cannot be identified, reset, inspected, or replaced." },
      { heading: "Define what works without each service", body: "Test the wall input first, then local network control, hub automation, internet outage, account outage, and power restoration. Matter support does not by itself prove every advanced setting is exposed to every platform. Record the recovery and factory-reset path before handing the control to household routines." },
      { heading: "When a finished smart switch is better", body: "Use a complete listed smart switch when it matches the load and wiring, provides the required physical control, and avoids squeezing a separate module into the box. Skip the retrofit when the neutral, enclosure, heat, certification, or maintenance path is uncertain. Preserving the old switch appearance is not worth an unsafe or unserviceable installation." },
    ],
    sources: [
      { name: "Shelly 1 Gen4 product page", url: "https://www.shelly.com/products/shelly-1-gen4", note: "Official draft-anchor model identity, protocol, dry-contact, input, and rating information." },
      { name: "Shelly 1 Gen4 knowledge base", url: "https://kb.shelly.cloud/knowledge-base/shelly-1-gen4", note: "Official wiring diagrams, technical limits, and operating documentation." },
      { name: "Amazon ASIN B0DZHZCL6Z", url: "https://www.amazon.com/dp/B0DZHZCL6Z", note: "Exact draft anchor listing identity; variant and seller must be checked before publication." },
    ],
    relatedGuides: ["smart-wall-switches-buying-guide", "smart-wall-switches-compatibility-and-fit-guide", "matter-hubs-bridges-buying-guide"],
  }),

  pilotGuide({
    site: "smarthome",
    slug: "smart-ceiling-fan-controllers-buying-guide",
    familySlug: "smart-ceiling-fan-controllers",
    title: "Smart Ceiling-Fan Controller Buying Guide: RF Compatibility, Speed, and Fallback",
    dek: "Choose between an RF bridge, in-wall fan control, receiver module, or connected fan by motor type, remote protocol, separate light control, local fallback, and household workflow.",
    category: "climate",
    image: "/images/affiliate/broad-smarthome-ceiling-fan-controllers.webp",
    imageAlt: "Editorial living-room climate scene representing smart ceiling-fan control",
    searchQuestion: "What is the best way to add smart control to an existing ceiling fan with a remote?",
    quickAnswer: "Start with the fan's motor, receiver, remote frequency, and wall wiring. An RF bridge is the least invasive choice for a compatible remote-controlled fan, while an in-wall control or receiver may offer clearer local operation. Do not put a fan motor on a lighting dimmer.",
    governance: {
      decision: "rewrite",
      independentDemand: "Retrofitting a remote-controlled fan requires protocol and motor-path decisions that differ from smart thermostats, switches, or buying a factory-connected fan.",
      distinctFrom: "Current climate pages do not compare RF learning, fan-speed command state, light-channel separation, wall-control conflicts, and manual recovery.",
      benchmark: "Publish only after compatible frequencies, fan types, remote requirements, supported ecosystems, device limits, cloud/local behavior, and current model identity are verified.",
    },
    comparisonTable: {
      title: "Four ways to make a ceiling fan smart",
      columns: ["Best fit", "Main limit"],
      rows: [
        { label: "RF bridge", values: ["Existing compatible handheld-remote fan", "May transmit commands without reading the fan's true state."] },
        { label: "In-wall fan control", values: ["Compatible AC motor and suitable wall wiring", "Cannot be treated as a generic light dimmer."] },
        { label: "Canopy receiver", values: ["Fan supports the exact receiver and there is canopy space", "Installation and model matching are more involved."] },
        { label: "Factory-smart fan", values: ["Replacing the whole fan already makes sense", "Highest cost and may still depend on an app or cloud."] },
        { label: "Separate light channel", values: ["Fan and light can be controlled independently", "Not every remote or retrofit exposes both functions."] },
        { label: "Manual fallback", values: ["Physical control remains understandable", "Remote-only recovery is fragile when batteries or services fail."] },
      ],
    },
    editorialMethod: [
      "Identify the exact fan, motor, receiver, remote, frequency, and wall conductors before selecting a retrofit.",
      "Compare RF bridges separately from devices that directly switch or regulate motor power.",
      "Test state synchronization and manual recovery rather than counting voice-platform logos.",
      "Use the current manufacturer compatibility checker and exact Amazon identity at the publication gate.",
    ],
    sections: [
      { heading: "Identify the existing control path", body: "Record fan brand and model, AC or DC motor, canopy receiver, remote model and frequency, number of speeds, reverse control, light kit, dimming, wall conductors, and any pull chains. A remote that looks similar may use a different protocol, and a fan that supports RF is not automatically compatible with every RF bridge." },
      { heading: "Understand what an RF bridge does", body: "A bridge learns or selects supported radio commands and retransmits them from a fixed location. It does not become part of the motor circuit. That simplifies installation, but one-way RF can leave the app's displayed state different from the actual fan after someone uses the original remote or a command is missed." },
      { heading: "Treat motor control as motor control", body: "Use only controls listed for the exact fan and motor type. A lighting dimmer is not a fan-speed controller. Confirm load limits, neutral and traveler requirements, receiver compatibility, canopy clearance, electrician needs, and whether light and fan conductors can be controlled separately before changing wiring." },
      { heading: "Map platform and outage behavior", body: "List what works from the original remote, wall control, local network, vendor app, Alexa, Google, SmartThings, Home Assistant, and any Matter bridge. Test router and internet outages plus power restoration. Keep a labeled physical control available so a guest can operate the fan without an account." },
      { heading: "When to skip the retrofit", body: "Keep the original remote when automation is occasional, compatibility cannot be proven, or the bridge cannot reliably reach the receiver. Choose a compatible in-wall or canopy solution when true local state and physical control matter. Replace the fan only when the fan itself is due for replacement, not merely to collect another smart-home badge." },
    ],
    sources: [
      { name: "Bond Bridge product page", url: "https://bondhome.io/product/bond-bridge/", note: "Official supported-device categories, ecosystem integrations, range, and setup context for the draft anchor." },
      { name: "Bond supported devices", url: "https://bondhome.io/supported-devices/", note: "Manufacturer compatibility path; exact remote compatibility remains a pre-purchase check." },
      { name: "Amazon ASIN B071GVGVVH", url: "https://www.amazon.com/dp/B071GVGVVH", note: "Exact Bond Bridge BD-1000 draft anchor listing identity." },
    ],
    relatedGuides: ["smart-wall-switches-buying-guide", "smart-wall-switches-compatibility-and-fit-guide", "matter-hubs-bridges-buying-guide"],
  }),

  pilotGuide({
    site: "smarthome",
    slug: "smart-window-air-conditioners-buying-guide",
    familySlug: "smart-window-air-conditioners",
    title: "Smart Window Air Conditioner Buying Guide: Fit, Electrical Load, Noise, and App Value",
    dek: "Choose a connected window AC by room load, window geometry, circuit, installation support, compressor noise, drainage, recall status, and what remains usable offline.",
    category: "climate",
    image: "/images/affiliate/broad-smarthome-window-air-conditioners.webp",
    imageAlt: "Editorial room climate scene representing a smart window air-conditioner installation",
    searchQuestion: "Which smart window air conditioner should I buy for a bedroom or home office?",
    quickAnswer: "Size cooling capacity to the room and conditions, then verify the exact window opening, circuit, support, noise profile, and drainage. Wi-Fi scheduling is useful only after the unit fits safely and still has complete physical controls. Check current recalls by model and serial before installing or buying used.",
    governance: {
      decision: "rewrite",
      independentDemand: "Window AC buyers need a model-specific fit and installation decision plus an offline-control check, not a general smart thermostat or indoor-air monitor article.",
      distinctFrom: "Existing smart-home climate coverage does not answer sash geometry, saddle versus conventional chassis, dedicated circuit needs, seasonal sealing, condensate, or appliance recall verification.",
      benchmark: "Publish only after exact BTU class, room-size guidance, window dimensions, electrical requirements, support hardware, app/platform behavior, and recall status are rechecked.",
    },
    comparisonTable: {
      title: "Window AC checks in the order that matters",
      columns: ["Confirm", "Why it can disqualify a model"],
      rows: [
        { label: "Cooling load", values: ["Room area, sun, ceiling, people, equipment", "Oversizing can cycle poorly; undersizing may run continuously."] },
        { label: "Window", values: ["Opening width, sash height, sill depth, screens", "Nominal room coverage cannot compensate for a chassis that does not fit."] },
        { label: "Structure", values: ["Weight, brackets, exterior clearance, lease rules", "Improvised support creates fall, water, and building-envelope risks."] },
        { label: "Electrical", values: ["Voltage, plug, circuit load, extension-cord prohibition", "A convenient outlet may not be a suitable circuit."] },
        { label: "Noise", values: ["Compressor behavior, fan settings, sleep or call use", "One headline dBA does not describe cycling and vibration in the real window."] },
        { label: "Controls", values: ["Physical panel, schedule, app, platform, outage recovery", "Cloud features do not replace local control or safe restart behavior."] },
      ],
    },
    editorialMethod: [
      "Use Energy Star sizing guidance, the exact installation manual, and measured window geometry.",
      "Treat structural support, circuit suitability, and recall status as publication and purchase gates.",
      "Separate cooling performance from app convenience and platform compatibility.",
      "Avoid claims based on retailer review averages or an unverified current price.",
    ],
    sections: [
      { heading: "Size the cooling job before choosing features", body: "Measure the room and adjust for sun exposure, ceiling height, occupancy, cooking, and heat-producing office equipment. Use current sizing guidance rather than automatically buying the largest BTU number. The product must manage humidity and normal load without making short cycles, drafts, or constant maximum operation the default." },
      { heading: "Measure the complete window opening", body: "Record opening width and height, sash travel, sill and stool depth, storm window, exterior obstruction, screen removal, wall thickness, unit weight, and the manufacturer's required support. A U- or saddle-shaped chassis can preserve more view but creates its own sill and wall-clearance rules." },
      { heading: "Verify electricity, support, sealing, and water", body: "Use the stated voltage and plug on a suitable grounded circuit; follow the manual on extension cords and shared loads. Install approved brackets and anti-tip or sash restraints where required. Plan seasonal air sealing, condensate direction, exterior clearance, filter access, and safe removal or storage." },
      { heading: "Evaluate noise and smart control in the real routine", body: "Bedroom and meeting-room use is affected by compressor transitions, fan pitch, chassis vibration, street opening, and notification sounds—not just one laboratory number. Confirm physical controls, scheduling, shared access, privacy, router or internet outage behavior, power-loss restart, and whether a smart plug is prohibited for the appliance." },
      { heading: "Run a recall and identity check", body: "Before purchase and installation, match brand, exact model, serial range, manufacture information, and any open safety notice through the manufacturer and CPSC. Do the same for used or transferred units. Skip the connected premium when a correctly sized non-connected inverter model meets the schedule through reliable onboard controls." },
    ],
    sources: [
      { name: "GE Profile PWDV08WWF product page", url: "https://www.geappliances.com/appliance/GE-PROFILE-8-000-BTU-Smart-Electronic-Window-Air-Conditioner-for-Medium-Rooms-up-to-350-sq-ft-PWDV08WWF", note: "Official model dimensions, electrical, installation, controls, and performance information for the current draft anchor." },
      { name: "ENERGY STAR room air-conditioner guidance", url: "https://www.energystar.gov/products/room_air_conditioners", note: "Authoritative room sizing and efficiency context." },
      { name: "CPSC recalls search", url: "https://www.cpsc.gov/Recalls", note: "Model and serial recall verification before publication and installation." },
      { name: "Amazon ASIN B0CJMVS4G3", url: "https://www.amazon.com/dp/B0CJMVS4G3", note: "Exact GE Profile PWDV08WWF draft anchor listing identity." },
    ],
    relatedGuides: ["indoor-air-quality-monitors-buying-guide", "temperature-humidity-sensors-buying-guide"],
  }),

  pilotGuide({
    site: "homeoffice",
    slug: "standing-desk-converters-buying-guide",
    familySlug: "standing-desk-converters",
    title: "Standing Desk Converter Buying Guide: Work Surface, Lift Range, and Stability",
    dek: "Choose a desktop sit-stand converter by existing desk strength, keyboard and monitor geometry, lift path, usable surface, stability, and the seated setup it leaves behind.",
    category: "desks",
    image: "/images/affiliate/broad-homeoffice-standing-desk-converters.webp",
    imageAlt: "Editorial home-office desk scene representing a desktop standing converter",
    searchQuestion: "Should I buy a standing desk converter or replace my desk with a full height-adjustable desk?",
    quickAnswer: "A converter is sensible when the existing desk is stable, the added seated height still fits, and the platform holds the real keyboard and monitor arrangement through its full lift path. Choose a full adjustable desk when depth, knee space, load, wobble, or seated ergonomics fail after stacking a converter on top.",
    governance: {
      decision: "rewrite",
      independentDemand: "Converter buyers must evaluate the interaction with an existing fixed desk; that is a separate purchase from choosing a complete electric standing desk.",
      distinctFrom: "Existing standing-desk pages do not cover added seated height, forward lift travel, keyboard-tray geometry, desktop load concentration, or keeping the original desk.",
      benchmark: "Publish only after platform dimensions, keyboard tray, lift range, load, base footprint, travel path, assembly, and exact ASIN are rechecked.",
    },
    comparisonTable: {
      title: "Converter or full adjustable desk?",
      columns: ["Desktop converter", "Full height-adjustable desk"],
      rows: [
        { label: "Existing furniture", values: ["Keeps a suitable stable desk", "Replaces the desk and resets the whole geometry."] },
        { label: "Seated height", values: ["Adds thickness above the old surface", "Can usually lower the entire surface farther."] },
        { label: "Usable depth", values: ["Platform and keyboard tray divide the space", "Larger continuous top is easier for varied layouts."] },
        { label: "Lift motion", values: ["May move up, forward, or in an arc", "Usually moves vertically but needs frame clearance."] },
        { label: "Load and stability", values: ["Depends on converter and original desk", "Depends on frame, top, feet, and assembly."] },
        { label: "Move or rental", values: ["Easier to add and remove", "More capable but heavier and more disruptive."] },
      ],
    },
    editorialMethod: [
      "Measure both seated and standing geometry with the current desk, chair, monitors, and input devices.",
      "Map the converter base and complete lift path before relying on top dimensions.",
      "Use manufacturer limits for load and adjustment; avoid medical or posture-correction claims.",
      "Recheck the precise platform variant and Amazon listing before publication.",
    ],
    communityEvidence: [{
      sourceName: "Reddit r/Ergonomics",
      title: "Standing desk converter decision discussion",
      url: "https://www.reddit.com/r/Ergonomics/comments/1ts0svx",
      note: "Used to identify recurring complaints about added seated height, shallow work surfaces, and monitor movement; no anecdote is represented as clinical evidence.",
    }],
    sections: [
      { heading: "Audit the desk you already own", body: "Measure top depth, width, thickness, flat support area, edge shape, wall clearance, drawer or hutch interference, and rated or credible load capacity. Check wobble before adding height and leverage. A converter cannot repair a weak desk, and a large stated top can still sit on a base that does not fit the available surface." },
      { heading: "Build the seated position first", body: "Converter platforms raise the keyboard and may move it forward. Measure the lowest keyboard height, chair range, elbow position, monitor eye line, knee room, mouse space, and wrist clearance. If the lowest setting makes normal seated work awkward, the product fails even if its standing height is ideal." },
      { heading: "Simulate the complete standing layout", body: "Place cardboard outlines for the base, upper platform, keyboard tray, laptop, monitors, arms, speakers, notebook, and cup. Trace any forward or arcing lift path and reserve cable slack. Confirm the highest useful keyboard position for the actual user rather than choosing by total advertised lift range." },
      { heading: "Check stability through the motion", body: "Add the real equipment weight and compare it with the stated capacity. Monitor arms introduce leverage that a simple weight total misses. Test typing, mouse movement, screen shake, pinch points, release handles, and controlled lowering before the return window closes. Keep children and pets away from the moving mechanism." },
      { heading: "Choose the full desk when the stack becomes the problem", body: "A complete adjustable desk is the cleaner choice when the converter consumes needed depth, raises the seated position too far, leaves poor monitor distance, overloads the old top, or wobbles at working height. Whichever path fits, alternate positions and movement based on comfort; no furniture guarantees a medical or posture outcome." },
    ],
    sources: [
      { name: "VIVO DESK-V000V product page", url: "https://vivo-us.com/products/desk-v000v", note: "Official dimensions, weight capacity, lift range, keyboard tray, and assembly context for the draft anchor." },
      { name: "OSHA computer workstation guidance", url: "https://www.osha.gov/etools/computer-workstations", note: "Authoritative workstation layout and adjustment principles without product-specific medical claims." },
      { name: "Amazon ASIN B0784HWPN6", url: "https://www.amazon.com/dp/B0784HWPN6", note: "Exact VIVO 36-inch draft anchor listing identity." },
    ],
    relatedGuides: ["standing-desk-anti-fatigue-mats-buying-guide", "adjustable-laptop-stands-buying-guide"],
    relatedProducts: ["ergear-48x24-electric-standing-desk"],
  }),

  pilotGuide({
    site: "homeoffice",
    slug: "usb-document-cameras-buying-guide",
    familySlug: "usb-document-cameras",
    title: "USB Document Camera Buying Guide: Detail, Working Area, Focus, and Meeting Apps",
    dek: "Choose a document camera by the objects you show, working distance, autofocus behavior, mounting stability, USB compatibility, lighting, and the meeting or teaching software.",
    category: "meetings",
    image: "/images/affiliate/broad-homeoffice-usb-document-cameras.webp",
    imageAlt: "Editorial video-call workspace representing an overhead USB document camera",
    searchQuestion: "Which USB document camera should I buy for handwriting, product demonstrations, crafts, or remote teaching?",
    quickAnswer: "Start with the largest object or page and the smallest detail viewers must read. Choose a camera and stand that cover that area at a stable working height, with controllable focus and exposure in the actual app. A high megapixel count cannot fix a shaking arm, glare, compression, or an unsupported USB path.",
    governance: {
      decision: "rewrite",
      independentDemand: "Showing paper or objects from above requires working-area, focus, stand, and lighting decisions that a face-level webcam page does not answer.",
      distinctFrom: "Existing webcam and desk-light guides focus on faces and calls rather than flat documents, demonstrations, manual focus, image rotation, and overhead clearance.",
      benchmark: "Publish only after sensor output, supported resolutions, focus modes, working distance, articulation, USB and OS compatibility, software path, and exact ASIN are checked.",
    },
    comparisonTable: {
      title: "Document-camera requirements by demonstration",
      columns: ["Prioritize", "Common failure"],
      rows: [
        { label: "Full letter page", values: ["Wide enough field at a usable height", "Stand cannot rise enough without cropping corners."] },
        { label: "Handwriting", values: ["Stable mount, exposure lock, low delay", "Autofocus hunts when the hand crosses the page."] },
        { label: "Small components", values: ["Close focus, controllable light, sufficient detail", "Digital zoom enlarges blur or compression."] },
        { label: "3D objects", values: ["Articulated head and depth of field", "Flatbed-style position hides sides and labels."] },
        { label: "Meeting apps", values: ["UVC camera recognition and selectable resolution", "App reduces quality or mirrors and crops unexpectedly."] },
        { label: "Shared desks", values: ["Repeatable fold, cable reach, quick alignment", "Setup takes longer than the demonstration saves."] },
      ],
    },
    editorialMethod: [
      "Define field of view and smallest readable detail with a real page or object.",
      "Test the full USB, operating-system, meeting-app, recording, and sharing path.",
      "Evaluate stand stability, glare, shadow, focus, and exposure separately from sensor resolution.",
      "Treat the exact Amazon listing as a model anchor, not proof of app performance on every computer.",
    ],
    sections: [
      { heading: "Measure the demonstration area", body: "Choose the largest sheet, book, circuit board, craft, or product you regularly show. Mark its footprint and the camera position on the desk. Compare the required field of view at a practical arm height, leaving room for hands and tools. A camera that captures a letter page only from an unstable maximum extension is not a good fit." },
      { heading: "Match focus behavior to moving hands", body: "Continuous autofocus can help with objects at changing heights but may pulse when a hand enters the frame. Manual focus or focus lock can be better for handwriting and fixed work. Check close-focus distance, exposure compensation, white balance, image rotation, mirroring, and whether controls work in the chosen app or only in vendor software." },
      { heading: "Design the stand and light as part of the image", body: "A rigid arm and weighted base often improve legibility more than extra pixels. Look for hinge drift, desk vibration, cable pull, shadow from the camera head, glossy-page glare, and flicker from room lighting. Use diffuse side lighting and preserve an unobstructed work area rather than pointing one harsh lamp straight down." },
      { heading: "Verify the complete software path", body: "Confirm the operating system, USB connector and bandwidth, driver policy, UVC recognition, app camera selection, maximum transmitted resolution, screen sharing, recording, and any managed-computer restrictions. Make a local recording in the actual meeting platform; a camera's capture resolution may be reduced by the app or network." },
      { heading: "When a webcam or phone mount is enough", body: "Use an existing webcam on a secure overhead mount when it already covers the field, focuses reliably, and leaves controls accessible. A phone can offer excellent image quality but adds battery, notification, mount, app, and account friction. Buy a dedicated document camera when repeatable deployment and a stable working area are the real needs." },
    ],
    sources: [
      { name: "IPEVO V4K product page", url: "https://www.ipevo.com/products/v4k", note: "Official sensor, resolution, focus, arm, compatibility, and software details for the draft anchor." },
      { name: "IPEVO V4K support", url: "https://www.ipevo.com/software/visualizer", note: "Manufacturer software and supported control workflow." },
      { name: "Amazon ASIN B079DLTG9F", url: "https://www.amazon.com/dp/B079DLTG9F", note: "Exact IPEVO V4K draft anchor listing identity." },
    ],
    relatedGuides: ["video-call-setup-guide", "business-usb-c-monitors-buying-guide"],
    relatedProducts: ["logitech-mx-brio-4k-webcam", "elgato-key-light-neo"],
  }),

  pilotGuide({
    site: "homeoffice",
    slug: "ergonomic-kneeling-chairs-buying-guide",
    familySlug: "ergonomic-kneeling-chairs",
    title: "Kneeling Chair Buying Guide: Fit Range, Pressure, Adjustment, and Desk Height",
    dek: "Choose a kneeling chair by body fit, shin-pad pressure, seat angle, adjustment sequence, desk clearance, entry and exit, and whether it complements rather than replaces movement.",
    category: "ergonomics",
    image: "/images/affiliate/broad-homeoffice-kneeling-chairs.webp",
    imageAlt: "Editorial ergonomic workspace representing an adjustable kneeling chair",
    searchQuestion: "Is a kneeling chair worth buying for a home office, and how do I know whether it will fit?",
    quickAnswer: "Treat a kneeling chair as an optional alternate seat, not a posture treatment. It is worth trying only when the adjustment range matches the user and desk, the shin support does not create pressure, and entry and exit are safe. Keep a conventional adjustable chair and regular movement available.",
    governance: {
      decision: "rewrite",
      independentDemand: "Buyers are deciding whether a nontraditional supported-kneeling position fits their body, desk, mobility, and rotation routine—not choosing another conventional task chair.",
      distinctFrom: "Existing ergonomic chair pages do not address shin loading, angled-seat fit, limited back support, entry difficulty, or alternating between seat types.",
      benchmark: "Publish only after adjustment range, seat and pad dimensions, load rating, caster or rocker design, assembly, return terms, and exact ASIN are verified; make no medical claims.",
    },
    comparisonTable: {
      title: "Kneeling-chair fit checks",
      columns: ["Pass signal", "Skip signal"],
      rows: [
        { label: "Adjustment", values: ["User can set hip, knee, and foot position without crowding", "One fixed geometry must serve very different users."] },
        { label: "Shin pressure", values: ["Pads distribute contact without pain or numbness", "Pressure concentrates at knees or shins."] },
        { label: "Desk fit", values: ["Hands reach input devices without raised shoulders", "Seat height collides with desk or forces awkward reach."] },
        { label: "Entry and exit", values: ["User can sit, stand, and move it safely", "Mobility, balance, clothing, or workspace makes transitions difficult."] },
        { label: "Task duration", values: ["Used as one position in a varied day", "Expected to force one position for long sessions."] },
        { label: "Fallback", values: ["Conventional chair and movement remain available", "Purchase requires abandoning a proven comfortable setup."] },
      ],
    },
    editorialMethod: [
      "Evaluate fit and task geometry without promising pain relief, posture correction, or treatment.",
      "Measure the user, desk, keyboard, monitor, and entry path as one system.",
      "Prioritize a reversible trial, clear return terms, and gradual use.",
      "Verify the exact model dimensions and load rating before publication.",
    ],
    sections: [
      { heading: "Decide whether an alternate seat is useful", body: "A kneeling chair changes how the seat and shin pads share support. It does not remove the need to adjust the desk, keyboard, monitor, breaks, or total sitting time. Define the task and duration it might serve, and keep the current chair available rather than expecting one unfamiliar position to solve discomfort." },
      { heading: "Fit the user and desk together", body: "Check user height, body proportions, stated load limit, seat height and angle range, distance to shin pads, foot clearance, desk underside, keyboard height, and monitor line of sight. Shared workstations need an adjustment process that each user can repeat. A broad height claim is weaker than dimensions and a reversible trial." },
      { heading: "Pay attention to pressure and transitions", body: "Support should contact the shins rather than concentrate force on the kneecaps. Stop for pain, numbness, swelling, instability, or difficulty standing. People with relevant joint, circulation, balance, mobility, pregnancy, or medical concerns should seek appropriate professional guidance instead of treating marketing language as an assessment." },
      { heading: "Inspect frame, wheels, and assembly", body: "Compare frame stiffness, base footprint, fasteners, pad attachment, caster behavior or rocking arc, floor protection, pinch points, and movement under the desk. Retighten only as the manual specifies. A rolling base may ease entry but should not slide unpredictably when weight transfers to it." },
      { heading: "Use it as part of position variety", body: "Begin with short, comfortable sessions and rotate among sitting, standing, and movement according to the user's response. Skip the category when desk height cannot be corrected, shin pressure remains uncomfortable, safe entry is difficult, or the return policy does not permit a meaningful home trial. Comfort is individual evidence, not a cure claim." },
    ],
    sources: [
      { name: "VIVO DRAGONN DN-CH-K01B product page", url: "https://vivo-us.com/products/dn-ch-k01b", note: "Official adjustment, dimensions, capacity, frame, caster, and assembly information for the draft anchor." },
      { name: "OSHA computer workstation guidance", url: "https://www.osha.gov/etools/computer-workstations", note: "Authoritative neutral-position, adjustability, and workstation evaluation context." },
      { name: "Amazon ASIN B073ZN7B52", url: "https://www.amazon.com/dp/B073ZN7B52", note: "Exact DRAGONN draft anchor listing identity." },
    ],
    relatedGuides: ["office-footrests-buying-guide", "standing-desk-anti-fatigue-mats-buying-guide"],
    relatedProducts: ["hon-ignition-2-0-chair", "branch-ergonomic-chair"],
  }),

  pilotGuide({
    site: "baby",
    slug: "baby-food-storage-containers-buying-guide",
    familySlug: "baby-food-storage-containers",
    title: "Baby Food Storage Container Buying Guide: Portions, Freezing, Labels, and Cleaning",
    dek: "Choose reusable baby-food containers by real portion size, material, freezer and reheating workflow, leak resistance, labeling, stacking, cleaning, and replacement access.",
    category: "feeding",
    image: "/images/affiliate/broad-baby-food-storage-containers.webp",
    imageAlt: "Editorial infant-feeding preparation scene representing portioned baby-food storage",
    searchQuestion: "Which baby food storage containers are best for small portions, freezing, daycare, and reheating?",
    quickAnswer: "Choose containers around the food volume and handling path you actually use. Verify material, lid fit, freezer and reheating instructions, date labeling, cleaning access, and daycare rules. Small individual containers are convenient for transport; trays can be efficient for batch freezing when portions are transferred and labeled safely.",
    governance: {
      decision: "rewrite",
      independentDemand: "Parents choosing portion storage need material, temperature, label, leak, and rotation decisions that baby-food-maker pages do not answer.",
      distinctFrom: "Existing feeding content covers preparation appliances, warming, washing, and drying but not storing homemade portions across refrigerator, freezer, bag, daycare, and reheating steps.",
      benchmark: "Publish only after exact container volume, material, temperature limits, lid instructions, dishwasher guidance, replacement parts, and current ASIN are rechecked.",
    },
    comparisonTable: {
      title: "Choose the container format by workflow",
      columns: ["Works well when", "Watch for"],
      rows: [
        { label: "Small glass tubs", values: ["Portions move from fridge or freezer to table", "Weight, breakage, thermal shock, and bulky transport."] },
        { label: "Plastic tubs", values: ["Light weight and drop resistance matter", "Scratches, stains, odors, and exact heat limits."] },
        { label: "Silicone pods", values: ["Flexible release and compact portions matter", "Lid seal, odor retention, and supported heating method."] },
        { label: "Freezer tray", values: ["One batch becomes many same-size portions", "Cubes need dated protected storage after release."] },
        { label: "Pouches", values: ["Portable dispensing is the primary job", "Cleaning, drying, valve access, and caregiver supervision."] },
        { label: "Ordinary containers", values: ["Food-safe sizes already match the routine", "Oversized volume and unclear daycare or heating fit."] },
      ],
    },
    editorialMethod: [
      "Trace one portion from preparation through cooling, labeling, storage, transport, reheating, feeding, leftovers, and washing.",
      "Use public food-safety guidance for time and temperature boundaries, plus exact manufacturer care instructions.",
      "Separate container convenience from nutrition, allergy, and feeding-development decisions.",
      "Recheck material, size, lid count, and Amazon variant before publication.",
    ],
    sections: [
      { heading: "Start with one real serving path", body: "Record typical portion volume, food texture, preparation batch, refrigerator and freezer space, transport distance, daycare labeling, reheating method, and who feeds the child. A large set is not efficient when the chosen sizes create leftovers, occupy the wrong shelf, or cannot follow the household's normal cleaning cycle." },
      { heading: "Verify every temperature transition", body: "Use only the manufacturer's stated freezer, refrigerator, dishwasher, microwave, oven, and warming instructions for the exact material and lid. Allow for expansion, vent or remove lids as directed, avoid thermal shock, and inspect glass, seals, and surfaces. A freezer-safe claim does not automatically authorize every reheating method." },
      { heading: "Design labeling and rotation", body: "Label contents and preparation or storage date using a system that survives condensation and washing. Put older portions where caregivers can see them, and separate allergen or texture stages when that matters. Follow current food-safety and pediatric guidance for preparation, cooling, refrigeration, freezing, thawing, reheating, and leftovers rather than extending time because the seal looks tight." },
      { heading: "Test lids, stacking, and cleaning", body: "Fill one container with the actual texture, close it as another caregiver would, transport it upright and on its side, freeze it, thaw it by the approved method, and clean every groove. Confirm lids remain paired, containers stack without trapping moisture, replacement parts exist, and worn, cracked, chipped, warped, or persistently odorous pieces can be removed." },
      { heading: "When ordinary containers or trays are enough", body: "Use existing food-safe containers when their portions, lids, labels, temperature limits, and daycare rules already fit. A covered tray can simplify batch freezing if portions are transferred to dated protected storage as directed. Skip elaborate systems that add proprietary parts or difficult cleaning without making the real feeding workflow safer or easier." },
    ],
    sources: [
      { name: "OXO Tot Glass Baby Blocks", url: "https://www.oxo.com/glass-baby-blocks.html", note: "Official capacity, materials, lid, storage, and care information for the draft anchor." },
      { name: "USDA food storage guidance", url: "https://www.foodsafety.gov/food-safety-charts/cold-food-storage-charts", note: "Authoritative refrigerator and freezer storage context; follow child-specific clinical advice when applicable." },
      { name: "CDC food safety for young children", url: "https://www.cdc.gov/food-safety/about/safer-food-choices-for-children-under-5-years-old.html", note: "Public-health food handling context for young children." },
      { name: "Amazon ASIN B075H1X6M7", url: "https://www.amazon.com/dp/B075H1X6M7", note: "Exact OXO Tot 4-ounce Glass Baby Blocks draft anchor identity." },
    ],
    relatedGuides: ["baby-food-makers-buying-guide", "automatic-bottle-washers-buying-guide", "baby-bottle-drying-rack-storage-workflow-guide"],
  }),

  pilotGuide({
    site: "baby",
    slug: "baby-bouncers-buying-guide",
    familySlug: "baby-bouncers",
    title: "Baby Bouncer Buying Guide: Fit, Supervision, Floor Use, and Sleep Boundaries",
    dek: "Choose a bouncer by the exact child limits, harness, recline, floor stability, caregiver workflow, cleaning, portability, and a firm rule that it is not a sleep space.",
    category: "sleep",
    image: "/images/affiliate/broad-baby-bouncers.webp",
    imageAlt: "Editorial nursery scene representing an awake and supervised baby-bouncer setup",
    searchQuestion: "Which baby bouncer should I buy, and what safety limits matter before using it?",
    quickAnswer: "Choose only a current model whose stated age, weight, development, harness, and recline limits match the child and whose base sits stable on the floor. Use it only while the baby is awake and supervised. If the baby falls asleep, move the baby to a firm, flat sleep surface designed for infant sleep.",
    governance: {
      decision: "rewrite",
      independentDemand: "A bouncer is awake-time soothing equipment with product-specific restraint and developmental limits; it is not interchangeable with a bassinet, swing, carrier, or play mat.",
      distinctFrom: "Existing baby sleep content does not answer bouncer recline, restraint, floor placement, awake supervision, portability, or mandatory transfer from inclined sitting to safe sleep.",
      benchmark: "Publish only after exact model, child limits, positions, harness, conversion mode, current manual, registration, and recall status are verified.",
    },
    comparisonTable: {
      title: "Bouncer decisions that cannot be inferred from appearance",
      columns: ["Verify", "Boundary"],
      rows: [
        { label: "Child stage", values: ["Exact minimum, maximum, and developmental instructions", "Stop at the earliest stated limit or milestone."] },
        { label: "Position", values: ["Approved recline for the child's current stage", "Do not improvise padding or a different angle."] },
        { label: "Restraint", values: ["Harness fit, routing, buckle, and each-use check", "Never leave straps loose or use unapproved parts."] },
        { label: "Placement", values: ["Stable floor, clear of hazards and pets", "Never use on beds, sofas, counters, or other elevated surfaces."] },
        { label: "Sleep", values: ["Awake, supervised use only", "Transfer a sleeping baby to an approved firm, flat sleep space."] },
        { label: "Care", values: ["Cover removal, washing, frame inspection, storage", "Stop for damage, missing parts, or an applicable recall."] },
      ],
    },
    editorialMethod: [
      "Use the exact current manufacturer manual, CPSC recall record, and public safe-sleep guidance.",
      "Treat age, weight, development, restraint, placement, and sleep as non-negotiable boundaries.",
      "Evaluate cleaning and caregiver use without claiming the product improves sleep or development.",
      "Verify the Amazon color and fabric variant without assuming it changes the base model limits.",
    ],
    sections: [
      { heading: "Match the exact child and model", body: "Read the current manual for minimum and maximum weight, age guidance, recline positions, harness use, and the developmental event that ends infant mode. Use the earliest applicable limit. Similar-looking fabrics and frames can have different instructions, so record the model and manufacture information and register the product where supported." },
      { heading: "Build one safe floor location", body: "Place the bouncer directly on a stable floor, away from stairs, cords, heaters, traffic, climbing siblings, and pets. Never set it on a bed, sofa, table, counter, or other elevated or soft surface. Check the base is fully opened and locked as directed before placing the child in it." },
      { heading: "Use the restraint every time", body: "Route and fasten the harness exactly as the manual shows, with clothing and blankets clear of the buckle and moving frame. Do not carry or move the bouncer with the child in it. Stop using infant mode at the stated weight or developmental milestone and never add padding, toys, or accessories the manufacturer has not approved." },
      { heading: "Keep the sleep boundary explicit", body: "A bouncer is not a crib, bassinet, or sleep surface. Use it only for awake, supervised time. If the baby becomes drowsy or falls asleep, move the baby promptly to a firm, flat surface intended for infant sleep and follow current safe-sleep guidance. Motion, apparent comfort, or an online anecdote does not change that rule." },
      { heading: "Plan cleaning, handoff, and exit", body: "Practice cover removal and correct washing before a spill, inspect seams, harness, fasteners, and frame after cleaning, and keep the manual with the product. Tell every caregiver the same placement and sleep rules. Stop for damage, missing parts, instability, an applicable recall, poor harness fit, or any instruction limit." },
    ],
    sources: [
      { name: "BabyBjörn Bouncer Bliss", url: "https://www.babybjorn.com/products/baby-bouncers/bouncer-bliss/", note: "Official model, positions, child limits, material, and care information for the draft anchor." },
      { name: "CPSC Safe Sleep", url: "https://www.cpsc.gov/SafeSleep", note: "Authoritative safe-sleep surface and transfer boundary." },
      { name: "CPSC recalls search", url: "https://www.cpsc.gov/Recalls", note: "Model and manufacture-date recall check before publication, handoff, or secondhand use." },
      { name: "Amazon ASIN B0CLVMCHTJ", url: "https://www.amazon.com/dp/B0CLVMCHTJ", note: "Exact BabyBjörn Bouncer Bliss draft anchor listing identity; selected fabric must be rechecked." },
    ],
    relatedGuides: ["crib-mattresses-buying-guide", "bedside-bassinets-buying-guide"],
  }),

  pilotGuide({
    site: "baby",
    slug: "baby-play-gyms-buying-guide",
    familySlug: "baby-play-gyms",
    title: "Baby Play Gym Buying Guide: Floor Space, Toy Placement, Cleaning, and Stage Fit",
    dek: "Choose a play gym by usable floor area, age and developmental instructions, toy attachment, overhead clearance, washability, supervision, storage, and how it changes as the baby moves.",
    category: "sleep",
    image: "/images/affiliate/broad-baby-play-gyms.webp",
    imageAlt: "Editorial nursery floor scene representing an awake supervised baby play gym",
    searchQuestion: "Which baby play gym should I buy for newborn floor play and later reaching, kicking, and tummy time?",
    quickAnswer: "Choose a gym that fits a clear floor area, uses age-appropriate securely attached elements, and can be cleaned on the household's real schedule. Favor adjustable or removable toys and enough usable mat space over a long feature list. Use it for awake, supervised floor play—not sleep or containment.",
    governance: {
      decision: "rewrite",
      independentDemand: "Play gyms combine a floor surface, arches, detachable toys, sound or lights, and changing motor stages; that decision is not covered by ordinary play mats or sleep products.",
      distinctFrom: "Current baby pages do not compare overhead toy geometry, kicking panels, detachable small components, mat boundary, cleaning separation, or transition after rolling and mobility.",
      benchmark: "Publish only after exact age guidance, included pieces, attachment method, battery compartment, cleaning instructions, assembly, registration, and recall status are checked.",
    },
    comparisonTable: {
      title: "Play-gym features by real use stage",
      columns: ["Useful when", "Check before choosing"],
      rows: [
        { label: "Overhead arches", values: ["Baby watches and reaches during supervised floor play", "Clearance, stability, attachment security, and removal."] },
        { label: "Kick panel", values: ["Feet can reach it in the approved position", "Volume, battery access, and later seated-play conversion."] },
        { label: "Detachable toys", values: ["Positions can change as reach develops", "Age grading, small parts, cords, loops, and wear."] },
        { label: "Padded mat", values: ["Floor is clean, firm, and comfortable", "Washability, seam drying, traction, and actual usable area."] },
        { label: "Portable fold", values: ["Gym moves between clear supervised areas", "Loose pieces, arch stress, and storage footprint."] },
        { label: "Simple mat and toys", values: ["Household already owns suitable age-appropriate toys", "Requires more setup but may be easier to wash and rotate."] },
      ],
    },
    editorialMethod: [
      "Evaluate the exact included toy set and assembly rather than treating every color variant as identical.",
      "Use age grading, manufacturer instructions, CPSC recall checks, and supervised-use boundaries.",
      "Separate play and caregiver convenience claims from sleep, therapy, or developmental promises.",
      "Model washing and drying of the mat, fabric parts, plastic toys, and electronic unit separately.",
    ],
    communityEvidence: [{
      sourceName: "Reddit r/lovevery",
      title: "Play-gym use and value discussion",
      url: "https://www.reddit.com/r/lovevery/comments/1ls9ryg",
      note: "Used to identify buyer questions about usable months, toy rotation, floor space, and simpler alternatives; owner comments are not product-performance proof.",
    }],
    sections: [
      { heading: "Measure clear floor space, not package size", body: "Open the gym footprint on a firm, level floor and include arch width, kicking panel, caregiver kneeling space, and a clear perimeter away from furniture edges, cords, heaters, stairs, and pets. A compact stored shape does not prove it leaves enough unobstructed play space when assembled." },
      { heading: "Match toys to the current stage", body: "Check the exact age grading and instructions, then position only approved attachments where the baby can see or reach them without adding cords, loops, clips, or household objects. Reassess after rolling, grabbing, mouthing, sitting, or pulling changes the interaction. Remove damaged or no-longer-appropriate pieces immediately." },
      { heading: "Inspect every attachment and battery door", body: "Before each session, check arches, hooks, seams, mirrors, hard edges, toy closures, electronic panels, and battery compartments. Assemble and lock parts exactly as instructed. A detachable object must remain age-appropriate in the way it is used after removal, and a familiar toy still needs inspection after washing or travel." },
      { heading: "Plan separate cleaning paths", body: "The mat, fabric toys, hard plastic pieces, mirror, and electronic panel may have different care instructions. Confirm what can be machine washed, wiped, or submerged, then dry completely before reassembly. Avoid scented or improvised cleaners not supported by the instructions, and keep battery areas dry." },
      { heading: "Keep play, sleep, and containment separate", body: "Use the gym only for awake, supervised floor play. It is not a sleep surface, restraint, play yard, or substitute for caregiver observation. A simple washable mat with a few age-appropriate toys may be better when storage is tight, electronics would go unused, or the integrated design makes cleaning and stage changes harder." },
    ],
    sources: [
      { name: "Fisher-Price FWT10 instruction sheet", url: "https://service.mattel.com/instruction_sheets/FWT10-Eng.pdf", note: "Manufacturer assembly, battery, use, and care instructions for the Kick and Play gym family represented by the draft anchor." },
      { name: "CPSC recalls search", url: "https://www.cpsc.gov/Recalls", note: "Exact product and date recall check before publication and use." },
      { name: "CPSC toy safety guidance", url: "https://www.cpsc.gov/Safety-Education/Safety-Guides/Toys", note: "Authoritative age grading, small-parts, and toy-condition context." },
      { name: "Amazon ASIN B0793D9WBY", url: "https://www.amazon.com/dp/B0793D9WBY", note: "Exact Fisher-Price Deluxe Kick and Play Piano Gym draft anchor identity." },
    ],
    relatedGuides: ["baby-bouncers-buying-guide", "crib-mattresses-buying-guide"],
  }),

  pilotGuide({
    site: "pet",
    slug: "collapsible-wire-dog-crates-buying-guide",
    familySlug: "collapsible-wire-dog-crates",
    title: "Collapsible Wire Dog Crate Buying Guide: Size, Door Path, Divider, and Safe Setup",
    dek: "Choose a folding wire crate by the individual dog's standing and turning measurements, door clearance, wire and latch condition, divider plan, tray, flooring, transport, and supervised introduction.",
    category: "comfort",
    image: "/images/affiliate/broad-pet-collapsible-wire-dog-crates.webp",
    imageAlt: "Editorial pet room scene representing a correctly sized folding wire dog crate",
    searchQuestion: "What size collapsible wire dog crate should I buy, and when is wire better than plastic or soft-sided construction?",
    quickAnswer: "Measure the dog standing, turning, and lying naturally, then match the manufacturer's interior dimensions rather than a breed label. A wire crate is useful for ventilation, visibility, and a removable divider; choose plastic for a more enclosed travel-style shell or soft-sided only for an already calm dog under appropriate supervision.",
    governance: {
      decision: "rewrite",
      independentDemand: "Crate buyers need an animal-specific size, construction, door, divider, setup, and behavior decision—not a general dog bed or carrier comparison.",
      distinctFrom: "Existing pet comfort pages do not answer wire spacing, latch access, collapsible frame locks, divider growth plan, tray fit, crate cover, or introduction workflow.",
      benchmark: "Publish only after exact internal and external dimensions, weight range guidance, wire spacing, doors, latches, divider, tray, assembly, and current ASIN are verified.",
    },
    comparisonTable: {
      title: "Wire, plastic, and soft-sided crate trade-offs",
      columns: ["Best fit", "Main limit"],
      rows: [
        { label: "Folding wire", values: ["Home use, airflow, visibility, divider adjustment", "Heavy, open, and unsuitable for dogs that can bend or panic against wire."] },
        { label: "Plastic kennel", values: ["More enclosed rest and some approved travel uses", "Bulkier storage and less adjustable interior."] },
        { label: "Soft-sided crate", values: ["Portable temporary setup for crate-comfortable dogs", "Fabric and mesh are not escape-resistant for chewing or panic."] },
        { label: "Single door", values: ["One clear room path", "Can force awkward placement or access."] },
        { label: "Multiple doors", values: ["More flexible room placement", "Adds latches and panels to inspect."] },
        { label: "Divider", values: ["Adjusts usable space during growth or training", "Must fit securely without trapping paws or collar hardware."] },
      ],
    },
    editorialMethod: [
      "Use the dog's measurements and behavior plus the exact manufacturer's interior dimensions.",
      "Separate home containment, rest, vehicle restraint, and airline transport requirements.",
      "Treat introduction and distress as behavior and welfare issues, not proof that a stronger crate is always the answer.",
      "Recheck model, door count, divider, tray, and current Amazon variant before publication.",
    ],
    communityEvidence: [{
      sourceName: "Reddit r/poodles",
      title: "Dog crate sizing discussion",
      url: "https://www.reddit.com/r/poodles/comments/1lnemxi",
      note: "Used to identify recurring confusion about adult size, dividers, and breed labels; individual comments do not replace measuring the dog or professional behavior advice.",
    }],
    sections: [
      { heading: "Measure the individual dog", body: "Measure standing height to the top of the head or ears as appropriate, nose-to-rump length, turning space, and the natural lying posture. Compare those measurements with the exact interior dimensions and current manufacturer sizing guidance. Breed and weight ranges are starting points because dogs of the same label can have different proportions." },
      { heading: "Plan doors and room clearance", body: "Mark the crate's outside footprint, every door swing, latch reach, baseboard, vent, heater, sunlight, cord, foot traffic, and emergency exit. Confirm the tray can slide out for cleaning without moving furniture. A second door is valuable only if it creates a genuinely safer or easier placement." },
      { heading: "Inspect the folded frame and divider", body: "Follow the assembly sequence, fully engage frame hooks and locks, secure the divider exactly as instructed, and inspect wire ends, welds, coating, hinges, handles, latches, tray, and gaps. Remove collars or gear when advised to reduce snag risk, and never lift or carry an occupied folding crate by its handle." },
      { heading: "Introduce confinement gradually", body: "Pair the crate with short voluntary sessions, normal rewards, and calm release rather than using it as punishment. Monitor for panting, drooling, frantic escape attempts, bent wire, injury, or escalating distress. A dog that panics in confinement may need veterinary or qualified behavior support, not simply a heavier crate." },
      { heading: "Keep each crate type in its lane", body: "A home wire crate is not automatically approved as vehicle restraint or airline cargo equipment. Check the carrier, vehicle, airline, and destination rules for the exact trip. Choose plastic or soft-sided construction only when its containment, ventilation, access, cleaning, and the dog's behavior fit the real job." },
    ],
    sources: [
      { name: "RSPCA crate-training guidance", url: "https://www.rspca.org.uk/adviceandwelfare/pets/dogs/environment/crates", note: "Independent welfare guidance for crate sizing, gradual introduction, placement, water access, and avoiding punitive confinement." },
      { name: "Humane World crate-training guidance", url: "https://www.humaneworld.org/en/resources/crate-training-101", note: "Animal-welfare context for gradual introduction and avoiding punishment or prolonged confinement." },
      { name: "Amazon ASIN B09G48LHVX", url: "https://www.amazon.com/dp/B09G48LHVX", note: "Exact Amazon Basics 36-inch double-door crate draft anchor listing identity." },
    ],
    relatedGuides: ["washable-orthopedic-pet-beds-buying-guide", "soft-sided-pet-carriers-buying-guide"],
    relatedProducts: ["petfusion-ultimate-dog-bed"],
  }),

  pilotGuide({
    site: "pet",
    slug: "cat-trees-and-towers-buying-guide",
    familySlug: "cat-trees-and-towers",
    title: "Cat Tree and Tower Buying Guide: Stability, Perch Size, Scratching, and Placement",
    dek: "Choose a cat tower by the cat's body and mobility, base stability, vertical spacing, perch and condo dimensions, scratching surfaces, anchoring, cleaning, and the room route.",
    category: "comfort",
    image: "/images/affiliate/broad-pet-cat-trees-and-towers.webp",
    imageAlt: "Editorial cat room scene representing a stable multi-level cat tree",
    searchQuestion: "Which cat tree should I buy for a large cat, multiple cats, or a small apartment?",
    quickAnswer: "Choose the shortest stable tower that provides the elevations and scratching surfaces the cats will actually use. Compare base footprint, perch and opening dimensions, level spacing, total load, anti-tip anchoring, fabric cleanability, and placement near a useful view. Height alone is a poor measure of fit.",
    governance: {
      decision: "rewrite",
      independentDemand: "A freestanding vertical structure must be matched to cat size, jumping ability, shared routes, anchoring, and room layout; that decision differs from beds, scratchers, or wall shelves.",
      distinctFrom: "Existing comfort content does not assess base leverage, perch body fit, condo entrances, level transitions, multi-cat escape paths, scratching orientation, or anti-tip attachment.",
      benchmark: "Publish only after exact assembled dimensions, base, perch and condo sizes, stated capacity, materials, anchoring hardware, replacement parts, assembly, and ASIN are checked.",
    },
    comparisonTable: {
      title: "Cat-tower features that determine real fit",
      columns: ["Measure", "Failure to avoid"],
      rows: [
        { label: "Base", values: ["Footprint, weight, floor level, wall anchor route", "Tall narrow unit rocks or tips during a jump."] },
        { label: "Perches", values: ["Usable length, width, rim, and body support", "Cat hangs off a headline 'large' perch."] },
        { label: "Level spacing", values: ["Jump height, landing area, route up and down", "Older or less mobile cat cannot transition safely."] },
        { label: "Condos", values: ["Interior and opening dimensions, exits, airflow", "Cat cannot turn or another cat can block the only exit."] },
        { label: "Scratch zones", values: ["Horizontal or vertical preference and usable height", "Short wrapped sections do not allow a full stretch."] },
        { label: "Surface care", values: ["Hair removal, spot cleaning, replaceable posts", "Odor, loose fabric, and worn rope make the unit disposable."] },
      ],
    },
    editorialMethod: [
      "Measure each cat and observe existing climbing, sleeping, scratching, and avoidance behavior.",
      "Model the assembled structure, wall anchor, landing forces, and multi-cat routes in the intended room.",
      "Use exact dimensions instead of manufacturer size adjectives or retailer review averages.",
      "Recheck every included component and current Amazon variation before publication.",
    ],
    sections: [
      { heading: "Buy for the cat, not the silhouette", body: "Measure body length, comfortable curl or stretch, shoulder width, and the current height each cat reaches willingly. Observe vertical versus horizontal scratching, enclosed versus open sleep, and whether age, weight, vision, arthritis, or confidence changes jumping. A dramatic tower can fail if its usable surfaces are too small." },
      { heading: "Evaluate stability as a system", body: "Compare base width and weight, tower height, post spacing, connector design, floor level, wall distance, anchor hardware, and the force of a running jump. Assemble on a flat surface, tighten in the specified order, use the approved anti-tip attachment, and recheck fasteners after initial use. Keep unstable units out of service." },
      { heading: "Trace routes for every cat", body: "Map the approach, landing, climb, turnaround, retreat, and descent. Multi-cat homes need more than one comfortable destination and routes that reduce blocking. Older or small cats may benefit from closer steps and broad landings; an agile large cat still needs perches and openings that support its actual body." },
      { heading: "Judge scratching and cleaning separately", body: "Check how much post height remains available for a full stretch, whether rope or fabric can be replaced, and which orientation the cats already prefer. Inspect exposed staples, loose fibers, torn plush, wobbling posts, hair, vomit, and odor. Follow material-specific cleaning instructions and dry fully before access." },
      { heading: "Consider lower and distributed alternatives", body: "Use a lower broad tower when tip risk or mobility makes height less useful. Wall shelves can distribute routes but require appropriate wall structure and precise installation. Separate beds and scratchers can be easier to clean and replace in a small room. Choose the arrangement that creates stable usable territory, not the largest object that fits the floor plan." },
    ],
    sources: [
      { name: "Yaheetech cat tree collection", url: "https://www.yaheetech.shop/collections/cat-trees", note: "Manufacturer model and component context; exact 54-inch variant dimensions must be verified before publication." },
      { name: "Ohio State Indoor Pet Initiative: environmental needs", url: "https://indoorpet.osu.edu/cats/basic-indoor-cat-needs", note: "Veterinary-school context for vertical space, resting, scratching, and environmental choice." },
      { name: "Amazon ASIN B0794T79KM", url: "https://www.amazon.com/dp/B0794T79KM", note: "Exact Yaheetech 54-inch dark-gray draft anchor listing identity." },
    ],
    relatedGuides: ["washable-orthopedic-pet-beds-buying-guide", "interactive-puzzle-feeders-buying-guide"],
  }),

  pilotGuide({
    site: "pet",
    slug: "pet-strollers-buying-guide",
    familySlug: "pet-strollers",
    title: "Pet Stroller Buying Guide: Cabin Fit, Entry, Wheels, Brakes, and Folding",
    dek: "Choose a dog or cat stroller by the individual animal's cabin dimensions and weight, entry method, floor support, wheel and brake fit, ventilation, restraint points, folding, and transport route.",
    category: "comfort",
    image: "/images/affiliate/broad-pet-strollers.webp",
    imageAlt: "Editorial pet travel scene representing a compact pet stroller",
    searchQuestion: "Which pet stroller should I buy for a small dog, cat, senior pet, or mobility-limited animal?",
    quickAnswer: "Match cabin length, width, height, floor support, entry height, and stated load to the individual animal—weight capacity alone is not enough. Then test wheel size, brakes, handle fit, restraint attachment, fold size, and the complete doorway, sidewalk, car, or transit route. Ask a veterinarian about new mobility or exercise limits.",
    governance: {
      decision: "rewrite",
      independentDemand: "A wheeled cabin creates animal-fit, handling, braking, terrain, fold, and restraint decisions that soft carriers, ramps, harnesses, and travel crates do not answer.",
      distinctFrom: "Existing pet travel content does not compare stroller cabin geometry, entry height, wheel diameter, curb behavior, brake access, handle height, or one-hand loading and folding.",
      benchmark: "Publish only after exact cabin and folded dimensions, load capacity, wheel and brake design, tether instructions, ventilation, cleaning, assembly, and current ASIN are verified.",
    },
    comparisonTable: {
      title: "Pet mobility and transport options",
      columns: ["Useful when", "Not a substitute for"],
      rows: [
        { label: "Pet stroller", values: ["Animal needs a wheeled resting or protected transport option", "Veterinary evaluation, safe exercise, or a vehicle restraint."] },
        { label: "Soft carrier", values: ["Short carried trips and accepted cabin fit", "Long uneven routes or a load the caregiver cannot carry."] },
        { label: "Mobility harness", values: ["Pet can walk with appropriate assisted support", "A diagnosis or individualized rehabilitation plan."] },
        { label: "Wagon", values: ["Large flat cargo area is useful and safely adapted", "A pet-specific enclosure, tether, ventilation, or brake design."] },
        { label: "Small wheels", values: ["Smooth indoor floors and compact folding", "Cracks, gravel, curbs, or rough paths."] },
        { label: "Larger wheels", values: ["Uneven outdoor surfaces and longer routes", "Compact storage or easy lifting into a small car."] },
      ],
    },
    editorialMethod: [
      "Measure the animal in its natural seated and lying positions plus every doorway, vehicle, and storage point.",
      "Evaluate restraint, ventilation, floor support, wheel behavior, brakes, and folding as one transport workflow.",
      "Avoid medical or rehabilitation claims and direct new mobility changes to veterinary assessment.",
      "Recheck exact color, cabin, wheel, and accessory variant on Amazon before publication.",
    ],
    sections: [
      { heading: "Start with the animal's body and reason for use", body: "Measure natural body length, seated height, shoulder width, turning space, and current weight. Note heat tolerance, balance, vision, anxiety, ability to step in, and any recent change in walking. New pain, weakness, breathing difficulty, or exercise intolerance needs veterinary attention; a stroller should not hide an undiagnosed problem." },
      { heading: "Match the cabin and entry", body: "Compare usable interior dimensions rather than outside size. Check floor stiffness, padding, head clearance, ventilation with covers open and closed, entry height, zipper or latch path, and whether the pet can turn and lie naturally. Load and unload with brakes set, and support the animal as its condition requires." },
      { heading: "Choose wheels for the complete route", body: "Walk the planned path and note thresholds, elevator gaps, curb cuts, broken pavement, gravel, grass, slopes, rain, crowds, and transit rules. Small wheels save folded space but catch more easily. Confirm steering, wheel locks, parking brakes, handle height, tip behavior, visibility, and safe curb technique before a long outing." },
      { heading: "Use only approved restraint points", body: "Follow the manual for internal tether attachment and suitable harness use; do not clip to a collar in a way that can injure or entangle the pet. Keep the enclosure closed as instructed, hands on the stroller on slopes, and the animal supervised. A stroller is not a crash-tested vehicle restraint unless the exact product explicitly establishes that separate use." },
      { heading: "Rehearse folding, storage, and cleaning", body: "Practice removing the pet, setting brakes, folding, lifting, loading the vehicle, reopening, and checking locks without rushing. Measure the folded unit, cargo opening, stair carry, and caregiver lift. Clean liners, mesh, frame, and wheels according to the manual and stop using damaged tethers, latches, fabric, wheels, or brakes." },
    ],
    sources: [
      { name: "Pet Gear Happy Trails Lite", url: "https://www.petgearinc.com/product_info.asp?id=938", note: "Official dimensions, capacity, entry, mesh, tether, wheels, brake, fold, and care information for the draft anchor." },
      { name: "AVMA pet mobility and veterinary care resources", url: "https://www.avma.org/resources/pet-owners", note: "Veterinary context for changes in health or mobility; the stroller page makes no diagnosis or treatment claim." },
      { name: "Amazon ASIN B00THLOACM", url: "https://www.amazon.com/dp/B00THLOACM", note: "Exact Pet Gear Happy Trails Lite Boysenberry draft anchor identity." },
    ],
    relatedGuides: ["soft-sided-pet-carriers-buying-guide", "dog-ramps-buying-guide", "vehicle-pet-restraints-buying-guide"],
  }),
];
