import type { Guide, Product, Roundup, SiteKey, Tool } from "./types";
import { amazonProductOverrides } from "./amazon-overrides";

export const products: Product[] = [
  {
    site: "pet",
    slug: "petlibro-granary-automatic-cat-feeder",
    asin: "B0BYD73PHN",
    name: "PETLIBRO Granary Automatic Cat Feeder",
    brand: "PETLIBRO",
    category: "feeding",
    image: "/images/affiliate/pet-petlibro-granary-automatic-cat-feeder.webp",
    summary: "An automatic dry-food feeder for cats and small dogs where steady meal timing matters more than extra smart features.",
    verdict: "The PETLIBRO Granary is the feeder to start with when the goal is dependable scheduled feeding without turning every meal into an app project.",
    whyItMatters: "Automatic feeders solve routine friction only if the food path stays clean, portions are predictable, and the pet cannot easily break into the hopper.",
    bestFor: "Cats that need scheduled dry-food meals",
    priceBand: "$",
    rating: 4.6,
    scores: [
      { label: "Portion control", value: 9 },
      { label: "Cleaning", value: 7 },
      { label: "Reliability", value: 8 },
    ],
    pros: ["Good fit for timed dry-kibble routines", "Sealed hopper helps keep food fresher", "Simple enough for non-smart-home households"],
    cons: ["Not for wet food", "Large or irregular kibble can still be a compatibility risk"],
    specs: { ASIN: "B0BYD73PHN", "Product type": "Automatic feeder", "Use case": "Scheduled meals", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm the exact Granary capacity and Wi-Fi/app version on Amazon", "Verify kibble-size compatibility before relying on scheduled portions", "Compare power backup, bowl access, and chute cleaning steps"],
    alternatives: ["Choose a larger feeder only if you travel often or feed multiple pets.", "Use a slow feeder bowl if the main issue is eating speed rather than timing."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/3Qj2NaW", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "pet",
    slug: "catit-flower-cat-water-fountain",
    asin: "B0146QXOB0",
    name: "Catit Flower Cat Water Fountain",
    brand: "Catit",
    category: "feeding",
    image: "/images/affiliate/pet-catit-flower-cat-water-fountain.webp",
    summary: "A cat water fountain for homes where encouraging drinking matters more than smart tracking.",
    verdict: "The Catit Flower Fountain is a practical first fountain because it is easy to understand, easy to place, and focused on the one job most cats need: fresher moving water.",
    whyItMatters: "Water fountains can help some cats drink more, but only if the unit is quiet enough, easy enough to clean, and does not become another ignored appliance.",
    bestFor: "Cats that prefer moving water",
    priceBand: "$",
    rating: 4.3,
    scores: [
      { label: "Cleaning", value: 8 },
      { label: "Cat appeal", value: 8 },
      { label: "Counter fit", value: 8 },
    ],
    pros: ["Simple design with recognizable replacement filters", "Good low-cost fountain option", "Small enough for kitchens and laundry rooms"],
    cons: ["Filter replacements add ongoing cost", "Some cats still prefer bowls"],
    specs: { ASIN: "B0146QXOB0", "Product type": "Water fountain", "Use case": "Daily hydration", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm compatible Catit replacement filters for the exact fountain version", "Compare reservoir size against number of cats", "Verify pump access and plastic cleaning steps before buying"],
    alternatives: ["Choose a stainless-steel fountain if plastic cleaning is a concern.", "Keep a backup water bowl nearby during the transition."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4oFSqdZ", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "pet",
    slug: "furbo-360-dog-camera",
    asin: "B0BWN22T25",
    name: "Furbo 360 Dog Camera",
    brand: "Furbo",
    category: "home-care",
    image: "/images/affiliate/pet-furbo-360-dog-camera.webp",
    summary: "A treat-tossing pet camera for dog owners who want check-ins, two-way audio, and a more interactive camera.",
    verdict: "Furbo 360 makes the most sense when the camera is part reassurance and part routine interaction, especially for dogs that respond well to voice and treats.",
    whyItMatters: "Pet cameras are easy to overbuy. The useful question is whether alerts, app access, audio, and treat features reduce anxiety or just add more notifications.",
    bestFor: "Dog owners who want interactive check-ins",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Video clarity", value: 8 },
      { label: "Alerts", value: 8 },
      { label: "Interaction", value: 9 },
    ],
    pros: ["Treat tossing can make check-ins more engaging", "Wide rotating view suits open rooms", "Strong brand recognition for pet-camera shoppers"],
    cons: ["Smart alerts and cloud features can involve ongoing cost", "Treat compatibility and placement need checking"],
    specs: { ASIN: "B0BWN22T25", "Product type": "Pet camera", "Use case": "Interactive monitoring", "Link status": "Amazon affiliate link added" },
    evidence: ["Compare which alerts require a Furbo subscription", "Check treat-size compatibility and whether your dog reacts calmly", "Verify camera placement, 360-degree room coverage, and privacy comfort"],
    alternatives: ["Choose a basic Wyze-style camera if you only need live view.", "Skip treat tossing if your dog gets overexcited or guards food."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/43SYVR1", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "pet",
    slug: "wyze-cam-pan-v3-pet-camera",
    asin: "B0DTNKLF1K",
    name: "Wyze Cam Pan v3",
    brand: "Wyze",
    category: "home-care",
    image: "/images/affiliate/pet-wyze-cam-pan-v3-pet-camera.webp",
    summary: "A budget pan-and-tilt camera that can work for pet check-ins when treat tossing is unnecessary.",
    verdict: "Wyze Cam Pan v3 is the budget comparison point for pet monitoring: less pet-specific, but often enough for people who just want to see the room.",
    whyItMatters: "A general security camera can be the better buy if the pet does not need treats or two-way interaction. The trade-off is fewer pet-specific alerts and a less playful experience.",
    bestFor: "Budget pet check-ins in apartments",
    priceBand: "$",
    rating: 4.2,
    scores: [
      { label: "Budget fit", value: 9 },
      { label: "Room coverage", value: 8 },
      { label: "Pet features", value: 5 },
    ],
    pros: ["Lower cost than dedicated pet cameras", "Pan-and-tilt view helps cover more of a room", "Useful for simple live checks"],
    cons: ["No treat tossing", "Cloud storage and smart alerts may need plan review"],
    specs: { ASIN: "B0DTNKLF1K", "Product type": "Indoor camera", "Use case": "Simple pet monitoring", "Link status": "Amazon affiliate link added" },
    evidence: ["Compare Wyze cloud, local storage, and privacy settings", "Check placement where the pet actually rests, not just the room entrance", "Verify whether pan tracking or subscription features are needed"],
    alternatives: ["Choose Furbo if treat tossing is important.", "Use a fixed camera if the room is small and the pet stays in one spot."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4w0eORs", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "pet",
    slug: "litter-genie-plus-pail",
    asin: "B09V399NTV",
    name: "Litter Genie Plus Pail",
    brand: "Litter Genie",
    category: "home-care",
    image: "/images/affiliate/pet-litter-genie-plus-pail.webp",
    summary: "A litter disposal pail for reducing daily odor trips between the litter box and the outside trash.",
    verdict: "Litter Genie Plus is not glamorous, but it solves a real apartment problem: containing scooped litter odor between trash runs.",
    whyItMatters: "Odor control often fails after the box is scooped. A disposal pail can make daily maintenance easier if refill cost and placement are acceptable.",
    bestFor: "Apartments where litter odor control is the priority",
    priceBand: "$",
    rating: 4.4,
    scores: [
      { label: "Odor control", value: 8 },
      { label: "Daily convenience", value: 9 },
      { label: "Refill cost", value: 6 },
    ],
    pros: ["Keeps scooped litter contained near the box", "Useful for multi-day trash routines", "Small footprint for bathrooms or closets"],
    cons: ["Refills add recurring cost", "Does not replace litter-box cleaning"],
    specs: { ASIN: "B09V399NTV", "Product type": "Litter disposal pail", "Use case": "Odor containment", "Link status": "Amazon affiliate link added" },
    evidence: ["Check Litter Genie refill compatibility and recurring cost", "Compare pail footprint against the litter-box area", "Use with regular scooping rather than treating it as a cleaning shortcut"],
    alternatives: ["Choose a covered trash can if refill cost is the main concern.", "Use better litter and ventilation if odor starts before scooping."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4uU4Twb", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "pet",
    slug: "petfusion-ultimate-dog-bed",
    asin: "B089RGDQBB",
    name: "PetFusion Ultimate Dog Bed",
    brand: "PetFusion",
    category: "comfort",
    image: "/images/affiliate/pet-petfusion-ultimate-dog-bed.webp",
    summary: "A supportive bolstered dog bed for pets that need a real rest zone rather than a thin mat.",
    verdict: "PetFusion Ultimate is a good comparison pick when support, washable covers, and a sofa-like edge matter more than the cheapest possible bed.",
    whyItMatters: "Pet beds fail when the foam flattens, covers are hard to wash, or the size is wrong for the dog's sleeping shape.",
    bestFor: "Dogs that like bolsters and supportive foam",
    priceBand: "$",
    rating: 4.5,
    scores: [
      { label: "Support", value: 8 },
      { label: "Washability", value: 8 },
      { label: "Size options", value: 8 },
    ],
    pros: ["Bolster edge suits dogs that curl or lean", "Washable cover matters for long-term use", "Better support than thin budget mats"],
    cons: ["Takes more floor space", "Not the cheapest option for destructive chewers"],
    specs: { ASIN: "B089RGDQBB", "Product type": "Dog bed", "Use case": "Daily comfort", "Link status": "Amazon affiliate link added" },
    evidence: ["Match the selected PetFusion size to the dog's stretched-out sleeping length", "Check cover-removal, zipper access, and washing instructions", "Compare foam support against pet weight and chewing habits"],
    alternatives: ["Choose an elevated cot for hot climates or outdoor use.", "Choose a cheaper washable mat for crates or travel."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4eAjIO1", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "pet",
    slug: "chomchom-roller-pet-hair-remover",
    asin: "B0C2FMZMHP",
    name: "ChomChom Roller Pet Hair Remover",
    brand: "ChomChom",
    category: "home-care",
    image: "/images/affiliate/pet-chomchom-roller-pet-hair-remover.webp",
    summary: "A reusable pet-hair roller for furniture, bedding, and car seats where sticky sheets get expensive.",
    verdict: "ChomChom is a practical first pet-hair tool because it targets the surfaces people actually notice: sofas, blankets, and seats.",
    whyItMatters: "Pet hair cleanup is a repeated chore, so reusable tools can matter more than one-time deep cleaning products.",
    bestFor: "Furniture and car-seat pet hair",
    priceBand: "$",
    rating: 4.6,
    scores: [
      { label: "Furniture cleanup", value: 9 },
      { label: "Running cost", value: 9 },
      { label: "Detail work", value: 6 },
    ],
    pros: ["Reusable design avoids sticky-sheet waste", "Strong fit for sofas and bedding", "Easy impulse add-on for pet households"],
    cons: ["Not for every fabric texture", "Corners and tight seams still need another tool"],
    specs: { ASIN: "B0C2FMZMHP", "Product type": "Pet hair remover", "Use case": "Furniture cleanup", "Link status": "Amazon affiliate link added" },
    evidence: ["Compare surface type before recommending it for sofas, bedding, or car seats", "Use as a reusable furniture tool rather than a vacuum replacement", "Check the hair chamber and cleaning motion so expectations are realistic"],
    alternatives: ["Use a vacuum attachment for rugs and deep seams.", "Choose disposable rollers for clothing and travel bags."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4eUGkKC", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "pet",
    slug: "shark-neverchange-max-air-purifier",
    asin: "B0C95R5CBW",
    name: "Shark NeverChange Max Air Purifier",
    brand: "Shark",
    category: "home-care",
    image: "/images/affiliate/pet-shark-neverchange-max-air-purifier.webp",
    summary: "A larger-room air purifier option for pet homes that need help with dander, dust, odor, and everyday room freshness.",
    verdict: "The Shark NeverChange Max is the pet-home air purifier pick when room coverage matters more than buying the smallest possible unit. It is a better fit for living rooms and open areas than tiny bedroom-only purifiers.",
    whyItMatters: "Air purifiers work best when room size, filter upkeep, noise, and placement are realistic. They should support cleaning routines, not replace litter care, vacuuming, or washing pet bedding.",
    bestFor: "Larger rooms with pet dander and odor concerns",
    priceBand: "$$$",
    rating: 4.4,
    scores: [
      { label: "Room coverage", value: 9 },
      { label: "Noise control", value: 8 },
      { label: "Filter upkeep", value: 7 },
    ],
    pros: ["Better fit for larger pet rooms than compact purifiers", "Targets dust, dander, smoke, and odor support", "Useful when the air purifier needs to live in a main room"],
    cons: ["Larger footprint than small bedroom units", "Odor control still depends on cleaning the source"],
    specs: { ASIN: "B0C95R5CBW", "Product type": "Air purifier", "Use case": "Pet dander, dust, and odor", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm the Shark NeverChange Max model and listed room coverage on Amazon", "Check filter upkeep and replacement terms before comparing price", "Place near pet zones without blocking airflow"],
    alternatives: ["Choose a smaller purifier for a single bedroom.", "Prioritize litter and fabric cleaning if odor starts at the source."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4fZIfP6", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "risepro-compact-standing-desk",
    name: "RisePro Compact Standing Desk",
    brand: "RisePro",
    category: "desks",
    image: "/images/affiliate/homeoffice-risepro-compact-standing-desk.webp",
    summary: "A compact electric standing desk with stable lift behavior for small rooms.",
    bestFor: "Apartments and bedrooms under 120 square feet",
    priceBand: "$$$",
    rating: 4.7,
    scores: [
      { label: "Stability", value: 9 },
      { label: "Assembly", value: 7 },
      { label: "Cable routing", value: 8 },
    ],
    pros: ["Stable at common standing heights", "Memory presets work reliably", "Narrow top still fits dual monitors with an arm"],
    cons: ["Limited color options", "Cable tray is sold separately"],
    specs: { Width: "48 in", Height: "28-47 in", Capacity: "176 lb" },
    evidence: ["Checked wobble at sitting and standing heights", "Measured usable width with monitor arm", "Timed one-person assembly"],
    offers: [],
  },
  {
    site: "homeoffice",
    slug: "alignmesh-ergonomic-chair",
    name: "AlignMesh Ergonomic Chair",
    brand: "AlignMesh",
    category: "ergonomics",
    image: "/images/affiliate/homeoffice-alignmesh-ergonomic-chair.webp",
    summary: "A breathable task chair with enough adjustment range for most home office users.",
    bestFor: "Eight-hour workdays without premium chair pricing",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Adjustability", value: 8 },
      { label: "Seat comfort", value: 8 },
      { label: "Build quality", value: 7 },
    ],
    pros: ["Adjustable lumbar height", "Seat depth fits a wide range of users", "Mesh back stays cool"],
    cons: ["Arm pads feel basic", "Tall users may want a higher backrest"],
    specs: { "Seat height": "17-21 in", "Seat depth": "Adjustable", Warranty: "5 years" },
    evidence: ["Mapped adjustment range to user heights", "Checked pressure points after long sitting blocks", "Compared arm and lumbar travel"],
    offers: [],
  },
  {
    site: "homeoffice",
    slug: "beamkey-video-desk-lamp",
    name: "BeamKey Video Desk Lamp",
    brand: "BeamKey",
    category: "meetings",
    image: "/images/affiliate/homeoffice-beamkey-video-desk-lamp.webp",
    summary: "A desk lamp that doubles as soft video-call lighting without taking over the desk.",
    bestFor: "Remote workers in dim rooms",
    priceBand: "$",
    rating: 4.2,
    scores: [
      { label: "Light quality", value: 8 },
      { label: "Desk footprint", value: 9 },
      { label: "Controls", value: 7 },
    ],
    pros: ["Warm and neutral color modes", "Slim base", "Good face fill when placed behind a monitor"],
    cons: ["No app controls", "Glossy surfaces show fingerprints"],
    specs: { Brightness: "900 lm", "Color modes": "3", Power: "USB-C" },
    evidence: ["Compared webcam exposure before and after", "Measured base footprint", "Checked glare on glossy monitors"],
    offers: [],
  },
  {
    site: "homeoffice",
    slug: "flexispot-e7-mini-standing-desk",
    asin: "B0F9X3FDYY",
    name: "FlexiSpot E7 Mini Standing Desk",
    brand: "FlexiSpot",
    category: "desks",
    image: "/images/affiliate/homeoffice-flexispot-e7-mini-standing-desk.webp",
    summary: "A compact electric standing desk for bedrooms, rentals, and small apartment work corners.",
    verdict: "The E7 Mini is the desk to start with when the room is the constraint. It is less about building a huge command center and more about getting sit-stand movement into a bedroom corner without making the room feel smaller.",
    whyItMatters: "Small desks fail when the monitor stand, laptop, dock, and cables all compete for the same shallow surface. A compact standing desk only works if the top still leaves enough depth for typing posture and screen distance.",
    bestFor: "Small rooms where a full 55-inch desk will not fit",
    priceBand: "$$$",
    rating: 4.6,
    scores: [
      { label: "Small-room fit", value: 9 },
      { label: "Lift range", value: 8 },
      { label: "Accessory needs", value: 7 },
    ],
    pros: ["Shorter desktop options fit tight rooms", "Dual-motor style lift range is useful for sitting and standing", "Good fit for laptop plus one-monitor setups"],
    cons: ["Limited surface area for printers or large speakers", "Cable tray and accessories may need separate purchase"],
    specs: { ASIN: "B0F9X3FDYY", "Desk type": "Electric standing desk", "Use case": "Compact workstation", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm the exact FlexiSpot E7 Mini desktop size and frame option on Amazon", "Compare against full-size desks before ranking", "Check accessory needs such as cable tray, casters, and monitor arm separately"],
    alternatives: ["Choose a larger UPLIFT-style desk if you run two large monitors and have the wall width.", "Use a monitor arm before buying a wider desk if your main problem is depth, not width."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4eRxmxH", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "uplift-v3-standing-desk",
    name: "UPLIFT V3 Standing Desk",
    brand: "UPLIFT Desk",
    category: "desks",
    image: "/images/affiliate/homeoffice-uplift-v3-standing-desk.webp",
    summary: "A configurable standing desk option for heavier multi-monitor home offices.",
    bestFor: "Long-term workstations with heavier monitors and accessories",
    priceBand: "$$$$",
    rating: 4.7,
    scores: [
      { label: "Customization", value: 9 },
      { label: "Heavy setup fit", value: 9 },
      { label: "Budget fit", value: 6 },
    ],
    pros: ["Strong fit for multi-monitor and accessory-heavy setups", "Many configuration paths for desktop size and finish", "Useful premium comparison option"],
    cons: ["Higher total cost once accessories are added", "Large packages can be harder to move or assemble alone"],
    specs: { "Desk type": "Electric standing desk", "Use case": "Premium workstation", "Link status": "Needs confirmed purchase link or secondary merchant" },
    evidence: ["Useful for comparing larger, more configurable standing desks", "Use as a premium alternative in desk roundups", "Verify Amazon listing or use direct brand offer if available"],
    offers: [],
  },
  {
    site: "homeoffice",
    slug: "branch-ergonomic-chair",
    asin: "B0GWGK4JFK",
    name: "Branch Ergonomic Chair",
    brand: "Branch",
    category: "ergonomics",
    image: "/images/affiliate/homeoffice-branch-ergonomic-chair.webp",
    summary: "A mid-range ergonomic chair for home workers who need adjustment without premium chair pricing.",
    verdict: "The Branch Ergonomic Chair is the safer middle path for people leaving a dining chair behind. It has enough adjustment to solve common home-office pain points without jumping into premium-chair pricing.",
    whyItMatters: "Chair fit is personal, but most home workers need the same basics first: seat height that lets feet rest flat, arms that do not force shoulders upward, and back support that stays useful after lunch.",
    bestFor: "Remote workers upgrading from a dining chair",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Adjustment range", value: 8 },
      { label: "Daily comfort", value: 8 },
      { label: "Price fit", value: 8 },
    ],
    pros: ["Useful adjustment set for a broad range of users", "Cleaner design than many budget task chairs", "Strong fit for under-$500 chair shoppers"],
    cons: ["Not as deeply adjustable as premium Steelcase or Herman Miller models", "Fit still depends heavily on user height and seat preference"],
    specs: { ASIN: "B0GWGK4JFK", "Chair type": "Ergonomic task chair", "Use case": "All-day home office", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm the Branch color, arm style, and return policy on the current Amazon listing", "Compare seat depth, lumbar adjustment, and user height range", "Treat chair fit as personal even when the feature set looks right"],
    alternatives: ["Compare HON Ignition 2.0 if you prefer a more traditional office-chair feel.", "Look at used Steelcase or Herman Miller options if return policy and local condition are easy to verify."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4eWkGpe", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "hon-ignition-2-0-chair",
    asin: "B07GNDDNMW",
    name: "HON Ignition 2.0 Ergonomic Chair",
    brand: "HON",
    category: "ergonomics",
    image: "/images/affiliate/homeoffice-hon-ignition-2-0-chair.webp",
    summary: "A practical ergonomic chair for buyers who want office-grade adjustability without luxury pricing.",
    verdict: "HON Ignition 2.0 is a practical pick when adjustability matters more than a designer look. It is best treated as an office-grade workhorse, not a lounge chair.",
    whyItMatters: "A chair can look ergonomic and still miss the basics. The buying question is whether the exact configuration gives you the arm, lumbar, and seat controls your body actually needs.",
    bestFor: "Value-focused buyers who still want adjustable arms and lumbar support",
    priceBand: "$",
    rating: 4.4,
    scores: [
      { label: "Adjustability", value: 8 },
      { label: "Durability signal", value: 8 },
      { label: "Design polish", value: 6 },
    ],
    pros: ["Often easy to find through office suppliers and Amazon", "Good practical alternative to cheap gaming chairs", "Useful for comparison against Branch and Steelcase entry models"],
    cons: ["Plain office look", "Configuration names and listings can be confusing"],
    specs: { ASIN: "B07GNDDNMW", "Chair type": "Task chair", "Use case": "Budget ergonomic upgrade", "Link status": "Amazon affiliate link added" },
    evidence: ["Verify the exact HON Ignition 2.0 configuration before linking", "Compare arm, lumbar, and seat-depth options because listings vary", "Check whether the Amazon seller includes the expected warranty path"],
    alternatives: ["Choose Branch if you want a cleaner home-office look.", "Skip both and shop premium used chairs if you need deeper back customization."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4w3ELzP", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "huanuo-titanlift-heavy-duty-monitor-arm",
    asin: "B0DQ19YC9H",
    name: "HUANUO TitanLift Heavy Duty Monitor Arm",
    brand: "HUANUO",
    category: "ergonomics",
    image: "/images/affiliate/homeoffice-huanuo-titanlift-heavy-duty-monitor-arm.webp",
    summary: "A heavy-duty monitor arm for larger screens where weight rating and desk clamp fit matter before cable tidiness.",
    verdict: "The HUANUO TitanLift is the monitor-arm pick to inspect when you run a heavier ultrawide or large display and a basic arm feels risky.",
    whyItMatters: "A monitor arm is not just a tidiness accessory. For large screens, the real buying question is whether the arm supports the monitor weight, VESA pattern, and desk edge without sagging or crowding the setup.",
    bestFor: "Large or heavier single-monitor setups",
    priceBand: "$$",
    rating: 4.7,
    scores: [
      { label: "Stability", value: 9 },
      { label: "Adjustment", value: 9 },
      { label: "Value", value: 7 },
    ],
    pros: ["Higher weight-rating focus than basic monitor arms", "Helps recover desk depth with large displays", "Useful for ultrawide and gaming-monitor shoppers"],
    cons: ["More arm than a standard 24-inch monitor needs", "Clamp clearance, desk thickness, and VESA support must be checked carefully"],
    specs: { ASIN: "B0DQ19YC9H", "Arm type": "Heavy-duty single monitor arm", "Use case": "Large screen support", "Link status": "Amazon affiliate link added" },
    evidence: ["Verify monitor weight and screen size before brand preference", "Check VESA pattern, desk-edge clearance, and clamp/grommet mounting options", "Compare with budget Amazon Basics arm if your monitor is standard size"],
    alternatives: ["Choose Amazon Basics if price matters more than heavy-screen support.", "Use the stock stand if your monitor is already at eye height and desk depth is not a problem."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/43O98hI", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "amazon-basics-monitor-arm",
    asin: "B0CQXMT3QC",
    name: "Amazon Basics Monitor Arm",
    brand: "Amazon Basics",
    category: "ergonomics",
    image: "/images/affiliate/homeoffice-amazon-basics-monitor-arm.webp",
    summary: "A budget monitor arm for home offices that need better screen height without a premium accessory spend.",
    verdict: "Amazon Basics is the budget monitor-arm option to consider when the goal is simple height and depth improvement, not a premium adjustment feel.",
    whyItMatters: "The cheapest way to make a small desk feel bigger is often removing the bulky stock monitor stand. Just check monitor weight, VESA support, and clamp space before buying.",
    bestFor: "Budget buyers with one standard-size monitor",
    priceBand: "$",
    rating: 4.2,
    scores: [
      { label: "Budget fit", value: 9 },
      { label: "Adjustment", value: 7 },
      { label: "Finish", value: 6 },
    ],
    pros: ["Good low-cost comparison option", "Can make a small desk feel deeper", "Easy Amazon search and purchase path"],
    cons: ["Less polished than premium arms", "Weight and clamp limits need careful checking"],
    specs: { ASIN: "B0CQXMT3QC", "Arm type": "Single monitor arm", "Use case": "Budget setup", "Link status": "Amazon affiliate link added" },
    evidence: ["Verify current Amazon Basics listing compatibility with your monitor weight", "Check VESA pattern and desk clamp clearance before buying", "Compare against HUANUO TitanLift if heavy-screen support matters"],
    alternatives: ["Choose HUANUO TitanLift if heavy-screen support matters more than the lowest price.", "Avoid a monitor arm if your desk edge is too thin, too thick, or blocked by a rear panel."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/3Sjls73", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "logitech-litra-glow",
    name: "Logitech Litra Glow",
    brand: "Logitech",
    category: "meetings",
    image: "/images/affiliate/homeoffice-logitech-litra-glow.webp",
    summary: "A compact video-call light for improving face lighting without adding a large studio panel.",
    verdict: "Logitech Litra Glow is the simple meeting-light pick when you want better face exposure without building a creator studio around your desk.",
    whyItMatters: "Most bad video calls are lighting problems before they are webcam problems. A compact front light can make a normal laptop or webcam feed look cleaner and less shadowy.",
    bestFor: "Laptop and monitor-based video calls in dim rooms",
    priceBand: "$",
    rating: 4.4,
    scores: [
      { label: "Video-call fit", value: 9 },
      { label: "Desk footprint", value: 9 },
      { label: "Lighting control", value: 8 },
    ],
    pros: ["Small enough for crowded desks", "Strong fit for remote meeting searches", "Brand is easy for buyers to recognize"],
    cons: ["Not a full room light", "Mounting position depends on monitor thickness and setup"],
    specs: { "Light type": "Compact video light", "Use case": "Meetings", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm the current Logitech Litra Glow mount and power connection on Amazon", "Compare with desk lamps and larger key lights", "Check whether it fits your monitor or laptop placement"],
    alternatives: ["Choose BenQ ScreenBar Halo if desk illumination matters more than face lighting.", "Use a regular lamp if it can sit in front of you without glare."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4eUoqaK", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "benq-screenbar-halo",
    name: "BenQ ScreenBar Halo",
    brand: "BenQ",
    category: "meetings",
    image: "/images/affiliate/homeoffice-benq-screenbar-halo.webp",
    summary: "A monitor light bar for reducing desk clutter while improving keyboard and desk illumination.",
    verdict: "The ScreenBar Halo is a desk-lighting upgrade for people who want the work surface lit but do not want another lamp base eating desk space.",
    whyItMatters: "In compact offices, lighting and clutter fight each other. A monitor light bar can brighten the keyboard and desk area while leaving room for notebooks, docks, and input devices.",
    bestFor: "Desk lighting without taking up surface space",
    priceBand: "$",
    rating: 4.5,
    scores: [
      { label: "Desk footprint", value: 10 },
      { label: "Lighting quality", value: 8 },
      { label: "Budget fit", value: 6 },
    ],
    pros: ["Leaves the desktop clear", "Pairs naturally with monitor-arm setups", "Good premium lighting option"],
    cons: ["More expensive than basic lamps", "May not fit every monitor shape cleanly"],
    specs: { "Light type": "Monitor light bar", "Use case": "Desk illumination", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm BenQ ScreenBar Halo compatibility with the monitor shape and bezel", "Check whether the included controller and backlight matter for your desk", "Compare with Logitech Litra Glow for camera-focused lighting"],
    alternatives: ["Choose Logitech Litra Glow if your main issue is how your face looks on calls.", "Choose a standard desk lamp if you need room lighting, not just desktop lighting."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4gw54dg", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "anker-675-usb-c-docking-station",
    name: "Anker 675 USB-C Docking Station",
    brand: "Anker",
    category: "desks",
    image: "/images/affiliate/homeoffice-anker-675-usb-c-docking-station.webp",
    summary: "A docking station for laptop users who want a cleaner desk, charging, and quick monitor/peripheral connections.",
    verdict: "The Anker 675 is best for laptop-first workers who want the desk to behave like a docking station instead of a nest of loose cables.",
    whyItMatters: "Cable management is easiest when the connection routine is simple. If one cable can handle display, charging, and peripherals, the desk is more likely to stay clean after real workdays.",
    bestFor: "Laptop-first workers who dock and undock daily",
    priceBand: "$$",
    rating: 4.3,
    scores: [
      { label: "Cable cleanup", value: 9 },
      { label: "Laptop workflow", value: 8 },
      { label: "Budget fit", value: 6 },
    ],
    pros: ["Natural fit for cable-managed laptop desks", "Useful for one-cable laptop desk setups", "Pairs well with standing desks and monitor arms"],
    cons: ["Port needs vary by laptop", "Higher cost than simple USB hubs"],
    specs: { "Device type": "USB-C docking station", "Use case": "Cable management", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm the current Anker 675 port layout against your laptop and monitor", "Verify charging wattage, display support, and cable placement before buying", "Use as an optional upgrade rather than a universal recommendation"],
    alternatives: ["Use a cheaper USB-C hub if you only connect one monitor and a keyboard.", "Skip a dock if your laptop rarely leaves the desk."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4xZcT1J", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "baby",
    slug: "infant-optics-dxr-8-pro",
    name: "Infant Optics DXR-8 PRO Baby Monitor",
    brand: "Infant Optics",
    category: "sleep",
    image: "/images/affiliate/baby-infant-optics-dxr-8-pro.webp",
    summary: "A dedicated baby monitor for parents who want a separate screen instead of relying on a phone app overnight.",
    verdict: "Infant Optics DXR-8 PRO is a strong starting point for parents who want local monitoring, a parent unit, and less phone dependency at night.",
    whyItMatters: "Baby monitors are partly about reassurance and partly about friction. A dedicated parent unit can be easier at 2 a.m. than opening an app, checking Wi-Fi, and managing phone battery.",
    bestFor: "Parents who want a non-Wi-Fi parent unit",
    priceBand: "$$",
    rating: 4.6,
    scores: [
      { label: "Night video", value: 9 },
      { label: "Parent unit", value: 9 },
      { label: "Ease of use", value: 8 },
    ],
    pros: ["Dedicated screen avoids phone dependence", "Good fit for overnight monitoring", "Interchangeable lens ecosystem is useful for different rooms"],
    cons: ["Not ideal if remote app access is the main need", "Parent-unit battery and range still need household checking"],
    specs: { "Product type": "Baby monitor", "Use case": "Local overnight monitoring", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm the DXR-8 PRO bundle contents, lens options, and parent-unit details on Amazon", "Compare local monitor versus Wi-Fi preference", "Check room layout, range needs, and overnight charging routine"],
    alternatives: ["Choose Nanit if app insights and wall-mounted tracking matter more.", "Choose a simpler audio monitor if video adds more anxiety than value."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/44mp7Ub", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "baby",
    slug: "nanit-pro-smart-baby-monitor",
    name: "Nanit Pro Smart Baby Monitor",
    brand: "Nanit",
    category: "sleep",
    image: "/images/affiliate/baby-nanit-pro-smart-baby-monitor.webp",
    summary: "A smart Wi-Fi baby monitor for parents who want app access, sleep insights, and a more connected nursery setup.",
    verdict: "Nanit Pro is the premium smart-monitor comparison point. It is best for parents who want data and remote app access, not just a camera feed.",
    whyItMatters: "Smart monitors can be helpful, but subscription features, mounting position, Wi-Fi reliability, and privacy comfort matter before the feature list.",
    bestFor: "Parents who want smart sleep insights",
    priceBand: "$$",
    rating: 4.4,
    scores: [
      { label: "Smart features", value: 9 },
      { label: "Video setup", value: 8 },
      { label: "Budget fit", value: 5 },
    ],
    pros: ["Strong app-first feature set", "Useful for parents who want remote access", "Good comparison point for premium nursery tech"],
    cons: ["Higher price than local monitors", "Subscription and mounting details need careful review"],
    specs: { "Product type": "Smart baby monitor", "Use case": "App-based monitoring", "Link status": "Amazon affiliate link added" },
    evidence: ["Check which Nanit insights require a subscription", "Verify the included mount or stand option for the nursery", "Compare Wi-Fi privacy comfort against local monitors"],
    alternatives: ["Choose Infant Optics if you want a parent unit and less app dependence.", "Use an audio monitor if sleep data is not helpful for your household."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4en5QrN", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "baby",
    slug: "baby-jogger-city-tour-2-stroller",
    name: "Baby Jogger City Tour 2 Stroller",
    brand: "Baby Jogger",
    category: "travel",
    image: "/images/affiliate/baby-baby-jogger-city-tour-2-stroller.svg",
    summary: "A compact travel stroller for families who need a smaller fold without giving up everyday errand usability.",
    verdict: "City Tour 2 is a practical travel-stroller pick when storage and car-trunk space matter, but the stroller still needs to feel useful outside the airport.",
    whyItMatters: "Travel strollers are often bought for one trip, then used for errands every week. Fold size, recline, basket access, and wheel behavior all matter.",
    bestFor: "Families balancing travel and daily errands",
    priceBand: "$$",
    rating: 4.4,
    scores: [
      { label: "Fold size", value: 9 },
      { label: "Maneuvering", value: 8 },
      { label: "Storage", value: 6 },
    ],
    pros: ["Compact fold for small cars and apartments", "More everyday-friendly than ultra-minimal umbrella strollers", "Good fit for travel-stroller comparisons"],
    cons: ["Basket space is limited", "Rough sidewalks may still favor a larger stroller"],
    specs: { "Product type": "Travel stroller", "Use case": "Errands and travel", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm the exact City Tour 2 version, color, and included accessories on Amazon", "Compare folded dimensions against trunk, hallway, and travel storage needs", "Check age, weight, recline, basket access, and car-seat adapter compatibility"],
    alternatives: ["Choose Summer 3Dlite if price and simplicity matter more.", "Choose a full-size stroller if rough sidewalks are daily reality."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/3SoHfKv", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "baby",
    slug: "summer-3dlite-convenience-stroller",
    name: "Summer 3Dlite Convenience Stroller",
    brand: "Summer",
    category: "travel",
    image: "/images/affiliate/baby-summer-3dlite-convenience-stroller.webp",
    summary: "A budget-friendly lightweight stroller for errands, grandparents' cars, and simple travel needs.",
    verdict: "Summer 3Dlite is the value comparison pick: not the most polished stroller, but a sensible lightweight option when budget and simplicity lead.",
    whyItMatters: "A second stroller can be useful if it folds easily, stores easily, and does not make short errands feel like a gear project.",
    bestFor: "Budget lightweight stroller needs",
    priceBand: "$",
    rating: 4.2,
    scores: [
      { label: "Budget fit", value: 9 },
      { label: "Weight", value: 8 },
      { label: "Premium feel", value: 5 },
    ],
    pros: ["Lower cost than premium travel strollers", "Easy to keep as a secondary stroller", "Useful for quick errands"],
    cons: ["Less refined than premium compact strollers", "Comfort and wheel feel have limits"],
    specs: { "Product type": "Lightweight stroller", "Use case": "Budget travel", "Link status": "Amazon affiliate link added" },
    evidence: ["Check the current Summer 3Dlite model, color, and weight limit", "Compare folded size to car trunk or closet space", "Use as a value lightweight stroller rather than an all-terrain stroller"],
    alternatives: ["Choose Baby Jogger City Tour 2 for a more compact travel-first setup.", "Choose a full-size stroller if storage and suspension are priorities."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4w6SNRm", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "baby",
    slug: "philips-avent-bottle-sterilizer",
    name: "Philips Avent Bottle Sterilizer",
    brand: "Philips Avent",
    category: "feeding",
    image: "/images/affiliate/baby-philips-avent-bottle-sterilizer.webp",
    summary: "A countertop sterilizer for families who want a dedicated bottle routine without relying on microwave bags.",
    verdict: "Philips Avent is a familiar sterilizer option for bottle-heavy households that want a clear countertop routine and broad bottle-brand recognition.",
    whyItMatters: "Feeding gear is used when parents are tired. Capacity, drying expectations, and cleaning steps matter more than fancy buttons.",
    bestFor: "Families cleaning several bottles per day",
    priceBand: "$",
    rating: 4.3,
    scores: [
      { label: "Capacity", value: 8 },
      { label: "Routine fit", value: 8 },
      { label: "Counter footprint", value: 7 },
    ],
    pros: ["Dedicated routine for bottles and small feeding parts", "Recognizable brand for registry shoppers", "Useful when counter space is available"],
    cons: ["Takes more space than microwave bags", "Drying needs vary by exact model"],
    specs: { "Product type": "Bottle sterilizer", "Use case": "Bottle routine", "Link status": "Amazon affiliate link added" },
    evidence: ["Check the exact Philips Avent sterilizer model because drying features vary", "Compare bottle, nipple, cap, and pump-part capacity", "Verify compatibility with the bottle system you actually use"],
    alternatives: ["Choose microwave sterilizer bags for occasional use.", "Choose a washer-style device only if budget and counter space allow."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4xCYDLT", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "baby",
    slug: "baby-brezza-sterilizer-dryer-advanced",
    name: "Baby Brezza Sterilizer Dryer Advanced",
    brand: "Baby Brezza",
    category: "feeding",
    image: "/images/affiliate/baby-baby-brezza-sterilizer-dryer-advanced.webp",
    summary: "A sterilizer and dryer combo for parents who want bottles and pump parts closer to ready-to-use after a cycle.",
    verdict: "Baby Brezza Sterilizer Dryer Advanced is the convenience upgrade when drying time is the pain point, not just sterilizing.",
    whyItMatters: "Sterilizing is only half the routine. Wet parts still need a clean place to dry, and that is where combo units can reduce counter clutter.",
    bestFor: "Parents who want sterilizing plus drying",
    priceBand: "$$",
    rating: 4.4,
    scores: [
      { label: "Drying convenience", value: 9 },
      { label: "Capacity", value: 8 },
      { label: "Counter fit", value: 6 },
    ],
    pros: ["Drying function can simplify bottle routines", "Good fit for pump parts and bottle-heavy days", "Useful registry upgrade item"],
    cons: ["Costs more than basic sterilizers", "Counter footprint and cycle time need checking"],
    specs: { "Product type": "Sterilizer dryer", "Use case": "Bottle and pump-part routine", "Link status": "Amazon affiliate link added" },
    evidence: ["Compare Baby Brezza cycle options, drying modes, and capacity", "Check counter footprint and where clean parts will land after a cycle", "Verify part compatibility for your bottle and pump system"],
    alternatives: ["Choose Philips Avent for a simpler countertop routine.", "Use microwave bags if space is more important than drying convenience."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/3SpGssK", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "baby",
    slug: "ergobaby-omni-breeze-carrier",
    name: "Ergobaby Omni Breeze Baby Carrier",
    brand: "Ergobaby",
    category: "travel",
    image: "/images/affiliate/baby-ergobaby-omni-breeze-carrier.webp",
    summary: "A structured baby carrier for families who want hands-free errands, walks, and travel days.",
    verdict: "Ergobaby Omni Breeze is the carrier to compare when adjustability and airflow matter, especially for parents who expect frequent carrier use.",
    whyItMatters: "A carrier has to fit both baby and adult. Strap adjustment, hip support, heat, and carry positions matter more than color or pattern.",
    bestFor: "Hands-free errands and travel",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Adjustability", value: 9 },
      { label: "Airflow", value: 8 },
      { label: "Learning curve", value: 6 },
    ],
    pros: ["Multiple carry positions", "Good fit for warm-weather carrier shoppers", "Useful alternative to stroller-only travel"],
    cons: ["Needs proper adjustment", "Some parents prefer softer wraps for newborn days"],
    specs: { "Product type": "Baby carrier", "Use case": "Hands-free travel", "Link status": "Amazon affiliate link added" },
    evidence: ["Check Ergobaby's age, weight, and position guidance for the exact Omni Breeze listing", "Compare fit for both caregivers before choosing it as the only carrier", "Review safe positioning instructions before use"],
    alternatives: ["Choose a soft wrap for slower newborn days at home.", "Use a stroller when heat or back comfort is the limiting factor."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/43PAsfm", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "baby",
    slug: "hatch-rest-sound-machine",
    name: "Hatch Rest Sound Machine",
    brand: "Hatch",
    category: "sleep",
    image: "/images/affiliate/baby-hatch-rest-sound-machine.webp",
    summary: "A sound machine and night light for building more consistent nursery sleep cues.",
    verdict: "Hatch Rest is a useful nursery routine tool when parents want sound, light, and repeatable cues in one device.",
    whyItMatters: "Sleep products should support a routine, not promise magic. Consistent sound, dim light, and simple controls can make bedtime smoother.",
    bestFor: "Nursery sound and night-light routines",
    priceBand: "$",
    rating: 4.3,
    scores: [
      { label: "Routine support", value: 8 },
      { label: "Controls", value: 8 },
      { label: "Portability", value: 6 },
    ],
    pros: ["Combines sound and night light", "Useful through baby and toddler stages", "Strong registry recognition"],
    cons: ["App features may be more than some families need", "Not a substitute for safe sleep basics"],
    specs: { "Product type": "Sound machine", "Use case": "Sleep routine", "Link status": "Amazon affiliate link added" },
    evidence: ["Confirm which Hatch Rest generation and app features the Amazon listing includes", "Check room brightness, sound controls, and whether portability matters", "Use alongside safe sleep guidance rather than as a sleep guarantee"],
    alternatives: ["Choose a simple white-noise machine if app features are unnecessary.", "Use a separate dim night light if sound is not needed."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4eW2tbl", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
];

export const roundups: Roundup[] = [
  {
    site: "pet",
    slug: "best-automatic-cat-feeders",
    title: "Best Automatic Cat Feeders for Consistent Meals",
    dek: "Scheduled feeders should solve meal timing without creating cleaning problems, food jams, or a new routine your pet can defeat.",
    category: "feeding",
    intent: "Choose a feeder that keeps meal timing steady without creating cleaning or jamming problems.",
    intro: "Automatic feeders are useful when the household schedule is inconsistent, but they are not all-purpose pet sitters. Start with food type, portion range, cleaning access, and whether the hopper can survive a curious cat. Smart features are nice only after the feeding path is reliable.",
    decisionGuide: [
      { label: "Dry-food routine", detail: "Choose a feeder with clear portion controls and a hopper that seals well." },
      { label: "Pet eats too fast", detail: "A slow feeder may solve the problem better than a scheduled feeder." },
      { label: "Short trips", detail: "Prioritize power backup, food capacity, and a simple schedule you can verify before leaving." },
      { label: "Multiple pets", detail: "Check whether one pet can steal meals before assuming a single feeder is enough." },
    ],
    methodology: ["Check dry-food compatibility before app features", "Compare hopper size against real feeding schedule", "Prioritize cleaning access around the chute and bowl"],
    productSlugs: ["petlibro-granary-automatic-cat-feeder"],
    faqs: [
      { question: "Are automatic feeders safe for wet food?", answer: "Most are designed for dry kibble. Wet-food feeders need cooling packs and shorter holding times." },
      { question: "What matters most for cats on a diet?", answer: "Portion repeatability and a tamper-resistant lid matter more than camera or voice features." },
      { question: "Should I still have someone check on my pet?", answer: "Yes for longer trips. A feeder can support routine, but it does not replace water checks, litter care, and general pet safety." },
    ],
  },
  {
    site: "pet",
    slug: "best-pet-cameras-for-apartments",
    title: "Best Pet Cameras for Apartments",
    dek: "Apartment-friendly pet cameras should balance room coverage, privacy comfort, alerts, and whether interactive features are actually useful.",
    category: "home-care",
    intent: "Keep an eye on pets without turning every hallway shadow into a notification.",
    intro: "A pet camera should reduce worry, not create a second stream of notifications. Dedicated pet cameras are better for interaction, while budget pan-and-tilt cameras can be enough for simple check-ins. The right choice depends on room layout, privacy comfort, subscription tolerance, and how your pet reacts to voice or treats.",
    decisionGuide: [
      { label: "Dog responds to treats", detail: "A treat-tossing camera can make short check-ins more useful." },
      { label: "Simple room check", detail: "A budget pan-and-tilt camera may be enough if live view is the main need." },
      { label: "Privacy-sensitive home", detail: "Check indicator lights, storage settings, and placement before buying." },
      { label: "Notification fatigue", detail: "Favor adjustable alerts over the longest feature list." },
    ],
    methodology: ["Match camera type to the pet's behavior", "Check storage and subscription requirements", "Place the camera where the pet actually rests"],
    productSlugs: ["furbo-360-dog-camera", "wyze-cam-pan-v3-pet-camera"],
    faqs: [
      { question: "Do pet cameras need subscriptions?", answer: "Live view usually works without one, but cloud history and smarter alerts often cost extra." },
      { question: "Where should a pet camera go?", answer: "Place it where your pet naturally rests, with a visible status light and no view into private neighbor spaces." },
      { question: "Is treat tossing always worth it?", answer: "No. It is useful for some dogs, but unnecessary for pets that ignore treats or become overexcited." },
    ],
  },
  {
    site: "pet",
    slug: "best-pet-odor-and-litter-upgrades",
    title: "Best Pet Odor and Litter Upgrades for Apartments",
    dek: "Odor control works best when scooping, disposal, airflow, and cleaning routines support each other.",
    category: "home-care",
    intent: "Reduce pet odor in small homes without relying on one product to solve every source.",
    intro: "Pet odor is usually a system problem. Litter disposal, air movement, fabric cleaning, and routine maintenance all matter. The best upgrade is often the one that removes daily friction, because odor control fails when the routine is too annoying to keep.",
    decisionGuide: [
      { label: "Litter-box odor", detail: "Start with scooping routine and disposal before buying fragrance-heavy products." },
      { label: "Dander and dust", detail: "A compact air purifier can help if the room size and filter upkeep make sense." },
      { label: "Furniture smells", detail: "Washable covers and hair removal matter before room sprays." },
      { label: "Small apartment", detail: "Choose compact tools that can live near the problem area." },
    ],
    methodology: ["Separate litter odor from fabric odor", "Check recurring refill or filter costs", "Match purifier size to the actual room"],
    productSlugs: ["litter-genie-plus-pail", "shark-neverchange-max-air-purifier", "chomchom-roller-pet-hair-remover"],
    faqs: [
      { question: "Will an air purifier remove litter smell?", answer: "It can help with airborne particles and some odors, but it cannot replace scooping, litter changes, or cleaning the box." },
      { question: "Are litter disposal pails worth it?", answer: "They are useful when the outside trash is inconvenient and daily scooping needs better odor containment." },
      { question: "What should I buy first?", answer: "Start with the problem source: litter disposal for box odor, washable textiles for fabric odor, and filtration for dust or dander." },
    ],
  },
  {
    site: "pet",
    slug: "best-dog-beds-and-comfort-upgrades",
    title: "Best Dog Beds and Comfort Upgrades for Everyday Rest",
    dek: "A good comfort upgrade should match your pet's sleep position, cleaning needs, floor space, and chewing behavior.",
    category: "comfort",
    intent: "Choose comfort gear that pets actually use and owners can keep clean.",
    intro: "Pet comfort gear is easy to buy emotionally and hard to keep using if it is the wrong size, hard to wash, or placed where the pet never rests. Start with sleeping shape, washable covers, and where the bed will live in the room.",
    decisionGuide: [
      { label: "Dog curls or leans", detail: "A bolstered bed can feel more secure than a flat mat." },
      { label: "Hot climate", detail: "Consider airflow and washable surfaces before thick foam." },
      { label: "Heavy shedding", detail: "Pair the bed with a reusable hair-removal routine." },
      { label: "Chewer", detail: "Avoid assuming premium foam means chew-proof construction." },
    ],
    methodology: ["Match bed size to sleeping position", "Check cover removal and washing steps", "Consider hair cleanup as part of the comfort routine"],
    productSlugs: ["petfusion-ultimate-dog-bed", "chomchom-roller-pet-hair-remover"],
    faqs: [
      { question: "Do dogs need bolsters?", answer: "Some dogs love a raised edge for leaning or curling, while others prefer flat mats or cool surfaces." },
      { question: "What makes a pet bed easier to own?", answer: "A removable washable cover, realistic size, and fabric that does not trap hair too aggressively." },
      { question: "Should I buy based on weight or length?", answer: "Use both. Weight helps with support, but sleeping length and curl style decide the footprint." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-standing-desks-for-small-spaces",
    title: "Best Standing Desks for Small Spaces",
    dek: "Compact desks need stable lift columns, usable depth, realistic monitor placement, and cable routing that does not eat the work surface.",
    category: "desks",
    intent: "Find a standing desk that fits a bedroom, rental, or apartment corner without feeling like a temporary folding table.",
    intro: "Small-space standing desks are easy to overbuy. A desk can have a great motor and still be wrong if the top is too shallow, the cable path snags when it rises, or the room no longer works as a bedroom after work. Start with the footprint, then check whether the desk can support your monitor, keyboard, and laptop routine without turning every accessory into a separate project.",
    decisionGuide: [
      { label: "Small bedroom corner", detail: "Prioritize a compact top, quiet lift, and a monitor arm rather than a wide desktop." },
      { label: "Laptop plus one monitor", detail: "A small electric desk can work well if the monitor stand does not consume half the depth." },
      { label: "Two large monitors", detail: "Move up to a wider premium desk or use monitor arms before committing to a tiny frame." },
      { label: "Rental apartment", detail: "Favor easy assembly, fewer wall-mounted accessories, and cable routing that can move with you." },
    ],
    methodology: ["Prioritize desktop depth before width for monitor distance", "Check lift range against sitting and standing elbow height", "Account for monitor arms, laptop docks, and cable trays before buying accessories"],
    productSlugs: ["flexispot-e7-mini-standing-desk"],
    faqs: [
      { question: "Is 48 inches wide enough for a home office desk?", answer: "Yes for a laptop plus one or two monitors if you use a monitor arm and keep accessories narrow." },
      { question: "What height range should I look for?", answer: "Choose a desk that supports your seated elbow height and standing elbow height without maxing out the motor." },
      { question: "What should I skip in a small standing desk setup?", answer: "Skip oversized speakers, deep monitor stands, and decorative desk shelves until the core keyboard, mouse, monitor, and cable path are solved." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-ergonomic-chairs-under-500",
    title: "Best Ergonomic Chairs Under $500",
    dek: "A good sub-$500 chair should have real adjustment range, breathable support, usable seat depth, and a return policy that respects body-fit risk.",
    category: "ergonomics",
    intent: "Avoid cheap chairs that look adjustable but fail during long workdays.",
    intro: "The best chair under $500 is not the one with the longest feature list. It is the one that lets you sit at the right height, keep your shoulders relaxed, and change posture without fighting the controls. Return policy matters because two people with the same height can still need different seat depth and lumbar feel.",
    decisionGuide: [
      { label: "First real office chair", detail: "Choose a balanced task chair with clear controls and a reasonable return window." },
      { label: "Hot room or warm climate", detail: "Mesh or breathable backs usually feel better through long summer workdays." },
      { label: "Plain office look is fine", detail: "HON-style task chairs can be a better value than decorative home-office chairs." },
      { label: "Back support is the priority", detail: "Check lumbar height and seat depth before caring about headrests." },
    ],
    methodology: ["Map seat height and seat depth to user height ranges", "Separate task-chair support from lounge-style recline", "Check arm, lumbar, return-window, and warranty details before ranking"],
    productSlugs: ["branch-ergonomic-chair", "hon-ignition-2-0-chair"],
    faqs: [
      { question: "Is mesh better than cushion?", answer: "Mesh runs cooler and supports airflow, while cushion can feel softer but may compress over time." },
      { question: "What adjustment is most important?", answer: "Seat height, seat depth, and lumbar position usually matter more than decorative headrests." },
      { question: "Should I buy a gaming chair for office work?", answer: "Usually only if the fit is excellent. For typing-heavy work, task-chair adjustment and seat depth matter more than racing styling." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-monitor-arms-for-home-office",
    title: "Best Monitor Arms for Home Office Desks",
    dek: "Monitor arms are one of the fastest ways to recover desk depth, reduce neck strain, and make a compact workstation easier to clean.",
    category: "ergonomics",
    intent: "Choose a monitor arm that matches monitor weight, desk edge, cable path, and adjustment needs.",
    intro: "A monitor arm can make a small desk feel more expensive than it is. The win is not the arm itself; it is the desk depth you get back, the cleaner keyboard area, and the ability to put the display where your neck wants it. The risk is buying an arm before checking monitor weight, VESA support, and clamp clearance.",
    decisionGuide: [
      { label: "Premium single monitor", detail: "Choose a smoother arm if you adjust height or depth throughout the week." },
      { label: "Budget setup", detail: "A basic arm can still free meaningful desk space if the monitor weight is within range." },
      { label: "Thick or unusual desk edge", detail: "Measure clamp clearance before buying. Some desks need a different mount plan." },
      { label: "Dual monitor setup", detail: "Consider two single arms for easier positioning unless you know the exact layout." },
    ],
    methodology: ["Check VESA pattern and monitor weight before brand preference", "Compare clamp clearance against the actual desk edge", "Prioritize smooth height and depth adjustment over decorative cable covers"],
    productSlugs: ["huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    faqs: [
      { question: "Do all monitors work with monitor arms?", answer: "No. You need a compatible VESA mount pattern or a reliable adapter, and the monitor weight must sit within the arm's supported range." },
      { question: "Are monitor arms worth it for small desks?", answer: "Often yes. Removing the stock stand can free several inches of usable depth, which matters more than width in many apartments." },
      { question: "Should I buy single or dual monitor arms?", answer: "Single arms are easier to position and upgrade. Dual arms can work well, but they need more careful weight and desk-edge planning." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-video-call-lighting-for-home-office",
    title: "Best Video Call Lighting for Home Offices",
    dek: "Better lighting can improve webcam quality more than buying a new camera, especially in bedrooms, rentals, and dim multipurpose rooms.",
    category: "meetings",
    intent: "Pick lighting that improves face exposure without creating glare, desk clutter, or a complicated studio setup.",
    intro: "Video-call lighting should make you look clearer without turning your desk into a studio. For most people, the right move is a small controllable light near the camera, not a giant panel. If your face is dark but the background is bright, even an expensive webcam will struggle.",
    decisionGuide: [
      { label: "Mostly Zoom or Meet calls", detail: "A compact front-facing video light is usually the fastest improvement." },
      { label: "Need desk lighting too", detail: "A monitor light bar helps the keyboard and desk more than it helps your face." },
      { label: "Tiny desk", detail: "Avoid large lamp bases and pick a light that mounts to the monitor or sits behind it." },
      { label: "Glare-sensitive monitor", detail: "Choose lights with angle control and test placement before keeping the box." },
    ],
    methodology: ["Match the light to the camera position, not just the desk surface", "Check whether the light causes monitor glare", "Prefer compact controls for frequent meeting days"],
    productSlugs: ["logitech-litra-glow", "benq-screenbar-halo"],
    faqs: [
      { question: "Is a desk lamp enough for video calls?", answer: "Sometimes. A lamp can help if it lights your face from the front or side, but it can also create harsh shadows or monitor glare." },
      { question: "Do I need a key light?", answer: "A small video light is usually enough for home meetings. Larger key lights make sense for creators or presenters who record often." },
      { question: "Where should I place a video light?", answer: "Near the camera and slightly above eye level is a good starting point. Avoid placing the only light behind you." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-home-office-cable-management",
    title: "Best Home Office Cable Management Upgrades",
    dek: "Cable management is not just about looks: it affects cleaning, standing-desk movement, laptop docking, and whether a setup stays usable after the first week.",
    category: "desks",
    intent: "Build a cleaner one-cable or low-cable workstation without buying a pile of accessories that fight each other.",
    intro: "Cable management fails when it starts with clips instead of a plan. Count the devices, decide where power lives, and separate moving standing-desk cables from fixed monitor or dock cables. The goal is not a perfect photo; it is a setup that still looks sane after a normal workweek.",
    decisionGuide: [
      { label: "Laptop-first workflow", detail: "A dock can reduce daily friction if you connect monitor, power, keyboard, and storage often." },
      { label: "Standing desk", detail: "Leave safe cable slack for the full height range before tightening anything down." },
      { label: "Small desk", detail: "Monitor arms and under-desk routing often matter more than decorative cable sleeves." },
      { label: "Simple setup", detail: "If you only have a charger and one monitor, skip the expensive dock and use clips or a tray." },
    ],
    methodology: ["Start with the main cable path from wall power to desk devices", "Separate standing-desk slack from fixed monitor and dock cables", "Choose docks and trays only after counting real devices"],
    productSlugs: ["anker-675-usb-c-docking-station", "huanuo-titanlift-heavy-duty-monitor-arm", "flexispot-e7-mini-standing-desk"],
    faqs: [
      { question: "What cable accessory should I buy first?", answer: "Start with a power strip or surge protector location, then solve the route to your laptop, monitor, and dock." },
      { question: "Do standing desks need special cable management?", answer: "They need extra slack and a path that moves with the desktop. A neat fixed cable path can still fail when the desk rises." },
      { question: "Is a docking station worth it?", answer: "For laptop-first workers who connect power, monitor, keyboard, and audio every day, a dock can reduce friction and visual clutter." },
    ],
  },
  {
    site: "baby",
    slug: "best-baby-monitors-for-apartments",
    title: "Best Baby Monitors for Apartments",
    dek: "Small spaces still need clear night video, manageable alerts, and a connection style that fits your comfort level.",
    category: "sleep",
    intent: "Choose a monitor that gives useful reassurance without unnecessary app noise.",
    intro: "Apartment baby monitors do not need the biggest feature list. They need clear night visibility, a connection method you trust, and controls that are easy when you are tired. Local parent-unit monitors and smart Wi-Fi monitors solve different problems, so start with your comfort level before comparing specs.",
    decisionGuide: [
      { label: "Want less phone dependence", detail: "Choose a dedicated parent-unit monitor for overnight use." },
      { label: "Want remote app access", detail: "A smart Wi-Fi monitor makes more sense if caregivers check in away from home." },
      { label: "Shared walls", detail: "Prioritize clear alerts and volume control rather than overly sensitive notifications." },
      { label: "Privacy concern", detail: "Compare local monitoring, account requirements, and storage settings before buying." },
    ],
    methodology: ["Compare local versus Wi-Fi connection trade-offs", "Check night video and alert clarity", "Review mounting, privacy, and subscription details"],
    productSlugs: ["infant-optics-dxr-8-pro", "nanit-pro-smart-baby-monitor"],
    faqs: [
      { question: "Are Wi-Fi monitors better?", answer: "Wi-Fi models are convenient outside the home, but local monitors can be simpler overnight." },
      { question: "Should I buy breathing analytics?", answer: "Treat analytics as optional reassurance, not a replacement for safe sleep guidance or medical advice." },
      { question: "Do apartments need long-range monitors?", answer: "Usually less than larger houses, but walls, interference, and where you sleep still matter." },
    ],
  },
  {
    site: "baby",
    slug: "best-travel-strollers",
    title: "Best Travel Strollers for Everyday Errands and Flights",
    dek: "The best travel stroller is easy to fold, light enough to carry, and still comfortable enough for real naps.",
    category: "travel",
    intent: "Pick a stroller that solves storage and travel friction without giving up daily usability.",
    intro: "Travel strollers are not just airport gear. They often become the stroller kept in the car, hallway, or grandparent's house. Fold size matters, but so do recline, wheel feel, basket access, and whether the stroller is pleasant enough for ordinary errands.",
    decisionGuide: [
      { label: "Small car or apartment", detail: "Prioritize folded dimensions and a carry-friendly frame." },
      { label: "Budget second stroller", detail: "A simpler lightweight stroller may be enough for errands and backup use." },
      { label: "Frequent flights", detail: "Check airline rules and folded size before assuming cabin-bin fit." },
      { label: "Daily rough sidewalks", detail: "A full-size stroller may be less frustrating than an ultra-light travel model." },
    ],
    methodology: ["Compare folded size against real storage needs", "Check age and weight limits", "Separate travel convenience from daily comfort"],
    productSlugs: ["baby-jogger-city-tour-2-stroller", "summer-3dlite-convenience-stroller"],
    faqs: [
      { question: "Do travel strollers fit airplane bins?", answer: "Some do, but airline rules vary. Check folded dimensions against the carrier before travel." },
      { question: "Can a travel stroller replace a full-size stroller?", answer: "It can for urban families, but storage basket size and rough-surface comfort are common trade-offs." },
      { question: "Should I buy the lightest stroller?", answer: "Not automatically. The lightest option can give up recline, shade, basket space, or wheel comfort." },
    ],
  },
  {
    site: "baby",
    slug: "best-bottle-sterilizers-and-dryers",
    title: "Best Bottle Sterilizers and Dryers for Daily Feeding Routines",
    dek: "The right sterilizer should match bottle count, pump parts, drying expectations, counter space, and how tired the routine feels.",
    category: "feeding",
    intent: "Make bottle cleanup easier without buying a countertop appliance that creates more work.",
    intro: "Bottle sterilizers are most useful when they reduce daily friction. A basic sterilizer can be enough for occasional use, while a sterilizer-dryer combo helps when bottles and pump parts pile up every day. Capacity and drying expectations matter before brand preference.",
    decisionGuide: [
      { label: "Several bottles per day", detail: "Choose enough capacity for bottles plus nipples, caps, and pump parts." },
      { label: "Drying is the pain point", detail: "A sterilizer-dryer combo may reduce clutter and waiting time." },
      { label: "Tiny kitchen", detail: "Microwave bags or a smaller unit may make more sense than a large appliance." },
      { label: "Registry upgrade", detail: "Convenience matters most if the unit will be used daily." },
    ],
    methodology: ["Compare bottle and pump-part capacity", "Check drying function versus sterilizing-only models", "Measure counter footprint before buying"],
    productSlugs: ["philips-avent-bottle-sterilizer", "baby-brezza-sterilizer-dryer-advanced"],
    faqs: [
      { question: "Do all parents need a bottle sterilizer?", answer: "No. Needs vary by feeding routine, medical guidance, and how many bottles or pump parts are used each day." },
      { question: "Is a dryer worth it?", answer: "It can be useful when drying space is limited or parts need to be ready faster." },
      { question: "Can I use microwave sterilizer bags instead?", answer: "Yes for many occasional routines, but bags can be less convenient for high-volume daily use." },
    ],
  },
  {
    site: "baby",
    slug: "best-baby-carriers-and-sleep-routine-upgrades",
    title: "Best Baby Carrier and Sleep Routine Upgrades",
    dek: "Some baby gear earns its space by making repeated daily moments easier: carrying, soothing, bedtime cues, and short errands.",
    category: "travel",
    intent: "Choose daily-use baby gear that supports routines without promising unrealistic fixes.",
    intro: "Carrier and sleep-routine products are easy to oversell. A carrier should fit the baby and caregiver safely; a sound machine should support a consistent routine, not replace safe sleep basics. Look for products that reduce real daily friction.",
    decisionGuide: [
      { label: "Hands-free errands", detail: "A structured carrier can help when stroller use is awkward." },
      { label: "Warm weather", detail: "Carrier airflow and caregiver fit matter before color." },
      { label: "Bedtime cues", detail: "A sound machine and dim light can help create repeatable signals." },
      { label: "Minimal setup", detail: "Skip app-heavy features if simple controls are enough." },
    ],
    methodology: ["Check age and weight guidance first", "Compare caregiver fit and learning curve", "Keep sleep products aligned with safe sleep guidance"],
    productSlugs: ["ergobaby-omni-breeze-carrier", "hatch-rest-sound-machine"],
    faqs: [
      { question: "Can a carrier replace a stroller?", answer: "For short errands and travel moments, sometimes. For long walks or hot days, a stroller can still be easier." },
      { question: "Are sound machines safe?", answer: "Use moderate volume and sensible placement. Follow pediatric guidance and avoid placing devices too close to the baby." },
      { question: "What matters most in a carrier?", answer: "Safe positioning, baby weight guidance, caregiver comfort, and whether it is easy enough to adjust correctly." },
    ],
  },
];

export const guides: Guide[] = [
  {
    site: "pet",
    slug: "automatic-feeder-buying-guide",
    title: "How to Choose an Automatic Pet Feeder",
    dek: "A practical checklist for portion control, power backup, cleaning, and food compatibility.",
    category: "feeding",
    relatedRoundups: ["best-automatic-cat-feeders"],
    sections: [
      { heading: "Start with food type", body: "Dry kibble feeders are the most reliable. If you feed wet food, choose a model with cooling support and shorter schedules." },
      { heading: "Measure portions by weight", body: "Cup markings hide big differences between kibble shapes. We prefer feeders that repeat the same gram weight across several meals." },
      { heading: "Plan for cleaning", body: "A feeder that takes ten minutes to clean every day will eventually stop being used. Removable bowls and clear chutes matter." },
    ],
  },
  {
    site: "homeoffice",
    slug: "small-home-office-setup-guide",
    title: "Small Home Office Setup Guide",
    dek: "How to spend space on the pieces that improve work most: desk depth, chair fit, lighting, monitor placement, and cable paths.",
    category: "desks",
    relatedRoundups: ["best-standing-desks-for-small-spaces", "best-ergonomic-chairs-under-500", "best-monitor-arms-for-home-office"],
    sections: [
      { heading: "Protect depth before width", body: "A slightly narrower desk with enough depth often works better than a wide shallow surface that pushes monitors too close." },
      { heading: "Solve lighting before buying a webcam", body: "Good face lighting can make an ordinary webcam look dramatically better in meetings." },
      { heading: "Use vertical space", body: "Monitor arms, wall shelves, and under-desk cable trays keep a compact setup from becoming cluttered." },
    ],
  },
  {
    site: "homeoffice",
    slug: "video-call-setup-guide",
    title: "Video Call Setup Guide for Home Offices",
    dek: "A practical path to better Zoom, Meet, and Teams calls using light placement, camera height, audio basics, and desk layout.",
    category: "meetings",
    relatedRoundups: ["best-video-call-lighting-for-home-office", "best-monitor-arms-for-home-office"],
    sections: [
      { heading: "Fix face lighting before buying another camera", body: "A dim room makes even a good webcam look noisy. Put a small light near the camera, avoid a bright window behind you, and reduce overhead-only shadows." },
      { heading: "Raise the camera to eye level", body: "A monitor arm, laptop stand, or stacked riser can make framing look more natural while also reducing neck strain during long meeting blocks." },
      { heading: "Keep controls reachable", body: "Lights that require awkward app toggles or rear-panel controls are easy to ignore. Favor simple brightness and color controls you can adjust between calls." },
    ],
  },
  {
    site: "homeoffice",
    slug: "home-office-cable-management-guide",
    title: "Home Office Cable Management Guide",
    dek: "How to plan power, docks, monitor arms, and standing-desk cable slack before buying accessories.",
    category: "desks",
    relatedRoundups: ["best-home-office-cable-management", "best-standing-desks-for-small-spaces"],
    sections: [
      { heading: "Map the cable path first", body: "Start from the wall outlet and trace each device: laptop, monitor, light, speakers, charger, and dock. This prevents buying trays or clips that solve the wrong part of the mess." },
      { heading: "Separate moving and fixed cables", body: "Standing desks need cable slack that moves safely. Keep the desk-lift path separate from monitor and dock cables so the setup works at both sitting and standing height." },
      { heading: "Use a dock only when it removes friction", body: "A USB-C dock is worth considering when you connect several devices every day. If your setup is just a laptop and one charger, simple cable clips may be enough." },
    ],
  },
  {
    site: "baby",
    slug: "baby-registry-essentials-guide",
    title: "Baby Registry Essentials Without the Clutter",
    dek: "A calmer way to separate daily-use gear from nice-to-have extras.",
    category: "sleep",
    relatedRoundups: ["best-baby-monitors-for-apartments", "best-travel-strollers", "best-bottle-sterilizers-and-dryers", "best-baby-carriers-and-sleep-routine-upgrades"],
    sections: [
      { heading: "Buy for the first 90 days first", body: "Prioritize sleep, feeding, diapering, and safe transport before specialized accessories." },
      { heading: "Check cleaning effort", body: "Anything used daily should be easy to wash, dry, and reassemble while tired." },
      { heading: "Keep safety notes visible", body: "For sleep and travel gear, read age, weight, and use-position limits before comparing style or color." },
    ],
  },
];

export const tools: Tool[] = [
  {
    site: "pet",
    slug: "pet-feeding-calculator",
    title: "Pet Feeding Schedule Calculator",
    dek: "Estimate meal size and schedule splits before comparing automatic feeders.",
    category: "feeding",
    kind: "feeding",
    relatedRoundups: ["best-automatic-cat-feeders"],
  },
  {
    site: "homeoffice",
    slug: "desk-height-calculator",
    title: "Desk Height Calculator",
    dek: "Estimate sitting and standing desk height targets from your height.",
    category: "ergonomics",
    kind: "desk",
    relatedRoundups: ["best-standing-desks-for-small-spaces"],
  },
  {
    site: "baby",
    slug: "diaper-usage-calculator",
    title: "Diaper Usage Calculator",
    dek: "Estimate weekly diaper usage by age range before planning subscriptions or registry quantities.",
    category: "feeding",
    kind: "diapers",
    relatedRoundups: ["best-bottle-sterilizers-and-dryers"],
  },
];

export function siteProducts(site: SiteKey) {
  return products.filter((product) => product.site === site).map(applyAmazonOverride);
}

export function siteRoundups(site: SiteKey) {
  return roundups.filter((roundup) => roundup.site === site);
}

export function siteGuides(site: SiteKey) {
  return guides.filter((guide) => guide.site === site);
}

export function siteTools(site: SiteKey) {
  return tools.filter((tool) => tool.site === site);
}

export function findProduct(site: SiteKey, slug: string) {
  const product = products.find((item) => item.site === site && item.slug === slug);
  return product ? applyAmazonOverride(product) : undefined;
}

export function findRoundup(site: SiteKey, slug: string) {
  return roundups.find((roundup) => roundup.site === site && roundup.slug === slug);
}

export function findGuide(site: SiteKey, slug: string) {
  return guides.find((guide) => guide.site === site && guide.slug === slug);
}

export function findTool(site: SiteKey, slug: string) {
  return tools.find((tool) => tool.site === site && tool.slug === slug);
}

export function applyAmazonOverride(product: Product): Product {
  const override = amazonProductOverrides[product.slug];
  return override ? { ...product, ...override } : product;
}
