import type { Guide, Product, Roundup, SiteKey, Tool } from "./types";

export const products: Product[] = [
  {
    site: "pet",
    slug: "portionpro-automatic-feeder",
    name: "PortionPro Automatic Feeder",
    brand: "PortionPro",
    category: "feeding",
    image: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?auto=format&fit=crop&w=1200&q=80",
    summary: "A programmable feeder for cats and small dogs where portion accuracy matters more than app extras.",
    bestFor: "Cats that need consistent meal timing",
    priceBand: "$$",
    rating: 4.6,
    scores: [
      { label: "Portion control", value: 9 },
      { label: "Cleaning", value: 7 },
      { label: "Reliability", value: 8 },
    ],
    pros: ["Consistent portions across dry kibble sizes", "Backup battery keeps schedules running", "Simple local controls for non-app households"],
    cons: ["Not ideal for large kibble", "Bowl angle can scatter food for fast eaters"],
    specs: { Capacity: "5 L", Power: "USB-C with battery backup", "Meal slots": "Up to 6 per day" },
    evidence: ["Timed dry-run schedule over seven days", "Measured three kibble sizes by weight", "Checked bowl cleaning time after wet-nose contact"],
    offers: [{ merchant: "Amazon", url: "https://example.com/pet/portionpro", label: "Check price", priceNote: "Typical mid-range feeder pricing" }],
  },
  {
    site: "pet",
    slug: "clearview-pet-camera",
    name: "ClearView Pet Camera",
    brand: "ClearView",
    category: "home-care",
    image: "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=1200&q=80",
    summary: "A wide-angle pet camera with strong night visibility and sensible alert controls.",
    bestFor: "Owners who want check-ins without constant alerts",
    priceBand: "$$",
    rating: 4.4,
    scores: [
      { label: "Video clarity", value: 8 },
      { label: "Alerts", value: 8 },
      { label: "Privacy controls", value: 7 },
    ],
    pros: ["Good low-light detail", "Adjustable motion zones", "Two-way audio is loud enough for medium rooms"],
    cons: ["Cloud features need a subscription", "No physical lens cover"],
    specs: { Resolution: "2K", "Field of view": "140 degrees", Audio: "Two-way" },
    evidence: ["Compared daytime and night clips", "Tested motion alerts with small and medium pets", "Reviewed privacy settings and indicator lights"],
    offers: [{ merchant: "Chewy", url: "https://example.com/pet/clearview", label: "View deal", priceNote: "Often discounted in bundles" }],
  },
  {
    site: "pet",
    slug: "odorlock-litter-box",
    name: "OdorLock Covered Litter Box",
    brand: "OdorLock",
    category: "home-care",
    image: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=80",
    summary: "A covered litter box that prioritizes odor control and easy scooping over smart features.",
    bestFor: "Apartments where odor control is the top priority",
    priceBand: "$",
    rating: 4.3,
    scores: [
      { label: "Odor control", value: 8 },
      { label: "Scooping access", value: 8 },
      { label: "Tracking control", value: 7 },
    ],
    pros: ["Wide top opening", "Replaceable carbon filter", "High sides reduce scatter"],
    cons: ["Large cats may prefer an uncovered box", "Plastic can retain odor if not washed weekly"],
    specs: { Size: "Large", Entry: "Front", Filter: "Carbon pad" },
    evidence: ["Checked access with clumping litter", "Compared odor after 24 and 48 hours", "Measured footprint for small bathrooms"],
    offers: [{ merchant: "Petco", url: "https://example.com/pet/odorlock", label: "Compare price", priceNote: "Budget-friendly" }],
  },
  {
    site: "homeoffice",
    slug: "risepro-compact-standing-desk",
    name: "RisePro Compact Standing Desk",
    brand: "RisePro",
    category: "desks",
    image: "https://images.unsplash.com/photo-1600494603989-9650cf6ddd3d?auto=format&fit=crop&w=1200&q=80",
    summary: "A compact electric standing desk with stable lift behavior for small rooms.",
    bestFor: "Apartments and bedrooms under 120 square feet",
    priceBand: "$$$",
    rating: 4.7,
    scores: [
      { label: "Stability", value: 9 },
      { label: "Assembly", value: 7 },
      { label: "Cable routing", value: 8 },
    ],
    pros: ["Stable at common standing heights", "Memory presets work reliably", "Narrow top still fits dual monitors with an arm"],
    cons: ["Limited color options", "Cable tray is sold separately"],
    specs: { Width: "48 in", Height: "28-47 in", Capacity: "176 lb" },
    evidence: ["Checked wobble at sitting and standing heights", "Measured usable width with monitor arm", "Timed one-person assembly"],
    offers: [],
  },
  {
    site: "homeoffice",
    slug: "alignmesh-ergonomic-chair",
    name: "AlignMesh Ergonomic Chair",
    brand: "AlignMesh",
    category: "ergonomics",
    image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=1200&q=80",
    summary: "A breathable task chair with enough adjustment range for most home office users.",
    bestFor: "Eight-hour workdays without premium chair pricing",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Adjustability", value: 8 },
      { label: "Seat comfort", value: 8 },
      { label: "Build quality", value: 7 },
    ],
    pros: ["Adjustable lumbar height", "Seat depth fits a wide range of users", "Mesh back stays cool"],
    cons: ["Arm pads feel basic", "Tall users may want a higher backrest"],
    specs: { "Seat height": "17-21 in", "Seat depth": "Adjustable", Warranty: "5 years" },
    evidence: ["Mapped adjustment range to user heights", "Checked pressure points after long sitting blocks", "Compared arm and lumbar travel"],
    offers: [],
  },
  {
    site: "homeoffice",
    slug: "beamkey-video-desk-lamp",
    name: "BeamKey Video Desk Lamp",
    brand: "BeamKey",
    category: "meetings",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=80",
    summary: "A desk lamp that doubles as soft video-call lighting without taking over the desk.",
    bestFor: "Remote workers in dim rooms",
    priceBand: "$",
    rating: 4.2,
    scores: [
      { label: "Light quality", value: 8 },
      { label: "Desk footprint", value: 9 },
      { label: "Controls", value: 7 },
    ],
    pros: ["Warm and neutral color modes", "Slim base", "Good face fill when placed behind a monitor"],
    cons: ["No app controls", "Glossy surfaces show fingerprints"],
    specs: { Brightness: "900 lm", "Color modes": "3", Power: "USB-C" },
    evidence: ["Compared webcam exposure before and after", "Measured base footprint", "Checked glare on glossy monitors"],
    offers: [],
  },
  {
    site: "homeoffice",
    slug: "flexispot-e7-mini-standing-desk",
    name: "FlexiSpot E7 Mini Standing Desk",
    brand: "FlexiSpot",
    category: "desks",
    image: "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?auto=format&fit=crop&w=1200&q=80",
    summary: "A compact electric standing desk for bedrooms, rentals, and small apartment work corners.",
    verdict: "The E7 Mini is the desk to start with when the room is the constraint. It is less about building a huge command center and more about getting sit-stand movement into a bedroom corner without making the room feel smaller.",
    whyItMatters: "Small desks fail when the monitor stand, laptop, dock, and cables all compete for the same shallow surface. A compact standing desk only works if the top still leaves enough depth for typing posture and screen distance.",
    bestFor: "Small rooms where a full 55-inch desk will not fit",
    priceBand: "$$$",
    rating: 4.6,
    scores: [
      { label: "Small-room fit", value: 9 },
      { label: "Lift range", value: 8 },
      { label: "Accessory needs", value: 7 },
    ],
    pros: ["Shorter desktop options fit tight rooms", "Dual-motor style lift range is useful for sitting and standing", "Good fit for laptop plus one-monitor setups"],
    cons: ["Limited surface area for printers or large speakers", "Cable tray and accessories may need separate purchase"],
    specs: { "Desk type": "Electric standing desk", "Use case": "Compact workstation", "Link status": "Amazon affiliate link added" },
    evidence: ["Useful for small-space standing desk comparisons", "Compare against full-size desks before ranking", "Check current Amazon availability and seller details"],
    alternatives: ["Choose a larger UPLIFT-style desk if you run two large monitors and have the wall width.", "Use a monitor arm before buying a wider desk if your main problem is depth, not width."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4eRxmxH", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "uplift-v3-standing-desk",
    name: "UPLIFT V3 Standing Desk",
    brand: "UPLIFT Desk",
    category: "desks",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80",
    summary: "A configurable standing desk option for heavier multi-monitor home offices.",
    bestFor: "Long-term workstations with heavier monitors and accessories",
    priceBand: "$$$$",
    rating: 4.7,
    scores: [
      { label: "Customization", value: 9 },
      { label: "Heavy setup fit", value: 9 },
      { label: "Budget fit", value: 6 },
    ],
    pros: ["Strong fit for multi-monitor and accessory-heavy setups", "Many configuration paths for desktop size and finish", "Useful premium comparison option"],
    cons: ["Higher total cost once accessories are added", "Large packages can be harder to move or assemble alone"],
    specs: { "Desk type": "Electric standing desk", "Use case": "Premium workstation", "Link status": "Needs confirmed purchase link or secondary merchant" },
    evidence: ["Useful for comparing larger, more configurable standing desks", "Use as a premium alternative in desk roundups", "Verify Amazon listing or use direct brand offer if available"],
    offers: [],
  },
  {
    site: "homeoffice",
    slug: "branch-ergonomic-chair",
    name: "Branch Ergonomic Chair",
    brand: "Branch",
    category: "ergonomics",
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=1200&q=80",
    summary: "A mid-range ergonomic chair for home workers who need adjustment without premium chair pricing.",
    verdict: "The Branch Ergonomic Chair is the safer middle path for people leaving a dining chair behind. It has enough adjustment to solve common home-office pain points without jumping into premium-chair pricing.",
    whyItMatters: "Chair fit is personal, but most home workers need the same basics first: seat height that lets feet rest flat, arms that do not force shoulders upward, and back support that stays useful after lunch.",
    bestFor: "Remote workers upgrading from a dining chair",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Adjustment range", value: 8 },
      { label: "Daily comfort", value: 8 },
      { label: "Price fit", value: 8 },
    ],
    pros: ["Useful adjustment set for a broad range of users", "Cleaner design than many budget task chairs", "Strong fit for under-$500 chair shoppers"],
    cons: ["Not as deeply adjustable as premium Steelcase or Herman Miller models", "Fit still depends heavily on user height and seat preference"],
    specs: { "Chair type": "Ergonomic task chair", "Use case": "All-day home office", "Link status": "Amazon affiliate link added" },
    evidence: ["Useful for comparing ergonomic chairs under $500", "Compare seat depth, lumbar adjustment, and return policy", "Check current Amazon listing before linking"],
    alternatives: ["Compare HON Ignition 2.0 if you prefer a more traditional office-chair feel.", "Look at used Steelcase or Herman Miller options if return policy and local condition are easy to verify."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4eWkGpe", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "hon-ignition-2-0-chair",
    name: "HON Ignition 2.0 Ergonomic Chair",
    brand: "HON",
    category: "ergonomics",
    image: "https://images.unsplash.com/photo-1611464908623-07f19927264e?auto=format&fit=crop&w=1200&q=80",
    summary: "A practical ergonomic chair for buyers who want office-grade adjustability without luxury pricing.",
    verdict: "HON Ignition 2.0 is a practical pick when adjustability matters more than a designer look. It is best treated as an office-grade workhorse, not a lounge chair.",
    whyItMatters: "A chair can look ergonomic and still miss the basics. The buying question is whether the exact configuration gives you the arm, lumbar, and seat controls your body actually needs.",
    bestFor: "Value-focused buyers who still want adjustable arms and lumbar support",
    priceBand: "$$",
    rating: 4.4,
    scores: [
      { label: "Adjustability", value: 8 },
      { label: "Durability signal", value: 8 },
      { label: "Design polish", value: 6 },
    ],
    pros: ["Often easy to find through office suppliers and Amazon", "Good practical alternative to cheap gaming chairs", "Useful for comparison against Branch and Steelcase entry models"],
    cons: ["Plain office look", "Configuration names and listings can be confusing"],
    specs: { "Chair type": "Task chair", "Use case": "Budget ergonomic upgrade", "Link status": "Needs confirmed purchase link or secondary merchant" },
    evidence: ["Useful for budget ergonomic chair comparisons", "Verify the exact configuration before linking", "Compare arm, lumbar, and seat-depth options"],
    alternatives: ["Choose Branch if you want a cleaner home-office look.", "Skip both and shop premium used chairs if you need deeper back customization."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4w3ELzP", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "ergotron-lx-monitor-arm",
    name: "Ergotron LX Monitor Arm",
    brand: "Ergotron",
    category: "ergonomics",
    image: "https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=1200&q=80",
    summary: "A premium monitor arm for freeing desk depth and making small workstations more ergonomic.",
    verdict: "The Ergotron LX is the monitor-arm pick for people who adjust their display often and do not want the arm to become the weak point of the setup.",
    whyItMatters: "A monitor arm is not just a tidiness accessory. It changes viewing distance, desk depth, neck angle, and how easy it is to clean or reconfigure a small desk.",
    bestFor: "Single-monitor setups where stability and smooth adjustment matter",
    priceBand: "$$",
    rating: 4.7,
    scores: [
      { label: "Stability", value: 9 },
      { label: "Adjustment", value: 9 },
      { label: "Value", value: 7 },
    ],
    pros: ["Strong fit for ergonomic monitor positioning", "Helps recover desk depth on compact desks", "Useful premium option for monitor-arm buyers"],
    cons: ["Costs more than basic arms", "Needs VESA compatibility and a suitable desk edge"],
    specs: { "Arm type": "Single monitor arm", "Use case": "Desk depth and posture", "Link status": "Amazon affiliate link added" },
    evidence: ["Useful for monitor-arm and small-desk comparisons", "Check monitor weight and VESA pattern before recommending", "Compare with budget Amazon Basics arm"],
    alternatives: ["Choose Amazon Basics if price matters more than premium movement.", "Use the stock stand if your monitor is already at eye height and desk depth is not a problem."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/43O98hI", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "amazon-basics-monitor-arm",
    name: "Amazon Basics Monitor Arm",
    brand: "Amazon Basics",
    category: "ergonomics",
    image: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=1200&q=80",
    summary: "A budget monitor arm for home offices that need better screen height without a premium accessory spend.",
    verdict: "Amazon Basics is the budget monitor-arm option to consider when the goal is simple height and depth improvement, not a premium adjustment feel.",
    whyItMatters: "The cheapest way to make a small desk feel bigger is often removing the bulky stock monitor stand. Just check monitor weight, VESA support, and clamp space before buying.",
    bestFor: "Budget buyers with one standard-size monitor",
    priceBand: "$",
    rating: 4.2,
    scores: [
      { label: "Budget fit", value: 9 },
      { label: "Adjustment", value: 7 },
      { label: "Finish", value: 6 },
    ],
    pros: ["Good low-cost comparison option", "Can make a small desk feel deeper", "Easy Amazon search and purchase path"],
    cons: ["Less polished than premium arms", "Weight and clamp limits need careful checking"],
    specs: { "Arm type": "Single monitor arm", "Use case": "Budget setup", "Link status": "Amazon affiliate link added" },
    evidence: ["Useful for budget monitor-arm comparisons", "Verify current listing compatibility", "Compare against Ergotron LX for premium alternative"],
    alternatives: ["Choose Ergotron LX for smoother frequent adjustment.", "Avoid a monitor arm if your desk edge is too thin, too thick, or blocked by a rear panel."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/3Sjls73", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "logitech-litra-glow",
    name: "Logitech Litra Glow",
    brand: "Logitech",
    category: "meetings",
    image: "https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?auto=format&fit=crop&w=1200&q=80",
    summary: "A compact video-call light for improving face lighting without adding a large studio panel.",
    verdict: "Logitech Litra Glow is the simple meeting-light pick when you want better face exposure without building a creator studio around your desk.",
    whyItMatters: "Most bad video calls are lighting problems before they are webcam problems. A compact front light can make a normal laptop or webcam feed look cleaner and less shadowy.",
    bestFor: "Laptop and monitor-based video calls in dim rooms",
    priceBand: "$",
    rating: 4.4,
    scores: [
      { label: "Video-call fit", value: 9 },
      { label: "Desk footprint", value: 9 },
      { label: "Lighting control", value: 8 },
    ],
    pros: ["Small enough for crowded desks", "Strong fit for remote meeting searches", "Brand is easy for buyers to recognize"],
    cons: ["Not a full room light", "Mounting position depends on monitor thickness and setup"],
    specs: { "Light type": "Compact video light", "Use case": "Meetings", "Link status": "Amazon affiliate link added" },
    evidence: ["Useful for video-call lighting comparisons", "Compare with desk lamps and larger key lights", "Check current Amazon availability"],
    alternatives: ["Choose BenQ ScreenBar Halo if desk illumination matters more than face lighting.", "Use a regular lamp if it can sit in front of you without glare."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4eUoqaK", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "benq-screenbar-halo",
    name: "BenQ ScreenBar Halo",
    brand: "BenQ",
    category: "meetings",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80",
    summary: "A monitor light bar for reducing desk clutter while improving keyboard and desk illumination.",
    verdict: "The ScreenBar Halo is a desk-lighting upgrade for people who want the work surface lit but do not want another lamp base eating desk space.",
    whyItMatters: "In compact offices, lighting and clutter fight each other. A monitor light bar can brighten the keyboard and desk area while leaving room for notebooks, docks, and input devices.",
    bestFor: "Desk lighting without taking up surface space",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Desk footprint", value: 10 },
      { label: "Lighting quality", value: 8 },
      { label: "Budget fit", value: 6 },
    ],
    pros: ["Leaves the desktop clear", "Pairs naturally with monitor-arm setups", "Good premium lighting option"],
    cons: ["More expensive than basic lamps", "May not fit every monitor shape cleanly"],
    specs: { "Light type": "Monitor light bar", "Use case": "Desk illumination", "Link status": "Needs confirmed purchase link or secondary merchant" },
    evidence: ["Useful for desk-lighting and monitor-light comparisons", "Check monitor compatibility before linking", "Compare with Logitech Litra Glow for camera-focused lighting"],
    alternatives: ["Choose Logitech Litra Glow if your main issue is how your face looks on calls.", "Choose a standard desk lamp if you need room lighting, not just desktop lighting."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4gw54dg", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "homeoffice",
    slug: "anker-675-usb-c-docking-station",
    name: "Anker 675 USB-C Docking Station",
    brand: "Anker",
    category: "desks",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80",
    summary: "A docking station for laptop users who want a cleaner desk, charging, and quick monitor/peripheral connections.",
    verdict: "The Anker 675 is best for laptop-first workers who want the desk to behave like a docking station instead of a nest of loose cables.",
    whyItMatters: "Cable management is easiest when the connection routine is simple. If one cable can handle display, charging, and peripherals, the desk is more likely to stay clean after real workdays.",
    bestFor: "Laptop-first workers who dock and undock daily",
    priceBand: "$$$",
    rating: 4.3,
    scores: [
      { label: "Cable cleanup", value: 9 },
      { label: "Laptop workflow", value: 8 },
      { label: "Budget fit", value: 6 },
    ],
    pros: ["Natural fit for cable-managed laptop desks", "Useful for one-cable laptop desk setups", "Pairs well with standing desks and monitor arms"],
    cons: ["Port needs vary by laptop", "Higher cost than simple USB hubs"],
    specs: { "Device type": "USB-C docking station", "Use case": "Cable management", "Link status": "Needs confirmed purchase link or secondary merchant" },
    evidence: ["Useful for home-office cable-management comparisons", "Verify ports against target laptops", "Use as optional upgrade rather than universal recommendation"],
    alternatives: ["Use a cheaper USB-C hub if you only connect one monitor and a keyboard.", "Skip a dock if your laptop rarely leaves the desk."],
    offers: [{ merchant: "Amazon US", url: "https://amzn.to/4xZcT1J", label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }],
  },
  {
    site: "baby",
    slug: "quietnest-baby-monitor",
    name: "QuietNest Baby Monitor",
    brand: "QuietNest",
    category: "sleep",
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1200&q=80",
    summary: "A dedicated baby monitor with clear night video and a parent unit that avoids phone dependency.",
    bestFor: "Parents who want a separate screen overnight",
    priceBand: "$$$",
    rating: 4.6,
    scores: [
      { label: "Night video", value: 9 },
      { label: "Range", value: 8 },
      { label: "Ease of use", value: 8 },
    ],
    pros: ["Strong night image", "Physical parent unit", "Simple alerts without an app account"],
    cons: ["No breathing analytics", "Screen battery needs daily charging"],
    specs: { Screen: "5 in", Range: "Up to 900 ft", Connection: "Local wireless" },
    evidence: ["Checked image clarity in a dark nursery", "Walk-tested signal through interior walls", "Reviewed alert volume and menu clarity"],
    offers: [{ merchant: "Target", url: "https://example.com/baby/quietnest", label: "Check price", priceNote: "Premium non-Wi-Fi monitor" }],
  },
  {
    site: "baby",
    slug: "cityfold-travel-stroller",
    name: "CityFold Travel Stroller",
    brand: "CityFold",
    category: "travel",
    image: "https://images.unsplash.com/photo-1595366286556-4d852c2d9382?auto=format&fit=crop&w=1200&q=80",
    summary: "A lightweight stroller that folds small enough for frequent errands and some airline cabins.",
    bestFor: "Travel and compact storage",
    priceBand: "$$$",
    rating: 4.4,
    scores: [
      { label: "Fold size", value: 9 },
      { label: "Maneuvering", value: 8 },
      { label: "Storage", value: 6 },
    ],
    pros: ["Fast one-hand fold", "Fits tight trunks", "Smooth steering on indoor floors"],
    cons: ["Small basket", "Wheels are less happy on gravel"],
    specs: { Weight: "13 lb", Fold: "One-hand", Recline: "Near-flat" },
    evidence: ["Measured folded footprint", "Tested curb and aisle turns", "Checked basket access with a diaper bag"],
    offers: [{ merchant: "Amazon", url: "https://example.com/baby/cityfold", label: "View offer", priceNote: "Commonly discounted" }],
  },
  {
    site: "baby",
    slug: "steamclear-bottle-sterilizer",
    name: "SteamClear Bottle Sterilizer",
    brand: "SteamClear",
    category: "feeding",
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&w=1200&q=80",
    summary: "A countertop sterilizer with enough capacity for bottle-heavy days.",
    bestFor: "Families washing several bottles per day",
    priceBand: "$$",
    rating: 4.3,
    scores: [
      { label: "Capacity", value: 8 },
      { label: "Drying", value: 7 },
      { label: "Counter footprint", value: 7 },
    ],
    pros: ["Holds bottles plus pump parts", "Simple cycle controls", "Removable tray is easy to rinse"],
    cons: ["Drying cycle is not silent", "Takes more counter space than microwave bags"],
    specs: { Capacity: "6 bottles", Cycle: "10 min sterilize", Drying: "Yes" },
    evidence: ["Loaded common bottle shapes", "Timed wash-to-ready routine", "Checked tray cleanup after mineral spots"],
    offers: [{ merchant: "Walmart", url: "https://example.com/baby/steamclear", label: "Compare price", priceNote: "Mid-range sterilizer" }],
  },
];

export const roundups: Roundup[] = [
  {
    site: "pet",
    slug: "best-automatic-cat-feeders",
    title: "Best Automatic Cat Feeders for Consistent Meals",
    dek: "We compare portion accuracy, cleaning time, backup power, and fit for multi-cat homes.",
    category: "feeding",
    intent: "Choose a feeder that keeps meal timing steady without creating cleaning or jamming problems.",
    methodology: ["Measure portions by weight, not just cup markings", "Check cleaning access around the chute and bowl", "Prioritize backup power for travel days"],
    productSlugs: ["portionpro-automatic-feeder"],
    faqs: [
      { question: "Are automatic feeders safe for wet food?", answer: "Most are designed for dry kibble. Wet-food feeders need cooling packs and shorter holding times." },
      { question: "What matters most for cats on a diet?", answer: "Portion repeatability and a tamper-resistant lid matter more than camera or voice features." },
    ],
  },
  {
    site: "pet",
    slug: "best-pet-cameras-for-apartments",
    title: "Best Pet Cameras for Apartments",
    dek: "Apartment-friendly cameras should balance alerts, low-light view, privacy controls, and quiet operation.",
    category: "home-care",
    intent: "Keep an eye on pets without turning every hallway shadow into a notification.",
    methodology: ["Test day and night visibility", "Compare alert sensitivity", "Review privacy controls and status indicators"],
    productSlugs: ["clearview-pet-camera"],
    faqs: [
      { question: "Do pet cameras need subscriptions?", answer: "Live view usually works without one, but cloud history and smarter alerts often cost extra." },
      { question: "Where should a pet camera go?", answer: "Place it where your pet naturally rests, with a visible status light and no view into private neighbor spaces." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-standing-desks-for-small-spaces",
    title: "Best Standing Desks for Small Spaces",
    dek: "Compact desks need stable lift columns, usable depth, realistic monitor placement, and cable routing that does not eat the work surface.",
    category: "desks",
    intent: "Find a standing desk that fits a bedroom, rental, or apartment corner without feeling like a temporary folding table.",
    intro: "Small-space standing desks are easy to overbuy. A desk can have a great motor and still be wrong if the top is too shallow, the cable path snags when it rises, or the room no longer works as a bedroom after work. Start with the footprint, then check whether the desk can support your monitor, keyboard, and laptop routine without turning every accessory into a separate project.",
    decisionGuide: [
      { label: "Small bedroom corner", detail: "Prioritize a compact top, quiet lift, and a monitor arm rather than a wide desktop." },
      { label: "Laptop plus one monitor", detail: "A small electric desk can work well if the monitor stand does not consume half the depth." },
      { label: "Two large monitors", detail: "Move up to a wider premium desk or use monitor arms before committing to a tiny frame." },
      { label: "Rental apartment", detail: "Favor easy assembly, fewer wall-mounted accessories, and cable routing that can move with you." },
    ],
    methodology: ["Prioritize desktop depth before width for monitor distance", "Check lift range against sitting and standing elbow height", "Account for monitor arms, laptop docks, and cable trays before buying accessories"],
    productSlugs: ["flexispot-e7-mini-standing-desk"],
    faqs: [
      { question: "Is 48 inches wide enough for a home office desk?", answer: "Yes for a laptop plus one or two monitors if you use a monitor arm and keep accessories narrow." },
      { question: "What height range should I look for?", answer: "Choose a desk that supports your seated elbow height and standing elbow height without maxing out the motor." },
      { question: "What should I skip in a small standing desk setup?", answer: "Skip oversized speakers, deep monitor stands, and decorative desk shelves until the core keyboard, mouse, monitor, and cable path are solved." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-ergonomic-chairs-under-500",
    title: "Best Ergonomic Chairs Under $500",
    dek: "A good sub-$500 chair should have real adjustment range, breathable support, usable seat depth, and a return policy that respects body-fit risk.",
    category: "ergonomics",
    intent: "Avoid cheap chairs that look adjustable but fail during long workdays.",
    intro: "The best chair under $500 is not the one with the longest feature list. It is the one that lets you sit at the right height, keep your shoulders relaxed, and change posture without fighting the controls. Return policy matters because two people with the same height can still need different seat depth and lumbar feel.",
    decisionGuide: [
      { label: "First real office chair", detail: "Choose a balanced task chair with clear controls and a reasonable return window." },
      { label: "Hot room or warm climate", detail: "Mesh or breathable backs usually feel better through long summer workdays." },
      { label: "Plain office look is fine", detail: "HON-style task chairs can be a better value than decorative home-office chairs." },
      { label: "Back support is the priority", detail: "Check lumbar height and seat depth before caring about headrests." },
    ],
    methodology: ["Map seat height and seat depth to user height ranges", "Separate task-chair support from lounge-style recline", "Check arm, lumbar, return-window, and warranty details before ranking"],
    productSlugs: ["branch-ergonomic-chair", "hon-ignition-2-0-chair"],
    faqs: [
      { question: "Is mesh better than cushion?", answer: "Mesh runs cooler and supports airflow, while cushion can feel softer but may compress over time." },
      { question: "What adjustment is most important?", answer: "Seat height, seat depth, and lumbar position usually matter more than decorative headrests." },
      { question: "Should I buy a gaming chair for office work?", answer: "Usually only if the fit is excellent. For typing-heavy work, task-chair adjustment and seat depth matter more than racing styling." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-monitor-arms-for-home-office",
    title: "Best Monitor Arms for Home Office Desks",
    dek: "Monitor arms are one of the fastest ways to recover desk depth, reduce neck strain, and make a compact workstation easier to clean.",
    category: "ergonomics",
    intent: "Choose a monitor arm that matches monitor weight, desk edge, cable path, and adjustment needs.",
    intro: "A monitor arm can make a small desk feel more expensive than it is. The win is not the arm itself; it is the desk depth you get back, the cleaner keyboard area, and the ability to put the display where your neck wants it. The risk is buying an arm before checking monitor weight, VESA support, and clamp clearance.",
    decisionGuide: [
      { label: "Premium single monitor", detail: "Choose a smoother arm if you adjust height or depth throughout the week." },
      { label: "Budget setup", detail: "A basic arm can still free meaningful desk space if the monitor weight is within range." },
      { label: "Thick or unusual desk edge", detail: "Measure clamp clearance before buying. Some desks need a different mount plan." },
      { label: "Dual monitor setup", detail: "Consider two single arms for easier positioning unless you know the exact layout." },
    ],
    methodology: ["Check VESA pattern and monitor weight before brand preference", "Compare clamp clearance against the actual desk edge", "Prioritize smooth height and depth adjustment over decorative cable covers"],
    productSlugs: ["ergotron-lx-monitor-arm", "amazon-basics-monitor-arm"],
    faqs: [
      { question: "Do all monitors work with monitor arms?", answer: "No. You need a compatible VESA mount pattern or a reliable adapter, and the monitor weight must sit within the arm's supported range." },
      { question: "Are monitor arms worth it for small desks?", answer: "Often yes. Removing the stock stand can free several inches of usable depth, which matters more than width in many apartments." },
      { question: "Should I buy single or dual monitor arms?", answer: "Single arms are easier to position and upgrade. Dual arms can work well, but they need more careful weight and desk-edge planning." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-video-call-lighting-for-home-office",
    title: "Best Video Call Lighting for Home Offices",
    dek: "Better lighting can improve webcam quality more than buying a new camera, especially in bedrooms, rentals, and dim multipurpose rooms.",
    category: "meetings",
    intent: "Pick lighting that improves face exposure without creating glare, desk clutter, or a complicated studio setup.",
    intro: "Video-call lighting should make you look clearer without turning your desk into a studio. For most people, the right move is a small controllable light near the camera, not a giant panel. If your face is dark but the background is bright, even an expensive webcam will struggle.",
    decisionGuide: [
      { label: "Mostly Zoom or Meet calls", detail: "A compact front-facing video light is usually the fastest improvement." },
      { label: "Need desk lighting too", detail: "A monitor light bar helps the keyboard and desk more than it helps your face." },
      { label: "Tiny desk", detail: "Avoid large lamp bases and pick a light that mounts to the monitor or sits behind it." },
      { label: "Glare-sensitive monitor", detail: "Choose lights with angle control and test placement before keeping the box." },
    ],
    methodology: ["Match the light to the camera position, not just the desk surface", "Check whether the light causes monitor glare", "Prefer compact controls for frequent meeting days"],
    productSlugs: ["logitech-litra-glow", "benq-screenbar-halo"],
    faqs: [
      { question: "Is a desk lamp enough for video calls?", answer: "Sometimes. A lamp can help if it lights your face from the front or side, but it can also create harsh shadows or monitor glare." },
      { question: "Do I need a key light?", answer: "A small video light is usually enough for home meetings. Larger key lights make sense for creators or presenters who record often." },
      { question: "Where should I place a video light?", answer: "Near the camera and slightly above eye level is a good starting point. Avoid placing the only light behind you." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-home-office-cable-management",
    title: "Best Home Office Cable Management Upgrades",
    dek: "Cable management is not just about looks: it affects cleaning, standing-desk movement, laptop docking, and whether a setup stays usable after the first week.",
    category: "desks",
    intent: "Build a cleaner one-cable or low-cable workstation without buying a pile of accessories that fight each other.",
    intro: "Cable management fails when it starts with clips instead of a plan. Count the devices, decide where power lives, and separate moving standing-desk cables from fixed monitor or dock cables. The goal is not a perfect photo; it is a setup that still looks sane after a normal workweek.",
    decisionGuide: [
      { label: "Laptop-first workflow", detail: "A dock can reduce daily friction if you connect monitor, power, keyboard, and storage often." },
      { label: "Standing desk", detail: "Leave safe cable slack for the full height range before tightening anything down." },
      { label: "Small desk", detail: "Monitor arms and under-desk routing often matter more than decorative cable sleeves." },
      { label: "Simple setup", detail: "If you only have a charger and one monitor, skip the expensive dock and use clips or a tray." },
    ],
    methodology: ["Start with the main cable path from wall power to desk devices", "Separate standing-desk slack from fixed monitor and dock cables", "Choose docks and trays only after counting real devices"],
    productSlugs: ["anker-675-usb-c-docking-station", "ergotron-lx-monitor-arm", "flexispot-e7-mini-standing-desk"],
    faqs: [
      { question: "What cable accessory should I buy first?", answer: "Start with a power strip or surge protector location, then solve the route to your laptop, monitor, and dock." },
      { question: "Do standing desks need special cable management?", answer: "They need extra slack and a path that moves with the desktop. A neat fixed cable path can still fail when the desk rises." },
      { question: "Is a docking station worth it?", answer: "For laptop-first workers who connect power, monitor, keyboard, and audio every day, a dock can reduce friction and visual clutter." },
    ],
  },
  {
    site: "baby",
    slug: "best-baby-monitors-for-apartments",
    title: "Best Baby Monitors for Apartments",
    dek: "Small spaces still need clear night video, manageable alerts, and connection choices that fit your comfort level.",
    category: "sleep",
    intent: "Choose a monitor that gives useful reassurance without unnecessary app noise.",
    methodology: ["Compare night image and alert clarity", "Check local versus Wi-Fi connection trade-offs", "Consider parent-unit battery behavior"],
    productSlugs: ["quietnest-baby-monitor"],
    faqs: [
      { question: "Are Wi-Fi monitors better?", answer: "Wi-Fi models are convenient outside the home, but local monitors can be simpler overnight." },
      { question: "Should I buy breathing analytics?", answer: "Treat analytics as optional reassurance, not a replacement for safe sleep guidance or medical advice." },
    ],
  },
  {
    site: "baby",
    slug: "best-travel-strollers",
    title: "Best Travel Strollers for Everyday Errands and Flights",
    dek: "The best travel stroller is easy to fold, light enough to carry, and still comfortable enough for real naps.",
    category: "travel",
    intent: "Pick a stroller that solves storage and travel friction without giving up daily usability.",
    methodology: ["Measure folded size against storage needs", "Test one-hand fold claims", "Compare wheel behavior on common surfaces"],
    productSlugs: ["cityfold-travel-stroller"],
    faqs: [
      { question: "Do travel strollers fit airplane bins?", answer: "Some do, but airline rules vary. Check folded dimensions against the carrier before travel." },
      { question: "Can a travel stroller replace a full-size stroller?", answer: "It can for urban families, but storage basket size and rough-surface comfort are common trade-offs." },
    ],
  },
];

export const guides: Guide[] = [
  {
    site: "pet",
    slug: "automatic-feeder-buying-guide",
    title: "How to Choose an Automatic Pet Feeder",
    dek: "A practical checklist for portion control, power backup, cleaning, and food compatibility.",
    category: "feeding",
    relatedRoundups: ["best-automatic-cat-feeders"],
    sections: [
      { heading: "Start with food type", body: "Dry kibble feeders are the most reliable. If you feed wet food, choose a model with cooling support and shorter schedules." },
      { heading: "Measure portions by weight", body: "Cup markings hide big differences between kibble shapes. We prefer feeders that repeat the same gram weight across several meals." },
      { heading: "Plan for cleaning", body: "A feeder that takes ten minutes to clean every day will eventually stop being used. Removable bowls and clear chutes matter." },
    ],
  },
  {
    site: "homeoffice",
    slug: "small-home-office-setup-guide",
    title: "Small Home Office Setup Guide",
    dek: "How to spend space on the pieces that improve work most: desk depth, chair fit, lighting, monitor placement, and cable paths.",
    category: "desks",
    relatedRoundups: ["best-standing-desks-for-small-spaces", "best-ergonomic-chairs-under-500", "best-monitor-arms-for-home-office"],
    sections: [
      { heading: "Protect depth before width", body: "A slightly narrower desk with enough depth often works better than a wide shallow surface that pushes monitors too close." },
      { heading: "Solve lighting before buying a webcam", body: "Good face lighting can make an ordinary webcam look dramatically better in meetings." },
      { heading: "Use vertical space", body: "Monitor arms, wall shelves, and under-desk cable trays keep a compact setup from becoming cluttered." },
    ],
  },
  {
    site: "homeoffice",
    slug: "video-call-setup-guide",
    title: "Video Call Setup Guide for Home Offices",
    dek: "A practical path to better Zoom, Meet, and Teams calls using light placement, camera height, audio basics, and desk layout.",
    category: "meetings",
    relatedRoundups: ["best-video-call-lighting-for-home-office", "best-monitor-arms-for-home-office"],
    sections: [
      { heading: "Fix face lighting before buying another camera", body: "A dim room makes even a good webcam look noisy. Put a small light near the camera, avoid a bright window behind you, and reduce overhead-only shadows." },
      { heading: "Raise the camera to eye level", body: "A monitor arm, laptop stand, or stacked riser can make framing look more natural while also reducing neck strain during long meeting blocks." },
      { heading: "Keep controls reachable", body: "Lights that require awkward app toggles or rear-panel controls are easy to ignore. Favor simple brightness and color controls you can adjust between calls." },
    ],
  },
  {
    site: "homeoffice",
    slug: "home-office-cable-management-guide",
    title: "Home Office Cable Management Guide",
    dek: "How to plan power, docks, monitor arms, and standing-desk cable slack before buying accessories.",
    category: "desks",
    relatedRoundups: ["best-home-office-cable-management", "best-standing-desks-for-small-spaces"],
    sections: [
      { heading: "Map the cable path first", body: "Start from the wall outlet and trace each device: laptop, monitor, light, speakers, charger, and dock. This prevents buying trays or clips that solve the wrong part of the mess." },
      { heading: "Separate moving and fixed cables", body: "Standing desks need cable slack that moves safely. Keep the desk-lift path separate from monitor and dock cables so the setup works at both sitting and standing height." },
      { heading: "Use a dock only when it removes friction", body: "A USB-C dock is worth considering when you connect several devices every day. If your setup is just a laptop and one charger, simple cable clips may be enough." },
    ],
  },
  {
    site: "baby",
    slug: "baby-registry-essentials-guide",
    title: "Baby Registry Essentials Without the Clutter",
    dek: "A calmer way to separate daily-use gear from nice-to-have extras.",
    category: "sleep",
    relatedRoundups: ["best-baby-monitors-for-apartments", "best-travel-strollers"],
    sections: [
      { heading: "Buy for the first 90 days first", body: "Prioritize sleep, feeding, diapering, and safe transport before specialized accessories." },
      { heading: "Check cleaning effort", body: "Anything used daily should be easy to wash, dry, and reassemble while tired." },
      { heading: "Keep safety notes visible", body: "For sleep and travel gear, read age, weight, and use-position limits before comparing style or color." },
    ],
  },
];

export const tools: Tool[] = [
  {
    site: "pet",
    slug: "pet-feeding-calculator",
    title: "Pet Feeding Schedule Calculator",
    dek: "Estimate meal size and schedule splits before comparing automatic feeders.",
    category: "feeding",
    kind: "feeding",
    relatedRoundups: ["best-automatic-cat-feeders"],
  },
  {
    site: "homeoffice",
    slug: "desk-height-calculator",
    title: "Desk Height Calculator",
    dek: "Estimate sitting and standing desk height targets from your height.",
    category: "ergonomics",
    kind: "desk",
    relatedRoundups: ["best-standing-desks-for-small-spaces"],
  },
  {
    site: "baby",
    slug: "diaper-usage-calculator",
    title: "Diaper Usage Calculator",
    dek: "Estimate weekly diaper usage by age range before planning subscriptions or registry quantities.",
    category: "feeding",
    kind: "diapers",
    relatedRoundups: ["best-baby-monitors-for-apartments"],
  },
];

export function siteProducts(site: SiteKey) {
  return products.filter((product) => product.site === site);
}

export function siteRoundups(site: SiteKey) {
  return roundups.filter((roundup) => roundup.site === site);
}

export function siteGuides(site: SiteKey) {
  return guides.filter((guide) => guide.site === site);
}

export function siteTools(site: SiteKey) {
  return tools.filter((tool) => tool.site === site);
}

export function findProduct(site: SiteKey, slug: string) {
  return products.find((product) => product.site === site && product.slug === slug);
}

export function findRoundup(site: SiteKey, slug: string) {
  return roundups.find((roundup) => roundup.site === site && roundup.slug === slug);
}

export function findGuide(site: SiteKey, slug: string) {
  return guides.find((guide) => guide.site === site && guide.slug === slug);
}

export function findTool(site: SiteKey, slug: string) {
  return tools.find((tool) => tool.site === site && tool.slug === slug);
}
