import type { Guide } from "./types";

export const expansionGuides: Guide[] = [
  {
    site: "network",
    slug: "mesh-wifi-vs-single-router-guide",
    title: "Mesh Wi-Fi vs Single Router: Which Should You Buy for Your Home?",
    dek: "Choose between one well-placed router and multi-node mesh by checking layout, dead zones, wired ports, and backhaul first.",
    category: "wifi",
    updatedAt: "June 28, 2026",
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes", "best-wifi-7-routers-for-home-networks"],
    sources: [
      {
        name: "Google Home: What is a mesh network?",
        url: "https://support.google.com/googlehome/answer/7182746?hl=en",
        note: "Primary explanation of mesh points, coverage, obstructions, and the difference from a traditional single-router network.",
      },
    ],
    sections: [
      { heading: "Start with the floor plan, not the Wi-Fi generation", body: "A single centrally placed router is often enough for an apartment or compact one-floor home. Mesh earns its extra cost when distance, dense walls, multiple floors, or an inconvenient modem location create repeatable dead zones." },
      { heading: "One strong router is the simpler baseline", body: "A single router has fewer radios, power adapters, app settings, and update points to manage. Before buying mesh, test whether moving the router into the open and closer to the center of the home solves the weak-room problem." },
      { heading: "Mesh solves distance by adding connection points", body: "Mesh places additional points closer to rooms that a single router cannot reach well. Those points still need a strong path back to the main router; placing a node inside the dead zone can simply repeat a weak connection." },
      { heading: "Count wired ports and backhaul options", body: "Some mesh points have Ethernet ports and some do not. Check whether the system supports wired backhaul, whether a switch is needed, and whether the main unit still has enough ports for desktops, TVs, consoles, or a NAS." },
      { heading: "Use a two-step buying rule", body: "Try central router placement first. Move to mesh only when the measured weak areas remain and you can place each node where it receives a good connection rather than where the signal has already failed." },
    ],
  },
  {
    site: "network",
    slug: "ethernet-stuck-at-100-mbps-guide",
    title: "Ethernet Stuck at 100 Mbps? Fix Cable, Port or Adapter",
    dek: "Use the negotiated link speed to isolate a bad cable, 100 Mbps port, wall jack, dock, adapter, or auto-negotiation fault before buying new network gear.",
    category: "wired",
    updatedAt: "July 16, 2026",
    image: "/images/affiliate/network-ethernet-adapter-realistic.webp",
    imageAlt: "Ethernet cables and USB-C network adapters arranged beside a laptop for link-speed troubleshooting",
    comparisonTable: {
      title: "What the measured link speed tells you",
      columns: ["Likely cause", "Next test"],
      rows: [
        { label: "Link is 1.0 Gbps+, speed test is slow", values: ["The local Ethernet link is not capped at 100 Mbps", "Check ISP service, router load, VPN, test server, and another wired device"] },
        { label: "Short control cable reaches 1.0 Gbps", values: ["Original patch cable, wall run, or termination", "Add the original path back one part at a time"] },
        { label: "Direct router link stays at 100 Mbps", values: ["Port rating, adapter, auto-negotiation, or driver", "Verify both model specifications, then test another port and adapter"] },
        { label: "Only the dock or USB adapter drops speed", values: ["The intermediate adapter or its host connection", "Test the adapter on another device and confirm its exact Ethernet rating"] },
        { label: "Only one switch port drops speed", values: ["Port configuration, cable, or failing switch port", "Move the same cable to a confirmed gigabit port and inspect management settings"] },
      ],
    },
    relatedRoundups: ["best-wired-networking-upgrades", "best-2-5g-home-network-upgrades"],
    relatedProducts: ["jadaol-cat6-flat-ethernet-cable", "netgear-gs308e-gigabit-switch", "tp-link-ue302c-2-5g-usb-c-ethernet-adapter"],
    relatedGuides: ["ethernet-cable-category-guide", "home-ethernet-switch-guide", "usb-c-ethernet-adapter-guide"],
    sources: [
      {
        name: "Intel Support: Ethernet Link Speed Capped at 100 Mbps",
        url: "https://www.intel.com/content/www/us/en/support/articles/000058908/ethernet-products/intel-killer-ethernet-products.html",
        note: "Primary troubleshooting reference for cable damage, link speed, and gigabit-capable connections.",
      },
      {
        name: "Intel Support: Troubleshoot Gigabit Ethernet speed issues",
        url: "https://www.intel.com/content/www/us/en/support/articles/000035045/ethernet-products.html",
        note: "Official guidance for checking both link partners, auto-negotiation, cabling, and adapter capability.",
      },
      {
        name: "Microsoft Support: Fix Ethernet connection problems in Windows",
        url: "https://support.microsoft.com/en-us/windows/experience/connectivity-networking/fix-ethernet-connection-problems-in-windows",
        note: "Official Windows path for connection status, cable substitution, drivers, and network troubleshooting.",
      },
    ],
    sections: [
      { heading: "First confirm the link says 100 Mbps", body: "Do not begin with an internet speed test. Open the Ethernet connection details in the operating system, router, or managed switch and record the negotiated link rate. A 100 Mbps link identifies a local wired-path problem; a 1.0 Gbps or faster link with a slow speed test points instead toward the ISP plan, router processing, server, or wider network." },
      { heading: "Use a short known-good cable as the control test", body: "Connect the computer directly to a confirmed gigabit LAN port with a short Cat5e-or-better patch cable. Gigabit copper uses all four twisted pairs, so a damaged plug, failed conductor, poor termination, or pinched run can remain connected while negotiating only 100 Mbps." },
      { heading: "Bypass the chain in a fixed order", body: "Test computer to router first. Then add the USB adapter or dock, switch, wall jack, patch panel, and permanent cable run one component at a time. Recheck link speed after every addition. The first step that drops from 1.0 Gbps to 100 Mbps is the branch to inspect." },
      { heading: "Check the rating of both ports", body: "A gigabit adapter cannot overcome a 10/100 router, switch, dock, television, or wall-module port. Read the exact model number rather than assuming every RJ45 socket is gigabit. On a managed switch, also check whether the port was administratively limited to 100 Mbps." },
      { heading: "Keep speed and duplex on auto-negotiation", body: "Intel's current support guidance identifies auto-negotiation as the normal setting for a gigabit link. Forcing 1.0 Gbps or full duplex on only one side can create a mismatch and can hide the physical fault. Restore automatic settings at both link partners, reconnect, and test again." },
      { heading: "Treat wall jacks as two terminations and one cable", body: "A permanent run can fail at either keystone, patch-panel termination, or inside the cable. Test the two patch leads separately, inspect all eight contacts, and use a cable tester when a short direct cable reaches gigabit but the wall path does not." },
      { heading: "Update drivers only after the physical control test", body: "If a known-good direct cable and confirmed gigabit port still negotiate at 100 Mbps, install the current adapter or laptop-vendor driver, restart, and check power-management settings. Avoid network resets as the first move because they do not repair a missing wire pair or a 100 Mbps port." },
      { heading: "Buy only the component that failed the test", body: "Replace the cable when the known-good cable restores gigabit. Replace or bypass the dock or adapter when the direct computer port works. Buy a gigabit or 2.5GbE switch only when its exact port is the ceiling. A new router is justified only after the router LAN port itself is proven to be the limiting link." },
      { heading: "One-minute decision path", body: "Link reads 1.0 Gbps or faster: investigate internet service or routing. Link reads 100 Mbps and a short control cable fixes it: replace or reterminate the cable path. Control cable does not fix it: verify both port specifications, auto-negotiation, driver, and adapter. Every purchase should correspond to the component that changes the measured link rate." },
    ],
  },
  {
    site: "network",
    slug: "netgear-gs908e-review",
    title: "NETGEAR GS908E Review: Smart Managed Plus or Old Gigabit Switch?",
    dek: "Check GS908E's eight gigabit ports, smart management, cable routing, hardware region, and whether GS308E or 2.5GbE is the better buy.",
    category: "wired",
    updatedAt: "July 12, 2026",
    relatedProducts: ["netgear-gs308e-gigabit-switch", "trendnet-teg-s350-2-5g-switch"],
    relatedRoundups: ["netgear-gs308e-vs-tp-link-tl-sg108", "best-wired-networking-upgrades"],
    sources: [
      {
        name: "NETGEAR GS908E data sheet",
        url: "https://www.netgear.com/media/GS908_GS908E_tcm148-62499.pdf",
        note: "Official port count, gigabit limit, smart-management positioning, cable-management design, and regional ordering information.",
      },
      {
        name: "NETGEAR GS908E user manual",
        url: "https://www.downloads.netgear.com/files/GDC/GS908E/GS908E_UM_EN.pdf",
        note: "Official setup, web-management, port, and hardware guidance.",
      },
    ],
    sections: [
      { heading: "GS908E is an eight-port gigabit switch", body: "The GS908E is a Smart Managed Plus gigabit switch. It can add ports and basic management to a home network, but it does not create a 2.5GbE or 10GbE path for a multi-gig internet plan, NAS, or workstation." },
      { heading: "The E suffix is the buying reason", body: "The managed version is for a defined need such as VLANs, QoS, port status, or troubleshooting visibility. If the job is only to connect a TV, console, desktop, and mesh node, an unmanaged switch may be simpler." },
      { heading: "Cable management helps placement, not speed", body: "The lifestyle enclosure and cable-routing design can keep a visible desk or media shelf tidier. Route cables with enough bend room and label the uplink, but do not treat a cleaner enclosure as evidence of faster throughput." },
      { heading: "GS908E versus GS308E versus 2.5GbE", body: "Compare GS908E with GS308E by management features, hardware version, price, and placement. Choose a 2.5GbE switch instead when the Deco BE63, NAS, desktop, or backhaul path must actually exceed gigabit." },
      { heading: "Check region and current availability", body: "NETGEAR lists separate regional ordering codes and older hardware can remain in search results after the market has moved on. Verify the exact model suffix, authorized seller, warranty, power supply, and return policy before using a low price as the deciding factor." },
    ],
  },
  {
    site: "network",
    slug: "wired-vs-wireless-mesh-backhaul-guide",
    title: "Wired vs Wireless Mesh Backhaul: When Ethernet Between Nodes Is Worth It",
    dek: "Decide whether Ethernet between mesh nodes is worth the installation effort by checking room layout, ports, switch placement, and node signal.",
    category: "wifi",
    updatedAt: "June 28, 2026",
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes", "best-wired-networking-upgrades"],
    sources: [
      {
        name: "Google Home: Hardwire Nest Wifi with Ethernet",
        url: "https://support.google.com/googlehome/answer/7215624?hl=en-GB",
        note: "Primary vendor documentation showing supported wired-backhaul layouts and model limitations.",
      },
    ],
    sections: [
      { heading: "Backhaul is the path between nodes", body: "Client devices connect to a nearby mesh point, but that point still needs a path to the main router. Wireless backhaul uses radio capacity for that trip; wired backhaul moves it onto Ethernet." },
      { heading: "Wireless backhaul wins on installation simplicity", body: "Wireless nodes need only power and sensible placement. It is the practical choice for rentals and finished homes where running Ethernet would be disruptive, provided each node can receive a strong upstream signal." },
      { heading: "Wired backhaul improves consistency", body: "Ethernet can reduce the effect of walls, floors, interference, and node-to-node distance on the backhaul path. It is especially useful for fixed offices, media rooms, and multi-floor homes that already have usable cabling." },
      { heading: "Confirm the exact model supports the topology", body: "Do not assume every point has Ethernet ports or that mixed generations can be hardwired together. Check the manufacturer diagram, port roles, switch placement, and whether setup must be completed wirelessly first." },
      { heading: "Use wiring where it changes a real bottleneck", body: "Wire the node serving the busiest or most difficult room first. If performance is already stable and the household rarely saturates the network, the installation effort may be better spent on router placement or one direct Ethernet run to a key device." },
    ],
  },
  {
    site: "homeoffice",
    slug: "48-vs-55-inch-desk-guide",
    title: "48-Inch vs. 55-Inch Desk for a Home Office",
    dek: "Compare usable depth, monitor layout, room clearance, and moving space before choosing desk width.",
    category: "desks",
    updatedAt: "June 27, 2026",
    relatedRoundups: ["best-standing-desks-for-small-spaces"],
    sources: [
      {
        name: "OSHA Computer Workstations Purchasing Guide",
        url: "https://www.osha.gov/etools/computer-workstations/checklists/purchasing-guide",
        note: "Primary workstation checklist covering desk depth, equipment space, leg clearance, and keyboard height.",
      },
    ],
    sections: [
      { heading: "Depth often matters before width", body: "A 55-inch desk is not automatically more comfortable if both options have the same shallow top. Reserve enough depth for the monitor, keyboard, and a readable viewing distance before using width as the deciding number." },
      { heading: "A 48-inch desk suits focused setups", body: "Forty-eight inches can work for a laptop plus one monitor, or two modest displays on arms, when speakers and storage stay compact. It is easier to fit in bedrooms, rentals, and rooms that still need a clear walking path." },
      { heading: "A 55-inch desk buys separation", body: "The extra width helps when two monitors, a desktop tower, writing space, or frequent paper work must stay available together. It also gives monitor arms and clamps more freedom without crowding the keyboard zone." },
      { heading: "Measure the room in working mode", body: "Include chair pullout, drawers, closet doors, bed clearance, baseboards, outlets, and the route used to carry the desktop into the room. A desk that technically fits against the wall can still make the room frustrating to use." },
      { heading: "Sketch the equipment footprint", body: "Mark monitor bases or arm clamps, keyboard, mouse, laptop, dock, microphone, and speakers on a 48-by-depth rectangle. Move to 55 inches only when the sketch shows a recurring collision rather than a desire to fill empty wall space." },
    ],
  },
  {
    site: "homeoffice",
    slug: "monitor-arm-compatibility-checklist",
    title: "Monitor Arm Compatibility Checklist",
    dek: "Check VESA pattern, monitor weight, desk clamp clearance, and cable movement before ordering an arm.",
    category: "ergonomics",
    updatedAt: "June 28, 2026",
    relatedRoundups: ["best-monitor-arms-for-home-office"],
    sources: [
      {
        name: "VESA Flat Display Mounting Interface",
        url: "https://vesa.org/resources/mounting-standard/",
        note: "Primary standards reference for compliant display mounting interfaces.",
      },
      {
        name: "OSHA Workstation Monitor Guidance",
        url: "https://www.osha.gov/etools/computer-workstations/components/monitors",
        note: "Primary guidance for monitor distance, height, viewing angle, and desk-space considerations.",
      },
    ],
    sections: [
      { heading: "Confirm the VESA mounting pattern", body: "Check the monitor manual or rear mounting holes for the stated VESA pattern. If the display lacks a standard interface, use only a model-specific adapter that preserves access to ports and does not exceed the arm's limits." },
      { heading: "Use the monitor-only weight", body: "Compare the arm rating with the display weight after removing the original stand. Stay inside both the minimum and maximum range because an arm designed for a heavier screen may not hold a light monitor in position." },
      { heading: "Inspect the desk edge from above and below", body: "A clamp needs a flat, strong contact area. Measure desktop thickness and check for aprons, cable trays, beveled edges, drawers, wall gaps, glass panels, or hollow sections that can block or weaken the mount." },
      { heading: "Plan the movement envelope", body: "The arm needs space behind and beside the display when it moves. Check wall clearance, portrait rotation, webcam position, laptop screens, and whether two arms will collide near the center of the desk." },
      { heading: "Leave enough cable slack", body: "Route power, display, and USB cables through the full height and depth range before tightening clips. The arm should move without pulling connectors, lifting a dock, or forcing a sharp bend at the monitor port." },
      { heading: "Using a monitor arm with a walking pad or treadmill desk", body: "A walking desk adds repeated movement that a seated setup does not. Use a rigid desk, a clamp area with flat support above and below, and an arm that keeps the monitor comfortably inside its weight range. Start at a slow walking speed and watch for screen oscillation, clamp movement, or a desktop that flexes. Leave enough power and display-cable slack for both arm adjustment and any sit-stand travel, and stop to reposition the screen instead of adjusting a bouncing arm while walking." },
    ],
  },
  {
    site: "pet",
    slug: "automatic-feeder-cleaning-checklist",
    title: "Automatic Pet Feeder Cleaning Checklist",
    dek: "A repeatable cleaning routine for bowls, chutes, hoppers, seals, and food-contact tools.",
    category: "feeding",
    updatedAt: "July 28, 2026",
    relatedRoundups: ["best-automatic-cat-feeders"],
    sources: [
      {
        name: "FDA: Proper Storage of Pet Food and Treats",
        url: "https://www.fda.gov/animal-veterinary/animal-health-literacy/proper-storage-pet-food-treats",
        note: "Primary food-handling guidance for washing bowls and utensils and keeping dry pet food cool, dry, and secure.",
      },
      {
        name: "PETLIBRO Granary PLAF103 cleaning",
        url: "https://petlibro.com/pages/how-do-i-disassemble-and-clean-the-granary-smart-feeder-af103-plaf103",
        note: "Exact washable-part, powered-base, drying, and reassembly restrictions for Granary PLAF103.",
      },
      {
        name: "PETLIBRO One RFID PLAF301 cleaning",
        url: "https://petlibro.com/pages/how-do-i-disassemble-and-clean-the-one-rfid-pet-feeder-af301-plaf301",
        note: "Exact base, collar-tag, RFID-reader, drying, and reassembly restrictions for One RFID PLAF301.",
      },
    ],
    sections: [
      { heading: "Follow the model manual first", body: "Automatic feeders combine washable food-contact parts with motors and electronics that must stay dry. Identify which bowl, hopper, lid, rotor, and chute pieces are removable or dishwasher-safe before taking the unit apart." },
      { heading: "Clean the bowl and utensils as food-contact items", body: "Wash and dry the feeding bowl and any scoop or measuring tool on a regular schedule. Do not let an automated schedule make leftover crumbs, oils, or moisture invisible." },
      { heading: "Empty old food before wiping the hopper", body: "Transfer usable kibble into a clean, dry container rather than topping up indefinitely. Remove crumbs from corners and seals, dry every washable part completely, and avoid returning food to a damp hopper." },
      { heading: "Inspect the chute and portion mechanism", body: "Look for oily buildup, broken kibble, jams, insects, and wear around the rotor or dispensing path. Use only the brush or cleaning method allowed by the manufacturer so water does not enter the motor housing." },
      { heading: "Test one meal after reassembly", body: "Reconnect power, confirm the clock and schedule, and dispense a test portion while you are present. Check that the bowl is seated, the chute is clear, and backup batteries or notifications still work." },
    ],
  },
  {
    site: "pet",
    slug: "pet-camera-subscription-cost-checklist",
    title: "Pet Camera Subscription Cost Checklist",
    dek: "Separate free live-view features from paid alerts, cloud history, multi-camera fees, and renewal terms.",
    category: "home-care",
    updatedAt: "June 27, 2026",
    relatedRoundups: ["best-pet-cameras-for-apartments"],
    sources: [
      {
        name: "Furbo Help Center: Nanny Plans and Pricing",
        url: "https://help.furbo.com/hc/en-us/articles/17462739016089-Furbo-Nanny-Plans-and-Pricing",
        note: "Primary vendor source for current plan tiers, storage windows, and additional-camera pricing; verify again before purchase because plans change.",
      },
    ],
    sections: [
      { heading: "Write down the free baseline", body: "Confirm whether live view, two-way audio, treat tossing, local storage, and basic motion or sound alerts work without a plan. A camera can be useful without paying monthly if those are the only features you need." },
      { heading: "Identify the feature that triggers payment", body: "Cloud history, longer clips, pet-specific detection, smart summaries, emergency-style alerts, and downloadable recordings are commonly separated into paid tiers. Name the one feature you would actually miss before comparing plan labels." },
      { heading: "Calculate the full household cost", body: "Check monthly, annual, and multi-year billing plus taxes, trial conversion, renewal price, and additional-camera fees. Compare the first-year promotion with the normal renewal total rather than treating the cheapest displayed monthly number as permanent." },
      { heading: "Check cancellation and storage consequences", body: "Find out how to cancel, when access ends, and whether saved cloud clips disappear after downgrade. Export any recordings you need before changing plans and avoid assuming that a hardware return automatically cancels a subscription." },
      { heading: "Recheck pricing at checkout", body: "Subscription features and tiers change more often than camera hardware. Use this checklist to compare the structure, then confirm the current vendor plan page and terms immediately before buying or starting a trial." },
    ],
  },
  {
    site: "baby",
    slug: "bottle-washer-vs-sterilizer-vs-dryer-guide",
    title: "Bottle Washer vs. Sterilizer vs. Dryer",
    dek: "Separate cleaning, sanitizing, and drying so you can choose the appliance that matches the real bottleneck.",
    category: "feeding",
    updatedAt: "July 26, 2026",
    relatedRoundups: ["best-bottle-sterilizers-and-dryers"],
    comparisonTable: {
      title: "Match the appliance to the repeated feeding-cleanup job",
      columns: ["Washer", "Sterilizer or sanitizing cycle", "Dryer"],
      rows: [
        { label: "Primary job", values: ["Remove milk residue using water and detergent", "Add a germ-reduction step after cleaning", "Remove remaining moisture"] },
        { label: "Choose when", values: ["Hand-scrubbing compatible parts is the bottleneck", "Current health and manufacturer guidance calls for sanitizing", "Clean parts stay wet or are needed again quickly"] },
        { label: "Does not prove", values: ["That every pump part is compatible", "That dirty parts have been cleaned", "That finished parts have clean storage"] },
        { label: "Buying check", values: ["Spray path, detergent, filter, cycle, and part fit", "Exact cycle instructions and item compatibility", "Small-part airflow, cycle time, and storage path"] },
      ],
    },
    sources: [
      {
        name: "CDC: Clean, Sanitize, and Store Infant Feeding Items",
        url: "https://www.cdc.gov/hygiene/about/clean-sanitize-store-infant-feeding-items.html",
        note: "Primary public-health guidance distinguishing cleaning, sanitizing, complete air-drying, and storage.",
      },
      {
        name: "CDC: How to Clean and Sanitize Breast Pumps",
        url: "https://www.cdc.gov/hygiene/about/about-breast-pump-hygiene.html",
        note: "Primary guidance for pump-part cleaning and following the pump manufacturer's instructions.",
      },
    ],
    sections: [
      { heading: "Cleaning, sanitizing, and drying are different jobs", body: "A washer removes milk residue with water and detergent. A sterilizer or sanitizing cycle adds an extra germ-reduction step after cleaning, while a dryer removes moisture; a machine name does not guarantee that it performs all three." },
      { heading: "Choose a washer when scrubbing is the bottleneck", body: "An all-in-one washer can help when many bottles, valves, nipples, and compatible pump parts accumulate each day. Confirm detergent requirements, spray coverage, filter maintenance, cycle time, and exact part compatibility." },
      { heading: "Choose a sterilizer when guidance calls for sanitizing", body: "CDC guidance notes that sanitizing needs vary with age and health circumstances and may be unnecessary as a separate step when compatible items use an appropriate dishwasher cycle. Follow current public-health, medical, and manufacturer guidance for your situation." },
      { heading: "Choose a dryer when clean parts stay wet", body: "Drying can be the useful upgrade when counter space is crowded or parts are needed again quickly. Check whether the cycle dries small valves and narrow pieces completely and where finished parts will be stored without recontamination." },
      { heading: "Map one full day before buying", body: "Count every bottle and part, note when each is needed again, and mark which steps currently consume time. Buy the appliance that removes that repeated bottleneck rather than the model with the longest list of overlapping cycle names." },
    ],
  },
  {
    site: "baby",
    slug: "ergobaby-omni-breeze-positions-by-age",
    title: "Ergobaby Omni Breeze Positions by Age: Inward, Outward, Hip & Back",
    dek: "Map every Omni Breeze carry position by size and development, including newborn inward carry, forward-facing readiness, hip carry, back carry, seat width, and setup changes.",
    category: "travel",
    updatedAt: "July 17, 2026",
    image: "/images/affiliate/baby-carrier-realistic.webp",
    imageAlt: "Caregiver wearing a realistic structured mesh baby carrier in a safe inward-facing position",
    relatedProducts: ["ergobaby-omni-breeze-carrier"],
    relatedRoundups: ["best-baby-carriers-by-age-and-position", "best-baby-carriers-and-sleep-routine-upgrades"],
    relatedGuides: ["ergobaby-omni-breeze-forward-facing-age-guide", "ergobaby-omni-breeze-newborn-fit-checklist", "ergobaby-omni-breeze-vs-babybjorn-harmony-by-age"],
    sources: [
      {
        name: "Ergobaby Omni Breeze product guidance",
        url: "https://ergobaby.com/omni-breeze-baby-carrier-all",
        note: "Official overall range, position requirements, seat adjustment, and fit guidance.",
      },
      {
        name: "Ergobaby Omni Breeze instructions",
        url: "https://ergobaby.com/instructions-omni-breeze/",
        note: "Official manuals and position-specific setup videos.",
      },
    ],
    sections: [
      { heading: "Age is only a shorthand", body: "The Omni Breeze positions depend on weight, height, head and neck control, and the ability to sit unassisted. Use the age ranges as planning estimates, then apply the exact product instructions and the baby's current developmental milestones." },
      { heading: "Front inward is the newborn starting position", body: "Ergobaby lists the carrier from 7lb and 20in, with the newborn carried facing inward. Set the seat width for the baby's height, provide the instructed head and neck support, and keep the face visible and close enough to monitor." },
      { heading: "Front outward requires head and neck control", body: "Ergobaby says the baby should have strong head and neck control, clear the top of the panel with the chin, and be over 25in, typically around 5 to 6 months. Turn the baby inward if sleepy, overstimulated, slumped, or unable to maintain the position." },
      { heading: "Hip and back carry come later", body: "The Omni Breeze guidance places hip and back carry after the baby can sit upright unassisted and meets the listed minimum weight, generally around 6 months. Practice over a soft surface with another adult until the transfer and strap sequence are controlled." },
      { heading: "Recheck the setup whenever the position changes", body: "Seat width, head support, button or slider settings, strap tension, and waistband height can change between positions. Follow the relevant official video rather than rotating the baby inside a configuration set for another carry mode." },
    ],
  },
  {
    site: "baby",
    slug: "ergobaby-omni-breeze-newborn-fit-checklist",
    title: "Ergobaby Omni Breeze Newborn Fit Checklist",
    dek: "Check minimum size, seat width, airway visibility, head support, waistband position, and caregiver fit before the first carry.",
    category: "travel",
    updatedAt: "July 1, 2026",
    relatedProducts: ["ergobaby-omni-breeze-carrier"],
    relatedRoundups: ["best-baby-carriers-and-sleep-routine-upgrades"],
    sources: [
      {
        name: "Ergobaby Omni Breeze product page and FAQ",
        url: "https://ergobaby.com/omni-breeze-baby-carrier-all",
        note: "Official newborn minimums, seating guidance, and carrier adjustments.",
      },
      {
        name: "Ergobaby instructions",
        url: "https://ergobaby.com/instructions-omni-breeze/",
        note: "Official setup manual and newborn position videos.",
      },
    ],
    sections: [
      { heading: "Confirm both listed newborn minimums", body: "Ergobaby lists the Omni Breeze from 7lb and 20in. Meeting one number does not replace the other, and babies below the stated limits need a different carrier plan rather than an improvised insert." },
      { heading: "Use front-inward carry", body: "A newborn starts facing the caregiver. Do not use front-outward, hip, or back carry simply because the carrier supports those positions later; each has separate developmental requirements." },
      { heading: "Set the seat before tightening the straps", body: "Use the waistband markings and official instructions to match the seat width to the baby's height. Center the baby, settle the bottom deeply, and check that the thighs are supported without forcing the legs wider than the instructed position." },
      { heading: "Keep the face visible and airway unobstructed", body: "The baby's face should remain visible to the caregiver, with the head supported according to the manual and the chin clear of the chest. Reposition immediately if the baby slumps, becomes difficult to observe, or the panel covers the face." },
      { heading: "Fit each caregiver separately", body: "Waistband height, shoulder straps, chest strap, and lumbar panel settings should be adjusted for the current wearer. A setting that feels secure on one adult may place the baby too low or shift pressure on another." },
      { heading: "Use short practice carries first", body: "Complete the first setup while calm and with another adult nearby. Check the carrier and baby frequently, stop if either person is uncomfortable, and use Ergobaby's manual or consultation support when the fit remains uncertain." },
    ],
  },
  {
    site: "network",
    slug: "deco-be63-ethernet-backhaul-setup",
    title: "Deco BE63 Ethernet Backhaul: 2.5Gbps Switch Setup",
    dek: "Keep Deco BE63 backhaul at 2.5Gbps by checking every port, switch, wall jack, cable, topology, and loop before blaming Wi-Fi 7.",
    category: "wifi",
    updatedAt: "August 8, 2026",
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes", "best-wired-networking-upgrades"],
    sources: [
      {
        name: "TP-Link Ethernet Backhaul FAQ",
        url: "https://www.tp-link.com/us/support/faq/1794/",
        note: "Official setup order, supported topology, switch placement, and loop cautions.",
      },
      {
        name: "Deco BE63 product and installation guide",
        url: "https://www.tp-link.com/us/document/125928/",
        note: "Official port roles, physical layout, setup process, and LED states.",
      },
    ],
    sections: [
      { heading: "Set up every node in the app first", body: "TP-Link instructs users to add the Deco units to the same mesh network before connecting Ethernet between them. Confirm that each satellite works wirelessly and appears in the app before changing the backhaul path." },
      { heading: "Wire from the LAN side of the main Deco", body: "In router mode, the modem or ONT connects to the main Deco's WAN/LAN port. A satellite should then connect to another port on the main Deco or to a switch that is downstream of the main Deco's LAN side." },
      { heading: "A switch can distribute the wired path", body: "A compatible switch can sit between the main Deco and multiple satellite units. Draw the physical path first and avoid connecting the same network segments in a way that creates an Ethernet loop." },
      { heading: "Check the negotiated link at every step", body: "The BE63 has auto-sensing 2.5Gbps WAN/LAN ports, but the path runs only as fast as its slowest switch, wall jack, cable, or adapter. A gigabit switch creates a gigabit backhaul even when both Deco ports support 2.5Gbps." },
      { heading: "Test one wired satellite before wiring all of them", body: "Connect one satellite, confirm its status and client performance, then add the remaining wired nodes. This makes a bad cable, wall termination, or switch port easier to identify." },
    ],
  },
  {
    site: "network",
    slug: "deco-be63-multigig-ports-guide",
    title: "Deco BE63 2.5GbE Ports Explained: WAN, LAN, Switches and Backhaul",
    dek: "Plan the four auto-sensing ports around a multi-gig internet connection, wired backhaul, office devices, and the real bottleneck in the path.",
    category: "wired",
    updatedAt: "July 1, 2026",
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh", "netgear-gs308e-gigabit-switch"],
    relatedRoundups: ["best-wifi-7-routers-for-home-networks", "best-wired-networking-upgrades"],
    sources: [
      {
        name: "TP-Link Deco BE63 specifications",
        url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be63/v1%20%281-pack%29/",
        note: "Official four-port 2.5GbE specification, auto-sensing roles, and backhaul capabilities.",
      },
      {
        name: "Deco BE63 installation guide",
        url: "https://www.tp-link.com/us/document/125928/",
        note: "Official port descriptions and initial connection flow.",
      },
    ],
    sections: [
      { heading: "All four Ethernet ports are 2.5Gbps and auto-sensing", body: "Each BE63 unit has four 2.5Gbps WAN/LAN ports. The system determines the role from the connection, but the main unit still needs one port for the modem or ONT in a normal router-mode installation." },
      { heading: "A multi-gig plan needs a complete multi-gig path", body: "Faster-than-gigabit internet requires a compatible modem or ONT port, suitable cable, BE63 port, and a client with 2.5GbE or sufficiently capable Wi-Fi. One gigabit component caps that branch of the network." },
      { heading: "Reserve ports before choosing a switch", body: "List the WAN connection, Ethernet backhaul, desktop, NAS, TV, and other fixed devices. A gigabit switch is fine for ordinary devices, while a 2.5GbE switch is needed when several wired clients must exceed gigabit speeds." },
      { heading: "Backhaul competes for the same port inventory", body: "A wired satellite uses one Ethernet port at each end of its path. Count that connection before assuming all advertised ports remain available for clients." },
      { heading: "Do not read Wi-Fi headline speed as one-device throughput", body: "BE10000 combines theoretical link rates across bands. Real client speed depends on client radio support, channel width, distance, interference, backhaul, and the wired path serving the mesh." },
    ],
  },
  {
    site: "network",
    slug: "wifi-7-device-compatibility-checklist",
    title: "Wi-Fi 7 Device Compatibility Checklist",
    dek: "Check client radios, 6GHz support, MLO, channel width, security, ports, and backhaul before paying for a Wi-Fi 7 upgrade.",
    category: "wifi",
    updatedAt: "July 1, 2026",
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["best-wifi-7-routers-for-home-networks", "best-mesh-wifi-for-apartments-and-homes"],
    sources: [
      {
        name: "TP-Link Deco BE63 specifications",
        url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be63/v1%20%281-pack%29/",
        note: "Official Wi-Fi generation support, backwards compatibility, 6GHz, MLO, channel, port, and performance qualifications.",
      },
      {
        name: "TP-Link Deco BE63 support center",
        url: "https://www.tp-link.com/us/support/download/deco-be63/",
        note: "Official hardware-version documentation, manuals, firmware, and Wi-Fi 7 feature guidance.",
      },
    ],
    sections: [
      { heading: "Older devices can connect without becoming Wi-Fi 7 devices", body: "A backwards-compatible Wi-Fi 7 router can serve Wi-Fi 6, Wi-Fi 5, and older clients on supported bands. Those clients retain their own radio, stream, channel-width, and security limits." },
      { heading: "Check the client specification, not only the phone or laptop year", body: "Look up the exact wireless adapter or device model for 802.11be, 6GHz, supported channel width, stream count, and MLO. Two products sold in the same year can have very different radios." },
      { heading: "MLO requires support at both ends", body: "Multi-Link Operation is a Wi-Fi 7 feature, but the router and client must both support compatible modes and current software. A Wi-Fi 6E client using 6GHz does not automatically gain MLO." },
      { heading: "6GHz range and eligibility differ from 2.4GHz", body: "The 6GHz band offers additional clean spectrum but generally has a shorter usable range through obstacles. Regulatory region, supported security, device capability, and placement all affect whether a client can use it." },
      { heading: "Verify the wired side of the upgrade", body: "A gigabit modem port, switch, USB adapter, or desktop NIC can limit a Wi-Fi 7 system. Map WAN, backhaul, and client ports before paying for wireless capacity the rest of the network cannot deliver." },
      { heading: "Upgrade for a measured reason", body: "Wi-Fi 7 is easier to justify for multi-gig internet, congested homes, new 6GHz clients, or a planned wired backhaul. Better router placement or one Ethernet run may help more when the current problem is a single weak room." },
    ],
  },
  {
    site: "homeoffice",
    slug: "monitor-arm-for-walking-desk-guide",
    title: "Best Monitor Arm Setup for a Walking Desk",
    dek: "Choose and position a monitor arm for viewing distance, standing height, desktop stiffness, clamp fit, cable slack, and controlled movement.",
    category: "ergonomics",
    updatedAt: "July 1, 2026",
    relatedProducts: ["huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    relatedRoundups: ["best-monitor-arms-for-home-office", "best-standing-desks-for-small-spaces"],
    sources: [
      {
        name: "OSHA workstation monitor guidance",
        url: "https://www.osha.gov/etools/computer-workstations/components/monitors",
        note: "Primary guidance for monitor height, distance, viewing angle, and placement.",
      },
      {
        name: "OSHA workstation position guidance",
        url: "https://www.osha.gov/etools/computer-workstations/positions",
        note: "Primary guidance for neutral standing and seated posture and changing position.",
      },
    ],
    sections: [
      { heading: "Walking changes the stability requirement", body: "Footfalls can move the floor, desk frame, desktop, arm, and screen. A high-capacity arm cannot compensate for a flexible desk, loose frame, or monitor mounted far beyond the desk's center of support." },
      { heading: "Match the arm to monitor-only weight and VESA pattern", body: "Use the display weight without its original stand and confirm the VESA interface. Keep the monitor comfortably inside the arm's supported range rather than selecting only by advertised screen size." },
      { heading: "Inspect the clamp area above and below", body: "Choose a flat, solid section of desktop without an apron, cable tray, control box, bevel, or hollow core at the mounting point. Check the desk maker's mounting guidance before clamping to glass or thin composite tops." },
      { heading: "Set the screen for standing before walking", body: "OSHA recommends placing the monitor directly ahead, with its top at or slightly below eye level and a generally comfortable 20–40in viewing distance. Establish a neutral standing setup while stationary, then begin at a slow pace." },
      { heading: "Use a restrained arm position", body: "Keeping the display closer to the arm post and avoiding maximum extension usually reduces leverage and visible oscillation. Stop walking before changing arm height or reach." },
      { heading: "Leave safe cable slack through every motion", body: "Test monitor movement and the desk's full sit-stand range with power, display, and USB cables attached. No connector should carry the load or become a trip or pinch point around the walking surface." },
    ],
  },
  {
    site: "homeoffice",
    slug: "reduce-monitor-wobble-walking-desk",
    title: "How to Reduce Monitor Wobble on a Walking Desk",
    dek: "Trace movement from the floor through the desk, clamp, arm, and screen before replacing a monitor arm that may not be the real cause.",
    category: "ergonomics",
    updatedAt: "July 1, 2026",
    relatedProducts: ["huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    relatedRoundups: ["best-monitor-arms-for-home-office", "best-standing-desks-for-small-spaces"],
    sources: [
      {
        name: "OSHA workstation monitor guidance",
        url: "https://www.osha.gov/etools/computer-workstations/components/monitors",
        note: "Primary guidance for readable distance, height, placement, clarity, and adjustable supports.",
      },
      {
        name: "OSHA workstation desk guidance",
        url: "https://www.osha.gov/etools/computer-workstations/components/desks",
        note: "Primary guidance for desk space, equipment placement, and neutral workstation arrangement.",
      },
    ],
    sections: [
      { heading: "Find the first moving component", body: "Walk at the normal pace while another person observes the treadmill, floor, desk feet, lifting columns, desktop, clamp, arm joints, and screen. Tightening the arm will not fix movement that begins in the floor or desk frame." },
      { heading: "Level and tighten the desk first", body: "Confirm that every foot contacts the floor, leveling pads are adjusted, frame fasteners are torqued according to the desk manual, and the desktop is secured. Test at seated and standing heights because column extension can change stability." },
      { heading: "Shorten the arm's lever", body: "Move the arm post closer to the monitor, reduce forward extension, and center the display over a stronger section of the desktop. A screen held far forward amplifies small movement at the clamp." },
      { heading: "Tune tension without overtightening", body: "Adjust lift and tilt tension using the arm instructions so the monitor holds position through its supported range. Do not force adjustment screws beyond their limits or treat extra tension as a substitute for correct monitor weight." },
      { heading: "Reduce walking speed before changing hardware", body: "A slower pace and shorter stride often reduce transmitted motion. If the screen is readable at a practical pace, replacing the desk or arm may offer little benefit." },
      { heading: "Separate walking tasks from precision tasks", body: "Use walking sessions for calls, reading, or light work and pause for detailed design, spreadsheet, or cursor-intensive tasks when movement affects vision or accuracy. An adjustable workstation should support changing posture, not require continuous walking." },
    ],
  },
  {
    site: "pet",
    slug: "air-purifier-pet-odor-source-control-guide",
    title: "Air Purifier for Pet Odor vs. Source Control",
    dek: "Separate airborne particles from odor gases, then build a room routine around cleaning, ventilation, carbon, CADR, placement, and filter cost.",
    category: "home-care",
    updatedAt: "July 1, 2026",
    relatedProducts: ["shark-neverchange-max-air-purifier"],
    relatedRoundups: ["best-pet-odor-and-litter-upgrades"],
    sources: [
      {
        name: "US EPA Guide to Air Cleaners in the Home",
        url: "https://www.epa.gov/indoor-air-quality-iaq/guide-air-cleaners-home",
        note: "Primary guidance for particle filters, gas filters, CADR, room sizing, placement, fan speed, and limitations.",
      },
      {
        name: "US EPA Indoor Air Quality overview",
        url: "https://www.epa.gov/indoor-air-quality-iaq/improving-indoor-air-quality",
        note: "Primary guidance on source control, ventilation, and supplemental air cleaning.",
      },
    ],
    sections: [
      { heading: "Start at the odor source", body: "Remove soiled litter, wash bedding, clean accidents with a material-appropriate method, groom as appropriate, and address damp fabrics or waste storage. An air cleaner is a supplement, not a way to leave an active source in the room." },
      { heading: "Particles and odor gases need different media", body: "A particle filter can capture airborne dander, dust, and hair fragments. Odor molecules are gases and need activated carbon or another gas-phase medium; a HEPA label alone does not describe odor removal." },
      { heading: "Use CADR to size particle cleaning", body: "EPA recommends choosing a smoke CADR suitable for the room area. CADR evaluates particle removal, not gas or odor performance, so a large room number does not prove that a thin carbon sheet will control persistent smells." },
      { heading: "Carbon quantity and replacement matter", body: "EPA notes that activated carbon can remove gases when there is enough material. Check the actual gas-filter stage, replacement schedule, price, and availability rather than relying on a generic odor icon." },
      { heading: "Placement and fan speed change results", body: "Place the unit where intake and outlet airflow remain open and where the pet cannot tip it, chew the cord, or block the grille. Higher fan speeds and longer run time generally move more air, though noise may affect the setting used in practice." },
      { heading: "Escalate persistent or unusual odors", body: "A continuing smell can point to hidden contamination, moisture, plumbing, litter-box issues, or a pet health concern. Investigate the source instead of masking it with fragrance or buying a larger purifier without diagnosis." },
    ],
  },
  {
    site: "homeoffice",
    slug: "usb-c-dock-vs-monitor-hub-guide",
    title: "USB-C Dock vs Monitor Hub: Which Home Office Upgrade Should You Buy?",
    dek: "Choose a standalone dock or USB-C monitor hub by exact laptop display support, replaceability, charging, Ethernet, DisplayLink needs, and the cable you touch every day.",
    category: "ergonomics",
    updatedAt: "July 22, 2026",
    image: "/images/affiliate/homeoffice-dual-monitor-dock-editorial-realistic.webp",
    imageAlt: "Dual-monitor desk connected through a compact docking station",
    relatedProducts: ["anker-675-usb-c-docking-station", "plugable-usbc-6950pdz-displaylink-dock", "plugable-tbt4-ud5-thunderbolt-dock", "caldigit-ts4-thunderbolt-dock"],
    relatedRoundups: ["best-dual-monitor-docks-mac-windows", "displaylink-vs-thunderbolt-dock-dual-monitors", "best-standing-desks-for-small-spaces"],
    relatedGuides: ["macbook-dual-monitor-dock-chip-compatibility-guide", "usb-c-dock-ports-explained-guide"],
    comparisonTable: {
      title: "Standalone dock or monitor hub",
      columns: ["Decision", "Standalone dock", "USB-C monitor hub"],
      rows: [
        { label: "Replacement", values: ["Replace dock without replacing display", "Hub and panel age together"] },
        { label: "Port depth", values: ["Wider choices including DisplayLink and Thunderbolt", "Usually fixed and simpler"] },
        { label: "Desk cables", values: ["More routing flexibility, one extra box", "Cleaner rear-of-monitor path"] },
        { label: "Dual displays", values: ["Depends on host and dock technology", "Daisy chain/MST and macOS limits must be checked"] },
      ],
    },
    sources: [
      { name: "Plugable TBT4-UD5 product page", url: "https://plugable.com/products/tbt4-ud5", note: "Example native Thunderbolt display and host compatibility." },
      { name: "Plugable USBC-6950PDZ product page", url: "https://plugable.com/products/usbc-6950pdz", note: "Example DisplayLink path for hosts with native display limits." },
      { name: "Anker 675 official FAQ", url: "https://service.anker.com/article-description/Anker-675-USB-C-Docking-Station-12-in-1-Monitor-Stand-Wireless-FAQ", note: "Example one-monitor dock and stand with an explicit USB-C video limitation." },
    ],
    sections: [
      { heading: "A dock is easier to replace", body: "A standalone USB-C dock can move between desks, be returned separately, and upgrade without replacing the monitor. It is the cleaner choice when Ethernet, card readers, audio, or extra USB ports matter." },
      { heading: "A monitor hub cleans the desk", body: "A display with built-in USB-C can reduce cable clutter and put charging, video, and USB devices behind the screen. The risk is being locked into the monitor's port limits and power delivery." },
      { heading: "Identify the display mechanism", body: "A monitor hub normally uses native USB-C DisplayPort Alt Mode and may offer daisy chaining through MST. macOS and the exact chip can limit that path. A standalone dock can use native Thunderbolt or DisplayLink, but those mechanisms have different tradeoffs." },
      { heading: "Charging wattage is the first physical filter", body: "Compare the laptop's sustained USB-C power need with the actual host output, not only the adapter input number. A setup that displays correctly can still drain a higher-power laptop under load." },
      { heading: "Dual-display support is model-specific", body: "Resolution, refresh rate, native display streams, DisplayPort Alt Mode, Thunderbolt, MST, DisplayLink, clamshell rules, and macOS limitations can change the answer. Check the exact laptop chip, cable, monitor input, and screen count before buying." },
      { heading: "Keep DisplayLink as a conscious exception", body: "A DisplayLink dock can solve two-screen office work on base M1 or M2 Macs, while introducing drivers, permissions, protected-video limits, and ongoing OS maintenance. A monitor hub rarely supplies that workaround by itself." },
      { heading: "Buy for the cable you want to touch daily", body: "If the goal is one cable on the desk, either path can work. Choose the one that keeps the ports you actually use reachable without making the monitor the failure point for every peripheral." },
      { heading: "Test sleep, wake, and return-window behavior", body: "A clean desk that loses displays after sleep is not a good system. Test login, clamshell mode, wake, conferencing, fullscreen video, charging, Ethernet, storage, and monitor controls before the return period ends." },
    ],
  },
  {
    site: "baby",
    slug: "baby-monitor-subscription-and-privacy-checklist",
    title: "Baby Monitor Subscription and Privacy Checklist",
    dek: "Before choosing Nanit, Infant Optics, or another monitor, separate local video, cloud history, app sharing, security, and renewal costs.",
    category: "monitoring",
    updatedAt: "July 9, 2026",
    relatedProducts: ["nanit-pro-smart-baby-monitor", "infant-optics-dxr-8-pro"],
    relatedRoundups: ["best-baby-monitors-for-apartments"],
    sections: [
      { heading: "Decide whether Wi-Fi is necessary", body: "Wi-Fi monitors can support remote viewing, app sharing, clips, and analytics. Non-Wi-Fi monitors can be simpler for in-home viewing and may avoid cloud-account decisions." },
      { heading: "Map free features separately from paid features", body: "Live view, background audio, event clips, sleep insights, multiple caregivers, breathing wear, and storage windows can sit in different plan tiers. Write down which feature justifies any monthly cost." },
      { heading: "Check who can see the camera", body: "Review account sharing, guest access, password practices, two-factor authentication, old caregivers, and whether the camera remains visible after a move or resale." },
      { heading: "Plan what happens when the internet fails", body: "A Wi-Fi monitor should not be the only way to know what is happening in the next room if the app, router, or cloud service is down. Keep a local routine for naps and overnight checks." },
      { heading: "Compare first year and renewal cost", body: "Trials and bundles can make the first year look cheaper than the long-term plan. Compare the normal annual total before treating a smart monitor as the same price as a local-video monitor." },
    ],
  },
];
