import type { Guide, Product, Roundup } from "./types";

const updatedAt = "July 10, 2026";

export const gscPriorityProducts: Product[] = [
  {
    site: "baby",
    slug: "dr-browns-all-in-one-sterilizer-dryer",
    asin: "B089QWNQXC",
    amazonTitle: "Dr. Brown's All-in-One Sterilizer and Dryer for Baby Bottles, Parts and Other Newborn Essentials",
    amazonDetailUrl: "https://www.amazon.com/dp/B089QWNQXC",
    seoTitle: "Dr. Brown's All-in-One Sterilizer and Dryer Review: Capacity, Drying & Fit",
    updatedAt,
    sources: [
      { name: "Amazon listing: Dr. Brown's All-in-One Sterilizer and Dryer", url: "https://www.amazon.com/dp/B089QWNQXC", note: "ASIN, title, bottle capacity, cycle modes, and current listing details." },
    ],
    editorialSections: [
      { heading: "Why this one fills the gap", body: "Dr. Brown's is the familiar mid-price sterilizer-dryer alternative missing from the current bottle-cleanup cluster. It is less of a full appliance than Momcozy KleanPal Pro and easier to compare against Baby Brezza." },
      { heading: "Capacity still needs a shape check", body: "Amazon lists room for up to six narrow or wide-neck bottles plus accessories, but real capacity changes with bottle height, pump parts, caps, and nipple rings. Count a full day of parts before assuming one cycle is enough." },
      { heading: "Treat 24-hour storage as conditional", body: "The listing says contents can remain sterilized up to 24 hours when the lid is unopened. That only helps if parts were cleaned first, the cycle completed correctly, and the lid stays closed until use." },
    ],
    name: "Dr. Brown's All-in-One Sterilizer and Dryer",
    brand: "Dr. Brown's",
    category: "feeding",
    image: "/images/affiliate/baby-bottle-sterilizer-dryer-realistic.webp",
    summary: "A mid-price bottle sterilizer and dryer for families who want one machine for clean bottles, pump parts, pacifiers, and accessories without moving up to a full bottle washer.",
    verdict: "Dr. Brown's All-in-One is the practical middle choice when drying matters and the routine does not justify a larger washer-style appliance. Confirm bottle shape, accessory load, and counter height before comparing it only by price.",
    whyItMatters: "Bottle cleanup pages need a recognizable mid-range sterilizer-dryer option between simple sterilizers and larger all-in-one washers.",
    bestFor: "Bottle-heavy routines that need sterilizing plus drying without automatic washing",
    priceBand: "$$",
    rating: 4.4,
    scores: [
      { label: "Drying convenience", value: 8 },
      { label: "Capacity", value: 8 },
      { label: "Counter fit", value: 7 },
    ],
    pros: ["Recognizable mid-range sterilizer-dryer", "Listed for up to six bottles plus accessories", "Separate sterilize, dry, combo, and storage-style use cases"],
    cons: ["Does not wash residue off parts", "Bottle shape and pump-part layout affect real capacity", "Needs counter height for the lid and internal stack"],
    specs: {
      ASIN: "B089QWNQXC",
      "Product type": "Bottle sterilizer and dryer",
      "Listed capacity": "Up to six narrow or wide-neck bottles plus accessories",
      "Cycle options": "Sterilize, dry, sterilize and dry, storage-style use",
      "Amazon title verified": "July 10, 2026",
    },
    evidence: [
      "Amazon listing verified ASIN B089QWNQXC and Dr. Brown's All-in-One title",
      "Listing bullets describe up to six bottles, steam sterilizing, drying, and up-to-24-hour closed-lid storage",
      "Buyer should confirm current bundle, seller, voltage, bottle fit, and return window at checkout",
    ],
    alternatives: ["Choose Baby Brezza when drying speed and large accessory load are the main concerns.", "Choose Momcozy KleanPal Pro when the bottleneck is washing, not just sterilizing and drying."],
    compareSlugs: ["baby-brezza-sterilizer-dryer-advanced", "grownsy-bottle-sterilizer-dryer", "momcozy-kleanpal-pro-baby-bottle-washer"],
    offers: [
      { merchant: "Amazon US", url: "https://www.amazon.com/dp/B089QWNQXC?tag=bingmada-20&linkCode=ll2&language=en_US&ref_=as_li_ss_tl", label: "Check Dr. Brown's sterilizer dryer on Amazon", priceNote: "Confirm ASIN B089QWNQXC, seller, live price, and selected bundle." },
    ],
  },
  {
    site: "baby",
    slug: "grownsy-bottle-sterilizer-dryer",
    asin: "B09HH7HSGV",
    amazonTitle: "GROWNSY Bottle Sterilizer and Dryer, Compact Electric Steam Baby Bottle Sterilizer",
    amazonDetailUrl: "https://www.amazon.com/dp/B09HH7HSGV",
    seoTitle: "GROWNSY Bottle Sterilizer and Dryer Review: Compact Counter Fit",
    updatedAt,
    sources: [
      { name: "Amazon listing: GROWNSY Bottle Sterilizer and Dryer", url: "https://www.amazon.com/dp/B09HH7HSGV", note: "ASIN, compact model title, item model LS-BE916, dimensions, and listing bullets." },
    ],
    editorialSections: [
      { heading: "Compact is the pitch", body: "This GROWNSY listing is the smaller counter-space candidate in the cluster. It is useful for shoppers who want a sterilizer-dryer but are hesitant about a large Baby Brezza, Momcozy, or Chicco footprint." },
      { heading: "Do not confuse it with a washer", body: "The listing describes steam sterilizing, drying, and storage functions. It should be evaluated after bottles and pump parts have been cleaned rather than as a replacement for washing." },
      { heading: "Version and seller checks matter", body: "The listing title and model details can shift over time. Confirm GROWNSY brand, ASIN B09HH7HSGV, dimensions, seller, and included trays before comparing price." },
    ],
    name: "GROWNSY Bottle Sterilizer and Dryer",
    brand: "GROWNSY",
    category: "feeding",
    image: "/images/affiliate/baby-bottle-sterilizer-dryer-realistic.webp",
    summary: "A compact bottle sterilizer and dryer for parents who want steam sanitizing and drying without dedicating a large appliance footprint.",
    verdict: "GROWNSY is the compact-value slot in the bottle sterilizer lineup. It deserves attention when counter space is the limiting factor, but buyers should verify tray layout and pump-part fit before relying on it for a full-day load.",
    whyItMatters: "Searches for baby bottle sterilizers include many shoppers who are comparing capacity against counter space, not just brand names.",
    bestFor: "Small kitchens that need a compact sterilizer-dryer",
    priceBand: "$",
    rating: 4.3,
    scores: [
      { label: "Counter fit", value: 9 },
      { label: "Drying convenience", value: 7 },
      { label: "High-volume routine", value: 5 },
    ],
    pros: ["Compact footprint compared with larger appliance-style units", "Steam sterilize and dry workflow", "Useful value candidate for small kitchens"],
    cons: ["Less spacious than large-capacity units", "Still requires cleaning before sterilizing", "Listing/version details should be verified carefully"],
    specs: {
      ASIN: "B09HH7HSGV",
      "Item model": "LS-BE916 listed on Amazon",
      "Product type": "Compact electric bottle sterilizer and dryer",
      "Listed dimensions": "8.1 x 7.5 x 14.94 inches",
      "Amazon title verified": "July 10, 2026",
    },
    evidence: [
      "Amazon listing verified ASIN B09HH7HSGV and GROWNSY Store byline",
      "Listing details included item model LS-BE916 and compact dimensions",
      "Buyer should confirm bottle count, tray layout, seller, voltage, filter or cleaning needs, and return window",
    ],
    alternatives: ["Choose Dr. Brown's when a more recognizable mid-range sterilizer-dryer matters.", "Choose Chicco or Baby Brezza when a larger six-bottle layout is more important than compact size."],
    compareSlugs: ["dr-browns-all-in-one-sterilizer-dryer", "chicco-advanced-sterilizer-dryer", "baby-brezza-sterilizer-dryer-advanced"],
    offers: [
      { merchant: "Amazon US", url: "https://www.amazon.com/dp/B09HH7HSGV?tag=bingmada-20&linkCode=ll2&language=en_US&ref_=as_li_ss_tl", label: "Check GROWNSY sterilizer dryer on Amazon", priceNote: "Confirm ASIN B09HH7HSGV, seller, model LS-BE916, and live price." },
    ],
  },
  {
    site: "baby",
    slug: "chicco-advanced-sterilizer-dryer",
    asin: "B0BG67HG7S",
    amazonTitle: "Chicco Advanced Electric Steam Sterilizer and Dryer for Baby Bottles, Pacifiers & Feeding Accessories",
    amazonDetailUrl: "https://www.amazon.com/dp/B0BG67HG7S",
    seoTitle: "Chicco Advanced Sterilizer and Dryer Review: 6-Bottle Capacity & Delay Start",
    updatedAt,
    sources: [
      { name: "Amazon listing: Chicco Advanced Electric Steam Sterilizer and Dryer", url: "https://www.amazon.com/dp/B0BG67HG7S", note: "ASIN, title, listed capacity, cycle options, dimensions, and style details." },
    ],
    editorialSections: [
      { heading: "The comparison reason", body: "Chicco gives the bottle sterilizer page a higher-capacity brand-name alternative with delay start and filtered drying claims, sitting between compact value units and the larger all-in-one washer category." },
      { heading: "Delay start is useful only with clean parts", body: "The delay feature can fit an evening routine, but bottle and pump parts still need to be cleaned before the sterilizing cycle. Do not use delay start to store dirty feeding parts." },
      { heading: "Measure height and storage mode", body: "Amazon lists this as a taller six-bottle unit. Check cabinet clearance, lid movement, and whether the unit can stay on the counter rather than being stored after every cycle." },
    ],
    name: "Chicco Advanced Electric Steam Sterilizer and Dryer",
    brand: "Chicco",
    category: "feeding",
    image: "/images/affiliate/baby-bottle-sterilizer-dryer-realistic.webp",
    summary: "A six-bottle steam sterilizer and dryer with multiple cycle options for families who want brand-name capacity without moving into a bottle washer.",
    verdict: "Chicco is the capacity-and-controls candidate. It is a stronger fit for families who want a full six-bottle sterilizer-dryer and delay start, while compact kitchens should compare GROWNSY or a smaller routine first.",
    whyItMatters: "A bottle sterilizer roundup needs one clearly larger, branded option for parents who care more about capacity than the smallest footprint.",
    bestFor: "Six-bottle sterilizing and drying with delay-start flexibility",
    priceBand: "$$",
    rating: 4.3,
    scores: [
      { label: "Capacity", value: 9 },
      { label: "Cycle control", value: 8 },
      { label: "Counter footprint", value: 5 },
    ],
    pros: ["Listed for up to six bottles plus accessories", "Sterilize only, sterilize and dry, dry only, and delay start modes", "Filtered drying and 24-hour closed-lid sterile-storage claim"],
    cons: ["Taller footprint needs cabinet clearance", "Does not wash bottles", "Smaller review base than some category leaders"],
    specs: {
      ASIN: "B0BG67HG7S",
      "Product type": "Electric steam sterilizer and dryer",
      "Listed capacity": "Up to six bottles plus accessories",
      "Cycle options": "Sterilize only, sterilize and dry, dry only, delay start",
      "Amazon title verified": "July 10, 2026",
    },
    evidence: [
      "Amazon listing verified ASIN B0BG67HG7S and Chicco Store byline",
      "Listing bullets describe six-bottle capacity, four cycle options, filtered drying, and up-to-24-hour closed-lid sterile storage",
      "Buyer should confirm current seller, dimensions, filter requirements, bottle fit, and return window",
    ],
    alternatives: ["Choose Dr. Brown's if a simpler mid-range sterilizer-dryer is enough.", "Choose Momcozy KleanPal Pro if washing is the pain point rather than only sterilizing and drying."],
    compareSlugs: ["dr-browns-all-in-one-sterilizer-dryer", "baby-brezza-sterilizer-dryer-advanced", "momcozy-kleanpal-pro-baby-bottle-washer"],
    offers: [
      { merchant: "Amazon US", url: "https://www.amazon.com/dp/B0BG67HG7S?tag=bingmada-20&linkCode=ll2&language=en_US&ref_=as_li_ss_tl", label: "Check Chicco sterilizer dryer on Amazon", priceNote: "Confirm ASIN B0BG67HG7S, seller, live price, and current cycle features." },
    ],
  },
  {
    site: "homeoffice",
    slug: "elgato-key-light-neo",
    asin: "B0FDBL5MVM",
    amazonTitle: "Elgato Key Light Neo Black with Monitor Mount",
    amazonDetailUrl: "https://www.amazon.com/dp/B0FDBL5MVM",
    seoTitle: "Elgato Key Light Neo Review: Monitor-Mounted Video Call Light",
    updatedAt,
    sources: [
      { name: "Amazon listing: Elgato Key Light Neo", url: "https://www.amazon.com/dp/B0FDBL5MVM", note: "ASIN, title, monitor mount, USB power, brightness, and edge-lit claims." },
    ],
    editorialSections: [
      { heading: "Why add it to the lighting cluster", body: "Elgato Key Light Neo is the direct upgrade path for searchers who want a purpose-built video-call light rather than a generic desk lamp or a keyboard-focused monitor light bar." },
      { heading: "Monitor fit controls the experience", body: "The Amazon title emphasizes a monitor mount. Check monitor thickness, laptop lid strength, camera placement, USB power, and whether the light blocks a webcam or screen controls." },
      { heading: "Brightness needs power planning", body: "The listing says it can reach up to 1000 lumens with USB power. Confirm the required external USB power source and whether laptop-only power changes brightness." },
    ],
    name: "Elgato Key Light Neo",
    brand: "Elgato",
    category: "meetings",
    image: "/images/affiliate/homeoffice-desk-light-realistic.webp",
    summary: "A monitor-mounted edge-lit video-call light for remote workers who want better face exposure and adjustable color without building a full studio setup.",
    verdict: "Key Light Neo is the sharper video-call pick when Logitech Litra Glow feels too basic but a large panel or floor stand is overkill. Verify mount fit and USB power before choosing it for a laptop-heavy desk.",
    whyItMatters: "The home-office lighting page needs a stronger dedicated call-light option for shoppers searching video call lighting rather than general desk illumination.",
    bestFor: "Dedicated face lighting for Zoom, Meet, Teams, and streaming calls",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Face lighting", value: 9 },
      { label: "Desk footprint", value: 9 },
      { label: "Setup flexibility", value: 7 },
    ],
    pros: ["Purpose-built for calls and streaming", "Edge-lit design aims to reduce glare", "Monitor mount keeps the desktop clear"],
    cons: ["Monitor or laptop fit must be checked", "Requires USB power planning for full brightness", "Less useful as general room lighting"],
    specs: {
      ASIN: "B0FDBL5MVM",
      "Light type": "Edge-lit monitor-mounted video light",
      Brightness: "Up to 1000 lumens with USB power per Amazon listing",
      "Use case": "Video calls and streaming",
      "Amazon title verified": "July 10, 2026",
    },
    evidence: [
      "Amazon listing verified ASIN B0FDBL5MVM and Elgato Store byline",
      "Listing bullets describe adjustable brightness and color temperature, monitor mounting, edge-lit lighting, and USB power",
      "Buyer should confirm mount version, monitor compatibility, USB power source, seller, and return window",
    ],
    alternatives: ["Choose Logitech Litra Glow for a simpler lower-cost call light.", "Choose Lume Cube Edge 2.0 or BenQ ScreenBar Halo when desk/task lighting matters as much as camera lighting."],
    compareSlugs: ["logitech-litra-glow", "lume-cube-edge-2-desk-light", "benq-screenbar-halo"],
    offers: [
      { merchant: "Amazon US", url: "https://www.amazon.com/dp/B0FDBL5MVM?tag=bingmada-20&linkCode=ll2&language=en_US&ref_=as_li_ss_tl", label: "Check Elgato Key Light Neo on Amazon", priceNote: "Confirm ASIN B0FDBL5MVM, mount bundle, USB power needs, and live price." },
    ],
  },
  {
    site: "homeoffice",
    slug: "lume-cube-edge-2-desk-light",
    asin: "B0CN7BK69P",
    amazonTitle: "LUME CUBE Edge 2.0 LED Desk Lamp with USB Charging Port and Circle Webcam Light",
    amazonDetailUrl: "https://www.amazon.com/dp/B0CN7BK69P",
    seoTitle: "Lume Cube Edge 2.0 Review: Desk Lamp and Webcam Light for Calls",
    updatedAt,
    sources: [
      { name: "Amazon listing: Lume Cube Edge 2.0 LED Desk Lamp", url: "https://www.amazon.com/dp/B0CN7BK69P", note: "ASIN, title, swing arm, USB ports, color temperature, brightness, and clamp details." },
    ],
    editorialSections: [
      { heading: "It is a hybrid, not just a call light", body: "Lume Cube Edge 2.0 belongs in the cluster because it bridges task lighting and camera lighting. It is better for shoppers who want one clamp lamp for desk work and video calls." },
      { heading: "Clamp and arm reach are the buying checks", body: "The listing describes a swing arm and clamp support up to 3.3 inches thick. Check desk edge depth, monitor arm conflicts, wall clearance, and whether the light can sit near the camera path." },
      { heading: "Camera lighting may need placement work", body: "A larger desk lamp can improve meetings only when it lights the face from the right angle. If it sits too far to the side, a smaller camera-mounted light may work better." },
    ],
    name: "Lume Cube Edge 2.0 LED Desk Lamp",
    brand: "Lume Cube",
    category: "meetings",
    image: "/images/affiliate/homeoffice-desk-light-realistic.webp",
    summary: "A clamp-on LED desk lamp with adjustable color, brightness, swing-arm positioning, USB ports, and a webcam-light role for home office calls.",
    verdict: "Lume Cube Edge 2.0 is the best fit when the buyer wants both a serious desk lamp and better call lighting. If the only pain point is a dark face on Zoom, Elgato or Logitech may be simpler.",
    whyItMatters: "Not every video-call-light shopper wants a tiny camera light; some need a real desk lamp that can also improve camera exposure.",
    bestFor: "Hybrid task lighting and video-call lighting on a fixed desk",
    priceBand: "$$$",
    rating: 4.4,
    scores: [
      { label: "Task lighting", value: 9 },
      { label: "Video-call fit", value: 7 },
      { label: "Desk footprint", value: 7 },
    ],
    pros: ["Swing arm can serve desk and camera-lighting jobs", "Adjustable brightness and color temperature", "USB-A and USB-C charging ports listed"],
    cons: ["Larger and pricier than compact video lights", "Clamp and wall clearance need checking", "May be less direct for face lighting than a monitor-mounted light"],
    specs: {
      ASIN: "B0CN7BK69P",
      "Light type": "Clamp-on LED desk lamp and webcam light",
      "Listed clamp support": "Surfaces up to 3.3 inches thick",
      Controls: "Adjustable brightness and color temperature",
      "Amazon title verified": "July 10, 2026",
    },
    evidence: [
      "Amazon listing verified ASIN B0CN7BK69P and LUME CUBE Store byline",
      "Listing bullets describe adjustable brightness, warm-to-cool color, swing arm, USB charging ports, and desk clamp",
      "Buyer should confirm color variant, clamp clearance, desk edge, power placement, seller, and return window",
    ],
    alternatives: ["Choose Elgato Key Light Neo when the priority is a compact monitor-mounted call light.", "Choose BenQ ScreenBar Halo when keyboard illumination with minimal desk footprint is the main job."],
    compareSlugs: ["elgato-key-light-neo", "benq-screenbar-halo", "logitech-litra-glow"],
    offers: [
      { merchant: "Amazon US", url: "https://www.amazon.com/dp/B0CN7BK69P?tag=bingmada-20&linkCode=ll2&language=en_US&ref_=as_li_ss_tl", label: "Check Lume Cube Edge 2.0 on Amazon", priceNote: "Confirm ASIN B0CN7BK69P, color, clamp fit, seller, and live price." },
    ],
  },
];

export const gscPriorityRoundups: Roundup[] = [
  {
    site: "baby",
    slug: "best-baby-carriers-by-age-and-position",
    title: "Best Baby Carriers by Age and Carry Position",
    dek: "Compare newborn inward carry, outward-facing readiness, hip carry, back carry, warm-weather comfort, and when a simpler carrier beats an all-stage model.",
    category: "travel",
    intent: "Choose a carrier by the baby's current milestone instead of buying the most feature-heavy option.",
    intro:
      "Baby carrier shopping gets easier when age is treated as a planning clue, not permission to use every position. Start with the carry position the baby can safely use now, then compare caregiver fit, heat, return policy, and how long the carrier should remain useful.",
    decisionGuide: [
      { label: "Newborn inward carry", detail: "Choose a carrier with clear newborn minimums, head support, and an easy front-inward setup." },
      { label: "Outward-facing interest", detail: "Wait for the listed head, neck, height, and weight requirements; do not use outward carry as a newborn feature." },
      { label: "Longer errands", detail: "A structured waist belt and lumbar support can matter more than the number of advertised positions." },
      { label: "Hot weather", detail: "Mesh helps, but shared body heat, shade, clothing, and trip length still decide comfort." },
    ],
    methodology: [
      "Separate current safe position from later advertised positions",
      "Compare official weight, height, and developmental guidance",
      "Keep caregiver fit and return policy visible because comfort is personal",
    ],
    productSlugs: [
      "ergobaby-omni-breeze-carrier",
      "babybjorn-carrier-harmony",
      "babybjorn-carrier-mini-3d-mesh",
      "momcozy-purehug-baby-carrier",
      "baby-tula-lite-carrier",
    ],
    faqs: [
      { question: "Can a newborn face outward in a carrier?", answer: "No. Newborns should use the model's approved inward-facing newborn setup after meeting the stated minimums." },
      { question: "Is an all-stage carrier always better?", answer: "Not always. A simpler newborn carrier can be easier early, while an all-stage carrier can reduce repeat buying later." },
      { question: "What matters more than age?", answer: "Weight, height, head and neck control, sitting ability, airway visibility, and the exact manual for the current carrier." },
    ],
  },
  {
    site: "baby",
    slug: "best-bottle-sterilizer-dryer-for-pump-parts",
    title: "Best Bottle Sterilizer and Dryer for Pump Parts",
    dek: "Choose between a sterilizer-dryer combo and a larger washer by counting valves, flanges, caps, bottles, drying space, and repeat cycles.",
    category: "feeding",
    intent: "Pick the feeding cleanup appliance that reduces daily pump-part and bottle friction.",
    intro:
      "A bottle sterilizer can be disappointing if the real problem is wet pump parts covering the counter. Count the small pieces first, then decide whether the daily bottleneck is washing, sanitizing, drying, or clean storage.",
    decisionGuide: [
      { label: "Drying is the pain point", detail: "A sterilizer-dryer combo can reduce counter clutter when clean parts stay wet too long." },
      { label: "Hand-washing is the pain point", detail: "A washer-style appliance deserves attention when scrubbing bottles and pump parts consumes the routine." },
      { label: "Small kitchen", detail: "Check footprint, lid clearance, drain route, and where clean parts will land after a cycle." },
      { label: "Occasional sanitizing", detail: "A simpler or smaller approach may beat a large appliance that will not stay on the counter." },
    ],
    methodology: [
      "Count bottles and pump parts instead of relying on headline bottle capacity",
      "Separate washing, sanitizing, drying, and storage",
      "Use CDC and manufacturer instructions as the safety baseline",
    ],
    productSlugs: [
      "baby-brezza-sterilizer-dryer-advanced",
      "dr-browns-all-in-one-sterilizer-dryer",
      "chicco-advanced-sterilizer-dryer",
      "grownsy-bottle-sterilizer-dryer",
      "momcozy-kleanpal-pro-baby-bottle-washer",
    ],
    faqs: [
      { question: "Do sterilizer dryers wash bottles?", answer: "Usually no. A sterilizer-dryer handles sanitizing and drying after cleaning unless the exact model includes a wash cycle." },
      { question: "Should pump parts go in a sterilizer?", answer: "Only if the pump and appliance instructions allow it. Follow the pump maker, appliance manual, and current health guidance." },
      { question: "Is drying worth paying for?", answer: "It can be if parts must be reused quickly or if clean wet pieces are creating counter clutter every day." },
    ],
  },
  {
    site: "baby",
    slug: "best-bottle-sterilizer-dryer-for-small-kitchens",
    title: "Best Bottle Sterilizer and Dryer for Small Kitchens",
    dek: "Compare compact footprint, lid clearance, bottle capacity, pump-part space, drying, storage, and the counter trade-offs that matter in a small kitchen.",
    category: "feeding",
    intent: "Choose a bottle sterilizer and dryer that fits a small kitchen without sacrificing the parts the daily routine actually needs.",
    intro: "The smallest appliance is not always the best small-kitchen choice. Measure the permanent footprint, lid swing, outlet, and clean landing area, then count pump valves and bottle parts before comparing capacity claims.",
    decisionGuide: [
      { label: "Smallest footprint", detail: "Start with GROWNSY when counter depth and storage after each cycle are the main constraints." },
      { label: "Six-bottle routine", detail: "Compare Chicco or Baby Brezza only after measuring height, lid clearance, and accessory space." },
      { label: "Recognizable middle option", detail: "Dr. Brown's fits families that want drying without moving to a full washer-style appliance." },
      { label: "Pump-heavy routine", detail: "Count valves, flanges, caps, and tubing before trusting a bottle-only capacity number." },
    ],
    methodology: [
      "Measure the appliance in its working position, including lid clearance",
      "Count real bottles and pump parts instead of comparing headline capacity alone",
      "Separate washing, sterilizing, drying, and clean storage",
      "Check current model, bundle, seller, return policy, and electrical requirements",
    ],
    productSlugs: [
      "grownsy-bottle-sterilizer-dryer",
      "dr-browns-all-in-one-sterilizer-dryer",
      "chicco-advanced-sterilizer-dryer",
      "baby-brezza-sterilizer-dryer-advanced",
    ],
    faqs: [
      { question: "Is a compact sterilizer dryer enough for pump parts?", answer: "It can be when the exact valves, flanges, caps, and tubing fit without blocking steam or airflow. Count the real daily load first." },
      { question: "Does a small sterilizer dryer wash bottles?", answer: "Usually no. Clean feeding parts before sanitizing and drying unless the exact appliance includes a compatible wash cycle." },
      { question: "Should the appliance stay on the counter?", answer: "Only when the lid can open safely, the outlet and steam path are clear, and the clean parts have a covered landing or storage plan." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-home-office-lighting-for-video-calls-in-small-rooms",
    title: "Best Home Office Lighting for Video Calls in Small Rooms",
    dek: "Choose compact lighting for Zoom, Meet, and Teams calls by face exposure, glare, monitor space, window position, and desk clutter.",
    category: "meetings",
    intent: "Improve video-call appearance in a small home office without turning the desk into a studio.",
    intro:
      "Small-room video calls usually fail because the camera sees a bright window, overhead shadows, or a dark face. A compact front light can outperform a new webcam when it is placed near the camera and adjusted before meetings.",
    decisionGuide: [
      { label: "Face is too dark", detail: "Start with a compact video light near the camera rather than a desk lamp behind the screen." },
      { label: "Need keyboard light", detail: "A monitor light bar helps desk visibility but may not brighten your face enough for calls." },
      { label: "Wear glasses", detail: "Prioritize dimming and angle control so the light does not reflect directly into the camera." },
      { label: "Tiny desk", detail: "Favor monitor-mounted or behind-monitor placement over lamp bases that consume the work surface." },
    ],
    methodology: [
      "Match the light to camera position first",
      "Check glare on glasses and glossy monitors",
      "Separate face lighting from desk lighting",
    ],
    productSlugs: ["logitech-litra-glow", "elgato-key-light-neo", "lume-cube-edge-2-desk-light", "benq-screenbar-halo"],
    faqs: [
      { question: "Is a monitor light bar good for video calls?", answer: "It can help the desk, but it may not light the face as well as a camera-adjacent video light." },
      { question: "Should the light be behind the monitor?", answer: "It should light your face from near the camera path. Behind-monitor placement can work only if the light is aimed correctly." },
      { question: "Do I need a new webcam first?", answer: "Often no. Fixing face lighting can improve a normal webcam more than replacing the camera in a dim room." },
    ],
  },
  {
    site: "homeoffice",
    slug: "best-monitor-arms-for-walking-desks",
    title: "Best Monitor Arm for a Walking Desk: 3 Stable Setups",
    dek: "Compare monitor weight range, clamp support, arm extension, screen wobble, cable slack, and desk stiffness before buying for a walking desk.",
    category: "ergonomics",
    intent: "Choose a monitor arm that stays usable while a walking pad adds movement to the desk and screen.",
    intro: "A walking-desk monitor arm is only as stable as the floor, desk frame, desktop, clamp, and screen path below it. Choose the arm after checking monitor-only weight, VESA, clamp clearance, extension, and the pace you can work at comfortably.",
    decisionGuide: [
      { label: "Heavy or curved display", detail: "Start with Ergotron HX after confirming monitor weight, curve adapter needs, and desk strength." },
      { label: "Value heavy-duty option", detail: "Compare HUANUO TitanLift when the monitor fits its range and a supported clamp area is available." },
      { label: "Light single monitor", detail: "Amazon Basics can fit a simpler setup when weight and VESA stay comfortably inside its range." },
      { label: "Walking stability first", detail: "Keep the display close to the post, reduce forward extension, and fix desk wobble before changing arms." },
    ],
    methodology: [
      "Use monitor-only weight and the exact VESA pattern",
      "Inspect the desktop above and below the clamp",
      "Compare short-extension stability with the desired standing height",
      "Test cable slack through sit-stand travel and walking-pad movement",
    ],
    productSlugs: ["ergotron-hx-monitor-arm", "huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    faqs: [
      { question: "Is a heavy-duty arm automatically stable on a walking desk?", answer: "No. Desk flex, lifting columns, floor movement, clamp position, and arm extension can dominate the result." },
      { question: "Should I use a dual monitor arm?", answer: "Only when the shared post and desktop can carry the combined leverage. Two independent arms can make weight and position easier to isolate." },
      { question: "How do I reduce screen wobble?", answer: "Level and tighten the desk, move the screen closer to the post, reduce extension, add safe cable slack, and slow the walking pace before replacing hardware." },
    ],
  },
];

export const gscPriorityGuides: Guide[] = [
  {
    site: "baby",
    slug: "ergobaby-omni-breeze-forward-facing-age-guide",
    title: "Ergobaby Omni Breeze Forward-Facing Age and Fit Guide",
    dek: "Check head and neck control, height, weight, chin clearance, overstimulation, and when to turn back inward.",
    category: "travel",
    updatedAt,
    relatedProducts: ["ergobaby-omni-breeze-carrier"],
    relatedRoundups: ["best-baby-carriers-by-age-and-position", "best-baby-carriers-and-sleep-routine-upgrades"],
    sources: [
      { name: "Ergobaby Omni Breeze product guidance", url: "https://ergobaby.com/omni-breeze-baby-carrier-all", note: "Official position, size, and FAQ guidance." },
      { name: "Ergobaby Omni Breeze instructions", url: "https://ergobaby.com/instructions-omni-breeze/", note: "Official setup videos and manuals." },
    ],
    sections: [
      { heading: "Forward-facing is not a newborn mode", body: "Use the front-inward newborn setup until the baby meets the exact outward-facing requirements in the current Ergobaby instructions. Age alone is not enough." },
      { heading: "Check control and panel height", body: "Before turning outward, confirm strong head and neck control, the listed height and weight guidance, and that the chin clears the top of the panel without slumping." },
      { heading: "Use outward carry for alert short sessions", body: "Turn the baby inward when sleepy, overstimulated, cold, hot, or unable to maintain posture. Outward carry is a situational option, not the default for every errand." },
      { heading: "Reset the carrier before changing direction", body: "Seat width, strap tension, waistband position, and panel support can change between inward and outward carry. Follow the position-specific official setup each time." },
    ],
  },
  {
    site: "baby",
    slug: "ergobaby-omni-breeze-vs-babybjorn-harmony-by-age",
    title: "Ergobaby Omni Breeze vs. BabyBjorn Harmony by Age",
    dek: "Compare newborn setup, outward carry, back carry, mesh comfort, waistband support, and caregiver fit across the first year.",
    category: "travel",
    updatedAt,
    relatedProducts: ["ergobaby-omni-breeze-carrier", "babybjorn-carrier-harmony"],
    relatedRoundups: ["babybjorn-harmony-vs-ergobaby-omni-breeze", "best-baby-carriers-by-age-and-position"],
    sources: [
      { name: "Ergobaby Omni Breeze", url: "https://ergobaby.com/omni-breeze-baby-carrier-all", note: "Official size, position, and material guidance." },
      { name: "BabyBjorn Carrier Harmony", url: "https://www.babybjorn.com/products/baby-carriers/baby-carrier-harmony/", note: "Official size, position, and adjustment guidance." },
    ],
    sections: [
      { heading: "Newborn months: setup friction matters", body: "Both carriers should be judged by the correct inward-facing newborn setup, airway visibility, head support, and how confidently each caregiver can load the baby." },
      { heading: "Middle months: outward carry is milestone-bound", body: "Do not compare outward-facing as a simple age feature. Check each manual's head, neck, height, and weight requirements before using that position." },
      { heading: "Later months: support and back carry separate them", body: "For longer outings, compare waistband support, shoulder pressure, back-carry workflow, and whether the carrier remains comfortable as the child gets heavier." },
      { heading: "The better carrier is the one you can adjust correctly", body: "A feature-rich carrier loses value if one caregiver cannot get a secure fit. Return policy, instruction clarity, and real fit testing are part of the buying decision." },
    ],
  },
  {
    site: "baby",
    slug: "baby-bottle-sterilizer-dryer-counter-space-checklist",
    title: "Baby Bottle Sterilizer Dryer Counter Space Checklist",
    dek: "Measure appliance footprint, lid swing, drying path, outlet location, pump-part capacity, and where clean parts go after the cycle.",
    category: "feeding",
    updatedAt,
    relatedProducts: [
      "momcozy-kleanpal-pro-baby-bottle-washer",
      "baby-brezza-sterilizer-dryer-advanced",
      "dr-browns-all-in-one-sterilizer-dryer",
      "grownsy-bottle-sterilizer-dryer",
      "chicco-advanced-sterilizer-dryer",
    ],
    relatedRoundups: ["best-bottle-sterilizers-and-dryers", "best-bottle-sterilizer-dryer-for-pump-parts"],
    sources: [
      { name: "CDC infant feeding item cleaning guidance", url: "https://www.cdc.gov/hygiene/about/clean-sanitize-store-infant-feeding-items.html", note: "Primary cleaning, sanitizing, drying, and storage guidance." },
    ],
    sections: [
      { heading: "Measure the permanent footprint", body: "A large feeding appliance works only if it can stay accessible. Measure width, depth, lid clearance, outlet position, and the loading path with cabinets open." },
      { heading: "Count small parts before bottles", body: "Nipples, rings, caps, valves, flanges, and pacifiers can consume more usable space than bottle bodies. Use the real daily routine before trusting a headline capacity number." },
      { heading: "Plan clean storage after drying", body: "Dry parts still need a clean landing spot. Decide whether parts stay in the appliance, move to a covered bin, or get assembled immediately." },
      { heading: "Keep washing and sanitizing separate", body: "A dryer or sterilizer does not remove milk residue unless the exact appliance includes a compatible wash cycle. Clean parts first according to the product and health guidance." },
    ],
  },
  {
    site: "homeoffice",
    slug: "home-office-lighting-for-video-calls-checklist",
    title: "Home Office Lighting for Video Calls Checklist",
    dek: "Fix face exposure, window backlight, glasses glare, monitor reflections, color temperature, and desk clutter before buying a webcam.",
    category: "meetings",
    updatedAt,
    relatedProducts: ["logitech-litra-glow", "elgato-key-light-neo", "lume-cube-edge-2-desk-light", "benq-screenbar-halo"],
    relatedRoundups: ["best-video-call-lighting-for-home-office", "best-home-office-lighting-for-video-calls-in-small-rooms"],
    sources: [
      { name: "OSHA lighting guidance for computer workstations", url: "https://www.osha.gov/etools/computer-workstations/components/lighting", note: "Primary workstation lighting guidance for glare and reflections." },
    ],
    sections: [
      { heading: "Put light near the camera path", body: "The camera needs the face lit, not just the room. Start with a small light near or above the camera and reduce strong backlight from windows." },
      { heading: "Check glasses and glossy screens", body: "If the light appears as a white spot in glasses or the monitor, lower brightness, move it sideways, or raise the angle until the reflection leaves the camera view." },
      { heading: "Separate call lighting from task lighting", body: "A monitor bar can make typing easier while a camera light makes the face clearer. Some desks need both, but each solves a different job." },
      { heading: "Save a repeatable meeting preset", body: "Use the same brightness, color temperature, camera height, and chair position for recurring calls so setup friction does not make the light go unused." },
    ],
  },
  {
    site: "homeoffice",
    slug: "standing-desk-wheels-pros-cons-small-spaces",
    title: "Standing Desk Wheels: Pros and Cons for Small Spaces",
    dek: "Decide whether casters help a compact standing desk or create wobble, cable risk, floor damage, and monitor-arm instability.",
    category: "desks",
    updatedAt,
    relatedProducts: ["ergear-48x24-electric-standing-desk", "flexispot-e7-mini-standing-desk"],
    relatedRoundups: ["best-standing-desks-for-small-spaces", "best-home-office-cable-management"],
    sources: [
      { name: "OSHA workstation desks guidance", url: "https://www.osha.gov/etools/computer-workstations/components/desks", note: "Primary desk and equipment-placement guidance." },
    ],
    sections: [
      { heading: "Wheels help only when the desk must move", body: "Casters can be useful in a multipurpose room, rental, or cleaning-heavy setup. If the desk stays in one place, stability usually matters more than mobility." },
      { heading: "Check lift stability at standing height", body: "A compact desk can feel stable when seated and still wobble when raised. Wheels add another movement point, especially with a monitor arm or heavy display." },
      { heading: "Plan cables before rolling", body: "Power, monitor, dock, light, and charger cables need slack and strain relief. Rolling a desk with tight cables can pull connectors or drag a power strip." },
      { heading: "Protect the floor and lock the position", body: "Use locking casters suited to the floor type, test chair clearance, and recheck level after moving. A desk that shifts during typing or calls is not a good trade." },
    ],
  },
  {
    site: "homeoffice",
    slug: "standing-desk-designs-for-small-spaces-guide",
    title: "Standing Desk Designs for Small Spaces",
    dek: "Compare narrow electric desks, wall-facing layouts, monitor arms, rolling setups, cable paths, and storage trade-offs for bedrooms and rentals.",
    category: "desks",
    updatedAt,
    relatedProducts: ["ergear-48x24-electric-standing-desk", "flexispot-e7-mini-standing-desk", "uplift-v3-standing-desk"],
    relatedRoundups: ["best-standing-desks-for-small-spaces", "best-monitor-arms-for-home-office"],
    sources: [
      { name: "OSHA workstation purchasing guide", url: "https://www.osha.gov/etools/computer-workstations/checklists/purchasing-guide", note: "Primary desk purchasing guidance for work surface and equipment fit." },
    ],
    sections: [
      { heading: "Design around depth first", body: "Many small desks are narrow and shallow. Protect monitor distance with an arm, laptop stand, or compact display before filling the width with accessories." },
      { heading: "Use the wall but do not trap the desk", body: "Wall-facing layouts save space, but height movement, monitor-arm clearance, outlets, baseboards, and cable trays still need room behind the desktop." },
      { heading: "Keep one clear conversion path", body: "If the room changes from bedroom to office each day, decide where the chair, walking pad, and cables go during each mode. A movable desk can help only when this path is planned." },
      { heading: "Avoid decorative storage until the core setup works", body: "Shelves, pegboards, risers, and trays can crowd a compact desk. Solve keyboard, mouse, monitor, light, and power first, then add storage for specific recurring items." },
    ],
  },
];
