import type { Guide, Product, Roundup } from "./types";

const updatedAt = "July 9, 2026";
const amazonUrl = (asin: string) => `https://www.amazon.com/dp/${asin}?tag=bingmada-20&linkCode=ll2&language=en_US&ref_=as_li_ss_tl`;
const amazonSource = (asin: string, note: string) => ({ name: `Amazon listing for ASIN ${asin}`, url: `https://www.amazon.com/dp/${asin}`, note });

export const networkPoeExpansionProducts: Product[] = [
  {
    site: "network",
    slug: "tp-link-tl-sg1005p-poe-switch",
    asin: "B076HZFY3F",
    amazonTitle: "TP-Link TL-SG1005P, 5 Port Gigabit PoE Switch, 4 PoE+ Ports @65W",
    seoTitle: "TP-Link TL-SG1005P Review: 5-Port PoE Switch Buying Notes",
    updatedAt,
    name: "TP-Link TL-SG1005P 5-Port Gigabit PoE Switch",
    brand: "TP-Link",
    category: "wired",
    image: "/images/affiliate/network-poe-switch-realistic.webp",
    summary: "A compact PoE+ switch guide for powering a few cameras, one access point, or a small smart-home wiring corner without buying managed features.",
    verdict: "TL-SG1005P is the clean starter PoE switch when four powered ports and a 65W budget are enough. It is not the right pick when VLANs, port monitoring, or more than four PoE devices are planned.",
    whyItMatters: "PoE switches are often bought by port count alone, but the real fit is powered-port count, per-port wattage, total power budget, and whether camera/AP isolation needs management.",
    bestFor: "Small camera or access-point installs needing four PoE+ ports",
    priceBand: "$",
    rating: 4.6,
    scores: [
      { label: "Starter value", value: 9 },
      { label: "PoE budget", value: 7 },
      { label: "Management features", value: 2 },
    ],
    pros: ["Four PoE+ gigabit ports plus one non-PoE gigabit port", "65W total PoE budget listed", "Fanless plug-and-play design"],
    cons: ["Only four powered ports", "No VLAN or port-monitoring interface", "Gigabit-only, so it is not a 2.5GbE AP uplink upgrade"],
    specs: {
      ASIN: "B076HZFY3F",
      Ports: "5x gigabit RJ45 total",
      "PoE ports": "4x PoE+ ports listed",
      "PoE budget": "65W total listed",
      Management: "Unmanaged",
      Cooling: "Fanless",
    },
    evidence: [
      "Amazon title verified as TP-Link TL-SG1005P 5 Port Gigabit PoE Switch",
      "Listing references 4 PoE+ ports, 30W per port, and 65W total budget",
      "Use it for a known four-device ceiling rather than a growing camera system",
      "Choose managed PoE when camera VLANs or AP isolation are required",
    ],
    editorialSections: [
      { heading: "Four PoE ports is the buying limit", body: "This is a small shelf switch. It is good when the buyer can name every powered device before checkout." },
      { heading: "Budget wattage, not just ports", body: "Four ports do not mean four maximum-power devices at once. Add the camera or access-point wattage and leave headroom for startup draw." },
      { heading: "Who should skip it", body: "Skip it for VLAN planning, eight-camera installs, 2.5GbE access points, or any network shelf likely to grow quickly." },
    ],
    alternatives: ["Choose TL-SG108PE when VLANs or monitoring matter.", "Choose NETGEAR GS308EPP when every port may need PoE+ and a larger power budget.", "Choose Reolink RLA-PS1 when the system is centered on Reolink cameras."],
    compareSlugs: ["tp-link-tl-sg108pe-poe-switch", "netgear-gs308epp-poe-switch", "reolink-rla-ps1-poe-switch"],
    sources: [
      { name: "TP-Link TL-SG1005P", url: "https://www.tp-link.com/us/business-networking/poe-switch/tl-sg1005p/", note: "Official model page and hardware family details." },
      amazonSource("B076HZFY3F", "Exact linked listing; confirm hardware version, 65W budget, seller, and included power adapter."),
    ],
    offers: [{ merchant: "Amazon US", url: amazonUrl("B076HZFY3F"), label: "Check TL-SG1005P price on Amazon", priceNote: "Confirm ASIN B076HZFY3F, hardware version, 4 PoE+ ports, 65W budget, and seller." }],
  },
  {
    site: "network",
    slug: "tp-link-tl-sg108pe-poe-switch",
    asin: "B01BW0AD1W",
    amazonTitle: "TP-Link TL-SG108PE V3, 8 Port Gigabit PoE Switch, Easy Smart Managed, 4 PoE+ Ports @64W",
    seoTitle: "TP-Link TL-SG108PE Review: Easy Smart PoE Switch Guide",
    updatedAt,
    name: "TP-Link TL-SG108PE 8-Port Easy Smart PoE Switch",
    brand: "TP-Link",
    category: "wired",
    image: "/images/affiliate/network-poe-switch-realistic.webp",
    summary: "An Easy Smart PoE switch guide for buyers who need four powered ports plus VLAN, QoS, IGMP, and basic traffic visibility on a small home network.",
    verdict: "TL-SG108PE is the better TP-Link pick when PoE and basic management matter together. It is less compelling if the buyer only needs unmanaged power or needs PoE on all eight ports.",
    whyItMatters: "Camera and access-point installs often need separation later. Easy Smart management can be the difference between a tidy camera VLAN and a flat network full of unmanaged devices.",
    bestFor: "Small PoE installs needing VLANs or basic switch management",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Management value", value: 8 },
      { label: "PoE flexibility", value: 7 },
      { label: "All-port PoE", value: 4 },
    ],
    pros: ["Eight gigabit ports with four PoE+ ports listed", "Easy Smart features include VLAN/QoS/IGMP-style management", "Fanless desktop or wall-mountable metal design"],
    cons: ["Only four of eight ports provide PoE", "64W budget needs checking against AP or camera draw", "Not a full Omada controller-managed switch"],
    specs: {
      ASIN: "B01BW0AD1W",
      Ports: "8x gigabit RJ45 total",
      "PoE ports": "4x PoE+ ports listed",
      "PoE budget": "64W total listed",
      Management: "Easy Smart managed",
      Features: "VLAN, QoS, IGMP, traffic monitoring listed",
    },
    evidence: [
      "Amazon title verified as TL-SG108PE V3 Easy Smart Managed 8 Port Gigabit PoE Switch",
      "Listing references 4 PoE+ ports, 64W budget, VLAN, QoS, and IGMP features",
      "Use it when camera/AP segmentation is planned but a rack switch is overkill",
      "Do not buy it expecting PoE on all eight ports",
    ],
    editorialSections: [
      { heading: "The management layer is the reason", body: "Compared with TL-SG1005P, this model adds enough management for basic segmentation and visibility without moving into a larger business switch." },
      { heading: "Four powered ports still limits growth", body: "Eight physical ports can hide the fact that only four are PoE. Count cameras, APs, and any powered bridges before comparing price." },
      { heading: "Who should skip it", body: "Skip it when every port may power a device, when Omada controller integration is required, or when 2.5GbE AP uplinks are the main goal." },
    ],
    alternatives: ["Choose TL-SG1005P for cheaper unmanaged PoE.", "Choose NETGEAR GS308EPP for PoE+ on all eight ports and a larger budget.", "Choose a 2.5GbE PoE switch for Wi-Fi 7 access points with multi-gig uplinks."],
    compareSlugs: ["tp-link-tl-sg1005p-poe-switch", "netgear-gs308epp-poe-switch", "trendnet-teg-s350-2-5g-switch"],
    sources: [
      { name: "TP-Link TL-SG108PE", url: "https://www.tp-link.com/us/business-networking/easy-smart-switch/tl-sg108pe/", note: "Official model page and Easy Smart switch family details." },
      amazonSource("B01BW0AD1W", "Exact linked listing; confirm V3, PoE budget, seller, and included power supply."),
    ],
    offers: [{ merchant: "Amazon US", url: amazonUrl("B01BW0AD1W"), label: "Check TL-SG108PE price on Amazon", priceNote: "Confirm ASIN B01BW0AD1W, V3 listing, 4 PoE+ ports, 64W budget, and seller." }],
  },
  {
    site: "network",
    slug: "netgear-gs308epp-poe-switch",
    asin: "B08MBF6JMQ",
    amazonTitle: "NETGEAR GS308EPP 8 Port PoE Gigabit Ethernet Easy Smart Managed Essentials Switch",
    seoTitle: "NETGEAR GS308EPP Review: 8-Port PoE+ Switch Buying Guide",
    updatedAt,
    name: "NETGEAR GS308EPP 8-Port PoE+ Easy Smart Switch",
    brand: "NETGEAR",
    category: "wired",
    image: "/images/affiliate/network-poe-switch-realistic.webp",
    summary: "A higher-budget 8-port PoE+ switch guide for buyers who want every port powered, a 123W budget, and small-business style management in a desktop or wall-mount box.",
    verdict: "GS308EPP is the stronger eight-device PoE choice when the buyer wants PoE+ on every port and enough budget for multiple cameras or APs.",
    whyItMatters: "A cheap four-port PoE switch can become a dead end after the fifth camera or second access point. All-port PoE reduces that growth trap.",
    bestFor: "Eight-port camera or access-point installs needing more PoE headroom",
    priceBand: "$$$",
    rating: 4.5,
    scores: [
      { label: "PoE headroom", value: 9 },
      { label: "All-port PoE", value: 9 },
      { label: "Budget fit", value: 6 },
    ],
    pros: ["Eight PoE+ ports listed", "123W total PoE budget listed", "Easy Smart managed essentials features for VLAN/QoS/monitoring"],
    cons: ["Costs more than four-port PoE switches", "Gigabit-only ports", "Buyers should confirm shipping availability and seller because Amazon availability can vary by location"],
    specs: {
      ASIN: "B08MBF6JMQ",
      Ports: "8x gigabit RJ45",
      "PoE ports": "8x PoE+ ports listed",
      "PoE budget": "123W total listed",
      Management: "Easy Smart Managed Essentials listed",
      Mounting: "Desktop or wall mount listed",
    },
    evidence: [
      "Amazon title verified as NETGEAR GS308EPP with 8 PoE+ ports and 123W budget",
      "Listing references VLAN, QoS, monitoring, and security controls",
      "Use it when all eight ports may eventually power cameras or access points",
      "Check location-specific availability before relying on this exact ASIN",
    ],
    editorialSections: [
      { heading: "All eight ports being PoE changes planning", body: "Instead of choosing which four devices get power, the buyer can plan a fuller camera or AP shelf and watch the total wattage budget." },
      { heading: "It is still gigabit-only", body: "This is not a multi-gig AP switch. If Wi-Fi 7 access points need 2.5GbE uplinks, shop a 2.5GbE PoE model instead." },
      { heading: "Who should skip it", body: "Skip it for one or two low-power devices, for 2.5GbE AP uplinks, or when a cheaper unmanaged four-port switch fully covers the plan." },
    ],
    alternatives: ["Choose TL-SG108PE for lower-cost Easy Smart management with four PoE ports.", "Choose TL-SG1005P for a small unmanaged install.", "Choose Reolink RLA-PS1 when the switch is mainly for a Reolink camera/NVR setup."],
    compareSlugs: ["tp-link-tl-sg108pe-poe-switch", "tp-link-tl-sg1005p-poe-switch", "reolink-rla-ps1-poe-switch"],
    sources: [amazonSource("B08MBF6JMQ", "Exact linked listing; confirm GS308EPP, 8 PoE+ ports, 123W budget, seller, and delivery availability.")],
    offers: [{ merchant: "Amazon US", url: amazonUrl("B08MBF6JMQ"), label: "Check GS308EPP price on Amazon", priceNote: "Confirm ASIN B08MBF6JMQ, GS308EPP model, 123W budget, seller, and delivery availability." }],
  },
  {
    site: "network",
    slug: "reolink-rla-ps1-poe-switch",
    asin: "B0BWHKQ5N9",
    amazonTitle: "REOLINK PoE Switch with 8 PoE and 2 Gigabit Uplink Ports, RLA-PS1",
    seoTitle: "Reolink RLA-PS1 Review: PoE Switch for Camera Systems",
    updatedAt,
    name: "Reolink RLA-PS1 PoE Switch",
    brand: "Reolink",
    category: "wired",
    image: "/images/affiliate/network-poe-switch-realistic.webp",
    summary: "A camera-first PoE switch guide for Reolink users comparing 8 PoE camera ports, 2 gigabit uplinks, a 120W budget, and NVR-centered wiring.",
    verdict: "RLA-PS1 is the camera-system pick when the buyer is already building around Reolink cameras or RLN36-style NVR wiring. It is less universal than a general managed PoE switch.",
    whyItMatters: "Camera PoE switches solve a different problem than desk switches: stable camera power, NVR uplinks, port priority, and simple wall-mount deployment often matter more than broad switch features.",
    bestFor: "Reolink PoE camera systems and NVR-centered installs",
    priceBand: "$$",
    rating: 4.4,
    scores: [
      { label: "Camera fit", value: 9 },
      { label: "General switch features", value: 5 },
      { label: "PoE budget", value: 8 },
    ],
    pros: ["Eight PoE camera ports plus two gigabit uplinks listed", "120W total PoE budget listed", "Designed around Reolink PoE camera and NVR workflows"],
    cons: ["PoE camera ports are listed as 10/100Mbps, while uplinks are gigabit", "Less flexible for VLAN-heavy general networking", "Best fit depends on staying inside Reolink camera/NVR assumptions"],
    specs: {
      ASIN: "B0BWHKQ5N9",
      Model: "RLA-PS1",
      "PoE ports": "8x 10/100Mbps PoE ports listed",
      Uplinks: "2x gigabit uplink ports listed",
      "PoE budget": "120W total listed",
      Standard: "IEEE 802.3af/at listed",
    },
    evidence: [
      "Amazon title verified as Reolink RLA-PS1 with 8 PoE and 2 gigabit uplink ports",
      "Listing references 120W total budget and compatibility with PoE IP cameras",
      "Use it for camera/NVR topology rather than a general office switch",
      "Confirm whether 10/100 camera ports are acceptable for the intended cameras",
    ],
    editorialSections: [
      { heading: "Camera topology first", body: "The product belongs in a camera plan: PoE cameras on powered ports, uplink to NVR/router, and power priority managed around cameras." },
      { heading: "The uplink split matters", body: "The listing describes 10/100 PoE ports and gigabit uplinks. That can be fine for many cameras but wrong for general high-speed wired clients." },
      { heading: "Who should skip it", body: "Skip it for access-point uplinks, NAS/desktop switching, VLAN-heavy networks, or non-camera devices that need full gigabit on every port." },
    ],
    alternatives: ["Choose NETGEAR GS308EPP for eight gigabit PoE+ ports.", "Choose TL-SG108PE for basic VLAN management.", "Choose TL-SG1005P for a tiny unmanaged PoE shelf."],
    compareSlugs: ["netgear-gs308epp-poe-switch", "tp-link-tl-sg108pe-poe-switch", "tp-link-tl-sg1005p-poe-switch"],
    sources: [
      { name: "Reolink RLA-PS1", url: "https://reolink.com/product/rla-ps1/", note: "Official product page availability and model context." },
      amazonSource("B0BWHKQ5N9", "Exact linked listing; confirm RLA-PS1 model, port speeds, PoE budget, seller, and NVR compatibility."),
    ],
    offers: [{ merchant: "Amazon US", url: amazonUrl("B0BWHKQ5N9"), label: "Check RLA-PS1 price on Amazon", priceNote: "Confirm ASIN B0BWHKQ5N9, RLA-PS1 model, port speeds, 120W budget, seller, and NVR fit." }],
  },
];

export const networkPoeExpansionRoundups: Roundup[] = [
  {
    site: "network",
    slug: "best-poe-switches-for-home-cameras-and-access-points",
    title: "Best PoE Switches for Home Cameras and Access Points",
    dek: "Compare TP-Link, NETGEAR, and Reolink PoE switches by powered-port count, total wattage, management, uplink speed, and camera/AP fit.",
    category: "wired",
    intent: "choose a PoE switch that powers cameras or access points without underbuying ports, watts, or management",
    intro: "PoE switch shopping should start with the devices that need power. Count powered ports, add wattage, decide whether VLANs matter, and only then compare price.",
    sections: [
      { heading: "Small installs can stay simple", body: "TL-SG1005P is enough when four powered ports and no management interface solve the shelf." },
      { heading: "Managed features help camera and AP networks", body: "TL-SG108PE and GS308EPP add useful visibility and segmentation options for camera or access-point networks." },
      { heading: "Camera-first switches are different", body: "Reolink RLA-PS1 fits Reolink camera/NVR layouts, but its port-speed assumptions should be checked before using it as a general switch." },
    ],
    decisionGuide: [
      { label: "Smallest shelf", detail: "Choose TP-Link TL-SG1005P for up to four PoE+ devices and a simple unmanaged setup." },
      { label: "Basic VLANs", detail: "Choose TP-Link TL-SG108PE when four PoE ports plus Easy Smart features are enough." },
      { label: "More PoE headroom", detail: "Choose NETGEAR GS308EPP when all eight ports may power devices and a 123W budget matters." },
      { label: "Reolink cameras", detail: "Choose Reolink RLA-PS1 when the camera/NVR system is already Reolink-centered." },
    ],
    methodology: ["Verified Amazon ASIN/title for each linked model", "Compared PoE port count, total wattage, management, and uplink limitations", "Prioritized camera/AP fit over raw switch size"],
    productSlugs: ["tp-link-tl-sg1005p-poe-switch", "tp-link-tl-sg108pe-poe-switch", "netgear-gs308epp-poe-switch", "reolink-rla-ps1-poe-switch"],
    faqs: [
      { question: "How many watts do I need for a PoE switch?", answer: "Add the maximum draw of every powered camera or access point and leave headroom. Per-port wattage and total switch budget both matter." },
      { question: "Do all switch ports provide PoE?", answer: "No. Some models have only four PoE ports even when the switch has five or eight total ports." },
      { question: "Do I need a managed PoE switch?", answer: "Use managed or Easy Smart features when cameras, APs, guest networks, or smart-home devices should be segmented or monitored." },
    ],
  },
  {
    site: "network",
    slug: "tp-link-tl-sg1005p-vs-tl-sg108pe-vs-netgear-gs308epp",
    title: "TP-Link TL-SG1005P vs TL-SG108PE vs NETGEAR GS308EPP",
    dek: "Compare three PoE switch paths: cheap unmanaged four-port PoE, Easy Smart four-port PoE, and all-port PoE+ with a larger power budget.",
    category: "wired",
    intent: "decide how much PoE switch to buy for cameras, access points, and small wired shelves",
    intro: "These three switches answer different versions of the same question: do you need only power, power plus basic management, or enough powered ports and watts for a fuller install?",
    sections: [
      { heading: "TL-SG1005P is the small default", body: "It keeps cost and setup low when four powered devices are enough and no VLAN controls are required." },
      { heading: "TL-SG108PE adds switch controls", body: "It is the middle pick when four PoE devices are enough but VLAN, QoS, IGMP, or monitoring should be available." },
      { heading: "GS308EPP is the headroom pick", body: "It costs more, but eight PoE+ ports and a 123W budget make growth easier." },
    ],
    decisionGuide: [
      { label: "Buy TL-SG1005P", detail: "You need a small unmanaged PoE switch for one to four devices." },
      { label: "Buy TL-SG108PE", detail: "You need basic managed features but still only four powered ports." },
      { label: "Buy GS308EPP", detail: "You expect more powered devices and want every port to support PoE+." },
    ],
    methodology: ["Compared exact Amazon-linked ASINs", "Separated total ports from powered ports", "Checked management features against camera/AP use cases"],
    productSlugs: ["tp-link-tl-sg1005p-poe-switch", "tp-link-tl-sg108pe-poe-switch", "netgear-gs308epp-poe-switch"],
    faqs: [
      { question: "Is the TL-SG108PE automatically better than TL-SG1005P?", answer: "Only if the extra ports and Easy Smart features matter. It still has four PoE ports, so it does not double powered-device capacity." },
      { question: "Why pay more for GS308EPP?", answer: "Because all eight ports can provide PoE+ and the listed total budget is much higher, which helps when the install may grow." },
    ],
  },
];

export const networkPoeExpansionGuides: Guide[] = [
  {
    site: "network",
    slug: "poe-switch-power-budget-calculator-guide",
    title: "PoE Switch Power Budget Calculator Guide",
    dek: "Before buying a PoE switch, add camera and access-point watts, check per-port limits, leave startup headroom, and decide which ports get priority.",
    category: "wired",
    updatedAt,
    relatedProducts: ["tp-link-tl-sg1005p-poe-switch", "tp-link-tl-sg108pe-poe-switch", "netgear-gs308epp-poe-switch", "reolink-rla-ps1-poe-switch"],
    relatedRoundups: ["best-poe-switches-for-home-cameras-and-access-points", "tp-link-tl-sg1005p-vs-tl-sg108pe-vs-netgear-gs308epp"],
    sections: [
      { heading: "Count powered devices separately", body: "Total switch ports and PoE ports are not the same. Write down every camera, access point, bridge, phone, or controller that needs power from Ethernet." },
      { heading: "Check per-port and total budget", body: "A switch can advertise 30W per port while still having a total budget that cannot run every port at max draw." },
      { heading: "Leave startup and cold-weather headroom", body: "Cameras with IR, PTZ motors, heaters, or long cable runs may draw more at certain times. Leave headroom rather than matching the budget exactly." },
      { heading: "Plan priority before an overload", body: "If the switch sheds lower-priority ports when the budget is exceeded, decide which cameras or APs should stay powered first." },
    ],
  },
  {
    site: "network",
    slug: "poe-vs-poe-plus-for-cameras-access-points",
    title: "PoE vs PoE+ for Cameras and Access Points",
    dek: "Understand 802.3af, 802.3at, per-port wattage, total switch budget, and when Wi-Fi access points need more than basic PoE.",
    category: "wired",
    updatedAt,
    relatedProducts: ["tp-link-tl-sg1005p-poe-switch", "tp-link-tl-sg108pe-poe-switch", "netgear-gs308epp-poe-switch"],
    relatedRoundups: ["best-poe-switches-for-home-cameras-and-access-points"],
    sections: [
      { heading: "PoE and PoE+ are power classes", body: "Basic PoE and PoE+ describe how much power can be delivered under supported standards. The endpoint and switch must agree on what is needed." },
      { heading: "Cameras vary widely", body: "Simple fixed cameras may be modest loads, while PTZ, heater, spotlight, or multi-sensor cameras can need more power." },
      { heading: "Access points can push the budget", body: "Modern Wi-Fi access points may need PoE+ or higher, and some also benefit from 2.5GbE uplinks. Check both power and data speed." },
      { heading: "Do not ignore cable and run length", body: "Poor cable, long runs, outdoor routing, or bad terminations can make a theoretically compatible PoE setup unreliable." },
    ],
  },
  {
    site: "network",
    slug: "managed-vs-unmanaged-poe-switch-home-guide",
    title: "Managed vs Unmanaged PoE Switch for Home Cameras",
    dek: "Use unmanaged PoE for simple power; choose Easy Smart or managed PoE when VLANs, camera isolation, monitoring, and port controls matter.",
    category: "wired",
    updatedAt,
    relatedProducts: ["tp-link-tl-sg1005p-poe-switch", "tp-link-tl-sg108pe-poe-switch", "netgear-gs308epp-poe-switch"],
    relatedRoundups: ["best-poe-switches-for-home-cameras-and-access-points", "best-wired-networking-upgrades"],
    sections: [
      { heading: "Unmanaged PoE is fine for a flat network", body: "If the goal is only to power a few devices and plug them into the same LAN, unmanaged PoE is simpler and cheaper." },
      { heading: "Managed PoE helps with isolation", body: "Cameras, guest Wi-Fi, smart-home devices, and access points often deserve VLAN or traffic controls. Easy Smart switches can be enough for basic segmentation." },
      { heading: "Monitoring can save troubleshooting time", body: "Port status, PoE draw, link speed, and error counters help diagnose a camera that drops offline or an AP that negotiates the wrong speed." },
      { heading: "Complexity has a cost", body: "Do not buy a managed switch if nobody will maintain VLANs, firmware, passwords, backups, or documentation." },
    ],
  },
];
