import type { Guide, Product, Roundup, Tool } from "./types";

const links = {
  deco: "https://www.amazon.com/dp/B0CN8QLS4K?_encoding=UTF8&th=1&linkCode=ll2&tag=bingmada-20&linkId=b7b75a3f16c9991d15ee7c37a26a8689&language=en_US&ref_=as_li_ss_tl",
  eero: "https://www.amazon.com/Amazon-eero-mesh-wifi-system/dp/B0FZCJ85L3?crid=1XA8RINJ2A45L&dib=eyJ2IjoiMSJ9.6kk8HBEnCb6rfXkcKtMbLZJOu3fSvaclSrfu6-7tRVq8Ipie_X5cZNTavtX05RQDzxq09YtwDDQRjjd4FGkRM8qFZq-F6Or8dUa_UAfVxM0WjSms717_wp_FExfsEuEsrpSrPeFh-Lb1HfCUwYdGtiRKwmF9dEcfplRnSPH3QaOb8neHNuEuF0Y4U8DaSbZTKKPFZCBfZG7UKQyiyxAYPbCcQxvWv3ZtEfwLkGr7490.r2tkDDSsKvyL0UtjqkgyBi9exP_KfUNuvFdMBoGuPqo&dib_tag=se&keywords=Amazon%2Beero%2B6%2B&qid=1782376089&sprefix=tp-link%2Bdeco%2Bxe75%2Bpro%2Caps%2C1013&sr=8-1&th=1&linkCode=ll2&tag=bingmada-20&linkId=1b35d10abee3792a841cd96c22e19527&language=en_US&ref_=as_li_ss_tl",
  orbi: "https://www.amazon.com/NETGEAR-Quad-Band-Satellite-Extenders-Internet/dp/B0CGJGXFCS?dib=eyJ2IjoiMSJ9.XDZJAElki-7g7FvjYUy3UWFILcRG8XZpN4_C5UeV8vNMgjB_oijcLjfAAzzAcahZOdMkhr5kLMp6Of5mrkkc1vjPx7GUNeZsbkp8OL9vYU3hIZqPmmc4E2Wz95o6c3lvZeKF9fa5-tXzKI5_5Tlq1j9PAdRWavgLtpQfwTEfcdP7Q8euv7zcKmFQVu54zdbfOfucRgJ3N1VUgYLpBKhS1f8EecWC65NZKfEkgga7RKc.1DzCvuqFi0A1XyPJvcZ3d4EOZ3A8h8RKQftwtojvxr4&dib_tag=se&keywords=NETGEAR%2BOrbi%2B750%2BSeries%2B%2F%2BRBK752&qid=1782376153&sr=8-1&th=1&linkCode=ll2&tag=bingmada-20&linkId=cc6f80b462cfc602d27465302c625821&language=en_US&ref_=as_li_ss_tl",
  be400: "https://www.amazon.com/TP-Link-Archer-Dual-Band-BE400-HomeShield/dp/B0DVBP5L6Y?crid=1ILMRQZT1G2HL&dib=eyJ2IjoiMSJ9.okkpX4ltsdNMqO6NU-UbzBCdBJ2fqJ1-7ITq3RKiq5gU6a4CdYQ4C7G0BlOqNdAbzjt6g1r6vhYJDfMa3J3suqYE_PEjJRO-2SKuT-_3aI22uP0Hu7lwiNGtogFVDsw9z4mOFaZybovF6JCCQBpMzYLvrd-XzeKDuzIFHr_iDseDDEsz3po9WKnMwm0j0w8oMeGG_dZmzGXlp7efIqIUiJbxSXq7RZjZak6DUFwIThQ.olt2_Rr1XEDNACvjespdNkS0OAnqcnCvroAo-as2e14&dib_tag=se&keywords=TP-Link%2BArcher%2BAX55&qid=1782376229&sprefix=netgear%2Borbi%2B750%2Bseries%2B%2F%2Brbk752%2Caps%2C1987&sr=8-1&th=1&linkCode=ll2&tag=bingmada-20&linkId=03bad2242557cdc89d8775d6c8f393a7&language=en_US&ref_=as_li_ss_tl",
  asus: "https://www.amazon.com/ASUS-RT-BE86U-Dual-Band-Subscription-Free-Comprehensive/dp/B0DGZZJ996?crid=2IKZ2CWXN5XAI&dib=eyJ2IjoiMSJ9.uYUdJ0qJV91ZQNkhXovpfLYa4y6gPl-kPk7yrrJeM5znuoeTnLwJ5OMg1d9hAEP1mrOElURt_wgjMnuV66OQj1wr3RueGAegYrO-KWlPHREs4mFoJf06LtYla2PWF0m6aMcK7hE1PHP_wXfbGlBxDsFXpm373CryjfEv2bWCLKzMwWVff-iJ3SV-0S6CCpan8mjBTeB9UiErciPEHsBIsYXgydcGnYqClGNu89n37Yc.2w-5OyF4WevQMjXnS7wV-lnmbajy81yzdxUcFS2W2lI&dib_tag=se&keywords=ASUS%2BRT-AX86U%2BPro&qid=1782376319&sprefix=tp-link%2Barcher%2Bax55%2Caps%2C978&sr=8-1&th=1&linkCode=ll2&tag=bingmada-20&linkId=49a63205972a96e4192fbc739ec4a908&language=en_US&ref_=as_li_ss_tl",
  beryl: "https://www.amazon.com/GL-iNet-GL-MT3000-Pocket-Sized-Wireless-Gigabit/dp/B0BPSGJN7T?crid=1G1N5NGC890CA&dib=eyJ2IjoiMSJ9.KRPEs162yJBDlko-G_3YKr_1NZE29EbE9I2Se5Y3TxDIZlmYErgc13cbMGU-xp0xazoEeApe2G8Qks4WgjCWGKM963E4xkowfoTIcG5FexE_GD7gPZT7k-L4pAf93r9m45jm2Fvl7y2coYR3uyXwFbVE0ao5r4-kYGh05lU2pK_1tcJKnfXTcVZDpt6_vkM-6Dp2IOTrYZrqcCrH1PsOaCLehiiNGzHj-am78U6vCzo.f_2dWJW09kvN7BudZdUD3Og-F_HSmG_1XsMaEAXrmlw&dib_tag=se&keywords=GL.iNet%2BGL-MT3000%2BBeryl%2BAX&qid=1782376355&sprefix=asus%2Brt-ax86u%2Bpro%2Caps%2C1278&sr=8-1&th=1&linkCode=ll2&tag=bingmada-20&linkId=a52da88cff9eb8c6d56af870524e0ce6&language=en_US&ref_=as_li_ss_tl",
  sg108: "https://www.amazon.com/TP-Link-Gigabit-Ethernet-Network-Switch/dp/B00A121WN6?crid=144LAIFNKDK64&dib=eyJ2IjoiMSJ9.Hv8K_Gll44fUpv3uCgpgINfGr1dl-PxfuXYKeaMWpMx-MKL24F_aeKdVaNsOxKof1JPver9lcVpfaDJMmtsCmC9g0G_6iA0OvUuruq6sbWNoaVfCqp9PjPY6g1ElRJk7H7RgLYo1zsGeWvi4lCnFr00F228Jeq8YWl9bAba-8eFuVPeqvvpfwIyVe52nVt8BDmh4VlFuYMhFH172eyI239wYcnH9EEzrwWZyYW--IA8.5-XfipT3sDXeB-UoSv9Mz4AtbxrunL0-RCgISrcvDCo&dib_tag=se&keywords=TP-Link%2BTL-SG108&qid=1782376395&sprefix=gl.inet%2Bgl-mt3000%2Bberyl%2Bax%2Caps%2C928&sr=8-1&th=1&linkCode=ll2&tag=bingmada-20&linkId=ff4ab3adcd93c8584e56a80ff901b9ab&language=en_US&ref_=as_li_ss_tl",
  gs308e: "https://www.amazon.com/NETGEAR-8-Port-Gigabit-Ethernet-Switch/dp/B0D9W9YNWD?dib=eyJ2IjoiMSJ9.7ODCNx22dJNzPZdWielg0jSa5dK5hhFC9fLUQNnpPfknR87Ztd7TTWev3L_X-cnN4JGiou-j7eiWgjw-karhDFhBe19n9AJkdXxhmP8u5GGk0fvzZTE3jG3h0bHQegU4yH54BJqQD9hJOqEtIV3cCx7oIvWtMHlcj9iURGP5zoSz5YZq7tQmqO0VDgMfE182xNRgqTy-2ra-G0xk-MmFP9_bIDpXA_im_9YD1Plci7w.o39A3-21SmTW_69srfhbYbCMX7hNIkKet_5mVPaSScY&dib_tag=se&keywords=NETGEAR%2BGS308&qid=1782376447&sr=8-1&th=1&linkCode=ll2&tag=bingmada-20&linkId=361fb450074d1a5a41b214192ef0eb8e&language=en_US&ref_=as_li_ss_tl",
  jadaol: "https://www.amazon.com/Jadaol-Ethernet-High-Speed-Internet-Streaming/dp/B00WD017GQ?crid=3MKTT3A4G7T3R&dib=eyJ2IjoiMSJ9.Hh6NJ6Ids09d07FKqKJbixbvyMiKiB3hm5FoarpRdTKeE5ztzRu3TkSKTC1RXYztSjAUFxLQaYSj_OmS5cUfVZbfYO2uE03ls6KcnGu8PIxiYOnL9-Cxj8h3KDnEtqhery89yFhzTpIwieTRYsUG3N9hfxSF3zPvoRReokhPGhdTJtlahrngTpmjKUe8JHB6ViBavTP33VaH5aN4DSe2dEK-ZWgwCzXL69UHhhoMwp8.NX8liGhqSv1ZU3KEE3CUR320pH_TdOQS2Ay70A2Gqvg&dib_tag=se&keywords=Cable%2BMatters%2BCat%2B6%2BEthernet%2BCable&qid=1782376494&sprefix=netgear%2Bgs308%2Caps%2C1307&sr=8-1&th=1&linkCode=ll2&tag=bingmada-20&linkId=db90af78777b92f51f5d5f8efba1cd39&language=en_US&ref_=as_li_ss_tl",
  monoprice: "https://www.amazon.com/Monoprice-SlimRun-Cat6A-Ethernet-Patch/dp/B01BGV2YP0?dib=eyJ2IjoiMSJ9.cF3HQHQ4_8mhmcMRXmR-ry2YMXMrQeS1PSG7kVoR-Vy8WQe5bbP3Pa35vI-rHGiBUBqzBFOYqPbBnjafskZgZsKycDPsq2UUcXsL9B27eyaDU8lV5BGmXAMU-YBZVW11dSB5f5vTEkfnET1GnNcu9WilHDySDSkGSJ9rnxkMx2qPQ0AT40DjlpgQtEfCgXiPzLcKwHectDfqb4Y0VkN9q7H9phmOoa7bnEbrgqpKwYU.WxX6bXBLt5LScVcZa4Kl6mEcKDaFZrJK5F1OQHDjgZY&dib_tag=se&keywords=Monoprice%2BCat6A%2BEthernet%2BCable&qid=1782376531&sr=8-1&th=1&linkCode=ll2&tag=bingmada-20&linkId=01124a5b12ac51c49d64951ec938a5f6&language=en_US&ref_=as_li_ss_tl",
  ugreen: "https://www.amazon.com/UGREEN-Ethernet-Delivery-Compatible-Chromebook/dp/B0BW2TLQ8S?dib=eyJ2IjoiMSJ9.a9XujlHZit9up3oMeDdq8ZrilN5pL6zaHU9ittIMI2dz_xu5EwkN6Al0aoBKRVU96SAx7nYK5l7FSFAhHAXJ77EpoQubX_lZOdengVBxIXJ-qhOMR5H5ofGqQby0ove_IezDAeEOxIs-7vnazYJ3FEEcIn49OF6uzBUaA2YG0WqfEbA2Z_Fk6zGrSiBHJvZCnfxGUM4yY3I7MdomX0dO0akoFNmj_1Vi3JER7gWnMkM.zZpzDRwCWRQXzgeVz28GqpGl9iAgw01qbOZVKyejrXc&dib_tag=se&keywords=Anker+USB-C+to+Ethernet+Adapter&qid=1782376569&sr=8-1&linkCode=ll2&tag=bingmada-20&linkId=0b087ba99c4427001f31fd9a2567ad7b&language=en_US&ref_=as_li_ss_tl",
  apc: "https://www.amazon.com/APC-Battery-Protector-Back-UPS-Uninterruptible/dp/B08SH8B7MT?crid=PDLO7LHKMHEJ&dib=eyJ2IjoiMSJ9.O4NdwAUSzXkvqZS-PCKYc2j7epY0gfcm2Em06Wm0d3PnRmgqruWVOJF7tcYN8EohcEqB9syhdcgDii2kAllRdRW7LDfPHgCoJl77EcvKK6TMTRTD0dSC40W9rMlFQm8K65v0l5iqVvSEIPD1tUrTR18cnWkXHT0wnysKOZFjnSbulxQGXbrLmN5Es7b0vmp77DwxxSpG21H38XPsi2OJga15jor68kWN6Hs_LB6EblY.iRxBuMjLzwTiTidj2uIn-CBy6K1cJQ3RC2jUxCOjCWA&dib_tag=se&keywords=APC+BE600M1+%2F+APC+Back-UPS+600VA&qid=1782376632&sprefix=anker+usb-c+to+ethernet+adapter%2Caps%2C976&sr=8-1&linkCode=ll2&tag=bingmada-20&linkId=5df28d176b5b98a728876aa23e217b70&language=en_US&ref_=as_li_ss_tl",
};

function offer(url: string) {
  return [{ merchant: "Amazon US", url, label: "Check price on Amazon", priceNote: "Check live price and availability on Amazon." }];
}

export const networkProducts: Product[] = [
  {
    site: "network",
    slug: "tp-link-deco-be63-wifi-7-mesh",
    seoTitle: "TP-Link Deco BE63 Buying Guide: Wi-Fi 7, 2.5G Ports & Backhaul",
    updatedAt: "June 28, 2026",
    name: "TP-Link Deco BE63 Wi-Fi 7 Mesh System",
    brand: "TP-Link",
    category: "wifi",
    image: "/images/affiliate/network-tp-link-deco-be63-wifi-7-mesh.webp",
    summary: "A research-based buying guide to the tri-band Deco BE63, including its Wi-Fi 7 radios, four 2.5Gbps ports per unit, wired-backhaul options, and the homes where a simpler router may be enough.",
    verdict: "The Deco BE63 is worth shortlisting when you need mesh coverage and can use its multi-gig ports or Ethernet backhaul. A small home with a modest internet plan may get the same practical result from a cheaper Wi-Fi 6 mesh kit or one well-placed router.",
    whyItMatters: "Mesh speed claims only matter when coverage, node placement, and backhaul are realistic. Multi-gig ports are especially useful if your modem, office, or switch can use them.",
    bestFor: "Wi-Fi 7 mesh with 2.5G wired backhaul",
    priceBand: "$$$",
    rating: 4.6,
    scores: [{ label: "Coverage", value: 9 }, { label: "Wired backhaul", value: 9 }, { label: "Value discipline", value: 8 }],
    pros: ["Tri-band BE10000 Wi-Fi 7 platform", "Four auto-sensing 2.5Gbps WAN/LAN ports on each unit", "Supports Ethernet backhaul and router or access-point mode"],
    cons: ["Overkill for small homes with modest internet plans", "Older client devices cannot use the newest Wi-Fi 7 features", "Real coverage and speed still depend on layout, interference, clients, and backhaul"],
    specs: {
      "Product type": "Tri-band Wi-Fi 7 mesh system",
      "Listed Wi-Fi class": "BE10000",
      "Listed radio rates": "6GHz 5188Mbps; 5GHz 4324Mbps; 2.4GHz 574Mbps",
      Ports: "4x 2.5Gbps WAN/LAN auto-sensing ports per unit",
      USB: "1x USB 3.0 port per unit",
      Modes: "Router and access point",
      Backhaul: "Wireless, Ethernet, or combined",
    },
    evidence: ["Confirm whether the Amazon listing is a 1-, 2-, or 3-pack", "Check whether the modem, switches, cabling, and wired clients can use 2.5Gbps", "Plan node locations and any Ethernet path before relying on coverage claims", "Complete initial mesh setup before connecting Ethernet backhaul, following TP-Link's instructions"],
    editorialSections: [
      {
        heading: "The hardware facts that matter",
        body: "TP-Link lists the Deco BE63 as a tri-band BE10000 system with 6GHz, 5GHz, and 2.4GHz radios. Each unit has four auto-sensing 2.5Gbps WAN/LAN ports and one USB 3.0 port. Those ports are the most practical reason to pay more: they can serve a multi-gig modem, wired backhaul, a switch, or a fast local device without forcing every connection through one shared gigabit port.",
      },
      {
        heading: "Fit for an apartment or smaller home",
        body: "Start with placement before buying extra nodes. In a compact single-floor space, one centrally positioned router—or a cheaper two-node Wi-Fi 6 kit—may solve the same problem with less cost and fewer boxes. The BE63 makes more sense when the modem is stuck at one end of the home, walls create measured weak zones, or several wired devices need 2.5Gbps ports.",
      },
      {
        heading: "Fit for a multi-floor home",
        body: "A node on each floor can shorten the path to nearby clients, but a wireless node still needs a strong upstream connection. Place it between the main unit and the weak area rather than inside the dead zone. Dense floors, masonry, appliances, and an inconvenient modem location can make Ethernet backhaul more valuable than adding another wireless node.",
      },
      {
        heading: "How wired backhaul changes the decision",
        body: "TP-Link says Deco units should first be set up wirelessly in the app and can then be connected by Ethernet. Mixed wired and wireless nodes are supported, while the allowed switch topology differs between router and access-point mode. The four 2.5Gbps ports per unit make the BE63 unusually flexible, but switches, cables, and the rest of the path must also support the speed you expect.",
      },
      {
        heading: "Who should skip the Deco BE63",
        body: "Skip it when one good router already covers the home, the internet plan is comfortably below gigabit, most important devices are older Wi-Fi 5 or Wi-Fi 6 clients, or there is no real need for multi-gig wired ports. Paying for a newer wireless class does not repair poor placement or make older clients use Wi-Fi 7 features.",
      },
    ],
    alternatives: ["Compare eero 6 when lower cost and a simple app-led setup matter more than Wi-Fi 7 or multi-gig ports.", "Compare TP-Link BE400 when one router can cover the home and mesh nodes would add unnecessary cost."],
    compareSlugs: ["amazon-eero-6-mesh-wifi-system", "tp-link-be400-wifi-7-router"],
    sources: [
      {
        name: "TP-Link Deco BE63 product specifications",
        url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be63/",
        note: "Official radio, port, operating-mode, Wi-Fi 7, and backhaul specifications.",
      },
      {
        name: "TP-Link Ethernet Backhaul FAQ",
        url: "https://www.tp-link.com/us/support/faq/1794/",
        note: "Official setup order, topology, mixed-backhaul, and switch guidance.",
      },
    ],
    offers: offer(links.deco),
  },
  {
    site: "network",
    slug: "amazon-eero-6-mesh-wifi-system",
    name: "Amazon eero 6 Mesh Wi-Fi System",
    brand: "Amazon eero",
    category: "wifi",
    image: "/images/affiliate/network-amazon-eero-6-mesh-wifi-system.webp",
    summary: "A simple 3-pack mesh Wi-Fi system for households that value easy setup and broad coverage over advanced network tuning.",
    verdict: "Amazon eero 6 is the simplicity pick: it makes the most sense when setup ease, app guidance, and enough coverage matter more than multi-gig ports or Wi-Fi 7 features.",
    whyItMatters: "Many homes need calmer coverage, not the fastest possible router. A simpler mesh kit can be the right buy if the bottleneck is dead zones and setup friction.",
    bestFor: "Simple mesh coverage for everyday homes",
    priceBand: "$$",
    rating: 4.4,
    scores: [{ label: "Setup ease", value: 9 }, { label: "Everyday coverage", value: 8 }, { label: "Advanced controls", value: 5 }],
    pros: ["Easy app-led setup", "Good fit for non-technical households", "3-pack format suits common multi-room layouts"],
    cons: ["Not the choice for multi-gig wired networking", "Some advanced features may depend on ecosystem or subscription decisions"],
    specs: { "Product type": "Mesh Wi-Fi system", "Listed coverage": "Up to 4,500 sq. ft.", "Listed devices": "75+ devices", "Use case": "Simple whole-home Wi-Fi" },
    evidence: ["Confirm whether the listing is eero 6 or another eero generation", "Check whether your internet speed needs exceed the listed capability", "Review app, account, and optional subscription features before buying"],
    alternatives: ["Choose Deco BE63 for Wi-Fi 7 and multi-gig ports.", "Choose a single router if one good placement covers the home."],
    offers: offer(links.eero),
  },
  {
    site: "network",
    slug: "netgear-orbi-970-wifi-7-mesh",
    name: "NETGEAR Orbi 970 Series Wi-Fi 7 Mesh System",
    brand: "NETGEAR",
    category: "wifi",
    image: "/images/affiliate/network-netgear-orbi-970-wifi-7-mesh.webp",
    summary: "A premium quad-band Wi-Fi 7 mesh system for very large homes, heavy device counts, and multi-gig internet setups.",
    verdict: "Orbi 970 is the premium ceiling pick. It is hard to justify for ordinary apartments, but it belongs on the shortlist for large homes that want maximum mesh capacity.",
    whyItMatters: "High-end mesh is expensive because it tries to solve coverage, backhaul, and device density at once. That only pays off when the home is large enough to need it.",
    bestFor: "Large homes with premium Wi-Fi 7 budgets",
    priceBand: "$$$$",
    rating: 4.5,
    scores: [{ label: "Premium coverage", value: 10 }, { label: "Device capacity", value: 9 }, { label: "Value discipline", value: 5 }],
    pros: ["Quad-band Wi-Fi 7 design", "Listed for very large coverage and high device counts", "10G internet port fits premium network plans"],
    cons: ["Very expensive for normal homes", "Needs careful placement and compatible gear to justify the cost"],
    specs: { "Product type": "Premium Wi-Fi 7 mesh", "Listed speed": "Up to 27Gbps", "Listed coverage": "Up to 10,000 sq. ft.", "Listed devices": "Up to 200 devices" },
    evidence: ["Confirm the exact RBE973S router and satellite bundle", "Check whether your internet and wired network can use 10G", "Compare the return path because premium mesh fit is layout-dependent"],
    alternatives: ["Choose Deco BE63 for Wi-Fi 7 at a more restrained budget.", "Choose eero 6 for simpler everyday coverage."],
    offers: offer(links.orbi),
  },
  {
    site: "network",
    slug: "tp-link-be400-wifi-7-router",
    name: "TP-Link BE400 Wi-Fi 7 Router",
    brand: "TP-Link",
    category: "wifi",
    image: "/images/affiliate/network-tp-link-be400-wifi-7-router.webp",
    summary: "A dual-band Wi-Fi 7 router for homes that want a single-router upgrade with 2.5Gbps ports and modern wireless support.",
    verdict: "TP-Link BE400 is the practical single-router Wi-Fi 7 option when mesh is unnecessary but a newer router and faster wired ports are attractive.",
    whyItMatters: "A single router can beat a mesh kit when it is placed well. The key is whether the home layout can be covered from one central location.",
    bestFor: "Single-router Wi-Fi 7 upgrades",
    priceBand: "$$",
    rating: 4.4,
    scores: [{ label: "Router value", value: 8 }, { label: "Port flexibility", value: 8 }, { label: "Large-home coverage", value: 6 }],
    pros: ["Wi-Fi 7 without buying a mesh kit", "Dual 2.5Gbps ports help modern modem and wired paths", "Good fit for apartments and smaller homes"],
    cons: ["Dual-band design is less expansive than premium tri-band systems", "May not solve distant rooms without better placement or mesh"],
    specs: { "Product type": "Wi-Fi 7 router", "Listed speed class": "BE6500", Ports: "Dual 2.5Gbps ports", "Listed coverage": "Up to 2,400 sq. ft." },
    evidence: ["Check router placement before choosing single-router coverage", "Confirm whether your internet plan or wired devices need 2.5Gbps", "Compare HomeShield and security features before relying on them"],
    alternatives: ["Choose Deco BE63 if you need mesh coverage.", "Choose ASUS RT-BE86U if gaming and a 10G port matter more."],
    offers: offer(links.be400),
  },
  {
    site: "network",
    slug: "asus-rt-be86u-wifi-7-gaming-router",
    name: "ASUS RT-BE86U Wi-Fi 7 Gaming Router",
    brand: "ASUS",
    category: "wifi",
    image: "/images/affiliate/network-asus-rt-be86u-wifi-7-gaming-router.webp",
    summary: "A Wi-Fi 7 gaming router with a 10G port for users who want stronger wired options, VPN support, and advanced controls.",
    verdict: "ASUS RT-BE86U is the enthusiast single-router pick when gaming, wired speed, VPN features, and more control matter more than plug-and-play simplicity.",
    whyItMatters: "Gaming routers should be judged by latency paths, wired ports, firmware controls, and placement, not only antenna styling.",
    bestFor: "Gaming and advanced single-router setups",
    priceBand: "$$$",
    rating: 4.5,
    scores: [{ label: "Advanced controls", value: 9 }, { label: "Wired speed", value: 9 }, { label: "Beginner simplicity", value: 6 }],
    pros: ["10G port for premium wired paths", "Mesh and VPN compatible features listed", "Good fit for gamers and home-lab-adjacent users"],
    cons: ["More router than many homes need", "Single-router coverage still depends on placement"],
    specs: { "Product type": "Wi-Fi 7 gaming router", "Listed speed": "Up to 6.8Gbps", Ports: "10G port listed", "Use case": "Gaming, VPN, advanced controls" },
    evidence: ["Check firmware features you actually need before paying for them", "Confirm whether a single router can cover the home", "Plan wired paths for gaming PCs or consoles where possible"],
    alternatives: ["Choose TP-Link BE400 for a simpler Wi-Fi 7 router.", "Choose Deco BE63 if coverage matters more than advanced controls."],
    offers: offer(links.asus),
  },
  {
    site: "network",
    slug: "glinet-beryl-ax-travel-router",
    name: "GL.iNet GL-MT3000 Beryl AX Travel Router",
    brand: "GL.iNet",
    category: "wifi",
    image: "/images/affiliate/network-glinet-beryl-ax-travel-router.webp",
    summary: "A portable Wi-Fi 6 travel router for hotels, rentals, RVs, cruises, VPN workflows, and remote-work travel kits.",
    verdict: "Beryl AX is the travel router pick for people who want a controlled network on the road instead of connecting every device directly to public Wi-Fi.",
    whyItMatters: "Travel routers solve a different problem than home routers: repeatable setup, VPN routing, captive portals, and keeping personal devices behind one small box.",
    bestFor: "Travel VPN and portable Wi-Fi setups",
    priceBand: "$$",
    rating: 4.6,
    scores: [{ label: "Travel utility", value: 9 }, { label: "VPN workflow", value: 9 }, { label: "Whole-home fit", value: 4 }],
    pros: ["Pocket Wi-Fi 6 travel router format", "2.5G port listed for flexible wired use", "Useful for hotels, rentals, RVs, and business travel"],
    cons: ["Not intended to replace a full home mesh system", "Captive portal behavior can still vary by venue"],
    specs: { "Product type": "Travel router", Wireless: "Wi-Fi 6", Ports: "2.5G router listed", "Use case": "Travel, VPN, public networks" },
    evidence: ["Check VPN protocol support against your provider", "Confirm power, port, and tethering needs for your travel kit", "Test captive portal behavior before relying on it for work trips"],
    alternatives: ["Choose a home router if the device will stay in one house.", "Use a USB-C Ethernet hub if the main need is one wired laptop."],
    offers: offer(links.beryl),
  },
  {
    site: "network",
    slug: "tp-link-tl-sg108-gigabit-switch",
    name: "TP-Link TL-SG108 8-Port Gigabit Switch",
    brand: "TP-Link",
    category: "wired",
    image: "/images/affiliate/network-tp-link-tl-sg108-gigabit-switch.webp",
    summary: "A simple unmanaged 8-port gigabit switch for adding wired ports to a TV stand, office desk, router shelf, or small network cabinet.",
    verdict: "TL-SG108 is the basic switch to start with when you need more Ethernet ports and do not need management features.",
    whyItMatters: "A small switch can make the network feel better than a router upgrade if the real problem is too few wired ports near important devices.",
    bestFor: "Simple wired port expansion",
    priceBand: "$",
    rating: 4.7,
    scores: [{ label: "Simplicity", value: 10 }, { label: "Port count", value: 8 }, { label: "Advanced features", value: 3 }],
    pros: ["Plug-and-play unmanaged design", "Fanless metal housing listed", "Good fit for consoles, TVs, printers, and desktops"],
    cons: ["Gigabit only", "No smart management features for VLAN-style setups"],
    specs: { "Product type": "8-port Ethernet switch", Speed: "Gigabit", Design: "Unmanaged, fanless", "Use case": "Wired expansion" },
    evidence: ["Count ports with two spares before buying", "Confirm whether gigabit is enough for NAS or multi-gig internet", "Use quality patch cables and avoid hiding the switch where heat builds up"],
    alternatives: ["Choose NETGEAR GS308E if you want easy smart management features.", "Choose a 2.5G switch if your wired devices exceed gigabit."],
    offers: offer(links.sg108),
  },
  {
    site: "network",
    slug: "netgear-gs308e-gigabit-switch",
    name: "NETGEAR GS308E 8-Port Gigabit Switch",
    brand: "NETGEAR",
    category: "wired",
    image: "/images/affiliate/network-netgear-gs308e-gigabit-switch.webp",
    summary: "An 8-port easy smart gigabit switch for users who want simple wired expansion with a little more control than an unmanaged switch.",
    verdict: "NETGEAR GS308E is the small step-up switch when you want quiet operation and basic smart-switch options without building a full network rack.",
    whyItMatters: "Smart features are only useful if you know why you need them. For many homes, they are a bonus rather than the reason to buy.",
    bestFor: "Quiet smart-ish wired expansion",
    priceBand: "$",
    rating: 4.5,
    scores: [{ label: "Wired expansion", value: 8 }, { label: "Smart features", value: 7 }, { label: "Multi-gig readiness", value: 3 }],
    pros: ["8-port desktop or wall-mount format", "Easy smart managed essentials listing", "Silent operation suits home offices"],
    cons: ["Still gigabit class", "More control than some homes need"],
    specs: { "Product type": "Easy smart gigabit switch", Speed: "Gigabit", Ports: "8", "Use case": "Home network hub" },
    evidence: ["Confirm GS308E rather than unmanaged GS308 if smart features matter", "Check port count against future wired devices", "Use only the management options you understand"],
    alternatives: ["Choose TP-Link TL-SG108 for simpler plug-and-play use.", "Choose a multi-gig switch for NAS or 2.5G office paths."],
    offers: offer(links.gs308e),
  },
  {
    site: "network",
    slug: "jadaol-cat6-flat-ethernet-cable",
    name: "Jadaol Cat 6 Flat Ethernet Cable",
    brand: "Jadaol",
    category: "wired",
    image: "/images/affiliate/network-jadaol-cat6-flat-ethernet-cable.webp",
    summary: "A flat Cat 6 Ethernet cable for routing wired internet along walls, under trim, or across rooms where a round cable is awkward.",
    verdict: "Jadaol Cat 6 is the practical cable pick when the problem is route shape and length, not building a permanent in-wall cable plant.",
    whyItMatters: "Ethernet cables are boring until the wrong shape blocks the route. Flat cables can be easier to place, but should still be checked for length and realistic speed needs.",
    bestFor: "Flat room-to-room Ethernet runs",
    priceBand: "$",
    rating: 4.4,
    scores: [{ label: "Routing convenience", value: 9 }, { label: "Everyday speed fit", value: 8 }, { label: "Permanent install fit", value: 5 }],
    pros: ["Flat cable can route more easily along walls or under edges", "Useful for routers, switches, consoles, PCs, and streaming devices", "Good inexpensive wired stability upgrade"],
    cons: ["Not the first choice for permanent in-wall installation", "Check exact length and category claims before buying"],
    specs: { "Product type": "Cat 6 Ethernet cable", Length: "50 ft listing", Connector: "RJ45", "Use case": "Room routing and device wiring" },
    evidence: ["Measure the route with slack before buying", "Avoid tight bends, door pinch points, and high-traffic floor paths", "Use Cat6A or better for longer future-proof multi-gig planning"],
    alternatives: ["Choose Monoprice Cat6A for short high-spec patch runs.", "Use a switch if the issue is multiple devices at one location."],
    offers: offer(links.jadaol),
  },
  {
    site: "network",
    slug: "monoprice-slimrun-cat6a-ethernet-patch-cable",
    name: "Monoprice SlimRun Cat6A Ethernet Patch Cable",
    brand: "Monoprice",
    category: "wired",
    image: "/images/affiliate/network-monoprice-slimrun-cat6a-ethernet-patch-cable.webp",
    summary: "A slim Cat6A patch cable pack for short network cabinet, switch, router, and desk runs where cleaner cable bundles matter.",
    verdict: "Monoprice SlimRun Cat6A is a tidy patch-cable pick for short high-spec runs, especially when a network shelf or desk has too many thick cables.",
    whyItMatters: "Short patch cables shape whether a network shelf stays serviceable. Slim cables can reduce clutter, but should be matched to the run and bend needs.",
    bestFor: "Short Cat6A patch runs and cleaner bundles",
    priceBand: "$",
    rating: 4.5,
    scores: [{ label: "Cable management", value: 9 }, { label: "Short-run spec", value: 9 }, { label: "Long-route flexibility", value: 4 }],
    pros: ["Cat6A patch cable spec", "SlimRun format helps dense switch and router areas", "10-pack suits network shelves and multi-device desks"],
    cons: ["5-foot patch length is not for room-to-room routing", "Slim cables should be handled without harsh bends"],
    specs: { "Product type": "Cat6A Ethernet patch cable", Length: "5 ft", Pack: "10-pack listing", "Use case": "Switch, router, and desk patching" },
    evidence: ["Confirm length and pack count before buying", "Use for patching rather than long floor runs", "Check whether slim cable gauge matches your durability expectations"],
    alternatives: ["Choose Jadaol flat Cat6 for longer room routing.", "Choose standard round cable for rougher handling or permanent paths."],
    offers: offer(links.monoprice),
  },
  {
    site: "network",
    slug: "ugreen-revodok-usb-c-gigabit-ethernet-hub",
    name: "UGREEN Revodok USB-C Gigabit Ethernet Hub",
    brand: "UGREEN",
    category: "wired",
    image: "/images/affiliate/network-ugreen-revodok-usb-c-gigabit-ethernet-hub.webp",
    summary: "A USB-C hub with gigabit Ethernet, HDMI, charging passthrough, and USB-A ports for laptops that need one practical desk adapter.",
    verdict: "UGREEN Revodok is the laptop adapter pick when Ethernet is part of a broader desk setup with HDMI, charging, and USB accessories.",
    whyItMatters: "A single Ethernet dongle is cleaner for one job, but a hub can reduce daily friction if the laptop also needs display, power, and USB ports.",
    bestFor: "Laptop Ethernet plus desk hub needs",
    priceBand: "$",
    rating: 4.4,
    scores: [{ label: "Port mix", value: 8 }, { label: "Laptop desk fit", value: 8 }, { label: "Network specialization", value: 6 }],
    pros: ["Gigabit Ethernet plus HDMI and USB ports", "100W PD charging listed", "Useful for MacBook, iPad, Steam Deck, and USB-C laptop desks"],
    cons: ["More hub than needed if you only want Ethernet", "Display and charging compatibility should be checked per device"],
    specs: { "Product type": "USB-C hub with Ethernet", Ethernet: "Gigabit", Charging: "100W PD listed", "Use case": "Laptop desk connectivity" },
    evidence: ["Confirm your laptop supports the display mode you need", "Check charging passthrough against your power adapter", "Use wired Ethernet for calls or downloads where Wi-Fi is unreliable"],
    alternatives: ["Choose a simple USB-C Ethernet adapter if you do not need HDMI or USB-A.", "Choose a full docking station for multiple displays and permanent desks."],
    offers: offer(links.ugreen),
  },
  {
    site: "network",
    slug: "apc-back-ups-router-modem-bundle",
    name: "APC Back-UPS Router and Modem Backup Bundle",
    brand: "APC",
    category: "backup",
    image: "/images/affiliate/network-apc-back-ups-router-modem-bundle.webp",
    summary: "A battery backup bundle for keeping router, modem, ONT, and small network devices online during short power interruptions.",
    verdict: "APC Back-UPS is the network resilience pick when your home loses power briefly and you want the internet path to survive the interruption.",
    whyItMatters: "A router UPS only helps if the modem or ONT and ISP path also stay online. The right setup starts by plugging in the whole network chain, not just the router.",
    bestFor: "Router, modem, and ONT backup power",
    priceBand: "$$",
    rating: 4.5,
    scores: [{ label: "Outage resilience", value: 8 }, { label: "Outlet usefulness", value: 8 }, { label: "Network-specific fit", value: 6 }],
    pros: ["Bundle includes 850VA and 600VA units in the listing", "Useful for router, modem, ONT, and USB charging needs", "Recognizable UPS brand for home networks"],
    cons: ["Runtime depends on actual watt load and battery condition", "May be more bundle than a tiny router shelf needs"],
    specs: { "Product type": "UPS battery backup bundle", Included: "850VA and 600VA units listed", "Use case": "Router and modem backup power" },
    evidence: ["List the modem, ONT, router, and mesh node wattage before estimating runtime", "Check outlet spacing for power bricks", "Confirm whether internet service remains active during local outages"],
    alternatives: ["Choose a smaller single UPS for one router and modem.", "Use no UPS if your ISP equipment outside the home loses power immediately."],
    offers: offer(links.apc),
  },
];

export const networkRoundups: Roundup[] = [
  {
    site: "network",
    slug: "best-mesh-wifi-for-apartments-and-homes",
    title: "Best Mesh Wi-Fi Systems for Apartments and Homes",
    dek: "The right mesh system should match layout, wall density, wired backhaul options, internet speed, and how much setup control you want.",
    category: "wifi",
    intent: "Choose mesh Wi-Fi that fixes coverage without overbuying speed you cannot use.",
    intro: "Mesh Wi-Fi is most useful when one router cannot cover the home cleanly. Start with node placement, wired backhaul, and internet plan speed before comparing the biggest number on the box.",
    decisionGuide: [
      { label: "Wi-Fi 7 upgrade", detail: "Choose Deco BE63 when multi-gig ports and newer client support matter." },
      { label: "Simple family setup", detail: "Choose eero 6 when ease of setup matters more than advanced tuning." },
      { label: "Very large premium home", detail: "Compare Orbi 970 only when coverage and device load justify the premium." },
      { label: "Travel and rentals", detail: "Use Beryl AX for portable networks, not whole-home coverage." },
    ],
    methodology: ["Map layout before speed class", "Check wired backhaul and port speeds", "Separate simplicity from enthusiast controls"],
    productSlugs: ["tp-link-deco-be63-wifi-7-mesh", "amazon-eero-6-mesh-wifi-system", "netgear-orbi-970-wifi-7-mesh", "glinet-beryl-ax-travel-router"],
    faqs: [
      { question: "Do I need Wi-Fi 7 mesh?", answer: "Only if your devices, internet plan, or wired backhaul can benefit. Many homes still do well with simpler Wi-Fi 6 mesh." },
      { question: "Is wired backhaul worth it?", answer: "Usually yes when it is available. It keeps mesh nodes from competing for the same wireless path." },
      { question: "How many mesh nodes do I need?", answer: "Start with layout, not square footage alone. Walls, floors, and router placement matter as much as size." },
    ],
  },
  {
    site: "network",
    slug: "best-wifi-7-routers-for-home-networks",
    title: "Best Wi-Fi 7 Routers for Home Networks",
    dek: "Single-router Wi-Fi 7 upgrades make sense when placement is good, the home is not too spread out, and wired ports matter.",
    category: "wifi",
    intent: "Pick a Wi-Fi 7 router without buying mesh when one strong router is enough.",
    intro: "A Wi-Fi 7 router can be a cleaner upgrade than mesh if the router can sit near the center of the home. Compare ports, firmware controls, client support, and whether the router solves the real bottleneck.",
    decisionGuide: [
      { label: "Practical Wi-Fi 7", detail: "TP-Link BE400 is the cleaner everyday single-router upgrade." },
      { label: "Gaming and controls", detail: "ASUS RT-BE86U is better when 10G, VPN, and advanced settings matter." },
      { label: "Coverage problem", detail: "Choose mesh instead if distant rooms are the issue." },
      { label: "Budget setup", detail: "Try placement and Ethernet first before buying a flagship router." },
    ],
    methodology: ["Check router placement before router class", "Compare WAN and LAN port speeds", "Match advanced features to real workflows"],
    productSlugs: ["tp-link-be400-wifi-7-router", "asus-rt-be86u-wifi-7-gaming-router", "tp-link-deco-be63-wifi-7-mesh"],
    faqs: [
      { question: "Is a router better than mesh?", answer: "A single router is better when it can cover the home from one good location. Mesh is better for spread-out layouts." },
      { question: "Do 10G ports matter?", answer: "Only if your modem, switch, NAS, or wired clients can use that path." },
      { question: "Will Wi-Fi 7 help old devices?", answer: "Older devices can still connect, but the newest benefits require compatible clients." },
    ],
  },
  {
    site: "network",
    slug: "best-wired-networking-upgrades",
    title: "Best Wired Networking Upgrades for Home Offices and TV Rooms",
    dek: "Switches, cables, and USB-C Ethernet adapters can fix stability problems that a router upgrade will never solve.",
    category: "wired",
    intent: "Build a stable wired path for desks, consoles, streamers, access points, and network shelves.",
    intro: "Wired networking is often the boring fix that actually works. A switch, the right cable route, or a laptop Ethernet hub can make office calls and downloads more stable than another Wi-Fi upgrade.",
    decisionGuide: [
      { label: "Need more ports", detail: "Start with TP-Link TL-SG108 for simple gigabit expansion." },
      { label: "Want basic smart controls", detail: "NETGEAR GS308E adds light management without a full rack." },
      { label: "Room-to-room run", detail: "Use the Jadaol flat Cat6 when route shape matters." },
      { label: "Laptop desk", detail: "Use the UGREEN hub when Ethernet is part of a broader USB-C setup." },
    ],
    methodology: ["Count ports before choosing switch size", "Separate patch cables from room runs", "Check laptop hub display and charging compatibility"],
    productSlugs: ["tp-link-tl-sg108-gigabit-switch", "netgear-gs308e-gigabit-switch", "jadaol-cat6-flat-ethernet-cable", "monoprice-slimrun-cat6a-ethernet-patch-cable", "ugreen-revodok-usb-c-gigabit-ethernet-hub"],
    faqs: [
      { question: "Should I wire devices instead of upgrading Wi-Fi?", answer: "For desks, TVs, consoles, and NAS devices, Ethernet is often more stable than a stronger wireless router." },
      { question: "Is gigabit enough?", answer: "For many homes yes, but multi-gig internet, NAS transfers, or newer desktops may justify 2.5G or 10G planning." },
      { question: "Are flat Ethernet cables okay?", answer: "They can be useful for room routing, but avoid harsh bends and do not treat them as a universal in-wall cable." },
    ],
  },
  {
    site: "network",
    slug: "best-ups-for-router-and-modem",
    title: "Best UPS for Router and Modem Backup Power",
    dek: "A router UPS should keep the whole internet chain online: modem or ONT, router, and any essential mesh node.",
    category: "backup",
    intent: "Keep home internet online through short outages without buying the wrong battery backup.",
    intro: "Backup power for networking only works when every required box stays on. Before buying a UPS, list the modem, ONT, router, switch, and mesh node that must survive the outage.",
    decisionGuide: [
      { label: "Router plus modem", detail: "APC Back-UPS is the starting point for common home network backup." },
      { label: "Power brick crowding", detail: "Check outlet spacing before assuming every device fits." },
      { label: "Long outage", detail: "Runtime depends on watt load and battery age, not just VA number." },
      { label: "ISP outage too", detail: "Skip overspending if the upstream service fails whenever power drops." },
    ],
    methodology: ["Count every network device that needs power", "Compare watt load against UPS capacity", "Check outlet spacing and battery replacement path"],
    productSlugs: ["apc-back-ups-router-modem-bundle"],
    faqs: [
      { question: "Will a UPS keep internet working?", answer: "Only if the modem or ONT, router, and upstream service remain powered and active." },
      { question: "What should plug into the UPS?", answer: "Start with modem or ONT, router, one key switch, and possibly one mesh node." },
      { question: "Do I need a huge UPS?", answer: "Not always. Network gear usually draws less power than desktops, but runtime depends on the actual load." },
    ],
  },
];

export const networkGuides: Guide[] = [
  {
    site: "network",
    slug: "wifi-7-vs-wifi-6-guide",
    title: "Wi-Fi 7 vs Wi-Fi 6 Buying Guide",
    dek: "How to decide whether Wi-Fi 7 is worth paying for in a real home network.",
    category: "wifi",
    updatedAt: "June 28, 2026",
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes", "best-wifi-7-routers-for-home-networks"],
    sections: [
      { heading: "Start with client support", body: "Wi-Fi 7 benefits are strongest when laptops, phones, or adapters can actually use the newer standard. Older devices can connect, but they do not magically become Wi-Fi 7 clients." },
      { heading: "Check wired ports", body: "A Wi-Fi 7 router with gigabit-only paths may still bottleneck a multi-gig internet plan. Look at WAN, LAN, switches, and backhaul together." },
      { heading: "Coverage still beats speed class", body: "A poorly placed Wi-Fi 7 router can perform worse than a well-placed Wi-Fi 6 mesh system. Layout comes first." },
      { heading: "Buy for the next bottleneck", body: "Upgrade when the current problem is coverage, device density, or wired speed. Skip it if the main problem is a bad router location." },
    ],
  },
  {
    site: "network",
    slug: "mesh-wifi-node-placement-guide",
    title: "Mesh Wi-Fi Node Placement Guide",
    dek: "How to place mesh nodes so they solve coverage instead of repeating a weak signal.",
    category: "wifi",
    updatedAt: "June 28, 2026",
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes"],
    sections: [
      { heading: "Do not place nodes at the dead zone", body: "A wireless mesh node needs a decent signal to repeat. Put it between the router and weak room, not at the farthest failing corner." },
      { heading: "Use wired backhaul where possible", body: "Ethernet between nodes frees wireless capacity and often improves stability more than buying a faster kit." },
      { heading: "Avoid hidden router shelves", body: "Cabinets, metal racks, and floor placement can weaken coverage. Height and openness still matter." },
      { heading: "Retest after moving furniture", body: "Large TVs, mirrors, appliances, and desks can change signal paths. Treat placement as a setup step, not a one-time guess." },
    ],
  },
  {
    site: "network",
    slug: "router-placement-guide",
    title: "Router Placement Guide for Apartments and Small Homes",
    dek: "How to choose a router location before buying another mesh node or extender.",
    category: "wifi",
    relatedRoundups: ["best-wifi-7-routers-for-home-networks"],
    sections: [
      { heading: "Central beats hidden", body: "The best router is often the one you can place centrally and openly. A closet location can waste an otherwise good router." },
      { heading: "Modem location is not destiny", body: "A longer Ethernet cable can move the router away from a bad modem corner while keeping the modem where the service enters." },
      { heading: "Separate office and entertainment needs", body: "Work calls, streaming boxes, and gaming systems may deserve Ethernet even if phones are fine on Wi-Fi." },
      { heading: "Measure before upgrading", body: "Run speed tests in the rooms that matter, then decide whether placement, Ethernet, mesh, or a router upgrade is the right fix." },
    ],
  },
  {
    site: "network",
    slug: "ethernet-cable-category-guide",
    title: "Ethernet Cable Category Guide",
    dek: "How to choose Cat6, Cat6A, flat cables, and patch cables without overbuying.",
    category: "wired",
    relatedRoundups: ["best-wired-networking-upgrades"],
    sections: [
      { heading: "Match the cable to the run", body: "A short patch cable behind a switch has different needs than a long room-to-room cable along walls." },
      { heading: "Cat6 is enough for many homes", body: "For common gigabit paths, Cat6 is practical and inexpensive. Cat6A makes more sense for higher-spec short patches or future planning." },
      { heading: "Flat cable is about routing", body: "Flat cables are useful under edges and along trim, but they should not be treated as the best answer for every permanent install." },
      { heading: "Leave slack and avoid pinch points", body: "A clean run should avoid tight bends, door compression, chair wheels, and places where people will trip." },
    ],
  },
  {
    site: "network",
    slug: "home-ethernet-switch-guide",
    title: "Home Ethernet Switch Buying Guide",
    dek: "How to pick port count, speed, fanless operation, and smart features for a small home network.",
    category: "wired",
    relatedRoundups: ["best-wired-networking-upgrades"],
    sections: [
      { heading: "Count ports with room to grow", body: "Buy for the devices you have plus a few spares. TV stands and desks often grow extra wired devices over time." },
      { heading: "Gigabit is still practical", body: "A gigabit switch is enough for many rooms. Multi-gig matters when internet, NAS, or client devices can actually exceed gigabit." },
      { heading: "Fanless matters at home", body: "A switch near a desk, bedroom, or TV should stay quiet. Fanless metal models are usually easier to live with." },
      { heading: "Smart features are optional", body: "Easy smart switches can be useful, but unmanaged switches are simpler when you only need more ports." },
    ],
  },
  {
    site: "network",
    slug: "usb-c-ethernet-adapter-guide",
    title: "USB-C Ethernet Adapter Guide",
    dek: "How to decide between a simple Ethernet dongle, USB-C hub, or full docking station.",
    category: "wired",
    relatedRoundups: ["best-wired-networking-upgrades"],
    sections: [
      { heading: "Start with the laptop workflow", body: "If Ethernet is the only missing port, a simple adapter is enough. If you also need HDMI, charging, and USB-A, a hub is cleaner." },
      { heading: "Check display compatibility", body: "USB-C hubs vary by HDMI resolution, refresh rate, and laptop support. Do not assume every port works the same on every computer." },
      { heading: "Power delivery matters", body: "A hub that passes through less power than your laptop needs can be annoying during long work sessions." },
      { heading: "Use Ethernet for stability", body: "A wired adapter is most useful for video calls, large downloads, gaming, or rooms where Wi-Fi is inconsistent." },
    ],
  },
  {
    site: "network",
    slug: "router-ups-runtime-guide",
    title: "Router UPS Runtime Planning Guide",
    dek: "How to estimate backup power needs for modem, ONT, router, switch, and one mesh node.",
    category: "backup",
    relatedRoundups: ["best-ups-for-router-and-modem"],
    sections: [
      { heading: "List the whole internet chain", body: "A UPS only helps if every required device stays powered: modem or ONT, router, switch, and sometimes a mesh node." },
      { heading: "Runtime depends on watts", body: "VA ratings are not runtime promises. Add up device wattage and leave margin for battery age." },
      { heading: "Check outlet shape", body: "Router and modem power bricks can block nearby outlets. Outlet spacing is part of the buying decision." },
      { heading: "Know the upstream limit", body: "Some internet service equipment outside the home may fail during local outages, limiting what your UPS can solve." },
    ],
  },
  {
    site: "network",
    slug: "travel-router-vpn-guide",
    title: "Travel Router and VPN Setup Guide",
    dek: "When a portable router helps with hotels, rentals, RVs, cruises, and public Wi-Fi.",
    category: "wifi",
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes"],
    sections: [
      { heading: "Use it for repeatable travel setups", body: "A travel router lets your devices connect to one familiar network while the router handles the venue connection." },
      { heading: "Check captive portals", body: "Hotels and public Wi-Fi can use sign-in pages that need testing. Do not assume every venue behaves the same." },
      { heading: "Match VPN support", body: "Confirm protocol support with your VPN provider before treating the router as a privacy solution." },
      { heading: "Do not confuse it with home mesh", body: "A travel router is portable and flexible, but it is not a replacement for a whole-home mesh system." },
    ],
  },
];

export const networkTools: Tool[] = [
  {
    site: "network",
    slug: "wifi-coverage-estimator",
    title: "Wi-Fi Coverage Estimator",
    dek: "Estimate a starting mesh node count from home size and connected device count before choosing routers or mesh kits.",
    category: "wifi",
    kind: "wifi",
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes", "best-wifi-7-routers-for-home-networks"],
  },
];
