import type { Guide, Product, Roundup } from "./types";
import { ebaySearchOffer } from "./ebay";

const updatedAt = "June 30, 2026";

export const smartHomeProducts: Product[] = [
  {
    site: "smarthome",
    slug: "aqara-smart-lock-u400",
    seoTitle: "Aqara U400 Review Guide: UWB, Matter over Thread & Door Fit",
    updatedAt,
    name: "Aqara Smart Lock U400",
    brand: "Aqara",
    category: "access",
    image: "/images/affiliate/smarthome-smart-lock-realistic.webp",
    summary: "A research-based buying guide to Aqara's UWB deadbolt, with the controller, phone, door-fit, battery, and regional-version checks that determine whether its hands-free entry features make sense.",
    verdict: "The U400 is the stronger Aqara choice for a compatible Apple-centered home that specifically values approach-based UWB unlocking. Buyers who mainly want fingerprint, keypad, or Apple Home Key access can spend less on the U100.",
    whyItMatters: "UWB is the headline feature, but the lock still has to fit a single-cylinder deadbolt and connect to the correct Matter controller or Thread border router. The exact regional version and household phone support matter more than the logo list.",
    bestFor: "Apple households that want UWB hands-free entry plus local backup methods",
    priceBand: "$$$$",
    rating: 4.5,
    scores: [{ label: "Entry options", value: 9 }, { label: "Ecosystem fit", value: 8 }, { label: "Setup clarity", value: 7 }],
    pros: ["UWB approach unlocking on supported devices", "Matter over Thread and Apple Home Key support", "Fingerprint, keypad, NFC, app, and physical-key fallbacks"],
    cons: ["Advanced ecosystem features require compatible controllers and phones", "Single-cylinder deadbolt and door measurements must be checked", "A rechargeable battery creates a charging routine"],
    specs: {
      "Primary network": "Matter over Thread",
      "Entry methods": "UWB, fingerprint, keypad, Home Key, NFC, app, physical key",
      "Door type": "Compatible single-cylinder deadbolt; verify dimensions",
      Battery: "Rechargeable; Aqara states up to 6 months under stated conditions",
      Weather: "Exterior assembly rated IP65",
      "Before buying": "Confirm regional version, phone support, Matter controller, and Thread border router",
    },
    evidence: ["Aqara lists UWB approach unlocking as the U400's differentiating feature.", "The manufacturer requires a compatible Thread-enabled controller for ecosystem integrations.", "Battery life is an estimate under stated conditions, not a guaranteed interval for every door."],
    editorialSections: [
      { heading: "The reason to buy the U400", body: "Choose it for UWB approach unlocking, not merely because it is the newer model. Fingerprint and keypad entry already cover most daily routines on cheaper locks." },
      { heading: "Compatibility comes in layers", body: "The lock, phone, Matter controller, Thread border router, and chosen ecosystem each play a role. Confirm the exact path for every household member before installation." },
      { heading: "Door fit and fallback", body: "Measure the existing deadbolt and door before checkout. Keep the physical key available and decide where the rechargeable battery will be charged before it becomes urgent." },
    ],
    sources: [{ name: "Aqara U400 product page", url: "https://www.aqara.com/us/product/smart-lock-u400/", note: "Features, compatibility, battery, weather rating, and installation requirements." }],
    compareSlugs: ["aqara-smart-lock-u100"],
    offers: [
      { merchant: "Amazon", url: "https://amzn.to/4oWMygy", label: "Check Aqara U400 price on Amazon", priceNote: "Confirm the exact regional version, finish, seller, and included accessories." },
      ebaySearchOffer("Aqara Smart Lock U400", "smarthome-aqara-smart-lock-u400"),
    ],
  },
  {
    site: "smarthome",
    slug: "aqara-smart-lock-u100",
    asin: "B0BZSD2L1W",
    seoTitle: "Aqara U100 Review Guide: Home Key, Fingerprint & Hub Requirements",
    updatedAt,
    name: "Aqara Smart Lock U100",
    brand: "Aqara",
    category: "access",
    image: "/images/affiliate/smarthome-smart-lock-realistic.webp",
    summary: "A practical guide to the U100's fingerprint, keypad, Apple Home Key, Zigbee, hub requirements, door fit, and AA-battery routine.",
    verdict: "The U100 is the value pick when fingerprint, keypad, and Apple Home Key entry solve the real problem. Its remote and cross-platform features are less direct than the U400 because an Aqara hub is central to the broader integration path.",
    whyItMatters: "A smart lock can work well locally while its remote features remain unavailable. Decide whether local entry is enough or whether an Aqara hub and compatible ecosystem controller belong in the budget.",
    bestFor: "Fingerprint and Apple Home Key entry without paying for UWB",
    priceBand: "$$$",
    rating: 4.4,
    scores: [{ label: "Entry options", value: 9 }, { label: "Value", value: 8 }, { label: "Remote setup", value: 6 }],
    pros: ["Fingerprint, keypad, Apple Home Key, NFC, app, and key entry", "Stores multiple fingerprints and temporary codes", "Replaceable AA batteries simplify the power routine"],
    cons: ["Aqara hub is required for remote and broader third-party functions", "Zigbee architecture is less direct than Matter-over-Thread locks", "Door dimensions and deadbolt type still require checking"],
    specs: {
      "Primary radio": "Zigbee",
      "Entry methods": "Fingerprint, keypad, Apple Home Key, NFC, app, physical key",
      Fingerprints: "Up to 50 listed by Aqara",
      Battery: "4 AA batteries",
      Weather: "Exterior assembly rated IP65",
      "Before buying": "Confirm door fit and whether an Aqara hub is needed for the intended remote features",
    },
    evidence: ["Aqara documents local fingerprint and Home Key entry separately from hub-enabled remote integrations.", "The U100 uses replaceable AA batteries rather than the U400's rechargeable pack.", "The lock is designed around a compatible single-cylinder deadbolt installation."],
    editorialSections: [
      { heading: "U100 versus U400", body: "The U100 covers the common local entry methods. Move to the U400 only when UWB hands-free approach unlocking and a Matter-over-Thread foundation justify the higher cost." },
      { heading: "Plan the hub before checkout", body: "If remote control, automations, Matter exposure, or third-party ecosystems are part of the goal, verify the required Aqara hub and ecosystem controller rather than assuming the lock alone is enough." },
      { heading: "Keep entry boring", body: "Enroll more than one fingerprint per frequent user, save a keypad fallback, and keep the physical key accessible outside the locked home." },
    ],
    sources: [
      { name: "Aqara U100 product page", url: "https://www.aqara.com/us/product/smart-lock-u100/", note: "Entry methods, Zigbee, hub, battery, and fit information." },
      { name: "Aqara US U100 listing", url: "https://us.aqara.com/products/smart-lock-u100", note: "Current US model positioning and specifications." },
    ],
    compareSlugs: ["aqara-smart-lock-u400"],
    offers: [
      { merchant: "Amazon", url: "https://amzn.to/4ybD4SS", label: "Check Aqara U100 price on Amazon", priceNote: "Confirm ASIN B0BZSD2L1W, finish, seller, and included accessories." },
      ebaySearchOffer("Aqara Smart Lock U100", "smarthome-aqara-smart-lock-u100"),
    ],
  },
  {
    site: "smarthome",
    slug: "ring-battery-doorbell-plus-2nd-gen",
    seoTitle: "Ring Battery Doorbell Plus 2nd Gen Guide: 2K Video & Subscription",
    updatedAt,
    name: "Ring Battery Doorbell Plus (2nd Gen)",
    brand: "Ring",
    category: "cameras",
    image: "/images/affiliate/smarthome-video-doorbell-realistic.webp",
    summary: "A research-based look at Ring's removable-battery 2K doorbell, including field of view, Wi-Fi, optional wiring, recording-plan boundaries, and the Chime Plus bundle in the linked offer.",
    verdict: "Choose Ring when its mature app, Alexa display path, removable battery, and optional hardwire support matter more than avoiding a subscription. Tapo D210 is the cleaner value choice for local microSD storage.",
    whyItMatters: "Doorbell value depends on what happens after an alert. Recording history and some advanced Ring features depend on a paid plan, so compare the long-term service choice before treating the hardware price as the total cost.",
    bestFor: "Alexa households that want a removable battery and polished Ring app",
    priceBand: "$$$",
    rating: 4.3,
    scores: [{ label: "App experience", value: 9 }, { label: "Power flexibility", value: 8 }, { label: "No-plan value", value: 5 }],
    pros: ["2K video with a square head-to-toe view", "Removable battery plus optional 8–24VAC wiring", "Dual-band Wi-Fi 6 and broad Ring/Alexa ecosystem"],
    cons: ["Recording history and some features require a Ring plan", "The linked Amazon offer is a Doorbell Plus and Chime Plus bundle", "Frequent motion can shorten the charging interval"],
    specs: {
      Video: "Retinal 2K",
      "Field of view": "140° horizontal × 140° vertical; 178° diagonal",
      Power: "Quick-release battery or optional 8–24VAC hardwire",
      Network: "Dual-band Wi-Fi 6",
      Weather: "IP55",
      "Linked offer": "Battery Doorbell Plus (2nd Gen) with Chime Plus",
    },
    evidence: ["Ring lists 2K video, 6× zoom, and a 140° by 140° view.", "Optional low-voltage wiring can keep the removable battery charged but does not turn it into every wired Ring model.", "Recording and advanced feature availability changes with the selected Ring plan."],
    editorialSections: [
      { heading: "The bundle is not the standalone doorbell", body: "The Amazon link supplied for this guide includes Chime Plus. Compare the bundle price against the standalone hardware before checkout and confirm the exact contents in the cart." },
      { heading: "Price the subscription separately", body: "Live view and alerts are not the same as saved event history. Check Ring's current plan matrix for the features and cameras you intend to cover." },
      { heading: "Battery or wire", body: "Battery installation offers placement flexibility. Existing compatible low-voltage wiring can reduce charging work, but voltage and transformer condition still need checking." },
    ],
    sources: [
      { name: "Ring Battery Doorbell Plus (2nd Gen)", url: "https://ring.com/products/battery-doorbell-plus-2nd-gen", note: "Video, view, power, network, and plan information." },
      { name: "Ring product support", url: "https://ring.com/support/products/doorbells/battery-doorbell-plus-2nd-gen?page=1", note: "Setup and model-specific support." },
    ],
    compareSlugs: ["eufy-video-doorbell-e340", "tapo-d210-video-doorbell"],
    offers: [
      { merchant: "Amazon", url: "https://amzn.to/4gKFmlp", label: "Check Ring + Chime Plus bundle on Amazon", priceNote: "This link is a bundle; confirm the 2nd Gen doorbell, Chime Plus, finish, and current plan trial." },
      ebaySearchOffer("Ring Battery Doorbell Plus 2nd Gen", "smarthome-ring-battery-doorbell-plus-2nd-gen"),
    ],
  },
  {
    site: "smarthome",
    slug: "tapo-d210-video-doorbell",
    asin: "B0D8M6GNP3",
    seoTitle: "Tapo D210 Review Guide: 2K Doorbell, Local Storage & Battery",
    updatedAt,
    name: "Tapo D210 Video Doorbell",
    brand: "Tapo",
    category: "cameras",
    image: "/images/affiliate/smarthome-video-doorbell-realistic.webp",
    summary: "A model-correct guide to the battery-only Tapo D210, covering 2K 3MP video, 160-degree view, included chime, microSD storage, optional cloud service, and person alerts.",
    verdict: "The D210 is the value pick for renters or subscription-averse buyers who want a battery doorbell, included chime, and local microSD recording. It is not the D225 and does not offer the D225's battery-or-hardwire choice.",
    whyItMatters: "Tapo's closely named doorbells have different power options. The supplied Amazon listing is the D210, so buyers should base installation plans on battery charging and 2.4GHz Wi-Fi rather than D225 specifications.",
    bestFor: "Battery installation with local microSD storage and no required recording plan",
    priceBand: "$",
    rating: 4.4,
    scores: [{ label: "No-plan value", value: 9 }, { label: "Image coverage", value: 8 }, { label: "Power flexibility", value: 6 }],
    pros: ["2K 3MP video and 160° diagonal head-to-toe view", "Local microSD recording up to 512GB plus optional Tapo Care", "Included indoor chime and free person detection"],
    cons: ["Battery-only D210 requires periodic charging", "2.4GHz Wi-Fi only", "microSD card is not included"],
    specs: {
      Model: "D210",
      Video: "2304 × 1296 (2K 3MP)",
      "Field of view": "160° diagonal",
      Battery: "5200mAh rechargeable",
      Storage: "microSD up to 512GB or optional Tapo Care cloud",
      Network: "2.4GHz Wi-Fi",
    },
    evidence: ["TP-Link identifies D210 as a battery doorbell and lists 2K 3MP resolution.", "Local recording needs a compatible microSD card purchased separately.", "Person detection is available without making cloud storage mandatory."],
    editorialSections: [
      { heading: "This listing is D210, not D225", body: "The supplied link resolves to ASIN B0D8M6GNP3 and model D210. Do not use D225 hardwire specifications or accessory assumptions for this purchase." },
      { heading: "Local storage changes the value equation", body: "A microSD card adds upfront cost but can avoid a recurring recording plan. Decide who can access the card and how footage will be handled if the doorbell itself is removed." },
      { heading: "Plan the charging route", body: "Battery life varies with events, live view, temperature, and settings. Make sure the doorbell can be removed and charged without turning the entrance into a recurring project." },
    ],
    sources: [{ name: "TP-Link Tapo D210 product page", url: "https://www.tp-link.com/us/smart-home/smart-doorbell/tapo-d210/", note: "Correct model, video, battery, storage, detection, chime, and network specifications." }],
    compareSlugs: ["ring-battery-doorbell-plus-2nd-gen"],
    offers: [{ merchant: "Amazon", url: "https://amzn.to/4wc5nhZ", label: "Check Tapo D210 price on Amazon", priceNote: "Confirm model D210 and ASIN B0D8M6GNP3; this is not the D225." }],
  },
  {
    site: "smarthome",
    slug: "ecobee-smart-thermostat-premium",
    asin: "B0B1X7G9J2",
    seoTitle: "ecobee Smart Thermostat Premium Guide: Wiring, Sensors & Bundle",
    updatedAt,
    name: "ecobee Smart Thermostat Premium",
    brand: "ecobee",
    category: "climate",
    image: "/images/affiliate/smarthome-smart-thermostat-realistic.webp",
    summary: "A compatibility-first guide to ecobee Premium, including 24VAC systems, C-wire or PEK power, room sensing, air-quality features, voice assistants, and the larger security bundle in the supplied offer.",
    verdict: "ecobee Premium is the stronger choice for households that want flexible room sensors, broad ecosystem support, and thermostat controls independent of one phone platform. The linked offer is a security bundle and should be compared against the thermostat-only package.",
    whyItMatters: "Thermostat installation is an HVAC compatibility decision first. Confirm wiring and equipment support before valuing sensors, voice control, air-quality trends, or optional security services.",
    bestFor: "Room-aware comfort and broad ecosystem support on a compatible 24VAC system",
    priceBand: "$$$$",
    rating: 4.5,
    scores: [{ label: "Room sensing", value: 9 }, { label: "Ecosystem fit", value: 9 }, { label: "Bundle clarity", value: 6 }],
    pros: ["Room SmartSensor support and occupancy-based comfort features", "Built-in air-quality, humidity, occupancy, Alexa, and Siri features", "Supports Apple Home, Alexa, Google Assistant, and SmartThings"],
    cons: ["HVAC compatibility and power wiring must be checked", "Some security features require an optional subscription", "The linked offer adds door/window sensors and a security trial"],
    specs: {
      HVAC: "Most 24VAC systems; verify exact equipment",
      Power: "C-wire or included Power Extender Kit for supported systems",
      Sensors: "Thermostat sensors plus compatible ecobee SmartSensors",
      Network: "Dual-band Wi-Fi",
      Ecosystems: "Apple Home, Alexa, Google Assistant, SmartThings",
      "Linked offer": "Comfort and Security Bundle with door/window sensors and trial",
    },
    evidence: ["ecobee provides a system compatibility checker and documents C-wire or PEK power paths.", "The Premium thermostat includes air-quality and occupancy sensing.", "Security alerts and services have separate subscription boundaries."],
    editorialSections: [
      { heading: "Check the HVAC before the app", body: "Photograph and label old wiring, identify system type, and use ecobee's compatibility checker. Multi-stage, heat-pump, accessory, and proprietary systems deserve extra care." },
      { heading: "Understand the linked bundle", body: "The supplied Amazon offer is not just the standard thermostat package. It includes door/window sensors and a Smart Security trial, so compare its price with the current thermostat-only option." },
      { heading: "Room sensors need a plan", body: "Place sensors where comfort problems actually occur and understand how participating sensors influence the schedule. More sensors do not automatically fix airflow or equipment sizing." },
    ],
    sources: [{ name: "ecobee Smart Thermostat Premium", url: "https://www.ecobee.com/en-us/smart-thermostats/smart-thermostat-premium/", note: "Compatibility, power, sensors, ecosystem, and service features." }],
    compareSlugs: ["google-nest-learning-thermostat-4th-gen"],
    offers: [
      { merchant: "Amazon", url: "https://amzn.to/4aoAX3U", label: "Check ecobee Comfort and Security bundle on Amazon", priceNote: "ASIN B0B1X7G9J2 is a bundle with door/window sensors and a trial; compare with thermostat-only pricing." },
      ebaySearchOffer("ecobee Smart Thermostat Premium", "smarthome-ecobee-smart-thermostat-premium"),
    ],
  },
  {
    site: "smarthome",
    slug: "google-nest-learning-thermostat-4th-gen",
    seoTitle: "Nest Learning Thermostat 4th Gen Guide: Matter, Wiring & Sensor",
    updatedAt,
    name: "Google Nest Learning Thermostat (4th Gen)",
    brand: "Google Nest",
    category: "climate",
    image: "/images/affiliate/smarthome-smart-thermostat-realistic.webp",
    summary: "A research-based guide to Google's 2024 Learning Thermostat, covering 24V HVAC compatibility, its 2.7-inch display, included temperature sensor offer, Matter, Google Home app, and power checks.",
    verdict: "Nest 4th Gen is the cleaner fit for Google Home households that value its display, learned schedules, and Matter integration. ecobee remains easier to recommend when room-sensor control and broad established ecosystem options are the priority.",
    whyItMatters: "A Matter logo does not bypass HVAC wiring requirements. Use Google's compatibility checker for the exact system, then decide whether learning behavior and the included remote sensor address a real comfort problem.",
    bestFor: "Google Home households that want a polished learning thermostat and remote sensor",
    priceBand: "$$$$",
    rating: 4.4,
    scores: [{ label: "Interface", value: 9 }, { label: "Automation", value: 8 }, { label: "Compatibility clarity", value: 7 }],
    pros: ["Large 2.7-inch 600×600 display", "Matter support and Google Home app control", "The supplied offer includes a Nest Temperature Sensor"],
    cons: ["Exact 24V HVAC and power compatibility must be checked", "Some advanced household integrations remain ecosystem-dependent", "Premium display and design raise the purchase price"],
    specs: {
      Display: "2.7-inch, 600 × 600",
      Sensors: "Temperature, humidity, ambient light, and Soli presence sensing",
      HVAC: "Most 24V systems; verify exact equipment",
      Network: "Dual-band Wi-Fi",
      "Smart home": "Matter; Google Home app",
      "Linked offer": "Polished Gold thermostat with Nest Temperature Sensor",
    },
    evidence: ["Google lists a 2.7-inch 600×600 display and built-in environmental sensing.", "The thermostat supports Matter but still requires compatible HVAC equipment and power.", "The supplied Amazon title includes a remote Nest Temperature Sensor."],
    editorialSections: [
      { heading: "Run the compatibility check first", body: "Do not infer compatibility from the previous thermostat's shape or wire count. Identify the HVAC terminals and use Google's current checker before purchase or removal." },
      { heading: "Learning is a preference, not magic", body: "Automatic schedules help households with repeatable routines. Homes with irregular occupancy may prefer deliberate schedules and sensor rules." },
      { heading: "Use the remote sensor intentionally", body: "Place the included sensor in a room with a known temperature problem, away from direct sun, drafts, and heat sources. It cannot repair airflow or an oversized HVAC system." },
    ],
    sources: [
      { name: "Google Nest Learning Thermostat 4th Gen specifications", url: "https://store.google.com/product/nest_learning_thermostat_4th_gen_specs?hl=en-US", note: "Display, sensors, network, and compatibility specifications." },
      { name: "Google Nest thermostat compatibility", url: "https://support.google.com/googlenest/answer/9230098", note: "HVAC and wiring compatibility guidance." },
    ],
    compareSlugs: ["ecobee-smart-thermostat-premium"],
    offers: [
      { merchant: "Amazon", url: "https://amzn.to/4gKFbXh", label: "Check Nest 4th Gen bundle on Amazon", priceNote: "Confirm the Polished Gold finish, included temperature sensor, seller, and HVAC compatibility." },
      ebaySearchOffer("Google Nest Learning Thermostat 4th Gen", "smarthome-google-nest-learning-thermostat-4th-gen"),
    ],
  },
];

export const smartHomeRoundups: Roundup[] = [
  {
    site: "smarthome", slug: "aqara-u400-vs-u100", category: "access",
    title: "Aqara U400 vs U100: Which Smart Lock Fits Your Entry Routine?",
    dek: "Compare UWB and Matter over Thread with fingerprint, Apple Home Key, Zigbee, hub requirements, batteries, and door fit.",
    intent: "choosing between Aqara's premium UWB lock and its lower-cost Home Key model",
    intro: "Both locks offer several local entry methods. The real dividing line is whether hands-free UWB and a Thread foundation are worth more than the U100's proven fingerprint, keypad, and Home Key routine.",
    sections: [
      { heading: "Choose U400 for UWB", body: "The U400 earns its price when compatible household phones can use approach-based UWB unlocking and the home already has the right controller infrastructure." },
      { heading: "Choose U100 for core entry methods", body: "The U100 is the pragmatic choice when fingerprint, keypad, Home Key, and a physical-key fallback cover daily use." },
      { heading: "Neither model skips fit checks", body: "Measure the deadbolt, door thickness, backset, and clearance; confirm the exact regional version and required hubs before checkout." },
    ],
    decisionGuide: [
      { label: "Buy U400", detail: "You specifically want UWB approach unlocking and have compatible phones and Thread/Matter infrastructure." },
      { label: "Buy U100", detail: "Fingerprint, keypad, and Home Key solve the problem and an Aqara hub can cover desired remote features." },
      { label: "Pause", detail: "The door is not a compatible single-cylinder deadbolt or household fallback access is unclear." },
    ],
    methodology: ["Compared first-party entry methods and radio architecture", "Separated local features from hub/controller-dependent features", "Prioritized door fit, battery routine, and backup access"],
    productSlugs: ["aqara-smart-lock-u400", "aqara-smart-lock-u100"],
    faqs: [
      { question: "Is the U400 automatically better than the U100?", answer: "No. It is better when UWB approach unlocking and Matter over Thread are useful in your home. The U100 covers common fingerprint, keypad, and Home Key routines for less." },
      { question: "Do I need a hub?", answer: "It depends on the lock and feature. The U100 relies on an Aqara hub for remote and broader integrations; the U400 needs compatible Matter/Thread controller infrastructure for ecosystem features." },
    ],
  },
  {
    site: "smarthome", slug: "ring-battery-doorbell-plus-2nd-gen-vs-tapo-d210", category: "cameras",
    title: "Ring Battery Doorbell Plus 2nd Gen vs Tapo D210",
    dek: "A direct comparison of Ring's app and power flexibility against Tapo's local storage, included chime, and lower recurring-cost path.",
    intent: "choosing a battery video doorbell with the right storage and subscription model",
    intro: "Ring is the ecosystem-and-app choice; Tapo D210 is the local-storage value choice. The supplied Ring link is a Chime Plus bundle, while the Tapo listing is the battery-only D210—not D225.",
    sections: [
      { heading: "Storage is the biggest split", body: "Tapo can record to a separately purchased microSD card. Ring's saved history and several advanced features depend on the current Ring plan." },
      { heading: "Power options differ", body: "Ring uses a removable battery and can connect to compatible low-voltage wiring. D210 is planned as a rechargeable battery installation." },
      { heading: "Compare the offers carefully", body: "Ring's linked offer includes Chime Plus. Tapo D210 includes an indoor chime, but a microSD card is extra." },
    ],
    decisionGuide: [
      { label: "Buy Ring", detail: "You prefer the Ring/Alexa ecosystem, removable battery, optional wiring, and accept the plan decision." },
      { label: "Buy Tapo", detail: "You want local microSD recording, an included chime, and lower upfront hardware cost." },
      { label: "Check placement", detail: "Confirm Wi-Fi strength, mounting height, removal clearance, and charging access before either." },
    ],
    methodology: ["Used manufacturer specifications for video, power, storage, and network", "Separated hardware features from paid-service features", "Matched the comparison to the exact D210 and Ring bundle offers"],
    productSlugs: ["ring-battery-doorbell-plus-2nd-gen", "tapo-d210-video-doorbell"],
    faqs: [
      { question: "Does Tapo D210 require a subscription?", answer: "No for compatible local microSD recording and basic supported features; Tapo Care is an optional cloud service." },
      { question: "Is the Tapo link a D225?", answer: "No. The supplied ASIN B0D8M6GNP3 is the Tapo D210, a battery model." },
    ],
  },
  {
    site: "smarthome", slug: "ecobee-premium-vs-nest-learning-thermostat-4th-gen", category: "climate",
    title: "ecobee Premium vs Nest Learning Thermostat 4th Gen",
    dek: "Compare HVAC compatibility, power, room sensors, learning controls, ecosystems, and the exact bundles linked here.",
    intent: "choosing a premium smart thermostat after confirming HVAC compatibility",
    intro: "ecobee leans toward explicit room-sensor control and broad ecosystems; Nest emphasizes a refined display, learned schedules, Google Home, and Matter. Wiring compatibility can override either preference.",
    sections: [
      { heading: "Compatibility decides the shortlist", body: "Run each manufacturer's checker against the actual terminals and HVAC equipment. Do not purchase based only on the old thermostat or a generic C-wire rule." },
      { heading: "Sensors reflect different control styles", body: "ecobee is strong for planned participating-room behavior. Nest pairs its learning approach with a remote temperature sensor in the linked offer." },
      { heading: "The linked ecobee offer is larger", body: "ASIN B0B1X7G9J2 includes security sensors and a trial. Compare that bundle with thermostat-only pricing before using it as a price benchmark." },
    ],
    decisionGuide: [
      { label: "Buy ecobee", detail: "You prioritize room-sensor control, broad assistants, and deliberate comfort schedules." },
      { label: "Buy Nest", detail: "You prefer Google Home, learned schedules, Matter, and the Nest display experience." },
      { label: "Call a pro", detail: "The system is proprietary, line-voltage, multi-stage, accessory-heavy, or its wiring is unclear." },
    ],
    methodology: ["Started with first-party HVAC and power requirements", "Compared sensor and ecosystem behavior rather than design alone", "Disclosed bundle-specific extras and optional service boundaries"],
    productSlugs: ["ecobee-smart-thermostat-premium", "google-nest-learning-thermostat-4th-gen"],
    faqs: [
      { question: "Which thermostat works without a C-wire?", answer: "Compatibility varies by HVAC system. ecobee provides a Power Extender Kit for supported systems; Nest power requirements also depend on the exact system. Use the current compatibility checker." },
      { question: "Does Matter guarantee HVAC compatibility?", answer: "No. Matter concerns smart-home communication; it does not change electrical or HVAC equipment requirements." },
    ],
  },
];

export const smartHomeGuides: Guide[] = [
  {
    site: "smarthome", slug: "matter-vs-thread-vs-zigbee", category: "automation", updatedAt: "July 11, 2026",
    title: "Matter vs Zigbee vs Thread: Which Smart-Home Standard Do You Need?",
    dek: "Understand Matter vs Zigbee vs Thread, including radios, controllers, border routers, hubs, compatibility, and offline control.",
    sections: [
      { heading: "Matter is the common application language", body: "Matter defines how supported device types can be commissioned and controlled across compatible ecosystems. A Matter logo does not identify the radio by itself; Matter can run over Wi-Fi, Ethernet, or Thread." },
      { heading: "Thread is an IP mesh network", body: "Thread is a low-power IPv6 mesh used by devices such as sensors and locks. Thread devices need a compatible border router to connect the Thread mesh with the home's other IP networks." },
      { heading: "Zigbee needs a coordinator or hub", body: "Zigbee is a separate low-power mesh technology. Its devices generally connect through a compatible hub or coordinator, which may then expose selected devices to other ecosystems." },
      { heading: "Controller and border router are different roles", body: "A Matter controller commissions and manages Matter devices. A Thread border router moves traffic between Thread and the rest of the network. One physical product may perform both roles, but the roles are not interchangeable." },
      { heading: "Plan the offline path", body: "For locks, lights, and climate, keep physical controls and local entry available. Cloud accounts, remote access, and voice assistants should enhance essential controls rather than become the only path." },
    ],
    sources: [
      { name: "Connectivity Standards Alliance — Matter", url: "https://csa-iot.org/all-solutions/matter/", note: "Matter scope and ecosystem role." },
      { name: "Thread Group — What is Thread?", url: "https://www.threadgroup.org/What-is-Thread/Overview", note: "Thread network and border-router fundamentals." },
    ],
    relatedRoundups: ["ultraloq-bolt-se-vs-aqara-u400", "aqara-u400-vs-u100"], relatedProducts: ["ultraloq-bolt-se-smart-lock", "aqara-smart-lock-u400", "aqara-smart-lock-u100"],
  },
  {
    site: "smarthome", slug: "smart-lock-door-fit-hub-compatibility", category: "access", updatedAt,
    title: "Smart Lock Compatibility Checklist: Door Fit, Hubs, Batteries & Backup",
    dek: "Measure the door, map every controller, and preserve a dependable entry method before replacing a deadbolt.",
    sections: [
      { heading: "Identify the lock type", body: "Confirm that the existing hardware is the same deadbolt type supported by the new lock. Mortise locks, interconnected handles, rim locks, and multipoint systems are not interchangeable with a standard US single-cylinder deadbolt." },
      { heading: "Measure before removal", body: "Record door thickness, backset, bore diameter, edge bore, deadbolt throw, trim clearance, and the distance to a storm door. Check that the bolt moves freely without pushing or pulling the door." },
      { heading: "Draw the ecosystem path", body: "List the lock radio, vendor hub, Matter controller, Thread border router, phone requirements, and voice ecosystem. Mark which features are local and which need internet or cloud service." },
      { heading: "Plan batteries and emergency entry", body: "Choose where spare batteries, charging cables, and physical keys will live. Enroll multiple local entry methods and test them with the door open before relying on the lock." },
    ],
    sources: [
      { name: "Aqara U400 product page", url: "https://www.aqara.com/us/product/smart-lock-u400/", note: "Example fit and controller requirements." },
      { name: "Aqara U100 product page", url: "https://www.aqara.com/us/product/smart-lock-u100/", note: "Example deadbolt, battery, and hub requirements." },
    ],
    relatedRoundups: ["ultraloq-bolt-se-vs-aqara-u400", "aqara-u400-vs-u100"], relatedProducts: ["ultraloq-bolt-se-smart-lock", "aqara-smart-lock-u400", "aqara-smart-lock-u100"],
  },
  {
    site: "smarthome", slug: "video-doorbell-battery-storage-subscription-guide", category: "cameras", updatedAt,
    title: "Video Doorbell Guide: Battery, Local Storage & Subscription Costs",
    dek: "Choose the installation and recording path first, then compare resolution, alerts, chimes, and app polish.",
    sections: [
      { heading: "Battery makes placement easier", body: "A rechargeable doorbell avoids new power wiring, but event frequency, live view, cold weather, Wi-Fi strength, and detection settings affect the charging interval. Confirm removal clearance and charging downtime." },
      { heading: "Hardwiring is model-specific", body: "Some battery models accept low-voltage wiring to maintain charge; others are battery-only. Verify voltage, transformer rating, chime behavior, and the exact model rather than assuming every version of a product family works alike." },
      { heading: "Local storage and cloud plans solve different problems", body: "microSD storage can avoid a monthly recording fee but may be lost with the device. Cloud recording adds off-device history but creates an account, privacy, bandwidth, and recurring-cost decision." },
      { heading: "Build a true annual cost", body: "Add the doorbell, chime, transformer work, wedge mount, microSD card, spare battery, and chosen cloud plan. Recheck which alert, history, sharing, and recognition features change when a trial ends." },
    ],
    sources: [
      { name: "Ring Battery Doorbell Plus (2nd Gen)", url: "https://ring.com/products/battery-doorbell-plus-2nd-gen", note: "Power and subscription example." },
      { name: "TP-Link Tapo D210", url: "https://www.tp-link.com/us/smart-home/smart-doorbell/tapo-d210/", note: "Battery and local-storage example." },
    ],
    relatedRoundups: ["ring-battery-doorbell-plus-2nd-gen-vs-tapo-d210"], relatedProducts: ["ring-battery-doorbell-plus-2nd-gen", "tapo-d210-video-doorbell"],
  },
];
