import type { Guide, Product, Roundup } from "./types";

const updatedAt = "July 9, 2026";

const amazonUrl = (asin: string) => `https://www.amazon.com/dp/${asin}?tag=bingmada-20&linkCode=ll2&language=en_US&ref_=as_li_ss_tl`;
const amazonSource = (asin: string, note: string) => ({ name: `Amazon listing for ASIN ${asin}`, url: `https://www.amazon.com/dp/${asin}`, note });

export const smartHomeLeakExpansionProducts: Product[] = [
  {
    site: "smarthome",
    slug: "aqara-water-leak-sensor-3-pack-hub-kit",
    asin: "B0F9987FZ4",
    amazonTitle: "Aqara Water Leak Sensor 3 Pack & Zigbee Hub Kits, Zigbee Wireless Water Leak Detector",
    seoTitle: "Aqara Water Leak Sensor 3 Pack Hub Kit: Buying Guide",
    updatedAt,
    name: "Aqara Water Leak Sensor 3 Pack & Zigbee Hub Kit",
    brand: "Aqara",
    category: "automation",
    image: "/images/affiliate/smarthome-aqara-water-leak-sensor-kit.svg",
    summary: "A buying guide for the Aqara water-leak kit listing, focused on Zigbee hub requirements, phone alerts, local hub alarm behavior, and whether an Aqara ecosystem is worth choosing for leak detection.",
    verdict: "Choose the Aqara kit when the home already uses Aqara or wants leak sensors tied into broader automations. Skip it if a simple Wi-Fi kit with no smart-home hub planning is the priority.",
    whyItMatters: "Leak sensors are only useful when the alert reaches someone quickly. The purchase decision is less about a tiny puck and more about hub placement, alarm routing, battery checks, and coverage under every risky appliance.",
    bestFor: "Aqara households that want multiple leak sensors and hub-based automations",
    priceBand: "$$",
    rating: 4.3,
    scores: [
      { label: "Aqara ecosystem fit", value: 9 },
      { label: "Multi-room coverage", value: 8 },
      { label: "Setup simplicity", value: 6 },
    ],
    pros: ["Three-sensor kit can cover several risk points at once", "Zigbee hub path supports app alerts and smart-home automations", "Good fit beside sinks, washers, water heaters, and basement equipment"],
    cons: ["The listing is a kit, so confirm the included hub model before checkout", "Hub range and router placement affect reliability", "Buyers outside Aqara may prefer a simpler Wi-Fi kit"],
    specs: {
      ASIN: "B0F9987FZ4",
      Listing: "Water Leak Sensor 3 Pack & Zigbee Hub Kit",
      Protocol: "Aqara Zigbee sensor path with included hub listed",
      Alerts: "App notifications and hub alarm path listed",
      "Before buying": "Confirm exact hub model, regional version, included sensor count, and seller",
    },
    evidence: [
      "Amazon listing title verified as Aqara Water Leak Sensor 3 Pack & Zigbee Hub Kits",
      "Listing bullets reference hub proximity, phone alerts, and local hub alarm behavior",
      "The kit should be compared against standalone sensors only after confirming what hub is included",
      "Place sensors where water appears first, not where the app looks neat on a floor plan",
    ],
    editorialSections: [
      { heading: "Buy it as a kit, not a loose sensor", body: "The linked ASIN is positioned as a three-sensor kit with a Zigbee hub. Confirm the exact hub model and contents because Aqara sells many similar hubs and sensors." },
      { heading: "Hub placement matters", body: "A leak sensor under a water heater is not useful if the hub is too far away or hidden behind dense walls. Put the hub where the risky rooms can reach it reliably." },
      { heading: "Best use case", body: "Aqara makes the most sense when leak alerts can trigger lights, sirens, plugs, valves, or broader automations already planned in the home." },
    ],
    alternatives: ["Choose Govee for a simpler Wi-Fi gateway kit.", "Choose X-Sense when four slim sensors and a base station are the main requirement.", "Choose YoLink when long-range placement matters more than Aqara automations."],
    compareSlugs: ["govee-wifi-water-leak-detector-3-pack", "x-sense-sws0a41-water-leak-detector-kit", "yolink-lora-water-alarm-bundle"],
    sources: [amazonSource("B0F9987FZ4", "Exact linked listing; confirm hub model, sensor count, seller, and regional compatibility.")],
    offers: [
      {
        merchant: "Amazon US",
        url: amazonUrl("B0F9987FZ4"),
        label: "Check Aqara leak sensor kit on Amazon",
        priceNote: "Confirm ASIN B0F9987FZ4, included hub, three-sensor quantity, seller, and regional version.",
      },
    ],
  },
  {
    site: "smarthome",
    slug: "govee-wifi-water-leak-detector-3-pack",
    asin: "B07J9HZ5VN",
    amazonTitle: "Govee WiFi Water Leak Detector 3 Packs, Leak Alert with Email/App Push and Sound Alarm",
    seoTitle: "Govee WiFi Water Leak Detector 3 Pack Review Guide",
    updatedAt,
    name: "Govee WiFi Water Leak Detector 3 Pack",
    brand: "Govee",
    category: "automation",
    image: "/images/affiliate/smarthome-govee-wifi-water-leak-detector.svg",
    summary: "A practical guide to the Govee 3-pack leak detector kit, including its gateway, app/email alerts, 100dB alarm claim, sensor naming, 2.4GHz planning, and where it beats hub-heavy smart-home setups.",
    verdict: "Govee is the straightforward value pick when the buyer wants several leak points covered quickly with a Wi-Fi gateway and loud local alarms.",
    whyItMatters: "Most leaks start in predictable places. A three-pack can cover the washer, sink, and water heater immediately, which may matter more than deep smart-home ecosystem features.",
    bestFor: "Budget multi-point leak coverage with gateway-based Wi-Fi alerts",
    priceBand: "$",
    rating: 4.4,
    scores: [
      { label: "Value coverage", value: 9 },
      { label: "Remote alerts", value: 8 },
      { label: "Ecosystem depth", value: 5 },
    ],
    pros: ["Three sensors cover more than one risk area", "Listing references email, app push, and sound alarm alerts", "Gateway path avoids pairing every sensor directly to Wi-Fi"],
    cons: ["Gateway still needs stable 2.4GHz Wi-Fi", "Not the deepest Matter, Thread, or Zigbee ecosystem choice", "Alerts should be tested before depending on the system during travel"],
    specs: {
      ASIN: "B07J9HZ5VN",
      Listing: "Govee WiFi Water Leak Detector 3 Packs",
      Alerts: "Email, app push, and local sound alarm listed",
      Gateway: "Wi-Fi gateway listed; supports multiple sensors",
      "Alarm level": "100dB adjustable alarm listed",
    },
    evidence: [
      "Amazon listing title verified as Govee WiFi Water Leak Detector 3 Packs",
      "Listing bullets reference real-time alerts, a Wi-Fi gateway, and multiple connected sensors",
      "The kit is best evaluated by coverage count and notification reliability rather than one-sensor price",
      "Name each sensor by physical location so an alert points to the right shutoff action",
    ],
    editorialSections: [
      { heading: "The gateway is the value trick", body: "A gateway lets several small sensors report through one Wi-Fi bridge. That keeps setup simple, but the gateway itself becomes the part that needs good Wi-Fi and power." },
      { heading: "Use location names, not generic labels", body: "Rename sensors as Water heater pan, Washer left side, Kitchen sink, or Sump pump. In a real leak, generic Sensor 1 labels waste time." },
      { heading: "Who should skip it", body: "Skip it if the home already has an Aqara, Home Assistant, or long-range YoLink plan and wants leak detection inside that ecosystem." },
    ],
    alternatives: ["Choose Aqara for hub-based smart-home automations.", "Choose X-Sense for a four-sensor base-station kit.", "Choose YoLink for long-range LoRa placement."],
    compareSlugs: ["aqara-water-leak-sensor-3-pack-hub-kit", "x-sense-sws0a41-water-leak-detector-kit", "yolink-lora-water-alarm-bundle"],
    sources: [amazonSource("B07J9HZ5VN", "Exact linked listing; confirm 3-pack quantity, gateway inclusion, seller, and alert features.")],
    offers: [
      {
        merchant: "Amazon US",
        url: amazonUrl("B07J9HZ5VN"),
        label: "Check Govee 3-pack price on Amazon",
        priceNote: "Confirm ASIN B07J9HZ5VN, 3-pack quantity, gateway, seller, and current app requirements.",
      },
    ],
  },
  {
    site: "smarthome",
    slug: "x-sense-sws0a41-water-leak-detector-kit",
    asin: "B0DFCMJH5L",
    amazonTitle: "X-Sense Wi-Fi Water Leak Detector Kit, 4 Water Sensors and 1 Base Station, Model SWS0A41",
    seoTitle: "X-Sense SWS0A41 Water Leak Detector Kit Review Guide",
    updatedAt,
    name: "X-Sense SWS0A41 Wi-Fi Water Leak Detector Kit",
    brand: "X-Sense",
    category: "automation",
    image: "/images/affiliate/smarthome-x-sense-sws0a41-water-leak-kit.svg",
    summary: "A four-sensor leak detector kit guide focused on the SWS0A41 base station, app alerts, 100dB alarm claim, top and bottom probes, mute controls, and basement placement.",
    verdict: "X-Sense is the stronger multi-point kit when four sensors, a base station, and loud local alarm behavior matter more than smart-home ecosystem depth.",
    whyItMatters: "The best leak sensor is usually the one that covers every likely wet spot. Four sensors can make a bigger difference than one premium sensor in the wrong room.",
    bestFor: "Basements, laundry rooms, and utility areas needing four leak points covered",
    priceBand: "$$",
    rating: 4.5,
    scores: [
      { label: "Coverage count", value: 9 },
      { label: "Local alarm path", value: 8 },
      { label: "Smart-home ecosystem", value: 4 },
    ],
    pros: ["Four sensors plus one base station listed", "Top and bottom probe design can detect drips or floor water", "App controls include alarm history and temporary mute behavior in listing bullets"],
    cons: ["Base station placement and Wi-Fi coverage still matter", "Less attractive when deep automation ecosystem control is required", "Sensor placement under appliances must avoid damage during cleaning"],
    specs: {
      ASIN: "B0DFCMJH5L",
      Model: "SWS0A41",
      Kit: "4 water sensors and 1 base station listed",
      Alerts: "App alerts plus base-station alarm listed",
      "Detection design": "Top and bottom water probes listed",
    },
    evidence: [
      "Amazon listing title verified as X-Sense Wi-Fi Water Leak Detector Kit, Model SWS0A41",
      "Listing bullets reference a base-station alarm up to 100dB, app alerts, and alarm history",
      "Top and bottom probe language supports both drip and floor-water placement scenarios",
      "The kit should be judged by actual risky locations covered, not only sensor count",
    ],
    editorialSections: [
      { heading: "Four sensors changes the plan", body: "A four-pack can cover washer, water heater, sump area, and sink cabinet without immediately buying add-ons." },
      { heading: "Base station volume is not enough", body: "A loud base-station alarm helps when someone is home. Remote app alerts still need Wi-Fi, account setup, permissions, and push notifications tested." },
      { heading: "Who should skip it", body: "Skip it if the buyer wants Matter, HomeKit, Zigbee, Thread, or LoRa as the main integration path rather than a focused leak-alarm kit." },
    ],
    alternatives: ["Choose Govee for a lower-cost three-sensor Wi-Fi gateway kit.", "Choose YoLink when long range and device-to-device alarm pairing matter.", "Choose Aqara for Aqara ecosystem automations."],
    compareSlugs: ["govee-wifi-water-leak-detector-3-pack", "yolink-lora-water-alarm-bundle", "aqara-water-leak-sensor-3-pack-hub-kit"],
    sources: [amazonSource("B0DFCMJH5L", "Exact linked listing; confirm SWS0A41 model, four-sensor quantity, base station, seller, and app requirements.")],
    offers: [
      {
        merchant: "Amazon US",
        url: amazonUrl("B0DFCMJH5L"),
        label: "Check X-Sense kit price on Amazon",
        priceNote: "Confirm ASIN B0DFCMJH5L, SWS0A41 model, four sensors, base station, and seller.",
      },
    ],
  },
  {
    site: "smarthome",
    slug: "yolink-lora-water-alarm-bundle",
    asin: "B0F24K2R8T",
    amazonTitle: "YoLink LoRa Smart Water Alarm Bundle: Hub + 2 Water Leak Sensors & 110dB Wireless Siren",
    seoTitle: "YoLink LoRa Smart Water Alarm Bundle Review Guide",
    updatedAt,
    name: "YoLink LoRa Smart Water Alarm Bundle",
    brand: "YoLink",
    category: "automation",
    image: "/images/affiliate/smarthome-yolink-lora-water-alarm-bundle.svg",
    summary: "A buying guide to the YoLink LoRa leak-alarm bundle, including the hub, two water leak sensors, wireless siren, long-range claims, optional SMS/email/push alerts, and device-to-device alarm pairing.",
    verdict: "YoLink is the long-range choice for basements, detached spaces, and awkward utility rooms where ordinary Wi-Fi or Zigbee sensors are risky.",
    whyItMatters: "Leak sensors often live in the worst wireless locations in a home. A long-range hub and siren bundle can be more valuable than a cheaper sensor that cannot report reliably.",
    bestFor: "Large homes, basements, and outbuildings needing long-range leak alerts",
    priceBand: "$$",
    rating: 4.4,
    scores: [
      { label: "Long-range fit", value: 9 },
      { label: "Alarm routing", value: 8 },
      { label: "Starter coverage", value: 6 },
    ],
    pros: ["Hub, two sensors, and siren bundle listed", "LoRa long-range positioning is useful for basements and outbuildings", "Device-to-device pairing can trigger local alarm behavior without relying only on Wi-Fi"],
    cons: ["Only two sensors in the linked bundle, so add-ons may be needed", "YoLink ecosystem planning matters before expanding", "Some notification paths may have limits or service terms to review"],
    specs: {
      ASIN: "B0F24K2R8T",
      Listing: "Hub plus 2 water leak sensors and wireless siren listed",
      Radio: "YoLink LoRa device ecosystem",
      Alerts: "Email, SMS/text, push, and siren alarm paths listed",
      "Alarm": "110dB wireless siren listed",
    },
    evidence: [
      "Amazon listing title verified as YoLink LoRa Smart Water Alarm Bundle",
      "Listing bullets reference LoRa range, optional email/SMS/push alerts, and device-to-device pairing",
      "The bundle is best compared on range and siren behavior, not raw sensor count",
      "Add sensor cost should be included for homes with more than two leak points",
    ],
    editorialSections: [
      { heading: "Range is the reason to buy it", body: "YoLink is most compelling where Wi-Fi, Zigbee, or Thread sensors are likely to be weak: basements, garages, detached utility spaces, or far ends of the house." },
      { heading: "Two sensors may not be enough", body: "The linked bundle starts with two sensors. Count water heater, washer, sump pump, HVAC condensate, refrigerator line, dishwasher, toilets, and sink cabinets before assuming the kit is complete." },
      { heading: "Siren routing needs testing", body: "Test the siren, phone alerts, and any device-to-device pairing while someone is home. A quiet app notification is not a full leak-response plan." },
    ],
    alternatives: ["Choose X-Sense when four sensors are more important than long range.", "Choose Govee for a low-cost gateway kit.", "Choose Aqara for Aqara ecosystem automations."],
    compareSlugs: ["x-sense-sws0a41-water-leak-detector-kit", "govee-wifi-water-leak-detector-3-pack", "aqara-water-leak-sensor-3-pack-hub-kit"],
    sources: [amazonSource("B0F24K2R8T", "Exact linked listing; confirm hub, two-sensor quantity, siren, seller, notification terms, and current availability.")],
    offers: [
      {
        merchant: "Amazon US",
        url: amazonUrl("B0F24K2R8T"),
        label: "Check YoLink bundle on Amazon",
        priceNote: "Confirm ASIN B0F24K2R8T, hub, two sensors, siren, seller, and notification terms.",
      },
    ],
  },
];

export const smartHomeLeakExpansionRoundups: Roundup[] = [
  {
    site: "smarthome",
    slug: "best-water-leak-sensors-for-sinks-water-heaters",
    title: "Best Water Leak Sensors for Sinks, Water Heaters and Basements",
    dek: "Compare Aqara, Govee, X-Sense, and YoLink by sensor count, hub requirements, alarm path, wireless range, and the rooms each kit should cover first.",
    category: "automation",
    intent: "choose a leak sensor kit before a washer, sink, basement, water heater, or sump pump leak becomes expensive",
    intro: "The right leak sensor is the one that covers the risky spot and gets an alert to the right person. Sensor count, hub range, local siren behavior, and app notifications matter more than a generic smart-home logo.",
    sections: [
      { heading: "Buy enough sensors for real risk points", body: "A single sensor under the water heater is useful, but many homes also need washer, dishwasher, refrigerator line, sink cabinet, sump pump, toilet, and HVAC condensate coverage." },
      { heading: "Match the wireless path to the room", body: "Wi-Fi gateway kits are simple near the router; Zigbee works well inside an existing hub ecosystem; LoRa is stronger for far basements or detached spaces." },
      { heading: "Local alarm plus remote alert is best", body: "A siren or base station helps when someone is home. Push, email, or SMS alerts help when nobody is nearby. Test both paths." },
    ],
    decisionGuide: [
      { label: "Aqara", detail: "Best when Aqara automations and hub-based smart-home control are already part of the plan." },
      { label: "Govee", detail: "Best value path for three common leak points with gateway-based Wi-Fi alerts." },
      { label: "X-Sense", detail: "Best when four sensors and a base station cover the basement or utility area." },
      { label: "YoLink", detail: "Best when range, siren routing, and outbuilding or basement placement are the hard parts." },
    ],
    methodology: ["Verified Amazon ASIN/title for each linked kit", "Compared alert path, sensor count, hub requirement, and placement risk", "Prioritized coverage of real leak sources over generic smart-home feature lists"],
    productSlugs: ["aqara-water-leak-sensor-3-pack-hub-kit", "govee-wifi-water-leak-detector-3-pack", "x-sense-sws0a41-water-leak-detector-kit", "yolink-lora-water-alarm-bundle"],
    faqs: [
      { question: "Where should I put the first leak sensor?", answer: "Start under the water heater or washer, then cover sink cabinets, dishwasher, refrigerator water line, sump pump, toilets, and HVAC condensate areas." },
      { question: "Is a Wi-Fi water leak sensor better than Zigbee?", answer: "Not automatically. Wi-Fi gateway kits are simple; Zigbee can be better inside a hub ecosystem; LoRa is useful when range is the problem." },
      { question: "Do leak sensors shut off water automatically?", answer: "These kits are primarily alert products unless paired with compatible valves or controllers. Automatic shutoff requires separate hardware and careful installation." },
    ],
  },
  {
    site: "smarthome",
    slug: "aqara-vs-govee-vs-xsense-vs-yolink-leak-sensors",
    title: "Aqara vs Govee vs X-Sense vs YoLink Water Leak Sensors",
    dek: "A decision-first comparison of four leak-sensor paths: Aqara automations, Govee value, X-Sense four-sensor coverage, and YoLink long-range siren bundles.",
    category: "automation",
    intent: "compare leak detector ecosystems before choosing a kit",
    intro: "These products all detect water, but they solve different buying problems. The best choice depends on whether the home needs smart-home automation, cheap multi-point coverage, a loud base station, or long-range placement.",
    sections: [
      { heading: "Aqara is for ecosystem buyers", body: "Aqara belongs on the shortlist when leak alerts should connect to Aqara hubs, automations, lights, plugs, or future valve control." },
      { heading: "Govee and X-Sense are coverage-first", body: "Govee is the lower-cost three-pack path. X-Sense adds a four-sensor base-station kit that fits basement and utility-room planning." },
      { heading: "YoLink is for difficult radio paths", body: "When the sensor sits far from the router or behind basement walls, YoLink's LoRa ecosystem can be the practical reason to spend more." },
    ],
    decisionGuide: [
      { label: "Pick Aqara", detail: "You already want Aqara hub automations and can confirm the kit contents." },
      { label: "Pick Govee", detail: "You want three common leak points covered with a simple Wi-Fi gateway kit." },
      { label: "Pick X-Sense", detail: "You want four sensors, a base station, and app alerts more than ecosystem depth." },
      { label: "Pick YoLink", detail: "You need long range or a wireless siren bundle for hard-to-reach spaces." },
    ],
    methodology: ["Separated sensor count from wireless architecture", "Checked local alarm and remote alert paths", "Flagged kit contents and add-on cost as checkout risks"],
    productSlugs: ["aqara-water-leak-sensor-3-pack-hub-kit", "govee-wifi-water-leak-detector-3-pack", "x-sense-sws0a41-water-leak-detector-kit", "yolink-lora-water-alarm-bundle"],
    faqs: [
      { question: "Which one is best for a basement?", answer: "X-Sense is attractive when four sensors and a base station cover several basement points. YoLink is stronger when range through floors or walls is the hard part." },
      { question: "Which one is best for Apple Home?", answer: "Do not buy only from the Apple logo. Confirm whether the selected kit and hub expose the leak sensor state to the ecosystem you actually use." },
      { question: "How many leak sensors do I need?", answer: "Count actual water sources: water heater, washer, dishwasher, refrigerator line, sump pump, sink cabinets, toilets, HVAC condensate, and any basement drains." },
    ],
  },
];

export const smartHomeLeakExpansionGuides: Guide[] = [
  {
    site: "smarthome",
    slug: "water-leak-sensor-placement-guide",
    title: "Water Leak Sensor Placement Guide",
    dek: "Put sensors where water appears first: under appliances, inside sink cabinets, by shutoff valves, near sump pumps, and around basement equipment.",
    category: "automation",
    updatedAt,
    relatedProducts: ["govee-wifi-water-leak-detector-3-pack", "x-sense-sws0a41-water-leak-detector-kit", "yolink-lora-water-alarm-bundle", "aqara-water-leak-sensor-3-pack-hub-kit"],
    relatedRoundups: ["best-water-leak-sensors-for-sinks-water-heaters", "aqara-vs-govee-vs-xsense-vs-yolink-leak-sensors"],
    sections: [
      { heading: "Start with the highest-cost leaks", body: "Water heaters, washing machines, sump pumps, dishwashers, refrigerator water lines, and upstairs bathrooms deserve attention before lower-risk corners." },
      { heading: "Put the sensor at the first wet point", body: "A sensor should touch the floor or drip path where water arrives early. Do not hide it behind a lip, mat, box, or appliance foot that keeps water away." },
      { heading: "Leave room for batteries and cleaning", body: "If the sensor cannot be reached without moving an appliance, battery replacement and testing will stop happening." },
      { heading: "Test every alert path", body: "Trigger a small safe test with a damp cloth or manufacturer-approved method, then verify the local alarm, phone notification, email, SMS, and household sharing path." },
    ],
    sources: [
      amazonSource("B07J9HZ5VN", "Example Wi-Fi gateway leak-sensor kit."),
      amazonSource("B0DFCMJH5L", "Example multi-sensor base-station kit."),
    ],
  },
  {
    site: "smarthome",
    slug: "wifi-vs-zigbee-vs-lora-water-leak-sensor-guide",
    title: "Wi-Fi vs Zigbee vs LoRa Water Leak Sensors",
    dek: "Choose the radio by room and response plan: simple Wi-Fi gateway kits, hub-based Zigbee automations, or long-range LoRa for basements and outbuildings.",
    category: "automation",
    updatedAt,
    relatedProducts: ["govee-wifi-water-leak-detector-3-pack", "aqara-water-leak-sensor-3-pack-hub-kit", "yolink-lora-water-alarm-bundle", "x-sense-sws0a41-water-leak-detector-kit"],
    relatedRoundups: ["aqara-vs-govee-vs-xsense-vs-yolink-leak-sensors", "best-water-leak-sensors-for-sinks-water-heaters"],
    sections: [
      { heading: "Wi-Fi gateway kits are the simple path", body: "A kit such as Govee or X-Sense can cover several sensors through a base station or gateway, but the gateway still needs stable power, app setup, and 2.4GHz Wi-Fi." },
      { heading: "Zigbee fits hub automations", body: "Aqara-style kits make sense when leak detection should trigger lights, sirens, plugs, valves, or scenes in an existing hub ecosystem." },
      { heading: "LoRa solves hard distance problems", body: "YoLink's long-range positioning is useful when the sensor lives in a basement, garage, utility room, or outbuilding where normal Wi-Fi is unreliable." },
      { heading: "The alert path matters more than the radio name", body: "Any protocol can fail if phone permissions, account sharing, hub power, router coverage, or batteries are ignored. Test alerts after placement and again after app or network changes." },
    ],
    sources: [
      amazonSource("B0F9987FZ4", "Example Aqara Zigbee kit listing."),
      amazonSource("B0F24K2R8T", "Example YoLink LoRa leak-alarm bundle listing."),
    ],
  },
];
