import type { Guide, Tool } from "./types";

const updatedAt = "July 1, 2026";

export const topicClusterGuides: Guide[] = [
  {
    site: "baby",
    slug: "ergobaby-omni-breeze-cleaning-guide",
    title: "How to Clean an Ergobaby Omni Breeze",
    dek: "Protect buckles, straps, mesh, and carrier shape while handling everyday drool, spills, and full-machine washes.",
    category: "travel",
    updatedAt,
    relatedProducts: ["ergobaby-omni-breeze-carrier"],
    relatedRoundups: ["babybjorn-harmony-vs-ergobaby-omni-breeze", "best-baby-carriers-and-sleep-routine-upgrades"],
    sources: [
      { name: "Ergobaby care instructions", url: "https://ergobaby.com/care-instructions", note: "Official carrier washing and care guidance." },
      { name: "Omni Breeze instructions", url: "https://ergobaby.com/instructions-omni-breeze/", note: "Official model setup and inspection guidance." },
    ],
    sections: [
      { heading: "Read the sewn-in label first", body: "Color, trim, and regional versions can have model-specific care instructions. Treat the label on the carrier as the controlling source before using a washer, detergent, or dryer." },
      { heading: "Spot-clean between full washes", body: "Address drool and small spills with a damp cloth and mild detergent so the carrier does not need an unnecessary full wash. Keep harsh cleaners, bleach, and fabric softener away unless the label explicitly allows them." },
      { heading: "Fasten hardware before machine washing", body: "Close buckles, secure loose straps, and use a laundry bag or pillowcase if the official instructions permit. A gentle cold cycle reduces repeated impact on hardware and mesh." },
      { heading: "Air-dry and inspect before reuse", body: "Let the carrier dry completely with its shape supported. Check webbing, seams, buckles, elastic, and mesh before placing the baby back in it." },
    ],
  },
  {
    site: "baby",
    slug: "babybjorn-harmony-newborn-fit-checklist",
    title: "BabyBjörn Harmony Newborn Fit Checklist",
    dek: "Check minimum size, inward-facing setup, leg position, head support, airway visibility, and caregiver adjustment.",
    category: "travel",
    updatedAt,
    relatedProducts: ["babybjorn-carrier-harmony"],
    relatedRoundups: ["babybjorn-harmony-vs-ergobaby-omni-breeze", "best-baby-carriers-and-sleep-routine-upgrades"],
    sources: [
      { name: "BabyBjörn Carrier Harmony", url: "https://www.babybjorn.com/products/baby-carriers/baby-carrier-harmony/", note: "Official size, position, and adjustment guidance." },
      { name: "BabyBjörn Harmony manual", url: "https://www.babybjorn.com/customer-service/manuals/", note: "Official manuals and model-specific instructions." },
    ],
    sections: [
      { heading: "Confirm the stated minimums", body: "Use the carrier only after the baby meets the listed weight and length requirements. A newborn begins front inward; later carry positions have separate developmental limits." },
      { heading: "Set the newborn height position", body: "Follow the Harmony manual for zipper, head-support, and leg-position settings. Do not reuse the configuration shown for an older baby." },
      { heading: "Keep the airway visible", body: "The baby's face should remain visible, with the chin clear of the chest and the head supported according to the instructions. Reposition immediately if the baby slumps or the fabric covers the face." },
      { heading: "Adjust each caregiver separately", body: "Set the waist belt, back support, and shoulder straps for the current wearer. Complete the first short carry with another adult nearby and recheck the fit after moving." },
    ],
  },
  {
    site: "baby",
    slug: "baby-carrier-hot-weather-and-caregiver-fit-guide",
    title: "Baby Carrier Guide for Hot Weather and Different Caregiver Builds",
    dek: "Compare mesh, waistband shape, shoulder-strap routing, clothing, trip length, and return policies without promising a universally cool fit.",
    category: "travel",
    updatedAt,
    relatedProducts: ["ergobaby-omni-breeze-carrier", "babybjorn-carrier-harmony"],
    relatedRoundups: ["babybjorn-harmony-vs-ergobaby-omni-breeze"],
    sources: [
      { name: "Ergobaby Omni Breeze", url: "https://ergobaby.com/omni-breeze-baby-carrier-all", note: "Official material, size, and adjustment information." },
      { name: "BabyBjörn Carrier Harmony", url: "https://www.babybjorn.com/products/baby-carriers/baby-carrier-harmony/", note: "Official material, size, and adjustment information." },
    ],
    sections: [
      { heading: "Mesh reduces fabric resistance, not shared body heat", body: "Both baby and adult still produce heat where their bodies touch. Shade, light clothing, hydration, pace, humidity, and shorter carries can matter as much as the carrier material." },
      { heading: "Check the adjustment range on the actual wearer", body: "Product ranges do not describe torso length, shoulder shape, waist placement, or pressure sensitivity. Use the return window to test strap access and load distribution with realistic weight." },
      { heading: "Do not share one strap setup", body: "Mark or remember each caregiver's settings and reset the carrier when it changes hands. The baby should remain high, centered, visible, and supported after every adjustment." },
      { heading: "Choose another tool when conditions demand it", body: "A stroller, shaded break, or shorter outing can be safer and more comfortable when either person overheats or when the carrier cannot be adjusted without pressure or slumping." },
      { heading: "Treat airflow as one decision factor", body: "Mesh can reduce fabric resistance, but trip length, humidity, shade, clothing, waistband pressure, and safe positioning still control whether a carrier is practical. Compare the complete fit instead of choosing from a mesh label alone." },
    ],
  },
  {
    site: "network",
    slug: "deco-be63-be67-two-pack-vs-three-pack",
    title: "Deco BE63 2-Pack vs 3-Pack: Which Pack Do You Need?",
    dek: "Start with two Deco nodes when one satellite covers the measured weak zone; buy three only for a separate floor or wing with a strong wireless or Ethernet path.",
    category: "wifi",
    updatedAt: "August 8, 2026",
    image: "/images/affiliate/network-tp-link-deco-be63-wifi-7-mesh-realistic.webp",
    imageAlt: "Three Wi-Fi 7 mesh nodes placed on a home floor plan for a two-pack versus three-pack decision",
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh", "tp-link-deco-be67-wifi-7-mesh"],
    relatedRoundups: ["tp-link-deco-be67-vs-be63", "best-mesh-wifi-for-apartments-and-homes"],
    relatedGuides: ["deco-wifi-7-single-unit-vs-two-pack", "deco-be63-be67-wired-backhaul-port-checklist", "is-deco-be67-worth-it-for-gigabit-internet"],
    comparisonTable: {
      title: "Two-pack or three-pack decision",
      columns: ["Two-pack", "Three-pack"],
      rows: [
        { label: "Best starting layout", values: ["Router zone plus one measured weak zone", "Three distinct floors, wings, or separated coverage zones"] },
        { label: "Wireless backhaul", values: ["Easier to keep one satellite on a strong upstream link", "Useful only when the middle node strengthens the path; avoid three weak hops"] },
        { label: "Ethernet backhaul", values: ["Two wired placements often cover a compact or medium home", "Makes sense when three wired rooms need their own nearby access point"] },
        { label: "Cost check", values: ["Leaves budget for a switch, cable, or better placement", "Compare the exact three-pack with a two-pack plus one compatible add-on"] },
        { label: "Common mistake", values: ["Putting the satellite inside the dead zone", "Crowding nodes together because the third unit came in the box"] },
      ],
    },
    sources: [
      { name: "TP-Link Deco BE63", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be63/", note: "Official pack and coverage information." },
      { name: "TP-Link Deco BE67", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be67/", note: "Official pack and coverage information." },
      { name: "TP-Link: How many Deco units do I need?", url: "https://www.tp-link.com/us/support/faq/1588/", note: "Official April 2026 guidance that added units do not automatically improve throughput or stability and that layout and backhaul control the answer." },
      { name: "TP-Link Deco placement guide", url: "https://www.tp-link.com/us/support/faq/1446/", note: "Official placement and experimentation guidance for satellite units." },
      { name: "TP-Link Ethernet backhaul guide", url: "https://www.tp-link.com/us/support/faq/1794/", note: "Official setup order, router-mode topology, switch, and mixed-backhaul guidance." },
    ],
    sections: [
      { heading: "Decision step 1: mark the failed zones", body: "Draw the modem, work areas, TVs, bedrooms, outdoor edge, floors, and thick barriers. Start with a two-pack when the main unit plus one well-placed satellite can serve the important zones. A third node earns its place only when it serves a separate floor or wing, or creates a stronger intermediate path." },
      { heading: "Decision step 2: test the upstream link", body: "A wireless satellite must still hear a strong upstream node. Place it before the dead zone, then measure latency and throughput where it will sit. TP-Link explicitly notes that adding units does not always improve throughput or stability; a third weak link can add roaming and airtime complexity without repairing coverage." },
      { heading: "Decision step 3: use Ethernet to place for clients", body: "Ethernet backhaul lets a satellite sit where client coverage is needed instead of where a wireless relay remains strong. In router mode, keep the switch and satellites on the LAN side of the main Deco. Check the negotiated speed of every switch port and cable before paying for a faster mesh model." },
      { heading: "Decision step 4: add the third node only after measurement", body: "Install two units, update firmware, test the real rooms, and inspect the Deco app's node relationship before opening or buying a third. Add it when one important zone remains weak and the proposed location has either a strong wireless upstream path or Ethernet." },
      { heading: "Choose BE63 versus BE67 after pack size", body: "Node count fixes coverage geometry; the model choice fixes radio and port capacity. BE63 is the disciplined choice for four 2.5GbE ports per unit and a 2.5Gbps wired plan. Compare BE67 when a defined 10GbE path or higher wireless capacity has a job. Do not buy one fewer node merely to afford a faster model if the layout still needs coverage." },
      { heading: "Match pack size, hardware, and region when comparing price", body: "Retail listings can describe the BE63 as a 2-pack, 3-pack, 2-piece, 3-piece, or whole-home system. Normalize price to the same model, hardware version, region, power accessories, seller, and node count. Also compare a two-pack plus one compatible add-on because bundle pricing changes." },
    ],
  },
  {
    site: "network",
    slug: "is-deco-be67-worth-it-for-gigabit-internet",
    title: "Is Deco BE67 Worth It? 1Gbps vs 2.5Gbps vs 10GbE",
    dek: "Decide whether Deco BE67 is worth the upgrade by separating WAN speed, local transfers, wireless backhaul, client support, and the actual 10GbE path.",
    category: "wifi",
    updatedAt: "July 13, 2026",
    relatedProducts: ["tp-link-deco-be67-wifi-7-mesh", "tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["tp-link-deco-be67-vs-be63"],
    sources: [
      { name: "TP-Link Deco BE67", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be67/", note: "Official wireless and Ethernet specifications." },
      { name: "TP-Link Deco BE63", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be63/", note: "Official comparison specifications." },
    ],
    sections: [
      { heading: "Gigabit internet does not require a 10GbE router", body: "BE67 can still provide coverage and capacity benefits, but its largest Ethernet advantage remains unused when the modem, switch, storage, and clients stay at gigabit." },
      { heading: "A 2.5Gbps plan can fit either model", body: "BE63's four 2.5GbE ports may be more convenient for several wired devices. BE67 makes more sense when one faster 10GbE path or greater wireless-backhaul capacity has a defined job." },
      { heading: "Local traffic can justify the upgrade", body: "Fast NAS transfers, workstation backups, or a 10GbE switch can use capacity even when the internet is slower. Draw that local path before paying for it." },
      { heading: "Future-proofing needs a date and device list", body: "List the expected modem, service tier, clients, switch, and storage upgrades. A vague future plan is weaker justification than fixing placement or adding Ethernet today." },
    ],
  },
  {
    site: "network",
    slug: "deco-mesh-connection-drops-troubleshooting",
    title: "Deco Mesh Connection Drops: A Troubleshooting Checklist",
    dek: "Separate ISP, modem, main-node, backhaul, roaming, cable, and client problems before resetting the whole network.",
    category: "wifi",
    updatedAt,
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh", "tp-link-deco-be67-wifi-7-mesh"],
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes", "tp-link-deco-be67-vs-be63"],
    sources: [
      { name: "TP-Link Deco support", url: "https://www.tp-link.com/us/support/faq/2428/", note: "Official Deco connectivity troubleshooting." },
      { name: "TP-Link Ethernet backhaul FAQ", url: "https://www.tp-link.com/us/support/faq/1794/", note: "Official topology and backhaul guidance." },
    ],
    sections: [
      { heading: "Define what actually drops", body: "Record whether one client, one node, Wi-Fi, local LAN, DNS, or the entire internet path fails. The LED, Deco app, modem status, and a wired test help narrow the layer." },
      { heading: "Test the modem and main Deco first", body: "Connect one known-good wired client where possible, inspect the modem or ONT, and check the ISP before moving every satellite. A mesh cannot repair an unstable upstream link." },
      { heading: "Simplify backhaul temporarily", body: "Remove suspect switches, wall jacks, and cables one at a time. For wireless satellites, move one node closer to the main unit and compare stability." },
      { heading: "Change one variable and keep a log", body: "Record firmware, topology, client model, time, and result. Avoid factory-resetting first because it removes evidence and introduces several new variables at once." },
    ],
  },
  {
    site: "pet",
    slug: "air-purifier-placement-near-litter-box",
    title: "Where to Place an Air Purifier Near a Litter Box",
    dek: "Capture airborne particles without blocking intake, blowing litter, crowding the cat, or treating filtration as a substitute for scooping.",
    category: "home-care",
    updatedAt,
    relatedProducts: ["levoit-vital-200s-p-air-purifier", "shark-neverchange-max-air-purifier"],
    relatedRoundups: ["levoit-vital-200s-p-vs-shark-neverchange-max", "best-pet-odor-and-litter-upgrades"],
    sources: [
      { name: "EPA air cleaners guidance", url: "https://www.epa.gov/indoor-air-quality-iaq/air-cleaners-and-air-filters-home", note: "Primary room-air-cleaner and source-control guidance." },
    ],
    sections: [
      { heading: "Keep intake and exhaust open", body: "Use the purifier maker's wall and furniture clearances. A unit hidden behind the litter box or inside a cabinet cannot circulate the room effectively." },
      { heading: "Avoid blowing directly across litter", body: "Strong exhaust can move dust and litter or make the cat avoid the box. Place the purifier nearby but outside the digging and exit path." },
      { heading: "Protect the purifier from accidents", body: "Keep cords, controls, filters, and air-quality sensors away from spray, tracked litter, and cleaning liquids. Use a stable floor position that cannot be tipped." },
      { heading: "Source control stays first", body: "Scoop, replace litter, clean the box, wash nearby surfaces, and ventilate appropriately. Filtration supports the routine but cannot remove waste that remains in the room." },
      { heading: "Treat carbon as a consumable", body: "Odor control depends on enough gas-phase media such as activated carbon. A thin or exhausted carbon layer cannot keep up with persistent litter odor regardless of fan speed, so price and inspect the correct replacement filter." },
      { heading: "Keep filter access practical", body: "Do not wedge the purifier behind the litter area. Put it where the prefilter can be cleaned and the main filter can be replaced without spilling captured hair and dust back into the room." },
    ],
  },
  {
    site: "pet",
    slug: "levoit-vital-200s-p-filter-cost-and-maintenance",
    title: "Levoit Vital 200S-P Filter Cost and Maintenance Guide",
    dek: "Plan washable pre-filter cleaning, main-filter replacement, sensor care, and annual cost before treating the purifier price as the full expense.",
    category: "home-care",
    updatedAt,
    relatedProducts: ["levoit-vital-200s-p-air-purifier"],
    relatedRoundups: ["levoit-vital-200s-p-vs-shark-neverchange-max"],
    sources: [
      { name: "Levoit Vital 200S-P", url: "https://levoit.com/products/vital-200s-p-smart-air-purifier", note: "Official filter and maintenance information." },
      { name: "Levoit support", url: "https://levoit.com/pages/support", note: "Official manuals and replacement guidance." },
    ],
    sections: [
      { heading: "The washable part is the pre-filter", body: "The main filter is still a replaceable consumable. Follow the manual for separating, cleaning, drying, and reinstalling the washable pre-filter." },
      { heading: "Pet rooms can load filters faster", body: "Hair, dust, dander, smoke, cooking particles, and fan runtime affect maintenance. Inspect the unit rather than treating one calendar interval as universal." },
      { heading: "Price the correct genuine replacement", body: "Confirm the Vital 200S-P filter model, seller, availability, and multipack terms. Add the expected replacement interval to a one- and three-year ownership estimate." },
      { heading: "Clean sensors and clear airflow", body: "Dust around the intake and sensor can affect readings and airflow. Unplug the unit and follow the manual rather than spraying cleaner into openings." },
    ],
  },
  {
    site: "smarthome",
    slug: "aqara-hub-m3-vs-m2",
    title: "Aqara Hub M3 vs M2: Matter, Thread, PoE & Upgrade Cost",
    dek: "Compare Aqara Hub M3 and M2 by Matter roles, Thread, Zigbee capacity, PoE, USB power, infrared control, migration work, and who should keep the M2.",
    category: "automation",
    updatedAt: "July 16, 2026",
    image: "/images/affiliate/smarthome-aqara-hub-m3-realistic.webp",
    imageAlt: "A smart-home hub, contact sensor, router, and Ethernet cable arranged for an Aqara hub upgrade decision",
    comparisonTable: {
      title: "Hub M3 and Hub M2 official-spec comparison",
      columns: ["Aqara Hub M3", "Aqara Hub M2"],
      rows: [
        { label: "Best fit", values: ["New mixed Aqara, Matter, and Thread systems", "Established Aqara Zigbee systems"] },
        { label: "Zigbee", values: ["Aqara Zigbee hub; up to 127 combined Thread/Zigbee devices", "Zigbee 3.0; up to 128 Aqara Zigbee devices with repeaters as required"] },
        { label: "Matter roles", values: ["Matter controller and Matter bridge", "Matter bridge support for compatible Aqara devices; not the same M3 controller foundation"] },
        { label: "Thread", values: ["Thread border router and Aqara Thread-device support", "No Thread radio or border-router role"] },
        { label: "Network", values: ["2.4/5GHz Wi-Fi, Ethernet, WPA3", "2.4GHz Wi-Fi and Ethernet"] },
        { label: "Power", values: ["USB-C 5V 2A or PoE 48V 0.27A; adapter not included", "Micro-USB 5V 1A; no PoE"] },
        { label: "Infrared", values: ["360-degree IR with supported feedback and AC Matter use cases", "360-degree IR control; ecosystem exposure varies"] },
        { label: "Local storage", values: ["8GB encrypted eMMC", "No equivalent 8GB local-storage claim on the official M2 page"] },
        { label: "Migration burden", values: ["Device, automation, ecosystem, and IR-scene verification required", "None when the current system remains stable"] },
      ],
    },
    relatedProducts: ["aqara-hub-m3"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    relatedGuides: ["aqara-hub-m3-matter-thread-setup", "aqara-hub-m3-home-assistant-matter-guide", "matter-thread-wifi-zigbee-device-checklist"],
    sources: [
      { name: "Aqara Hub M3", url: "https://us.aqara.com/products/hub-m3", note: "Current official M3 roles, capacity, network, power, storage, dimensions, and included components." },
      { name: "Aqara Hub M2", url: "https://www.aqara.com/us/product/hub-m2/", note: "Official M2 roles and specifications." },
      { name: "Aqara Hub M3 developer documentation", url: "https://opendoc.aqara.com/en/docs/AqaraDevice/Hub-M3.html", note: "Official Matter controller, bridge, Thread, ecosystem, and device-type documentation." },
      { name: "Aqara Hub M3 user manual", url: "https://www.aqara.com/wp-content/uploads/2024/05/M3-User-Manual-1.pdf", note: "Official setup, model, power, networking, mounting, and reset reference." },
    ],
    sections: [
      { heading: "Short answer: upgrade for a missing role, not for the model number", body: "M3 is the better foundation for a new Aqara-centered system that needs Thread, third-party Matter control in Aqara Home, Matter bridging, PoE, or edge-hub features. M2 remains the lower-friction choice when it already runs stable Zigbee automations and none of those new roles solves a documented problem." },
      { heading: "M3 adds Thread and a broader Matter-controller role", body: "M3 can act as a Thread border router, commission supported third-party Matter devices into Aqara Home, and bridge supported Aqara devices to other Matter controllers. M2 is primarily a Zigbee 3.0 hub with Ethernet, infrared control, and ecosystem bridging for compatible devices." },
      { heading: "PoE can change where the hub lives", body: "M3 accepts compatible PoE, so one Ethernet run can provide network and power at a central wall, ceiling, or equipment location. M2 has Ethernet but uses separate Micro-USB power. PoE adds value only when the switch, injector, cable path, and mounting location are already planned." },
      { heading: "M2 can remain beside M3 during migration", body: "Aqara describes M3 as an edge hub that can coordinate an Aqara hub cluster, but that does not eliminate migration work. Keeping M2 active while a small set of devices and automations is verified gives the household a rollback path and avoids resetting a stable installation in one session." },
      { heading: "Matter bridging does not expose every feature", body: "A bridged Zigbee device remains Zigbee, and the destination ecosystem receives only the functions represented by Aqara's bridge and its own Matter implementation. Advanced Aqara settings, infrared scenes, vendor-specific data, and some automations can remain available only in Aqara Home." },
      { heading: "Home Assistant does not make M3 automatically unnecessary", body: "Home Assistant can run its own Matter controller and Thread border router, while M3 can bridge supported Aqara devices into Home Assistant. The useful question is whether Aqara Home automations, Zigbee migration, PoE, infrared control, or Aqara Thread devices justify keeping M3 in that architecture." },
      { heading: "Price the accessories and migration time", body: "Compare the current M3 price with any required PoE switch or injector, USB power adapter, Ethernet run, and the time needed to rebuild or verify automations. A discounted M3 is not a saving when the existing M2 already covers every real use case." },
      { heading: "Choose M3 when", body: "Choose M3 for a new Aqara-heavy installation, planned Aqara Thread devices, supported third-party Matter devices inside Aqara Home, PoE placement, or a deliberate Matter-bridge path into Apple Home, Google Home, SmartThings, Alexa, or Home Assistant." },
      { heading: "Keep M2 when", body: "Keep M2 when its Zigbee automations are stable, Ethernet and infrared already solve the routine, another controller handles Matter and Thread, and no current device requires M3. Revisit the decision when a specific new device or automation creates a missing role." },
    ],
  },
  {
    site: "smarthome",
    slug: "aqara-hub-m3-home-assistant-matter-guide",
    title: "Aqara Hub M3 with Home Assistant: Matter Bridge Setup Guide",
    dek: "Plan the Aqara Hub M3 and Home Assistant Matter path, including controller roles, bridge pairing, IPv6 and mDNS checks, Thread boundaries, and missing feature risks.",
    category: "automation",
    updatedAt: "July 16, 2026",
    image: "/images/affiliate/smarthome-aqara-hub-m3-realistic.webp",
    imageAlt: "Smart-home hub, contact sensor, router, and Ethernet cable arranged for a Home Assistant Matter bridge setup",
    comparisonTable: {
      title: "Assign each platform one clear job",
      columns: ["Primary job", "Do not assume"],
      rows: [
        { label: "Home Assistant Matter integration", values: ["Matter controller connected to the Home Assistant Matter Server", "It is not itself a bridge that turns every Home Assistant entity into Matter"] },
        { label: "Aqara Hub M3", values: ["Aqara hub, Matter bridge/controller, and Thread border router", "It does not expose every Aqara feature or child device to Home Assistant"] },
        { label: "Aqara Zigbee child device", values: ["Stays on the Aqara Zigbee network and can be bridged when supported", "Matter bridging does not convert its radio to Thread"] },
        { label: "Aqara Matter-over-Thread device", values: ["Uses Matter for control and Thread for transport", "An M3 border router does not automatically merge unrelated Thread credentials"] },
        { label: "Home network", values: ["Carries IPv6 and mDNS discovery between controller and bridge", "VLAN isolation or multicast filtering will not always work without deliberate rules"] },
      ],
    },
    relatedProducts: ["aqara-hub-m3", "aqara-door-and-window-sensor-p2"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    relatedGuides: ["aqara-hub-m3-vs-m2", "aqara-hub-m3-matter-thread-setup", "matter-thread-wifi-zigbee-device-checklist"],
    sources: [
      { name: "Home Assistant Matter integration", url: "https://www.home-assistant.io/integrations/matter", note: "Official Matter controller, bridge, multi-admin, IPv6, mDNS, Thread, and troubleshooting guidance." },
      { name: "Aqara Hub M3 developer documentation", url: "https://opendoc.aqara.com/en/docs/AqaraDevice/Hub-M3.html", note: "Official confirmation that M3 can bridge supported Aqara devices to Home Assistant and other Matter ecosystems." },
      { name: "Aqara Hub M3 product page", url: "https://us.aqara.com/products/hub-m3", note: "Official M3 protocol, network, power, storage, controller, and bridge information." },
      { name: "Aqara Hub M3 user manual", url: "https://www.aqara.com/wp-content/uploads/2024/05/M3-User-Manual-1.pdf", note: "Official pairing, model, network, reset, and installation reference." },
    ],
    sections: [
      { heading: "Use the Matter bridge path when local common controls are enough", body: "M3 can bridge supported Aqara child devices into Home Assistant's Matter controller while Aqara Home continues to manage the native hub. This is useful for local common controls, but it can expose fewer entities and settings than Aqara's own app or a model-specific integration." },
      { heading: "Install Home Assistant's official Matter path first", body: "Home Assistant OS users should add the Matter integration and use the supported Matter Server app path. Confirm the integration is healthy before opening a new pairing window on M3; otherwise two setup problems become one ambiguous failure." },
      { heading: "Generate the pairing code from the Aqara side", body: "Aqara's current M3 instructions place third-party Matter ecosystem sharing on the hub device page in Aqara Home. Generate or display a fresh pairing code there, then use the Home Assistant Companion App's Matter commissioning flow. Keep the code private and close the pairing window when setup completes." },
      { heading: "Keep M3 and Home Assistant on a discovery-friendly LAN", body: "Matter depends on IPv6 and mDNS across the local network. Begin with M3 and Home Assistant on the same ordinary LAN, set Home Assistant IPv6 to automatic or static as appropriate, and avoid client isolation. Add VLAN or multicast rules only after the simple topology works." },
      { heading: "Check the exposed devices before rebuilding dashboards", body: "After pairing, inventory the entities Home Assistant actually created. Aqara decides which child devices and features the bridge publishes, and Home Assistant must support the corresponding Matter device type. Do not delete the old integration or dashboard until names, states, controls, and automations are verified." },
      { heading: "Keep Thread and Matter as separate troubleshooting layers", body: "Matter is the control protocol; Thread can be the transport for some devices. A bridged Aqara Zigbee sensor does not join Thread, while a native Matter-over-Thread device needs reachable Thread infrastructure. Record which Thread network commissioned each device instead of treating all border routers as one automatic mesh." },
      { heading: "Use multi-admin instead of resetting a working device", body: "When a Matter device or bridge already belongs to Aqara, Apple, or Google, use the platform's supported share-to-another-ecosystem flow where available. Resetting first can discard a working fabric, device names, and automations without solving the local network problem." },
      { heading: "Troubleshoot in this order", body: "Confirm the Home Assistant Matter integration, pairing window, current code, same-LAN reachability, IPv6, mDNS, and supported device type. Then download Home Assistant Matter diagnostics if needed. Reset M3 only after the official pairing and network checks fail and the existing Aqara configuration is backed up or documented." },
      { heading: "Choose another path when advanced Aqara features matter", body: "If the Matter bridge omits an essential sensor value, infrared function, vendor setting, event, or automation trigger, keep Aqara Home as the system of record and evaluate a supported local model-specific path. Matter interoperability is valuable, but it is not evidence that every proprietary feature should appear in Home Assistant." },
    ],
  },
  {
    site: "smarthome",
    slug: "aqara-p2-vs-p1-door-window-sensor",
    title: "Aqara P2 vs. P1 Door and Window Sensor",
    dek: "Choose native Matter over Thread or Aqara Zigbee by checking the existing hub, controller, border router, battery, and automation path.",
    category: "automation",
    updatedAt,
    relatedProducts: ["aqara-door-and-window-sensor-p2", "aqara-hub-m3"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    sources: [
      { name: "Aqara Sensor P2", url: "https://www.aqara.com/us/product/door-and-window-sensor-p2/", note: "Official Matter-over-Thread model details." },
      { name: "Aqara Sensor P1", url: "https://www.aqara.com/us/product/door-and-window-sensor-p1/", note: "Official Zigbee model details." },
    ],
    sections: [
      { heading: "P2 is Matter over Thread", body: "It needs a compatible Matter controller and Thread border router. It does not pair as a normal Zigbee child device simply because Aqara is the brand." },
      { heading: "P1 is Aqara Zigbee", body: "It is the cleaner fit when an existing compatible Aqara hub and Aqara Home automations already solve the task." },
      { heading: "Choose the network you already operate well", body: "Native Matter sharing can broaden ecosystem options, while Zigbee can keep an established Aqara setup simpler. Count required controllers before comparing sensor price." },
      { heading: "Physical installation still decides reliability", body: "Compare dimensions, magnet gap, battery access, clearance, and mounting surfaces for the exact door or window." },
    ],
  },
  {
    site: "smarthome",
    slug: "tapo-p125m-vs-p110m",
    title: "Tapo P110M vs P125M: Energy Monitoring or Matter?",
    dek: "Compare Tapo P110M vs P125M by energy monitoring, Matter control, outlet fit, pack options, electrical limits, and model-number details.",
    category: "automation",
    updatedAt: "July 11, 2026",
    relatedProducts: ["tapo-p110m-energy-monitoring-smart-plug", "tapo-p125m-matter-smart-plug"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    sources: [
      { name: "Tapo P125M", url: "https://www.tp-link.com/us/home-networking/smart-plug/tapo-p125m/", note: "Official P125M features." },
      { name: "Tapo P110M", url: "https://www.tp-link.com/us/home-networking/smart-plug/tapo-p110m/", note: "Official P110M features." },
    ],
    sections: [
      { heading: "P125M leads with compact Matter control", body: "It fits ordinary on-and-off automations where outlet clearance and ecosystem compatibility matter more than usage data." },
      { heading: "P110M adds energy monitoring", body: "Choose it when power history, estimates, or identifying a device's consumption is the actual goal. Confirm regional feature support in the current listing and app." },
      { heading: "Model and pack count belong in the title", body: "P125, P125M, P110, and P110M are not interchangeable. Verify the M suffix, ASIN, electrical rating, and number of plugs before comparing price." },
      { heading: "Neither plug approves every appliance", body: "Check running and startup loads and follow the maker's restrictions, especially for heaters, motors, compressors, and safety-critical devices." },
    ],
  },
  {
    site: "smarthome",
    slug: "matter-controller-vs-thread-border-router",
    title: "Thread Border Router vs. Matter Controller",
    dek: "Understand what a Thread border router does, how it differs from a Matter controller, when one device provides both, and why a Matter-over-Thread accessory may still fail to commission.",
    category: "automation",
    updatedAt: "July 26, 2026",
    relatedProducts: ["aqara-hub-m3", "aqara-door-and-window-sensor-p2", "tapo-p125m-matter-smart-plug"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    sources: [
      { name: "Matter overview", url: "https://csa-iot.org/all-solutions/matter/", note: "Primary standards-organization overview." },
      { name: "Thread overview", url: "https://www.threadgroup.org/What-is-Thread", note: "Primary Thread networking overview." },
      { name: "Apple Thread border-router support", url: "https://support.apple.com/en-us/102078", note: "Official exact-generation list for Thread-enabled Apple home hubs and local iPhone support." },
      { name: "Google Home Matter preparation", url: "https://support.google.com/googlehome/answer/12391458", note: "Official Google Home table separating Matter hubs with and without Thread border routing." },
      { name: "Aqara Hub M3 manual", url: "https://www.aqara.com/wp-content/uploads/2024/05/M3-User-Manual-1.pdf", note: "Official Matter-access and Thread border-router roles for Hub M3." },
      { name: "SmartThings Matter integration", url: "https://support.smartthings.com/hc/en-us/articles/11219700390804-SmartThings-x-Matter-Integration", note: "Official example of a Matter controller that may still require a separate Thread border router." },
    ],
    comparisonTable: {
      title: "Which role is present in common hubs?",
      columns: ["Matter controller or ecosystem hub", "Thread border router", "Buying implication"],
      rows: [
        {
          label: "HomePod mini / HomePod (2nd gen)",
          values: [
            "Yes, as an Apple home hub",
            "Yes",
            "Can cover both jobs for Apple Home; update software and keep the hub powered at home",
          ],
        },
        {
          label: "Apple TV 4K",
          values: [
            "Yes, when configured as an Apple home hub",
            "2nd gen and 3rd-gen Wi-Fi + Ethernet models are on Apple's Thread-enabled list",
            "Do not buy by the Apple TV 4K name alone; generation and configuration matter",
          ],
        },
        {
          label: "Nest Hub / Google Home hubs",
          values: [
            "Nest Hub generations and several Google speakers can act as Google Home Matter hubs",
            "Nest Hub 2nd gen and Nest Hub Max include Thread; Nest Hub 1st gen does not",
            "A Wi-Fi-only Matter hub controls Matter-over-Wi-Fi but still needs a separate border router for Thread",
          ],
        },
        {
          label: "Nest Wifi Pro / Google TV Streamer (4K)",
          values: [
            "Yes for Google Home",
            "Yes",
            "Both roles are published, but Thread credentials and the chosen ecosystem still need correct setup",
          ],
        },
        {
          label: "Aqara Hub M3",
          values: [
            "Yes for supported third-party Matter devices in Aqara Home",
            "Yes",
            "Also bridges supported Aqara devices; bridging a Zigbee child is not the same as converting it to Thread",
          ],
        },
        {
          label: "SmartThings 2015 Hub",
          values: [
            "Yes for Matter devices over Wi-Fi or LAN",
            "No",
            "A separate compatible Thread border router is required for Matter-over-Thread accessories",
          ],
        },
      ],
    },
    sections: [
      { heading: "The short answer: routing is not controlling", body: "A Thread border router forwards IPv6 traffic between the low-power Thread mesh and the home's Wi-Fi or Ethernet network. It does not decide what a lock, sensor, light, or plug should do. A Matter controller commissions the accessory into an ecosystem, holds permissions, and exposes controls and automations. Matter-over-Thread normally needs both roles, even when one physical hub supplies them." },
      { heading: "Matter-over-Wi-Fi needs a controller but not Thread", body: "A Matter accessory can communicate over Wi-Fi, Ethernet, or Thread. A Matter-over-Wi-Fi plug still needs a Matter controller or hub for the chosen ecosystem, but it does not need a Thread border router for its radio path. The Matter logo alone therefore does not tell you which network hardware is required; check the transport named on the box and current product page." },
      { heading: "Exact generation beats the family name", body: "Apple lists HomePod mini, HomePod (2nd generation), Apple TV 4K (2nd generation), and Apple TV 4K (3rd generation) Wi-Fi + Ethernet as Thread-enabled devices. Google lists Nest Hub (2nd generation), Nest Hub Max, Nest Wifi Pro, and Google TV Streamer (4K) among its Thread border routers, while Nest Hub (1st generation) remains a Matter hub without Thread. Similar names do not guarantee the same radio." },
      { heading: "A combined hub can still leave two separate Thread networks", body: "Buying a second border router does not automatically extend the first Thread mesh. Ecosystems may create separate Thread networks with different credentials, and multi-admin sharing controls the Matter fabric rather than magically merging every Thread credential set. Choose the primary ecosystem, verify credential sharing, and commission one accessory before resetting an existing installation." },
      { heading: "Write both requirements before purchase", body: "For a Matter-over-Thread device, write down the exact accessory model and transport, the primary Matter ecosystem and always-home controller, the exact Thread border-router model and generation, and the phone or app used for commissioning. For a Wi-Fi Matter device, replace the border-router check with Wi-Fi band, LAN, and account requirements." },
    ],
  },
  {
    site: "homeoffice",
    slug: "single-vs-dual-monitor-arm-walking-desk",
    title: "Single vs. Dual Monitor Arms for a Walking Desk",
    dek: "Compare independent adjustment, shared-post leverage, desk stiffness, clamp load, cable movement, and how walking changes screen stability.",
    category: "ergonomics",
    updatedAt,
    relatedProducts: ["huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    relatedRoundups: ["best-monitor-arms-for-home-office", "best-standing-desks-for-small-spaces"],
    sources: [
      { name: "OSHA monitor guidance", url: "https://www.osha.gov/etools/computer-workstations/components/monitors", note: "Primary monitor-position guidance." },
      { name: "VESA mounting standard", url: "https://vesa.org/resources/mounting-standard/", note: "Primary mounting-interface reference." },
    ],
    sections: [
      { heading: "Two single arms isolate adjustment", body: "Independent clamps and posts make it easier to tune different monitor weights and positions, but they consume more desk-edge space and require two strong mounting areas." },
      { heading: "A dual arm concentrates load", body: "One clamp can simplify the desk edge, while both screens apply leverage through the same post and desktop area. Desk stiffness and clamp support become especially important while walking." },
      { heading: "Keep screens close to their posts", body: "Long extension increases leverage and visible oscillation. Arrange the desk so both screens can stay near the support while maintaining a comfortable viewing distance." },
      { heading: "Test the full movement system", body: "Check monitor weight, VESA pattern, clamp clearance, desktop construction, sit-stand travel, cable slack, and screen movement at the intended walking speed." },
    ],
  },
  {
    site: "homeoffice",
    slug: "monitor-arm-clamp-reinforcement-guide",
    title: "Monitor Arm Clamp Reinforcement Guide",
    dek: "Decide whether a reinforcement plate can spread load safely, when a grommet mount is better, and when the desktop is unsuitable for an arm.",
    category: "ergonomics",
    updatedAt,
    relatedProducts: ["huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    relatedRoundups: ["best-monitor-arms-for-home-office"],
    sources: [
      { name: "VESA mounting standard", url: "https://vesa.org/resources/mounting-standard/", note: "Primary display-mounting reference." },
      { name: "OSHA workstation desks", url: "https://www.osha.gov/etools/computer-workstations/components/desks", note: "Primary desk and equipment-placement guidance." },
    ],
    sections: [
      { heading: "Inspect the desktop before adding a plate", body: "Identify solid wood, particleboard, laminate, veneer, glass, hollow core, edge profile, aprons, cable trays, and existing damage. Follow the desk maker's mounting limits." },
      { heading: "A plate spreads pressure but does not strengthen everything", body: "A larger contact area can reduce localized crushing. It cannot repair a hollow, cracked, water-damaged, very thin, or unsupported desktop." },
      { heading: "Keep contact surfaces flat", body: "The clamp and any reinforcement plate should sit fully on stable surfaces above and below. Beveled edges and obstructions create uneven force." },
      { heading: "Recheck after loading and movement", body: "Install within the arm and desk limits, then inspect for indentation, slipping, flex, and fastener loosening after height changes and walking-desk use." },
    ],
  },
  {
    site: "homeoffice",
    slug: "walking-pad-speed-monitor-stability-guide",
    title: "Walking-Pad Speed and Monitor Stability Guide",
    dek: "Use task difficulty, gait, floor, desk frame, arm extension, and cable movement to find a sustainable working speed.",
    category: "ergonomics",
    updatedAt,
    relatedProducts: ["huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    relatedRoundups: ["best-monitor-arms-for-home-office", "best-standing-desks-for-small-spaces"],
    sources: [
      { name: "OSHA workstation positions", url: "https://www.osha.gov/etools/computer-workstations/positions", note: "Primary neutral-posture and position-change guidance." },
      { name: "OSHA monitor guidance", url: "https://www.osha.gov/etools/computer-workstations/components/monitors", note: "Primary monitor distance and position guidance." },
    ],
    sections: [
      { heading: "Start stationary", body: "Set standing desk height, keyboard, mouse, monitor distance, and screen height before turning on the walking pad. A moving setup should begin from a neutral stationary position." },
      { heading: "Use a slow task-specific starting speed", body: "Typing, reading, calls, and focused editing tolerate different movement. Increase only while text remains easy to read and the gait stays natural." },
      { heading: "Trace wobble from the floor upward", body: "Observe the walking pad, floor, desk feet, frame, desktop, clamp, arm joints, and monitor. Replace only the first component that visibly introduces unacceptable movement." },
      { heading: "Stop before adjusting hardware", body: "Pause the belt before moving the monitor arm, changing desk height, routing cables, or reaching below the desk. Keep an easy stop control accessible." },
    ],
  },
];

export const topicClusterTools: Tool[] = [
  {
    site: "pet",
    slug: "pet-room-air-change-calculator",
    title: "Pet Room Air-Change and CADR Calculator",
    dek: "Estimate a planning CADR target from room area, ceiling height, and a pet-room air-change goal.",
    category: "home-care",
    updatedAt: "July 26, 2026",
    kind: "air",
    sections: [
      { heading: "The result is a room-volume planning target", body: "The calculator multiplies floor area by ceiling height, then converts a five-air-changes-per-hour planning goal into cubic feet per minute. It does not measure the purifier's delivered airflow in the actual furnished room." },
      { heading: "Compare CADR, not a maximum-room headline", body: "Use a current smoke CADR or another clearly defined clean-air delivery figure when screening purifiers. Open doors, high ceilings, furniture, filter loading, fan speed, noise tolerance, and room leakage can reduce the effective result." },
      { heading: "Remove odor and hair at the source", body: "An air purifier can support airborne particle control, but litter, urine, damp fabric, bedding, visible hair, and ventilation problems still need scooping, washing, vacuuming, drying, and source correction." },
    ],
    faqs: [
      { question: "Does a purifier remove pet hair from furniture?", answer: "No. A pre-filter may catch airborne hair, but floors, upholstery, bedding, and pet beds still need physical cleaning." },
      { question: "Is five air changes per hour mandatory?", answer: "No. It is the planning goal used by this tool, not a universal medical or building requirement. Adjust the decision to the room, pollutant, noise, ventilation, and professional guidance." },
    ],
    relatedRoundups: ["levoit-vital-200s-p-vs-shark-neverchange-max", "best-pet-odor-and-litter-upgrades"],
  },
  {
    site: "network",
    slug: "mesh-node-and-backhaul-planner",
    title: "Mesh Node and Backhaul Planner",
    dek: "Estimate a starting node count from home size and floors, then identify where Ethernet backhaul deserves priority.",
    category: "wifi",
    updatedAt: "July 26, 2026",
    kind: "mesh",
    sections: [
      { heading: "Floors create a placement problem, not an automatic shopping list", body: "The planner uses home size and floor count to create a first test layout. Stairwells, open landings, dense floor construction, long hallways, and the modem location decide whether nodes can hear one another; do not place one unit on every floor without checking the upstream path." },
      { heading: "Prioritize wired backhaul at the hardest boundary", body: "When practical, use Ethernet between the router and the node separated by the densest floor or longest distance. Wired backhaul can improve stability and preserve wireless airtime more reliably than upgrading every node to a higher speed class." },
      { heading: "Validate the smaller layout before adding a node", body: "Test the work area, bedrooms, TV, gaming, and outdoor edge with the first estimated layout. Move an existing node toward the weak area while preserving a strong link before buying another pack." },
    ],
    faqs: [
      { question: "How is this different from the Wi-Fi coverage estimator?", answer: "This planner focuses on floor count and backhaul priority. The coverage estimator uses home size and connected-device count to screen node count and network load." },
      { question: "Does every mesh node need Ethernet?", answer: "No. Wireless backhaul can work well with good placement, but Ethernet is especially useful across difficult floors, long distances, or busy office and media paths." },
    ],
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes", "tp-link-deco-be67-vs-be63"],
  },
  {
    site: "smarthome",
    slug: "matter-thread-compatibility-checker",
    title: "Matter and Thread Border Router Compatibility Checker",
    dek: "Translate planned Thread and Wi-Fi Matter devices into Matter controller, Thread border-router, and network requirements.",
    category: "automation",
    updatedAt: "July 26, 2026",
    kind: "matter",
    sections: [
      { heading: "Count transport before choosing a hub", body: "A Matter-over-Thread sensor or lock needs a compatible Matter controller and Thread border router. A Wi-Fi Matter device needs a Matter controller and the supported Wi-Fi network, but it does not need Thread solely because it carries the Matter logo." },
      { heading: "Check the exact controller hardware", body: "Phones can commission devices but should not automatically be counted as an always-available home controller or border router. Verify the exact speaker, display, TV box, hub, or Home Assistant radio and its current software against the chosen ecosystem." },
      { heading: "Map ecosystem sharing and fallback", body: "Decide which ecosystem commissions first, whether multi-admin sharing is required, which vendor app retains advanced settings, and what local physical control remains when internet, hub, phone, or account access fails." },
    ],
    faqs: [
      { question: "Does every Matter device need a Thread border router?", answer: "No. Matter can use Wi-Fi or Ethernet as well as Thread. Only the planned Matter-over-Thread path creates the Thread border-router requirement." },
      { question: "Is a Matter controller the same as a Thread border router?", answer: "No. They are separate roles, although one physical product can perform both. Verify each role on the exact model and software version." },
    ],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
  },
];
