import type { Guide, Tool } from "./types";

const updatedAt = "July 1, 2026";

export const topicClusterGuides: Guide[] = [
  {
    site: "baby",
    slug: "ergobaby-omni-breeze-cleaning-guide",
    title: "How to Clean an Ergobaby Omni Breeze",
    dek: "Protect buckles, straps, mesh, and carrier shape while handling everyday drool, spills, and full-machine washes.",
    category: "travel",
    updatedAt,
    relatedProducts: ["ergobaby-omni-breeze-carrier"],
    relatedRoundups: ["babybjorn-harmony-vs-ergobaby-omni-breeze", "best-baby-carriers-and-sleep-routine-upgrades"],
    sources: [
      { name: "Ergobaby care instructions", url: "https://ergobaby.com/care-instructions", note: "Official carrier washing and care guidance." },
      { name: "Omni Breeze instructions", url: "https://ergobaby.com/instructions-omni-breeze/", note: "Official model setup and inspection guidance." },
    ],
    sections: [
      { heading: "Read the sewn-in label first", body: "Color, trim, and regional versions can have model-specific care instructions. Treat the label on the carrier as the controlling source before using a washer, detergent, or dryer." },
      { heading: "Spot-clean between full washes", body: "Address drool and small spills with a damp cloth and mild detergent so the carrier does not need an unnecessary full wash. Keep harsh cleaners, bleach, and fabric softener away unless the label explicitly allows them." },
      { heading: "Fasten hardware before machine washing", body: "Close buckles, secure loose straps, and use a laundry bag or pillowcase if the official instructions permit. A gentle cold cycle reduces repeated impact on hardware and mesh." },
      { heading: "Air-dry and inspect before reuse", body: "Let the carrier dry completely with its shape supported. Check webbing, seams, buckles, elastic, and mesh before placing the baby back in it." },
    ],
  },
  {
    site: "baby",
    slug: "babybjorn-harmony-newborn-fit-checklist",
    title: "BabyBjörn Harmony Newborn Fit Checklist",
    dek: "Check minimum size, inward-facing setup, leg position, head support, airway visibility, and caregiver adjustment.",
    category: "travel",
    updatedAt,
    relatedProducts: ["babybjorn-carrier-harmony"],
    relatedRoundups: ["babybjorn-harmony-vs-ergobaby-omni-breeze"],
    sources: [
      { name: "BabyBjörn Carrier Harmony", url: "https://www.babybjorn.com/products/baby-carriers/baby-carrier-harmony/", note: "Official size, position, and adjustment guidance." },
      { name: "BabyBjörn Harmony manual", url: "https://www.babybjorn.com/customer-service/manuals/", note: "Official manuals and model-specific instructions." },
    ],
    sections: [
      { heading: "Confirm the stated minimums", body: "Use the carrier only after the baby meets the listed weight and length requirements. A newborn begins front inward; later carry positions have separate developmental limits." },
      { heading: "Set the newborn height position", body: "Follow the Harmony manual for zipper, head-support, and leg-position settings. Do not reuse the configuration shown for an older baby." },
      { heading: "Keep the airway visible", body: "The baby's face should remain visible, with the chin clear of the chest and the head supported according to the instructions. Reposition immediately if the baby slumps or the fabric covers the face." },
      { heading: "Adjust each caregiver separately", body: "Set the waist belt, back support, and shoulder straps for the current wearer. Complete the first short carry with another adult nearby and recheck the fit after moving." },
    ],
  },
  {
    site: "baby",
    slug: "baby-carrier-hot-weather-and-caregiver-fit-guide",
    title: "Baby Carrier Guide for Hot Weather and Different Caregiver Builds",
    dek: "Compare mesh, waistband shape, shoulder-strap routing, clothing, trip length, and return policies without promising a universally cool fit.",
    category: "travel",
    updatedAt,
    relatedProducts: ["ergobaby-omni-breeze-carrier", "babybjorn-carrier-harmony"],
    relatedRoundups: ["babybjorn-harmony-vs-ergobaby-omni-breeze"],
    sources: [
      { name: "Ergobaby Omni Breeze", url: "https://ergobaby.com/omni-breeze-baby-carrier-all", note: "Official material, size, and adjustment information." },
      { name: "BabyBjörn Carrier Harmony", url: "https://www.babybjorn.com/products/baby-carriers/baby-carrier-harmony/", note: "Official material, size, and adjustment information." },
    ],
    sections: [
      { heading: "Mesh reduces fabric resistance, not shared body heat", body: "Both baby and adult still produce heat where their bodies touch. Shade, light clothing, hydration, pace, humidity, and shorter carries can matter as much as the carrier material." },
      { heading: "Check the adjustment range on the actual wearer", body: "Product ranges do not describe torso length, shoulder shape, waist placement, or pressure sensitivity. Use the return window to test strap access and load distribution with realistic weight." },
      { heading: "Do not share one strap setup", body: "Mark or remember each caregiver's settings and reset the carrier when it changes hands. The baby should remain high, centered, visible, and supported after every adjustment." },
      { heading: "Choose another tool when conditions demand it", body: "A stroller, shaded break, or shorter outing can be safer and more comfortable when either person overheats or when the carrier cannot be adjusted without pressure or slumping." },
    ],
  },
  {
    site: "network",
    slug: "deco-be63-be67-two-pack-vs-three-pack",
    title: "Deco BE63 3-Pack vs. 2-Pack: When the 3-Piece Mesh Kit Makes Sense",
    dek: "Choose a Deco BE63 or BE67 2-pack versus 3-piece whole-home mesh kit from floors, wall density, Ethernet paths, and measured weak areas instead of maximum square-foot figures.",
    category: "wifi",
    updatedAt,
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh", "tp-link-deco-be67-wifi-7-mesh"],
    relatedRoundups: ["tp-link-deco-be67-vs-be63", "best-mesh-wifi-for-apartments-and-homes"],
    sources: [
      { name: "TP-Link Deco BE63", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be63/", note: "Official pack and coverage information." },
      { name: "TP-Link Deco BE67", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be67/", note: "Official pack and coverage information." },
    ],
    sections: [
      { heading: "Start with the rooms that actually fail", body: "Map the modem, work areas, TVs, bedrooms, outdoor edges, and floors. A third node is useful only when it creates a strong intermediate path or serves a distinct floor or wing." },
      { heading: "Too many wireless nodes can compete", body: "Nodes placed too close together can add airtime and roaming complexity without fixing coverage. Begin with two well-positioned units when the layout allows and add only after measurement." },
      { heading: "Wired backhaul changes node placement", body: "Ethernet lets a satellite sit where client coverage is needed instead of where a strong wireless relay remains available. Check switch speeds and wall-jack paths before selecting the pack." },
      { heading: "Match pack size when comparing price", body: "Retail listings can describe the Deco BE63 as a 3-pack, 3-piece, or whole-home mesh system. Compare the same model, hardware version, region, and node count before treating one offer as cheaper." },
    ],
  },
  {
    site: "network",
    slug: "is-deco-be67-worth-it-for-gigabit-internet",
    title: "Is Deco BE67 Worth It for 1Gbps or 2.5Gbps Internet?",
    dek: "Separate WAN speed, local transfers, wireless backhaul, client support, and future plans before paying for BE14000 and 10GbE.",
    category: "wifi",
    updatedAt,
    relatedProducts: ["tp-link-deco-be67-wifi-7-mesh", "tp-link-deco-be63-wifi-7-mesh"],
    relatedRoundups: ["tp-link-deco-be67-vs-be63"],
    sources: [
      { name: "TP-Link Deco BE67", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be67/", note: "Official wireless and Ethernet specifications." },
      { name: "TP-Link Deco BE63", url: "https://www.tp-link.com/us/deco-mesh-wifi/product-family/deco-be63/", note: "Official comparison specifications." },
    ],
    sections: [
      { heading: "Gigabit internet does not require a 10GbE router", body: "BE67 can still provide coverage and capacity benefits, but its largest Ethernet advantage remains unused when the modem, switch, storage, and clients stay at gigabit." },
      { heading: "A 2.5Gbps plan can fit either model", body: "BE63's four 2.5GbE ports may be more convenient for several wired devices. BE67 makes more sense when one faster 10GbE path or greater wireless-backhaul capacity has a defined job." },
      { heading: "Local traffic can justify the upgrade", body: "Fast NAS transfers, workstation backups, or a 10GbE switch can use capacity even when the internet is slower. Draw that local path before paying for it." },
      { heading: "Future-proofing needs a date and device list", body: "List the expected modem, service tier, clients, switch, and storage upgrades. A vague future plan is weaker justification than fixing placement or adding Ethernet today." },
    ],
  },
  {
    site: "network",
    slug: "deco-mesh-connection-drops-troubleshooting",
    title: "Deco Mesh Connection Drops: A Troubleshooting Checklist",
    dek: "Separate ISP, modem, main-node, backhaul, roaming, cable, and client problems before resetting the whole network.",
    category: "wifi",
    updatedAt,
    relatedProducts: ["tp-link-deco-be63-wifi-7-mesh", "tp-link-deco-be67-wifi-7-mesh"],
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes", "tp-link-deco-be67-vs-be63"],
    sources: [
      { name: "TP-Link Deco support", url: "https://www.tp-link.com/us/support/faq/2428/", note: "Official Deco connectivity troubleshooting." },
      { name: "TP-Link Ethernet backhaul FAQ", url: "https://www.tp-link.com/us/support/faq/1794/", note: "Official topology and backhaul guidance." },
    ],
    sections: [
      { heading: "Define what actually drops", body: "Record whether one client, one node, Wi-Fi, local LAN, DNS, or the entire internet path fails. The LED, Deco app, modem status, and a wired test help narrow the layer." },
      { heading: "Test the modem and main Deco first", body: "Connect one known-good wired client where possible, inspect the modem or ONT, and check the ISP before moving every satellite. A mesh cannot repair an unstable upstream link." },
      { heading: "Simplify backhaul temporarily", body: "Remove suspect switches, wall jacks, and cables one at a time. For wireless satellites, move one node closer to the main unit and compare stability." },
      { heading: "Change one variable and keep a log", body: "Record firmware, topology, client model, time, and result. Avoid factory-resetting first because it removes evidence and introduces several new variables at once." },
    ],
  },
  {
    site: "pet",
    slug: "air-purifier-placement-near-litter-box",
    title: "Where to Place an Air Purifier Near a Litter Box",
    dek: "Capture airborne particles without blocking intake, blowing litter, crowding the cat, or treating filtration as a substitute for scooping.",
    category: "home-care",
    updatedAt,
    relatedProducts: ["levoit-vital-200s-p-air-purifier", "shark-neverchange-max-air-purifier"],
    relatedRoundups: ["levoit-vital-200s-p-vs-shark-neverchange-max", "best-pet-odor-and-litter-upgrades"],
    sources: [
      { name: "EPA air cleaners guidance", url: "https://www.epa.gov/indoor-air-quality-iaq/air-cleaners-and-air-filters-home", note: "Primary room-air-cleaner and source-control guidance." },
    ],
    sections: [
      { heading: "Keep intake and exhaust open", body: "Use the purifier maker's wall and furniture clearances. A unit hidden behind the litter box or inside a cabinet cannot circulate the room effectively." },
      { heading: "Avoid blowing directly across litter", body: "Strong exhaust can move dust and litter or make the cat avoid the box. Place the purifier nearby but outside the digging and exit path." },
      { heading: "Protect the purifier from accidents", body: "Keep cords, controls, filters, and air-quality sensors away from spray, tracked litter, and cleaning liquids. Use a stable floor position that cannot be tipped." },
      { heading: "Source control stays first", body: "Scoop, replace litter, clean the box, wash nearby surfaces, and ventilate appropriately. Filtration supports the routine but cannot remove waste that remains in the room." },
    ],
  },
  {
    site: "pet",
    slug: "levoit-vital-200s-p-filter-cost-and-maintenance",
    title: "Levoit Vital 200S-P Filter Cost and Maintenance Guide",
    dek: "Plan washable pre-filter cleaning, main-filter replacement, sensor care, and annual cost before treating the purifier price as the full expense.",
    category: "home-care",
    updatedAt,
    relatedProducts: ["levoit-vital-200s-p-air-purifier"],
    relatedRoundups: ["levoit-vital-200s-p-vs-shark-neverchange-max"],
    sources: [
      { name: "Levoit Vital 200S-P", url: "https://levoit.com/products/vital-200s-p-smart-air-purifier", note: "Official filter and maintenance information." },
      { name: "Levoit support", url: "https://levoit.com/pages/support", note: "Official manuals and replacement guidance." },
    ],
    sections: [
      { heading: "The washable part is the pre-filter", body: "The main filter is still a replaceable consumable. Follow the manual for separating, cleaning, drying, and reinstalling the washable pre-filter." },
      { heading: "Pet rooms can load filters faster", body: "Hair, dust, dander, smoke, cooking particles, and fan runtime affect maintenance. Inspect the unit rather than treating one calendar interval as universal." },
      { heading: "Price the correct genuine replacement", body: "Confirm the Vital 200S-P filter model, seller, availability, and multipack terms. Add the expected replacement interval to a one- and three-year ownership estimate." },
      { heading: "Clean sensors and clear airflow", body: "Dust around the intake and sensor can affect readings and airflow. Unplug the unit and follow the manual rather than spraying cleaner into openings." },
    ],
  },
  {
    site: "smarthome",
    slug: "aqara-hub-m3-vs-m2",
    title: "Aqara Hub M3 vs. M2",
    dek: "Compare Matter-controller and Thread-border-router roles, Zigbee support, PoE, infrared control, migration, and when an existing M2 can stay.",
    category: "automation",
    updatedAt,
    relatedProducts: ["aqara-hub-m3"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    sources: [
      { name: "Aqara Hub M3", url: "https://www.aqara.com/us/product/hub-m3/", note: "Official M3 roles and specifications." },
      { name: "Aqara Hub M2", url: "https://www.aqara.com/us/product/hub-m2/", note: "Official M2 roles and specifications." },
    ],
    sections: [
      { heading: "M3 adds a native Thread and Matter foundation", body: "M3 is designed as a Matter controller and Thread border router in addition to supporting compatible Aqara Zigbee devices. M2 remains a Zigbee-centered hub and bridge for supported devices." },
      { heading: "Both hubs can still have a job", body: "An M2 may continue serving stable Zigbee automations while M3 handles newer Thread and Matter devices. Replacing it is not mandatory when the current setup already meets the goal." },
      { heading: "Power and placement differ", body: "Compare Ethernet, PoE, USB power, Wi-Fi, speaker, infrared coverage, and the physical location each automation requires." },
      { heading: "Migration is the hidden cost", body: "Inventory child devices, scenes, ecosystem links, family access, and infrared remotes. Move a small group first and keep the older hub until critical routines are verified." },
    ],
  },
  {
    site: "smarthome",
    slug: "aqara-p2-vs-p1-door-window-sensor",
    title: "Aqara P2 vs. P1 Door and Window Sensor",
    dek: "Choose native Matter over Thread or Aqara Zigbee by checking the existing hub, controller, border router, battery, and automation path.",
    category: "automation",
    updatedAt,
    relatedProducts: ["aqara-door-and-window-sensor-p2", "aqara-hub-m3"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    sources: [
      { name: "Aqara Sensor P2", url: "https://www.aqara.com/us/product/door-and-window-sensor-p2/", note: "Official Matter-over-Thread model details." },
      { name: "Aqara Sensor P1", url: "https://www.aqara.com/us/product/door-and-window-sensor-p1/", note: "Official Zigbee model details." },
    ],
    sections: [
      { heading: "P2 is Matter over Thread", body: "It needs a compatible Matter controller and Thread border router. It does not pair as a normal Zigbee child device simply because Aqara is the brand." },
      { heading: "P1 is Aqara Zigbee", body: "It is the cleaner fit when an existing compatible Aqara hub and Aqara Home automations already solve the task." },
      { heading: "Choose the network you already operate well", body: "Native Matter sharing can broaden ecosystem options, while Zigbee can keep an established Aqara setup simpler. Count required controllers before comparing sensor price." },
      { heading: "Physical installation still decides reliability", body: "Compare dimensions, magnet gap, battery access, clearance, and mounting surfaces for the exact door or window." },
    ],
  },
  {
    site: "smarthome",
    slug: "tapo-p125m-vs-p110m",
    title: "Tapo P110M vs P125M: Energy Monitoring or Matter?",
    dek: "Compare Tapo P110M vs P125M by energy monitoring, Matter control, outlet fit, pack options, electrical limits, and model-number details.",
    category: "automation",
    updatedAt: "July 11, 2026",
    relatedProducts: ["tapo-p125m-matter-smart-plug"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    sources: [
      { name: "Tapo P125M", url: "https://www.tp-link.com/us/home-networking/smart-plug/tapo-p125m/", note: "Official P125M features." },
      { name: "Tapo P110M", url: "https://www.tp-link.com/us/home-networking/smart-plug/tapo-p110m/", note: "Official P110M features." },
    ],
    sections: [
      { heading: "P125M leads with compact Matter control", body: "It fits ordinary on-and-off automations where outlet clearance and ecosystem compatibility matter more than usage data." },
      { heading: "P110M adds energy monitoring", body: "Choose it when power history, estimates, or identifying a device's consumption is the actual goal. Confirm regional feature support in the current listing and app." },
      { heading: "Model and pack count belong in the title", body: "P125, P125M, P110, and P110M are not interchangeable. Verify the M suffix, ASIN, electrical rating, and number of plugs before comparing price." },
      { heading: "Neither plug approves every appliance", body: "Check running and startup loads and follow the maker's restrictions, especially for heaters, motors, compressors, and safety-critical devices." },
    ],
  },
  {
    site: "smarthome",
    slug: "matter-controller-vs-thread-border-router",
    title: "Thread Border Router vs. Matter Controller",
    dek: "Understand what a Thread border router does, how it differs from a Matter controller, when one device provides both, and why a Matter-over-Thread accessory may still fail to commission.",
    category: "automation",
    updatedAt,
    relatedProducts: ["aqara-hub-m3", "aqara-door-and-window-sensor-p2", "tapo-p125m-matter-smart-plug"],
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
    sources: [
      { name: "Matter overview", url: "https://csa-iot.org/all-solutions/matter/", note: "Primary standards-organization overview." },
      { name: "Thread overview", url: "https://www.threadgroup.org/What-is-Thread", note: "Primary Thread networking overview." },
    ],
    sections: [
      { heading: "The Thread border router carries network traffic", body: "It connects the low-power Thread mesh to the wider IP network. If a device says Matter over Thread, the home needs a compatible Thread border router somewhere in the ecosystem path. Wi-Fi Matter devices such as a compatible smart plug do not need Thread for their radio path." },
      { heading: "The Matter controller manages the accessory", body: "It commissions devices, applies the ecosystem's permissions, and exposes controls and automations. Phones can assist setup without always serving as the always-home controller." },
      { heading: "One hub can provide both roles", body: "Some Apple, Google, Amazon, SmartThings, Aqara, and Home Assistant hardware combines the jobs. Check the exact generation and current software rather than the brand alone." },
      { heading: "Write both requirements before purchase", body: "For a Matter-over-Thread device, name the primary Matter controller and at least one compatible Thread border router. This prevents the common assumption that either role automatically includes the other." },
    ],
  },
  {
    site: "homeoffice",
    slug: "single-vs-dual-monitor-arm-walking-desk",
    title: "Single vs. Dual Monitor Arms for a Walking Desk",
    dek: "Compare independent adjustment, shared-post leverage, desk stiffness, clamp load, cable movement, and how walking changes screen stability.",
    category: "ergonomics",
    updatedAt,
    relatedProducts: ["huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    relatedRoundups: ["best-monitor-arms-for-home-office", "best-standing-desks-for-small-spaces"],
    sources: [
      { name: "OSHA monitor guidance", url: "https://www.osha.gov/etools/computer-workstations/components/monitors", note: "Primary monitor-position guidance." },
      { name: "VESA mounting standard", url: "https://vesa.org/resources/mounting-standard/", note: "Primary mounting-interface reference." },
    ],
    sections: [
      { heading: "Two single arms isolate adjustment", body: "Independent clamps and posts make it easier to tune different monitor weights and positions, but they consume more desk-edge space and require two strong mounting areas." },
      { heading: "A dual arm concentrates load", body: "One clamp can simplify the desk edge, while both screens apply leverage through the same post and desktop area. Desk stiffness and clamp support become especially important while walking." },
      { heading: "Keep screens close to their posts", body: "Long extension increases leverage and visible oscillation. Arrange the desk so both screens can stay near the support while maintaining a comfortable viewing distance." },
      { heading: "Test the full movement system", body: "Check monitor weight, VESA pattern, clamp clearance, desktop construction, sit-stand travel, cable slack, and screen movement at the intended walking speed." },
    ],
  },
  {
    site: "homeoffice",
    slug: "monitor-arm-clamp-reinforcement-guide",
    title: "Monitor Arm Clamp Reinforcement Guide",
    dek: "Decide whether a reinforcement plate can spread load safely, when a grommet mount is better, and when the desktop is unsuitable for an arm.",
    category: "ergonomics",
    updatedAt,
    relatedProducts: ["huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    relatedRoundups: ["best-monitor-arms-for-home-office"],
    sources: [
      { name: "VESA mounting standard", url: "https://vesa.org/resources/mounting-standard/", note: "Primary display-mounting reference." },
      { name: "OSHA workstation desks", url: "https://www.osha.gov/etools/computer-workstations/components/desks", note: "Primary desk and equipment-placement guidance." },
    ],
    sections: [
      { heading: "Inspect the desktop before adding a plate", body: "Identify solid wood, particleboard, laminate, veneer, glass, hollow core, edge profile, aprons, cable trays, and existing damage. Follow the desk maker's mounting limits." },
      { heading: "A plate spreads pressure but does not strengthen everything", body: "A larger contact area can reduce localized crushing. It cannot repair a hollow, cracked, water-damaged, very thin, or unsupported desktop." },
      { heading: "Keep contact surfaces flat", body: "The clamp and any reinforcement plate should sit fully on stable surfaces above and below. Beveled edges and obstructions create uneven force." },
      { heading: "Recheck after loading and movement", body: "Install within the arm and desk limits, then inspect for indentation, slipping, flex, and fastener loosening after height changes and walking-desk use." },
    ],
  },
  {
    site: "homeoffice",
    slug: "walking-pad-speed-monitor-stability-guide",
    title: "Walking-Pad Speed and Monitor Stability Guide",
    dek: "Use task difficulty, gait, floor, desk frame, arm extension, and cable movement to find a sustainable working speed.",
    category: "ergonomics",
    updatedAt,
    relatedProducts: ["huanuo-titanlift-heavy-duty-monitor-arm", "amazon-basics-monitor-arm"],
    relatedRoundups: ["best-monitor-arms-for-home-office", "best-standing-desks-for-small-spaces"],
    sources: [
      { name: "OSHA workstation positions", url: "https://www.osha.gov/etools/computer-workstations/positions", note: "Primary neutral-posture and position-change guidance." },
      { name: "OSHA monitor guidance", url: "https://www.osha.gov/etools/computer-workstations/components/monitors", note: "Primary monitor distance and position guidance." },
    ],
    sections: [
      { heading: "Start stationary", body: "Set standing desk height, keyboard, mouse, monitor distance, and screen height before turning on the walking pad. A moving setup should begin from a neutral stationary position." },
      { heading: "Use a slow task-specific starting speed", body: "Typing, reading, calls, and focused editing tolerate different movement. Increase only while text remains easy to read and the gait stays natural." },
      { heading: "Trace wobble from the floor upward", body: "Observe the walking pad, floor, desk feet, frame, desktop, clamp, arm joints, and monitor. Replace only the first component that visibly introduces unacceptable movement." },
      { heading: "Stop before adjusting hardware", body: "Pause the belt before moving the monitor arm, changing desk height, routing cables, or reaching below the desk. Keep an easy stop control accessible." },
    ],
  },
];

export const topicClusterTools: Tool[] = [
  {
    site: "pet",
    slug: "pet-room-air-change-calculator",
    title: "Pet Room Air-Change Calculator",
    dek: "Estimate a planning CADR target from room area, ceiling height, and a pet-room air-change goal.",
    category: "home-care",
    kind: "air",
    relatedRoundups: ["levoit-vital-200s-p-vs-shark-neverchange-max", "best-pet-odor-and-litter-upgrades"],
  },
  {
    site: "network",
    slug: "mesh-node-and-backhaul-planner",
    title: "Mesh Node and Backhaul Planner",
    dek: "Estimate a starting node count from home size and floors, then identify where Ethernet backhaul deserves priority.",
    category: "wifi",
    kind: "mesh",
    relatedRoundups: ["best-mesh-wifi-for-apartments-and-homes", "tp-link-deco-be67-vs-be63"],
  },
  {
    site: "smarthome",
    slug: "matter-thread-compatibility-checker",
    title: "Matter and Thread Border Router Compatibility Checker",
    dek: "Translate planned Thread and Wi-Fi Matter devices into Matter controller, Thread border-router, and network requirements.",
    category: "automation",
    kind: "matter",
    relatedRoundups: ["matter-starter-kit-hub-sensor-smart-plug"],
  },
];
